### ISSUE TITLE
Problem with Videos on SoccerHelp 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#1]
Dustin, the links to most of the video clips from DVDs aren't working on Basic and on Premium
 
What do you think?
 
It looks like the problem is that they aren't re-directing. Does that have to do with the change from http to https?
 
For example, look at the links on the bottom of   (under "Video Clips from Soccer Coaching DVDs we Sell - for Age 7 and older") - only 2 of them under Coach Doug are re-directing - "Hit the Coach" Practice Game  is re-directing to https://www.soccerhelp.com/soccer-videos/coach-doug-dvd-hit-the-coach-practice-game.shtml and Shooting and Kicking    is re-directing to https://www.soccerhelp.com/soccer-videos/coach-doug-dvd-shooting-and-kicking.shtml  
 
1. on https://www.soccerhelp.com/Soccer-Videos-Premium.shtml
 
the first 10 links don't work and it seems to be a different problem - could it be http vs. https? Did the video file names not get changed, or does the https link need to re-direct to the http file?
 
# 10 can go to   https://www.soccerhelp.com/soccer-videos/coach-doug-how-to-use-soccer-patches-to-motivate-players.shtml
 
If you fix the links so they work on Basic,, will that fix them on Premium too?
 
2. For example, on  http://www.soccerhelp.com/premium/Videos_Navigation_Page.shtml   there are some broken links >
Under "Motivation, Rewards, Fun, Self-Fulfilling Expectations and Positive Reinforcement"

the 2nd link How to Use SoccerHelp Patches for Fun and to Motivate Young Players
 
is to https://www.soccerhelp.com/shshop/coach-doug-how-to-use-soccer-patches-to-motivate-players.php
 
it should be re-directing to  https://www.soccerhelp.com/soccer-videos/coach-doug-how-to-use-soccer-patches-to-motivate-players.shtml
 
3. The links that are on the videos don't work > maybe because they aren't re-directing?

The Coach Doug videos work, but I notice they go to links that start  https://www.soccerhelp.com/soccer-videos/  - for example,  https://www.soccerhelp.com/soccer-videos/coach-doug-dvd-how-to-have-fun-practices-that-teach-soccer.shtml

and the others are going to links that start https://www.soccerhelp.com/shshop/   - for example https://www.soccerhelp.com/shshop/soccer-moves-basic-moves-and-foot-skills-workout.php  and https://www.soccerhelp.com/shshop/ans-power.php

For example -
on https://www.soccerhelp.com/Soccer_Video_Clips_Soccerhelp_Soccer_Moves_DVD.shtml
and
on https://www.soccerhelp.com/Soccer_Video_Clips_Anson_Dorrance_Soccer_Clinic_DVD.shtml
==============

All the videos are on the SoccerHelp YouTube Channel

The login for the YouTube Channel is Email addresses: dhuddlestontn@yahoo.com, starpatchus@yahoo.com, staff@soccerhelp.com
 
Pass is Morse127@

**Comment by dustinschaerer** [comment]
@david-huddleston I've fixed the videos on Basic and fixed most of the videos on Premium.  For now, I just hid the remaining links on the Premium video page: http://www.soccerhelp.com/premium/Videos_Navigation_Page.shtml

We need to revisit this early in June.

**Comment by david-huddleston** [comment]
@dustin - this is a test to see if this contacts you

**Comment by david-huddleston** [comment]
@dustinschaerer - I did this by typing @d and that pulled up a box with Dustin's name and I hit Enter and it will send him an email. Test >>>  ONLY send him an email if it is an Emergency or a Priority. Otherwise it will keep a list of Work Orders and a History

**Comment by david-huddleston** [comment]
@dustinschaerer  - when time, on Premium at http://www.soccerhelp.com/premium/Videos_Navigation_Page.shtml  , at the bottom only 2 of the 6 Coach Doug links work. re-direct them to the links that work that are on https://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml . For example - the first one is https://www.soccerhelp.com/soccer-videos/coach-doug-dvd-how-to-have-fun-practices-that-teach-soccer.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston OK, the Coach Doug links are all fixed in the HTML and I added redirects for the old URLs in our .htaccess file.
