### ISSUE TITLE
3 More Changes to 21 Tips

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#100]
Dustin, I sent you this as an email on 6-26-17 at 3:40 PM, use that.

Dustin, 3 changes

1. The first Subtitle is >

21 Tips for a Weak Soccer Team

Replace that with, in Bold >

21 Soccer Coaching Tips for Fast Results

(Dustin - that is the H2 - so change the H2 if needed )

2. The first sentence is >

This article has 21 tips for how to improve a weak youth soccer team in 2 practices. 

Replace it with (bold   soccer coaching   )>

This article has 21 soccer coaching tips for how to improve a weak youth soccer team in 2 practices. 

3. Make the H3 >

3 Soccer Drills to Try

(Dustin, that is the next Sub-Title below the 21 Tips)

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed, and this page is W3C validated.
