### ISSUE TITLE
Change to Soccer Practice 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#102]
Dustin , I emailed you this on 6-26-17 at 5:53 PM

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml 

Bold the first Sub-Title, which is below, and make it the H3 >

Things to Do at Soccer Practice

> Bold it and make it the H3

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed and validated.
