### ISSUE TITLE
3 changes to fix errors on SoccerHelp Premium, 6-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#103]
Dustin, I emailed you this on 6-26-17 at 6:20 PM. Use the email version

Dustin, on Premium 

1. On the bottom left of the Home page, update 

Copyright 1999-2011
to

Copyright 1999-2017

2. On http://www.soccerhelp.com/premium/Member_Contact_Us.shtml 

1. Delete the first sentence at the top, which is >

Use the following addresses to contact us directly if the Help Desk did not answer your questions.

2. Under "Shipping", delete > 

Answers to some of the most frequently asked questions about shipping can be found at the Help Desk or in Orders and Shipping FAQ's. Use this address for any other questions related to your shipments.

**Comment by dustinschaerer** [comment]
@david-huddleston Changes to both pages are completed.
