### ISSUE TITLE
Changes to Soccer Tactics , 6-27-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#105]
Dustin, I emailed you this on 6-27-17 at 9:47 AM - use the email so you can see colors, bold and formatting.

Dustin, on http://www.soccerhelp.com/soccer-tactics.shtml ,

1. Did you W3C validate?

2. Underline the following 3 things >

(a). At the start of the second para >

The 2 best things a coach can do

(b). at # 1 > 

Train Your Players to Be Brave, Tough and Aggressive 

(c).  at # 6 >

How to Teach Passing and Receiving 

3. Under the section where I replied to "Sal", bold the start of # 13, which is >

"Rules" to teach your Forward:

4. Make the title of the last section Bold Green, like >

Tips for a Coach with a Very Weak Soccer Team 
8v8 Soccer Formations 
Defending Deep Style of Play 
How to Select a Stopper, Fullbacks, Forward and Midfielders 
Where to Play Weak, Unskilled, Timid Soccer Players 
An Approach that is Better than Scrimmaging 
Practice Games I Recommend 
Coaching Rule No. 3

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed, and it is W3C validated!
