### ISSUE TITLE
Revised Changes to Soccer tactics, 6-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#107]
Dustin, I emailed you this on 6-28-17 at 12:15 PM

Dustin, Delete the version I sent at 12:12 PM and use this one - I made all the text the same size - 

Dustin, on http://www.soccerhelp.com/soccer-tactics.shtml 

Dustin, notice that the tests are green. 

1. Number 3 is >

Do you play  Dribble Across a Square at every practice? This is important -- play it at the start of practice as a warm-up -- twice with a 10 step wide square and then twice with a 14 step wide square.

Replace the text with (bold the first sentence AND bold the link) >

Dribbling is the most important soccer skill. To be good dribblers, players must able to dribble thru traffic while under pressure. Dribbling around cones is NOT a good way to train players to dribble in traffic while under pressure. The best way to train players to have great dribbling skills is by playing the Free Dribble Across a Square SoccerHelp Practice Game as a warm-up to start every practice. Every player has a ball and players dribble thru each other and keep score, so there is traffic and pressure to play fast - this Practice Game trains instinctive reactions. You will see results within 2 practices. We invented this drill and it is exclusive to SoccerHelp. Below is a typical of the results you can expect - 

"At every practice we do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA

2. Move number 3 about "Dribble Across a Square" to be # 1

3. After you have moved  "Dribble Across a Square" to be # 1, THEN   # 3 will be the para that starts " Do you play Dribble Around Cone & Pass Relay Race?"

The current text is >

Do you play Dribble Around Cone & Pass Relay Race? Use it to teach Aggressive Receiving - this is important - your players need to get more aggressive about winning the ball. Play it with pairs and give the winners a patch. You will get better, faster results from focusing on Aggressive Receiving than you will from focusing on passing - Aggressive Receiving is more important to teach.

Replace the text with below  (Bold  Teach Aggressive Receiving - Dribble Around Cone & Pass Relay Race goes to http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml     and  Aggressive Receiving  goes to  http://www.soccerhelp.com/terms/soccer-aggressive-receiving.shtml and    goes to http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_P.shtml#pass_to_space  ) >

Teach Aggressive Receiving - Aggressive Receiving means to train your players to be alert, ready for passes, to expect passes to Open Space (instead of always to their feet), and that they MUST anticipate bad passes, aggressively stop passes, and move to the ball before a defender can get to the ball. The exclusive SoccerHelp Dribble Around Cone & Pass Relay Race Practice Game is the best way to teach Aggressive Receiving . Every pass isn't going to be perfect and Receivers need to NOT expect perfect passes. Also, you will want to teach your players to Pass To Space (instead of always Passing to Feet) because that teaches them how to use Open Space and your attack will be much faster and better. For Passing to Space to work, your Receivers need to be taught that a pass might be made to Open Space instead of to their feet. You will want to praise and reward Aggressive Receiving and make a big deal out of it until that is the normal way your players play. If you are a Premium member, check out the Practice Game to teach "Passing to Space" at www.soccerhelp.com/premium/practice_games/Pass_Run_Shoot.shtml . Below is what coaches say -

"We played Dribble Across a Square and Dribble Around the Cone and Pass Relay Race at every practice, and the results were phenomenal." Greg, U9

"I tried hard to emphasize Passing To Space rather than passing to feet. The girls weren't good enough at passing and trapping to pass to feet." Corey, U12G

4. number 2 will be >

Train Your Players to Be Brave, Tough and Aggressive. Use the free Aggressive Soccer Drill to toughen up your players and get them used to contact so they don't get pushed around. If you are a Premium Member, also use the Win the 50/50 Ball No Lines Drill to train players to win 50/50 balls.

> Dustin, Bold the first part instead of underlining. 

And Add to the end of it >

Below is what coaches say.

"This is working beyond belief. Some of my timid girls are now amongst the toughest on the team." Mark, U1OG

"This made an immediate improvement on how to fight for a ball." Coach Chuck, U10B

So it reads >

Train Your Players to Be Brave, Tough and Aggressive. Use the free Aggressive Soccer Drill to toughen up your players and get them used to contact so they don't get pushed around. If you are a Premium Member, also use the Win the 50/50 Ball No Lines Drill to train players to win 50/50 balls. Below is what coaches say.

"This is working beyond belief. Some of my timid girls are now amongst the toughest on the team." Mark, U1OG

"This made an immediate improvement on how to fight for a ball." Coach Chuck, U10B

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
