### ISSUE TITLE
Contact Us on SH Home doesn't work, 6-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#108]
Dustin, 

Dustin, on SH Home, the Contact Us link below doesn't go to the correct page. It goes to a page that says >

The page you requested cannot be found!

Contact Us - We welcome your comments. Please report any errors or problems with using this site. TERMS OF USE:

**Comment by dustinschaerer** [comment]
@david-huddleston This was a simple fix, it's completed.
