### ISSUE TITLE
Contact Us on SH Home still doesn't work, 6-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#109]
Dustin, on 6-28-17 I sent you this email .

Dustin, on the bottom of SH Home, at the first of the "Terms of Use" para, the Contact Us link  doesn't work  >

Contact Us - We welcome your comments. Please report any errors or problems with using this site. TERMS OF USE:

The link still doesn't work. 

The link goes to > http://www.soccerhelp.com/soccershop/contact/ 

but when you click it, that page says >

The page you requested cannot be found!

David

**Comment by dustinschaerer** [comment]
@david-huddleston It's definitely updated, so please try clearing your page cache.  I just use Control + F5 to reload the page.

You can see the updated link URL in the bottom left corner now points to www.soccerhelp.com/soccershop/contact

Which doesn't have the trailing slash at the end.

![contact](https://user-images.githubusercontent.com/1232192/27697403-033fcf68-5ca9-11e7-8f0a-11aebaaecc89.png)

Dustin

**Comment by dustinschaerer** [comment]
Please close this ticket after confirming it works on your end.
