### ISSUE TITLE
After SH is on New Server - Changes to make to SH Home Page and a Few Other Pages

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#11]
Dustin, AFTER you get SH switched to a new Server, make the changes below.

Dustin, on 6-3-17 at 2:45 PM CST I sent you what is below in an email so you can see the report if you want to - 

Dustin, make the changes below to SH. Most of it is to SH Home, 

A.1. Do this AFTER we move to a new server -----
The Report says to 
“Canonicalize your IP address “

A.2.  on SH Home, the current title is 

Drills, Patches, Positions, Formations, Premium

Change it to 

Soccer Drills, Patches, Formations, Premium 

B. IMAGE ANALYSIS

12 images -- 
- All images have alt tags
- Add your exact keyword to an alt tag (Dustin, add "Soccer Drills" to the top Image - the Soccerhelp logo image ) 
- Add “Soccer Drills” to the top image - the SoccerHelp Logo image file name
- Remove any underscores in image file names

C. HEADING TAGS (Dustin, changes below) 
H1 Tag: Soccer Drills, Patches, Formations, Premium (Dustin, see # 1 above)
H2 Tag: Soccer Drills
H3 Tag: Soccer Drills

D. Add a link below the Site Map link that says “xml Site Map” and goes to the “xml Site Map”

E. CODE ANALYSIS  (Dustin, see below – are any of the things listed feasible?) 
Fail - HTML is not W3C validated
Fail - Remove inline CSS
Fail - Text to HTML ratio is too low (< 25%)
Fail - Add schemaorg markup

F. Delete the outbound links below -

   1. On the Right side bottom, delete the section Titled “Soccer Links” and the delete the 3 links – 

- FIFA
- National Soccer Coaches Association of America
- U.S. Youth Soccer

   2. At the bottom delete the sentence that includes a link –
To read more visit https://kickfornick.org/

G. Delete the following links in the alphabetical list –

   1.  Girls Soccer Training (it is a re-direct to https://soccerhelp.com/soccershop/training-girls-and-women-to-win-dvd-review

   2.  Mia Hamm Videos/DVD's 

   3. Newsletter Sign Up

   4. Delete the Second “Soccer Drills” link that goes to  http://www.soccerdrills.net/

   5. “Soccer Formations, Youth”  link that goes to http://www.soccerformations.net/ 

   6. Delete the Second “Soccer Patches” link that goes to http://www.soccerpatchesforkids.com/ )

   7. Delete the “Soccer Pictures and Soccer Photos” link that goes to https://www.soccerhelp.com/Soccer_Pictures_Soccer_Photos.shtml 

   8. Delete the first “Youth Soccer Drills” link that goes to http://www.youthsoccerdrills.com/ 

   9.  Delete the l“Soccer Positions” link that is Near the end of the list  (eighth form the end) that goes to http://www.soccerpositions.net/ 

H. Update the Copyright date from 2016 to 2017 -
Copyright 1999-2017

i. On https://www.soccerhelp.com/soccer-articles/090206-soccer-drills-aggressive.shtml  , under No. 1, delete –

   c. Try April Henirichs "Combat" game. To see it, watch the video clips on SOccerHelp Basic.

J. On https://www.soccerhelp.com/Soccer_Pictures_Soccer_Photos.shtml 

On this page, delete No. 1 and No. 2 and only leave the last sentence which is –

For Soccer Field Diagrams and information, see Soccer Field Index here on SoccerHelp.com

**Comment by dustinschaerer** [comment]
@david-huddleston This is all completed, on our current server, and I'll make sure the changes get rolled into the new server as well, except for these items, which I'll need to revisit once the server is ready:

C. HEADING TAGS (Dustin, changes below)
H1 Tag: Soccer Drills, Patches, Formations, Premium (Dustin, see # 1 above)
H2 Tag: Soccer Drills
H3 Tag: Soccer Drills

D. Add a link below the Site Map link that says “xml Site Map” and goes to the “xml Site Map”

E. CODE ANALYSIS (Dustin, see below – are any of the things listed feasible?)
Fail - HTML is not W3C validated
Fail - Remove inline CSS
Fail - Text to HTML ratio is too low (< 25%)
Fail - Add schemaorg markup

**Comment by dustinschaerer** [comment]
@david-huddleston This is **all completed.**  I'll make sure this is transfered onto the new server with everything else.
