### ISSUE TITLE
Changes to Basic Dribble Across a Square, 6-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#110]
Dustin, I emailed you this on 6-28-17 at 7:40 PM - use the email so you can see colors and bold.

Dustin, on http://www.soccerhelp.com/soccer_drills/Dribble.shtml

1. Make the Title Green so it stands out , like >
Dribble Across A Square ™

2. Add quotation marks in front of all 5 Tests (the green ones and the blue ones). like >

"My daughter is averaging 2-3 goals per game. It's been awesome watching her turn into a great player just by religiously doing SoccerHelp drills." Derik, U10 coach, Premium subscriber for 3 years

3. In the Tests, the Blue are still bold - unbold them , like >

"My daughter is averaging 2-3 goals per game. It's been awesome watching her turn into a great player just by religiously doing SoccerHelp drills." Derik, U10 coach, Premium subscriber for 3 years

4. There is supposed to be a separator line between the section named "U6 & U8 Coaches Read This:" and the section named "Comments" (like there is above) 

5. Under "Teaching Points" >

(a). At the end of the second Bullet, Delete >

For a video of the correct method of Speed Dribbling, see the Anson Dorrance-Tom Stone Soccer Clinic DVD at minute 19:15, "Dribbling for Speed".

(b). Under "Teaching Points", the third Bullet is >

How to do a "Pullback", "Stop/Turn", "Hook Turn", and a "Cutback".

Replace it with >

Different ways to turn. Show them several ways, but let the players choose the way that works best for them.

6. Somehow, a lot of the Black Text got bolded and there is too much bold. It should look like below - when I copied and pasted it, this is how it looked  > 

U6 & U8
Coaches
Read
This:	For U6, make the square 5 adult steps wide (use 4 cones per side instead of just at the corners), spread the players around the square and have the players just dribble across and stop (don't have them turn and dribble back). As soon as they have all dribbled across, have them all face inward and dribble back across to the opposite side and stop. Continue this approach of dribbling across and stopping each time until they have crossed the square 6 to 8 times (each trip across is "one"). Don't try to teach turns and don't keep score, just encourage them all and have fun. The benefit of this for U-6 is learning to dribble in traffic. Tell them to focus on their own ball and to NOT try to kick anyone else's ball. Another option is to put out enough cones that each player has a cone to turn around. U6 players can't understand imaginary lines, but if you give them a cone to go around they can often understand that idea. Don't have them keep score - just have them race for a couple of minutes and then take a short break or do something else in the square and then come back to this game. Again, the idea is to get them used to dribbling through traffic - doing that will improve their confidence, peripheral vision and instinctive reactions. For U8, make the square 6 adult steps wide and don't worry about keeping score. Watch a Video of this Soccer Drill that is a Game

Comment:	This is the best way to teach dribbling and how to use the bottom of the foot & the inside & outside of the foot to stop the ball and turn. Easy set-up & everyone has a ball. This is a great warm-up. It is 10 times better than dribbling through cones & is a good way to evaluate dribbling skill. This game helps children's brains to learn to process a lot of activity, to use peripheral vision, and to make correct, instinctive decisions and maintain composure when under pressure and in heavy traffic. Play Dribble Across a Square as a Warm-Up to start EVERY practice and you will see fantastic results.
Teaches:	•	Control dribbling, speed dribbling, to look up while dribbling, turning, how to dribble through traffic without panicking, shielding the ball, how to naturally find open space, "strength on the ball", dribbling under pressure, and instinctively avoiding other players. Players learn to use peripheral vision, to shield the ball when in traffic, and that they can speed up if they get in the clear. It is a "self-teaching" game and playing the game really teaches these skills and self-confidence & composure in heavy traffic & under pressure. It also teaches composure in chaotic situations and how to recognize openings in traffic and when it's safe to speed up. You will notice an improvement in "field vision" and "field awareness" (the ability to see opportunities in a crowd and across a field, and to make quick, instinctive, correct decisions). Playing this in a square that is 10 steps wide teaches "Control Dribbling", and making the square 15 to 20 steps wide will teach players how to look for Open Space, accelerate, Speed Dribble and "Breakaway" (how to look for Open Space, accelerate into it, and Speed Dribble). This is a SoccerHelp.com practice game that is a drill.
Keep Score:	Remember to have the players keep score so it will be "Game-Realistic" (so there will be competition and pressure) and so you can monitor progress. Give "tips" at the end of each Game about how they can improve (see below for good tips). Play this game 3 times to 6 with the Square about 10 steps wide (use a "step" the length of your players steps) AND 3 MORE TIMES to 6 with the Square 50% larger (e.g., about 15 of your player's steps wide). That will create over twice as much Open Space.
Set-up:	•	Use 4 disk cones to make a square about 10 steps wide (smaller or larger depending on age & number of players) -- make your "steps" the size of your players; so a "step" for U-8 is shorter than a "step" for U-14... by doing this, the square will always be about the correct size for your players.
•	Every player has a ball
•	Spread players around the square, all facing inward (like below):
•	Play this game 3 times to 6 with the Square about 10 steps wide (use a "step" the length of your players steps) AND 3 MORE TIMES to 6 with the Square 50% larger (e.g., about 15 of your player's steps wide). That will create over twice as much Open Space.
 

The Game:	Play this game 3 times to 6 with the Square about 10 steps wide (use a "step" the length of your players steps) AND 3 MORE TIMES to 6 with the Square 50% larger (e.g., about 15 of your player's steps wide). That will create over twice as much Open Space.
•	All players start on "Go" & each player dribbles across the square & back. (Tell them to dribble to the imaginary line on the opposite side of the square, make a turn & dribble back to where they started. Point out at the first of the game that the cones create an imaginary "Starting Line" and "Turning Line" for each player).
•	Teaching Turns Among the best ways to turn are a "Pullback", a "Stop/Turn", a "Cutback" or a "Hook Turn" to turn. Demonstrate the different ways to turn and then let each player choose the one that works best for them. When going really fast, a "Stop/Turn" is a good way to turn... when not going so fast, any of the 3 other ways are good. The way that is best for one player may not be the best for another. If certain players are doing better on their turns, have them demonstrate while the others watch. Your players will want to be able to turn better so they can improve their scores. You can give them "Tips" about how they can get a higher score. Here is a brief description of several turns: Do a Pullback, aka a "Drag Back", by putting the bottom of the foot on top of ball to stop it & then pull it back in the direction you came from. Do a Hook Turn by pulling the toes up & turning the foot so the outside of the foot can "hook" the ball, stop it & pull it back. A Cutback uses the inside of the foot to hook the ball). A Pullback is a good way to make a 180 degree turn to go the opposite way, but for most other turns or to go around a player or around a cone (like in the Dribble Around Cone & Pass Relay Race) it will work best to use the inside or outside of the foot. 
•	Tell players to look up while they dribble so they don't run into each other (don't worry, there won't be many collisions).
•	VERY IMPORTANT - READ THIS ABOUT KEEPING SCORE and GIVING TIPS: Each player should keep count of his or her trips across the square. A player gets one point each time he or she turns. Have the first player to reach the target score (e.g., 6 or 8) yell "Done" and raise their hand. As soon as a player yells "Done", blow your whistle and have all the other players stop as soon as they get back to the closest side of the square. Then, ask each player his or her score so you can monitor each player's progress and give tips for improvement. What I would do is start with one player and ask: "John, what was your score?" and then quickly ask each of the others. It is also an opportunity to praise anyone who has improved or to give tips such as "It is very important to keep control of the ball on your turns. If you lose the ball it will cost you several points". This only takes 2 or 3 minutes. The game is self-teaching, but it is helpful for the coach to be encouraging and to point out at the end of each Game how players can improve their performance by giving "tips" on how they can improve their score. A simple way to do this is to point out what the player did who won the Game. For example, in the smaller square, the winner will be the player who keeps the ball near his feet, "Shields" the ball from traffic, and makes the turns without losing the ball -- the winner will keep control of the ball. In the larger square, the winner must still keep control of the ball, BUT the winner will also look for Open Space and kick the ball into it so he can Speed Dribble, and he will still make the turns, so he can't kick it too hard. This is very much like a real game, where if you don't keep control you will lose the ball. This approach works because the players want to improve their score and if they use your "tips" they will see immediate results and get higher scores. See Monitoring Progress below for more about this. 
•	Play this game 3 times to 6 or 8 with the Square about 10 steps wide (use a "step" the length of your players steps) AND 3 MORE TIMES to 6 with the Square 50% larger (e.g., about 15 steps wide). That will create over twice as much Open Space. The smaller square creates more traffic and teaches control dribbling in traffic and chaos. The larger square creates more open space and teaches players how to look for Open Space, Accelerate into Open Space and "Breakaway". You can choose whether to play to 6 or 8. Play at the start of practice as a warm-up and at the end of practice until dribbling skills improve or your team gets tired of this game. For beginners, let them decide how to turn using the method they are most comfortable with. For advanced or select players, require a Pullback one game, then a Hook, then a Cutback. Let a "Stop/Turn" count for a Pullback. 
•	Teaching Acceleration into "Open Space" and "Speed Dribbling", and how to Breakaway. You can use the larger square to teach your players how to look for Open Space, accelerate into open space, and Speed Dribble -- this is an important skill that will help them learn how to "blow past" an opponent and will lead to "breakaways". In the larger square, players will still have to "Control Dribble" when in "traffic," but they will also have to learn how to look for "Open Space" and to quickly accelerate and "Speed Dribble" when they get Open Space. Tell them that they can go faster if they kick the ball in front of them, but they MUST still keep control of the ball. If they kick it too far, they won't be able to make their turn. In most games, a player will lose the game if he or she loses control of the ball even once. The game is self-teaching, but it is helpful for the coach to be encouraging and to point out at the end of each Game how players can improve their performance by giving "tips" on how they can improve their score. A simple way to do this is to point out what the player did who won the Game. For example, in the smaller square, the winner will be the player who keeps the ball near his feet, "Shields" the ball from traffic, and makes the turns without losing the ball -- the winner will keep control of the ball. In the larger square, the winner must still keep control of the ball, BUT the winner will also look for Open Space and kick the ball into it so he can Speed Dribble, and he will still make the turns, so he can't kick it too hard. This is very much like a real game, where if you don't keep control you will lose the ball. This approach works because the players want to improve their score and if they use your "tips" they will see immediate results and get higher scores.
Teaching Points:	•	"Control Dribbling" - When in traffic, keep the ball close to your feet so you can protect it ("shield" it) and learn how to look up while dribbling by keeping the ball close to your feet so you know where it is.
•	"Speed Dribbling" - Keep the ball near your feet when you are in traffic, but look for Open Space and when you get "open", kick the ball into the Open Space using the inside of foot or the "laces" and run to it so you can go faster, but you must still keep it under control so you can turn, so don't kick it too hard. To Speed Dribble, you kick the ball forward using the outside top of the front of the foot (not the inside of the foot). For a video of the correct method of Speed Dribbling, see the Anson Dorrance-Tom Stone Soccer Clinic DVD at minute 19:15, "Dribbling for Speed". 
•	How to do a "Pullback", "Stop/Turn", "Hook Turn", and a "Cutback".

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
