### ISSUE TITLE
Add a link to Premium Tips & Tactics Navigation page, 6-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#111]
Dustin, I emailed this on 6-28-17 at 7:49 PM - use the email .

Dustin, on  http://www.soccerhelp.com/premium/Tips_Tactics_Index.shtml , add as the first link (underlined, but NOT bold) >

Concepts That Apply to All Formations - Best Formations for Rec Teams - How to Teach a Formation - Assigning Players - Positioning Rules - Case Study of How a U12 Coach Taught Positions so His Weak Team Won a Tournament

that goes to http://www.soccerhelp.com/premium/Formations-Tips-Rec.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
