### ISSUE TITLE
On SH Home, add 3 new links and change a link in Alphabet List, 6-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#112]
Dustin, I emailed this on 6-28-17 at 10:43 PM  

Dustin, delete the version I sent you on 6-28 at 8:06 PM and use this one.

Dustin,

On SH Home, in the Alphabet list > 

1. Add as the first link in the Alphabet List >

70 Tips and Tactics

that goes to http://www.soccerhelp.com/soccer-tactics.shtml 

2. The Current first link is  20 Soccer Coaching Tips

Change the link name to >

21 Tips for Weak Teams

3. Add as a new third Link >

29 Practice Tips

that goes to >

http://www.soccerhelp.com/soccer-practice.shtml 

4. Add as a new fourth Link > 

18 Tips for U4 and U6

that goes to >

http://www.soccerhelp.com/U4-U6-soccer-coaching.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is also completed.
