### ISSUE TITLE
Delete graham-and-doddsville.com website, 6-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#113]
Dustin, I emailed this on 6-28-17 at 10:38 Am

Dustin,

Go ahead and delete the graham-and-doddsville.com/ website.

It isn't needed any longer.

David

**Comment by dustinschaerer** [comment]
@david-huddleston Its deleted.

**Comment by david-huddleston** [comment]
Dustin,

It is still online.

David

**Comment by dustinschaerer** [comment]
@david-huddleston I had deleted it from the new server but it was still on the old server with its DNS records still pointing to that old server.   I've suspended the account on the old server so it no longer works.
