### ISSUE TITLE
Changes to Premium 8v8 Formations, 6-29-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#114]
Dustin, i emailed you this on 6-29-17 at 11:32 AM - use the email so you can see colors and bold. 

Dustin, delete the version I sent on 6-29-17 at 11:27 AM - the first link was incorrect. 

Dustin, on http://www.soccerhelp.com/premium/Formations_And_Tips_8v8.shtml > 

1. Under " Index and Links to Topics: ", the second and third paras are >

Read this first - The 2 main questions to consider before selecting a Formation and Style of Play 
And then read no. 39: Read this if you play 8v8, 2-1-2-2 vs. 3-3-1 and 2-3-2 (this coach tried them all. Read about his experiences).

REPLACE THEM WITH (Dustin, be sure the links go to the correct destination - the current links go to # 36  and # 38 >

Read number 35 first - The 2 main questions to consider before selecting a Formation and Style of Play  
And then read no. 38, which is titled - Read this if you play 8v8, 2-1-2-2 vs. 3-3-1 and 2-3-2 (this coach tried them all. Read about his experiences).

2. Can you write a script to unbold all the links on this page (just the red Links)? If so, do that. If you can't, unbold the Links list - it is too much bold >

The links below are all Bold Red on the page. 

Read this first - The 2 main questions to consider before selecting a Formation and Style of Play. 
And then read no. 39: Read this if you play 8v8, 2-1-2-2 vs. 3-3-1 and 2-3-2 (this coach tried them all. Read about his experiences).
1.	How to teach a 2-1-2-2 formation, Defending, Attacking, Positioning, Movement, Shifting.
2.	Formations for 8v8. How a U-10 Coach, playing 8 v 8, can score more goals. How to teach a 2-1-2-2, and tips for scoring more goals. Also, which player (i.e., a FB or a MF) should pressure the ball when it is in the defensive corner (i.e., the corner in your "Defensive Third"). 
3.	8 v 8 formations for a U-10 Tournament team. SoccerHelp recommended a 3-3-1. Assigning positions and tips for scoring more goals.
4.	Premium Practice Games that will improve dribbling and tackling skills for U-10 team playing 8v8.
5.	What is the best 8v8 formation for U-9 Rec team?
6.	How to keep U-10 players from bunching up.
7.	Tips for playing a 2-1-2-2 formation (2 FB's, a Stopper, 2 MF's and 2 Forwards).
8.	8v8, 2-1-2-2, Importance of Controlling the "Center of the Field", Attacking Plan
9.	8v8, Comparison of 2-2-1-2 and 2-1-2-2; Should your best athlete play Goalkeeper or Stopper? Stopper Importance; Boys Rec U-13
10.	8v8, 2-1-2-2, 1-2-2-2, 2-1-3-1; Girls U-10 competitive
11.	8v8, How to teach a 2-1-3-1; U-12 Rec team needing to score more goals
12.	8v8, Detailed instructions for teaching a 2-1-2-2
13.	8v8, Discussion of 2-1-2-2-, 2-2-2-1, 1-2-2-2, and 2-1-3-1; Comparison of results from playing 2-2-2-1 and 2-1-2-2; U-11 competitive team
14.	8v8 Formations for U-11 Competitive Team with only 2 subs that is "playing up" - 2-1-2-2, 1-2-2-2, 3-2-2, 2-1-3-1
15.	Formations and Styles of Play for 8v8 with Few Subs, 3-3-1 and 2-1-2-2
16.	8v8 Formations to Hide Weak Players, 2-1-2-2 vs. 2-1-3-1
17.	8v8, 2-1-3-1 vs. 2-3-2 vs. 3-2-2 (a 2-1-3-1 is recommended), Tactics for Weak Teams that Are Losing their Matches
18.	8v8 Formations, new article, 2-1-2-2 compared to 2-1-3-1 (the 2-1-3-1 is recommended), How to Score More Goals, Assigning Positions Rules, Positioning Rules, Shifting, Defensive Assignments, Teaching Positions, Tactics.
19.	8v8, Attacking and defensive formations, conservative defense, 1-3-2-1, 3-1-2-1, 3-3-1
20.	8 v 8 Tips, 2-1-2-2, How deep should MF's and F's drop to help defend? Teaching Forwards to Stay in Position and Win Cleared Balls.
21.	8v8, 2-1-2-2, Styles of Play, Stopper role, winning the ball, Fullback "Rules", stopping fast counterattacks, MF's helping defend, full field defense, slowing the attack -New!
22.	8v8, comparison of 2-1-2-2 and 2-3-2; Stopper Importance in 8v8; Analysis, Evaluation and Tips; Controlling the Center of the Field; Girls Rec U-12.
23.	Tips for a Coach with a Very Weak Soccer Team, 8v8 Soccer Formations, Defending Deep Style of Play, How to Select a Stopper, Fullbacks, Forward and Midfielders, Where to Play Weak, Unskilled, Timid Soccer Players, An Approach that is Better than Scrimmaging, Practice Games I Recommend, Coaching Rule No. 3 
24.	How to Have High-Energy, Up-Tempo Soccer Practices, "Team Work Scores Goals" Cheer, New Soccer Coach with a Mixed Group of Players, Only 4 Soccer Practices Before Games Start, Tips, Soccer Tactics, Soccer Formation, Style of Play, Where Soccer Players Can be Most Successful, 8v8, 2-1-2-2 Soccer Formation
25.	Soccer Formations and Styles of Play for All Star Rec Team Playing 8v8, 2-1-3-1 vs. 2-1-2-2 vs. 1-2-1-2-1 Soccer Formations, Pressuring a ball in the corner, Advantage of a soccer Forward who is a "quick" dribbler, Advantage of a strong center midfielder
26.	Strategy for Playing a Better Soccer Team that Has Killed You in Prior Games, Is it better to "Pack In" the defense, or to use a soccer formation that has 4 or 5 "Layers" so you have a lot of Depth and control the Center? How to attack a "Packed In" soccer defense, 2-1-2-2 vs. 4-3 soccer formations, What type of soccer player to play at Stopper? Problem with Putting Timid Players at Fullback
27.	Playing a Better, Older, Undefeated Soccer Team 
28.	Soccer Defending - Balls played to Corner of your Defensive Third, Should you try to win the ball? If so, should it be the FB, the ST or the MF? 2 advantages of kicking the ball out of bounds
29.	8v8 Soccer Formations that Allow Fullbacks to Push Up, 2-1-2-2/1-2-2-2 soccer formation that uses a Stopper who becomes a Sweeper, Advantages of a 2-3-2, A soccer formation that emphasizes teaching attacking skills, Advantages of "Depth" and controlling the Center, Why clear the ball straight ahead? Should you defend the corners? How? 
30.	Importance of a Stopper in 8V8 Soccer, 2-1-2-2 vs. 2-3-2 Soccer Formation, Analysis, Evaluation and Tips, How to launch a counterattack and score more goals against a Pushed Up Team 
31.	25 Soccer Coaching Rules, How to Teach a Fast Break Soccer Counterattack, Avoiding Getting Caught in Transition, How to Teach "Shifting and Sagging" so you have good defensive field coverage, support and depth, How to Teach Soccer "First Defender/Second Defender", Is it better to be strong in the Center, or to defend the entire width of the soccer field? How to Increase Soccer Scoring, 8v8 2-2-1-2 Soccer Formation
32.	How to select a soccer Center Midfielder, Forward and Stopper - with a good athlete and 2 good players, Rec coaches can win most games if you have the right soccer formation, Advantages of a Strong Soccer Stopper and Center Midfielder, How to Defend the Center of the Soccer Field, Is it necessary to Defend the "wings" of the Field? Why you MUST limit the Field Coverage of your CMF, Pressuring Balls in Corner of Defensive Third, Best Positions for Weak Soccer Players, 8v8 Soccer Formations, 2-1-3-1 vs 2-1-2-2, Why 2-1-3-1 is Best for Most Rec 8v8 Soccer Teams, Who is Gerd Muller and why is he in this article?
33.	8v8 Soccer Formations, 2-2-1-2 vs 2-1-2-2 vs 1-3-3, How to Choose the Soccer Formation that Will Work Best, How to Adapt a Soccer Formation to Fit Your Team, Scoring More Soccer Goals, Soccer Field "Width" vs "Depth" - Which is More Important? Team Discount on the SoccerHelp Foot Skills and Moves Training DVD, Letter from a U11 Girls Competitive Soccer who Is Also a High School Coach
34.	Soccer Coaching Success Story, U11 Competitive Soccer, 8v8, 2-2-1-2 Soccer Formation, How a Team that Had Lost for 3 Years Started to Win, Only Gave Up 5 Goals in 12 Games, Soccer Tips for How to Score More Goals, Condition Soccer Players by Sprints -- Not Long, Slow Runs 
35.	The 2 main questions to consider before selecting a Formation and Style of Play
36.	8 v 8 Soccer Formations and Positions, 2-1-3-1 vs. 2-1-2-2, Target Forward and Stopper, What to Do if All Your Players Want to Score? How to Make Every Soccer Position Important
37.	Advantages of a 2-1-3-1 formation and how to launch a fast couinterattack from this formation
38.	Read this if you play 8v8, 2-1-2-2 vs. 3-3-1 and 2-3-2 (this coach tried them all. Read about his experiences). NOTE: Most Rec teams will do better using a 2-1-3-1 instead of a 2-1-2-2, because a 2-1-3-1 provides more strength in the center of the field and allows you to put weak players at RMF or LMF. Read about it at #18, 8v8 Formations, new article, 2-1-2-2 compared to 2-1-3-1
39.	3-1-3 vs 2-1-2-2 vs 1-2-2-2 vs 3-3-1 for a Team that Pushes Up
40.	2-1-3-1 works well for most Rec teams because it is very strong in the Center at Striker, CMF and Stopper.
41.	When to Push Up Fullbacks on attack? 3-3-1, 3-1-3, 1-2-2-2 compared
42.	1-2-1-3, 15 tips to improve your soccer team in 2 weeks, U10 Rec, Recruiting parents to coach Fullbacks and the Forward during games
43.	Tips from a U8 soccer coach playing 8v8 who won big using a 2-3-2 soccer formation and pushing up on attack

Number 3.   In number 18 at http://www.soccerhelp.com/premium/Formations_And_Tips_8v8.shtml#18 , unbold AND Un-italicize the letter (I pasted it below - there is too much bold) >

I'm a SoccerHelp Premium Member and I love the site. I know this is typical of several requests and I have read your site thoroughly, but I was helping to get some assistance on an issue. 
I coach a standard U11 girls team in a competitive Rec league in the DC area. I have implemented all the drills on your site throughout the year and use patches but we have recently gone into a scoring drought. We play Dribble Across a Square, "Dribble Around Cone and Shoot Relay Race" and various other helpful games every week at practice, but we can't put the ball in the goal for some odd reason. We also spend about 20 minutes each week on finishing drills and several players can do this in practice. 
Based on information on your site, we play a 2-1-2-2 formation. Here's a description of our players -- 3 players have excellent ball handling skills but they tend to hold onto the ball a bit too long, preferring to beat defenders off the dribble. I am working with them on the quick pass concept. These 3 players play midfield and one plays forward -- she is our best goal scorer but is above average at best. Our other forward is a player who is excellent in field positioning and has a nose for the goal, but she is not exceptionally fast and does not have great ball skils. She can, however, finish shots if they are in front of the goal. 
We play our best 2 athletes at stopper. One of them I described above, she is a quick player with great ball moves, not a very good distributor. The other player is a good athlete but has more of a defensive mindset. She pushes up nicely but tends to kick the ball forward towards the mids when it comes to her. We get into a lot of kicking matches when she's in the game. 
We have three excellent defensive players. Two of the defensive players are slower afoot but very aggressive and they can clear the ball nicely. The other defensive player is very quick and wins many balls, she can clear but not as far as the others. I rotate this last player to sweeper or offense sometimes as she is quite quick, but she does not have a nose for the goal. 
We have 3 other marginal players who I tend to rotate at mid or forward positions, sometimes letting one of them play fullback. We sub often in an attempt to keep the mids and sweeper fresh, as they do a lot of running. 
We started off the season with a 5-0 victory but have not been able to put the goal in the net in the past four matches, losing each of those games 2-0. 
I tell the team that the team with the most players in front of the goal on offense tend to score the most, but we often take the ball into the corner and try a cross, only to have it roll across the middle with nobody on far post or, more frequently, the ball is deflected. 
My feeling is that we should work on midfield positioning to create a swarming effect whenever the team has the ball on the other end of the field (which is about half the time, even against good teams) but I don't really know how to appropriately emphasize this point to the girls. We've tried crossing drills, corner drills, etc. but still have a tough time getting the ball in front of the other team's goal. 
Any help that you could supply would be greatly appreciated!!! I love the site and have used the drills and strategy quite a bit so far this year. I played college soccer, but coaching a Rec team is different. 
Thanks much, 
Blair

**Comment by dustinschaerer** [comment]
This is completed.
