### ISSUE TITLE
Delete links to Just Kickin It video on 4 pages, 6-29-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#116]
Dustin, on 6-29-17 I emailed you this at 5:11 PM

Dustin, (the link Dribble Around Cone & Pass Relay Race   goes to http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml ) 

delete the link to Click here to read a review of the "Just Kickin' It" video on the 4 pages listed below  and in its place put >

See Dribble Around Cone & Pass Relay Race No Lines Drill.

Below are the 4 pages to delete the Just Kickin It link from >

http://www.soccerhelp.com/TeachingIOF.shtml

http://www.soccerhelp.com/Overview.shtml

http://www.soccerhelp.com/2Touch.shtml  

http://www.soccerhelp.com/ProblemsIOF.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
