### ISSUE TITLE
Changes to Youth Soccer Positions, 6-30-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#117]
Dustin, I emailed you this on 6-30-17 at 8:58 PM. Use the email .

Delete the prior version from 8:56 PM on 6-30-17

Dustin, on http://www.soccerhelp.com/youth-soccer-positions.shtml 

1.  Dustin, after you make the change below, W3C this page

2. In number 12, the last sentence is >

If you need to "hide" some timid, unskilled players think about a 2-1-3-1 or 3-1-4-2 formation and put the weak players at RMF or LMF, and strong players at CFB, Stopper and CMF.

Replace 3-1-4-2 formation  with >

3-2-3-2 formation

So it reads (no links in this sentence ) > 

If you need to "hide" some timid, unskilled players think about a 2-1-3-1 or 3-2-3-2 formation and put the weak players at RMF or LMF, and strong players at CFB, Stopper and CMF.

**Comment by dustinschaerer** [comment]
@david-huddleston This is validated and all changes are in place now.
