### ISSUE TITLE
Add new first para to Terms, Styles of Play, 6-30-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#119]
Dustin, I sent this email on 6-30-17 at 10:42 AM

Dustin, on http://www.soccerhelp.com/terms/soccer-styles-of-play.shtml , 

Add as a new first Para (the link goes to http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_A.shtml )  >

If there are terms or concepts you want to read about such as First Attacker or First Defender, use the  SoccerHelp Dictionary

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
