### ISSUE TITLE
Move 3 links in the Soccer Positions Basics Links List, 6-30-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#120]
Dustin, I emailed you this on 6-30-17 at 3:02 PM

Dustin, on http://www.soccerhelp.com/Soccer_Positions_Basics.shtml 

> In the Links List, move the 3rd, 4th and 5th links to be # 1, 2 and 3. Below are the 3 to move >

Youth Soccer Positions - How to Teach, Coach & Assign
How to Evaluate Players and Assign Soccer Positions
How to Evaluate Soccer Players and Choose a Soccer Formation

After you move those 3 , the Links List will look like :

Youth Soccer Positions - How to Teach, Coach & Assign
How to Evaluate Players and Assign Soccer Positions
How to Evaluate Soccer Players and Choose a Soccer Formation
Soccer Positions Overview
Diagrams of Soccer Positions & Soccer Formations
SoccerHelp Kick-Offs Navigation Page
Soccer Formations Overview
Assigning Soccer Positions

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
