### ISSUE TITLE
Fifth version - Change to Soccer Formations article, 7-3-17, 1:54 PM

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#121]
Dustin, I emailed you this Fifth Version on 7-3-17 at 1:54 PM  - use the email so you can see colors, fonts, etc.

Dustin, I added a sentence to the end of this para >

How you Assign Positions can also make a huge difference. For example, the most important position for most youth Rec teams is Center Mid and the second most important is Stopper - great players at those 2 positions can make a huge difference. Another example - if you put timid players who are afraid of contact at Fullback they will give up a lot of goals and feel like failures - train players to be Brave before you put them at Fullback. See the Recommended Articles below for much more about Assigning Positions. Also see the section below titled "Tips for Assigning Positions".

Dustin, delete the prior 4 versions that I sent you on 6-30-17 at 5:12 PM and 7:16 PM, on 7-2-17 at 5:05 PM,  on 7-3-17 at 1:11 PM, and use this Fifth Version - I totally re-wrote it >

Dustin, on   www.soccerhelp.com/Soccer_Formations.shtml > 

1. This is a TOTAL re-write of this page. Delete all the text on the page and start over. 

The new text is at the end - Scroll Down and you will see. 

The link destinations and the H2, H3, Title Tag, etc. are below

2.  AFTER you make the changes below >

(a).  W3C validate this page

(b).  also lower case and dasherize the URL

3. Have all text, Titles and Sub-Titles be the same size. 

4. Change the Title Tag, Meta Description and Key Words as shown below >

<title>Soccer Formations - Youth Soccer Formations</title>
<meta name="keywords" content="Soccer Formations, Youth Soccer Formations">
<meta name="description" content="Soccer formations for youth Rec and Select U8 to U18. Your formation can make a huge difference in your team's fun and success. How to evaluate your team and choose the best formation. The best way to teach a formation and positions. 6v6, 7v7, 8v8, 9v9 and 11v11.">

5. The H1 is the Top Title > Soccer Formations

6. Have the H2 be > 

How to Choose the Best Soccer Formation and Style of Play

7. Have another H3 be >  What Soccer Formations Numbers Mean

8. Also make the sub-title below a H3 >     

How to Teach a Soccer Formation and Positions

9. Remove the H3 designation from >

<h3 class="hl">See prices for our iron on Motivational <a href="/soccershop/soccer-patches">Soccer Patches</a></h3>

10. I think all the links in the article actually work, but a list of the links (and the destination)  is below in the same order they are in the Article > 

Style of Play    goes to  http://www.soccerhelp.com/terms/soccer-styles-of-play.shtml
 Push Up   goes to  http://www.soccerhelp.com/terms/soccer-push-up.shtml 
Style of Play    goes to  http://www.soccerhelp.com/terms/soccer-styles-of-play.shtml
 Push Up    goes to  http://www.soccerhelp.com/terms/soccer-push-up.shtml
 Defend Deep     goes to  http://www.soccerhelp.com/terms/soccer-defend-deep.shtml 
How to Select a Formation and Assign Positions     goes to http://www.soccerhelp.com/soccer-articles/120824-Select-Soccer-Formation.shtml 
How to Train and Assign Positions    goes to  http://www.soccerhelp.com/youth-soccer-positions.shtml 
How to Choose a Formation     goes to  http://www.soccerhelp.com/Evaluating_Soccer_Players_And_Teams.shtml 
How to Assign Positions     goes to  http://www.soccerhelp.com/soccer-articles/120316-soccer-positions-assigning-players.shtml 
Sweeper     goes to  http://www.soccerhelp.com/terms/soccer-sweeper.shtml 
Fullbacks      goes to  http://www.soccerhelp.com/terms/soccer-fullbacks.shtml 
Stopper     goes to  http://www.soccerhelp.com/terms/soccer-stopper.shtml 
 Midfielders    goes to  http://www.soccerhelp.com/terms/soccer-midfielders.shtml 
Forward     goes to  http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_F.shtml#forwards 
Shifting and Sagging     goes to  http://www.soccerhelp.com/terms/soccer-shift-and-sag.shtml 
First Defender/Second Defender    goes to  http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_S.shtml#support 
First Attacker/Second Attacker     goes to http://www.soccerhelp.com/terms/soccer-first-attacker.shtml 
 overlap    goes to  http://www.soccerhelp.com/terms/soccer-overlap-and-overlapping-run.shtml 
 counterattack    goes to http://www.soccerhelp.com/terms/soccer-counterattack.shtml 
Center of the Field     goes to  http://www.soccerhelp.com/terms/soccer-center-of-the-field.shtml 
Defensive Third     goes to  http://www.soccerhelp.com/terms/soccer-defensive-third.shtml 
shift and sag     goes to http://www.soccerhelp.com/terms/soccer-shift-and-sag.shtml
shifting & sagging     goes to  http://www.soccerhelp.com/terms/soccer-shift-and-sag.shtml
Depth     goes to  http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_D.shtml#depth 
First Defender/Second Defender     goes to  http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_S.shtml#support 
Defend Deep     goes to  http://www.soccerhelp.com/terms/soccer-defend-deep.shtml 
Soccer Coaching Success Stories      goes to  http://www.soccerhelp.com/soccer-articles/120927-Soccer-Coaching-Tips-Success-Stories.shtml 
 Pushing Up    goes to  http://www.soccerhelp.com/terms/soccer-push-up.shtml
SoccerHelp Dictionary     goes to  http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_S.shtml 
SoccerHelp No Lines Drills   goes to  http://www.soccerhelp.com/soccer-drills.shtml 
Soccer Positions Diagrams     goes to  http://www.soccerhelp.com/soccer-positions-diagrams.shtml 
No Lines Drills  goes to http://www.soccerhelp.com/soccer-drills.shtml 
1,000 Testimonials  goes to http://soccerhelp.com/soccershop/testimonials 
No Lines Drills  goes to http://www.soccerhelp.com/soccer-drills.shtml
How to Select a Soccer Formation and Assign Positions      goes to  http://www.soccerhelp.com/soccer-articles/120824-Select-Soccer-Formation.shtml 
Youth Soccer Positions - How to Teach, Coach & Assign       goes to http://www.soccerhelp.com/youth-soccer-positions.shtml 
How to Choose a Soccer Formation       goes to  http://www.soccerhelp.com/Evaluating_Soccer_Players_And_Teams.shtml 
How to Assign Soccer Positions      goes to  http://www.soccerhelp.com/soccer-articles/120316-soccer-positions-assigning-players.shtml 
6v6 Soccer Formations      goes to  http://www.soccerhelp.com/Soccer_Tips_Soccer_Formations_6v6.shtml 
7v7 Soccer Formations      goes to  http://www.soccerhelp.com/Soccer_Tips_Soccer_Formations_7v7.shtml 
8v8 Soccer Formations       goes to http://www.soccerhelp.com/Soccer_Stopper_Soccer_Formation_8v8.shtml 
9v9 Soccer Formations       goes to  http://www.soccerhelp.com/9v9-Soccer-Formations.shtml 
11v11 Soccer Formations       goes to  http://www.soccerhelp.com/Soccer_Formations_Soccer_Positions.shtml 
Soccer Formation Basics       goes to  http://www.soccerhelp.com/Soccer_Formation_Basics.shtml 
Soccer Positions Basics & Soccer Kick-Offs      goes to  http://www.soccerhelp.com/Soccer_Positions_Basics.shtml 
Soccer Positions Overview      goes to  http://www.soccerhelp.com/Soccer_Positions.shtml 
Read about Premium or Sign-Up  http://www.soccerhelp.com/New_Articles_On_Soccerhelp_Premium.shtml 
11v11 Soccer Formations     goes to  http://www.soccerhelp.com/Soccer_Formations_Soccer_Positions.shtml 
 8v8 Soccer Formations    goes to  http://www.soccerhelp.com/Soccer_Stopper_Soccer_Formation_8v8.shtml 

>>>>Dustin, Below is the text to go on the page and how it should look >>>>>>>>>>>>>>>>>>> 

Soccer Formations

How to Choose Best Formation
What the Numbers Mean
How to Teach a Formation
Depth versus Width
Why the Center is Critical
Diagrams
Tips for Assigning Positions

Soccer formations for youth Rec and Select U8 to U18. Your formation can make a huge difference in your team's fun and success. How to evaluate your team and choose the best formation. The best way to teach a formation and positions. 6v6, 7v7, 8v8, 9v9 and 11v11.

The formation you use will determine the number of players on the field and their positions and responsibilities. For U6, don't worry about soccer formations or Styles of Play - just have fun and use SoccerHelp No Lines Practice Games to develop soccer skills.

For most Rec teams, a formation with Depth (like a 2-1-3-1) will work better than a typical formation that has more width (like a 3-2-2 or a 3-3-1).

How to Choose the Best Soccer Formation and Style of Play

The Formation and Style of Play you choose for your team should be based on -
1.	Your player's skill, speed and stamina 
2.	Whether you have unskilled players, slow players, or timid players who are scared of contact
3.	The speed of your Fullbacks and of the opposing Forwards
4.	The number of subs you have
5.	The width and length of the field you play on
You want to choose the Formation and Style of Play that is best for your team. If you have a great team of Select players who are all fast, skilled, and have stamina, and your team can play a short passing attack like the best Pro teams do, then you need a formation that has width and you can Push Up your Fullbacks to support your attack. But if you have a typical Recreational team that has some slow, unskilled, timid, or unmotivated players and only practice once a week, your team can't play like a Pro team and if you choose a Formation and Style of Play that a Pro team would use, it will be a disaster and no fun. This is discussed below by a U12 Recreational coach whose team didn't win a game for 3 seasons.
Your Style of Play is as important as your Formation and can make a huge difference in your team's fun and success. For example, if you Push Up your slow Fullbacks against fast Forwards, there is a chance you will give up lots of goals on fast counterattacks. But slow Fullbacks can be successful if they are Brave and if you Defend Deep (or you can Push them Up if you put a fast Sweeper behind them) - slow Fullbacks can be successful IF you don't ask them to win a foot race against faster opposing Forwards. Another example - if you lack subs and play on a large field, unless your players have fantastic stamina, you will probably want to choose a Formation and Style of Play that limits your player's running. 
How you Assign Positions can also make a huge difference. For example, the most important position for most youth Rec teams is Center Mid and the second most important is Stopper - great players at those 2 positions can make a huge difference. Another example - if you put timid players who are afraid of contact at Fullback they will give up a lot of goals and feel like failures - train players to be Brave before you put them at Fullback. See the Recommended Articles below for much more about Assigning Positions. Also see the section below titled "Tips for Assigning Positions".
The Formation and Style of Play you choose, and how you Assign Soccer Positions, will have a huge impact on how well your team plays, how much fun they have, and how many games they win. Tips are below and at the 4 Recommended Articles. 
Recommended Articles - for more about how to choose the best formation and style of play, and how to assign positions, see How to Select a Formation and Assign Positions ,  How to Train and Assign Positions , How to Choose a Formation , and How to Assign Positions . There are also some tips below for Assigning Positions.
What Soccer Formations Numbers Mean
Soccer formations numbering starts with the Defenders (the Fullbacks) and doesn't include the Goalie. For example, a 1-2-1-3-1 formation would consist of 1 Sweeper, 2 Fullbacks, 1 Stopper, 3 Midfielders and 1 Forward. Conventional numbering of soccer formations, such as a 4-4-2 formation, can be confusing, because midfielders often aren't lined up straight across. For example, when you look at a 4-4-2 on the field it might look like a 4-1-2-1-2. In most formations, there are "right" side and "left" side players. Right and left are as you face the opponent's Goalie - so, if you have 2 Fullbacks, one is the Right Fullback and one is the Left Fullback. 
How to Teach a Soccer Formation and Positions
The best way to teach a Formation and Style of Play is by putting players in their positions on a field and then holding a ball and walking around and teaching them how to shift with the ball when on defense and also where they should be (and NOT be) when attacking. As the ball moves, all players (including the Goalie) should be shifting with the ball and alert. They MUST "Shift and Sag" with the ball to maintain their "Relative Positions". For young players, it will help greatly if you give some specific "Rules" to go by - for example, if you are a "Left Side" player, stay on the left side of the field. This is explained in detail in Premium. If you are a Premium member, see www.soccerhelp.com/premium/Formations-Tips-Rec.shtml for lots of tips, "Positioning Rules" and a Case Study of how a U12 Coach taught positions so his weak team won a tournament, and see www.soccerhelp.com/premium/Assigning_Positions_Rules.shtml 
In order to teach a formation and positions, it will be very helpful to understand the concepts of Shifting and Sagging , First Defender/Second Defender , First Attacker/Second Attacker , and that positions are relative to each other and generally when on Defense the "left" side players should stay on the left side of the field, the "right" side players on the right side of the field (left and right are as you face the opposing Goalie), Fullbacks should be closer to their Goalie than their Midfielders are, and Midfielders should be closer to their Goalie than their Forwards are. These guidelines also apply when a team is on offense, but not as strictly. Offense is more creative than defense and players may overlap in order to advance the attack - this is particularly true with Midfielders and Forwards, but most coaches may want their Fullbacks to be conservative and stay in a defensive position in case there is a fast counterattack by the opponent.
For Most Rec Soccer Teams, Depth is More Important than Width. Why it is Critical to Defend the Center of the Field.
For most Rec teams, "Depth" is much more important than "Width". For example, a formation like a 2-1-3-1 (that has 4 lines of players) will work better and is easier to teach than a 3-2-2 (that only has 3 lines of players), and a 1-1-3-1 will work better than a 3-3, and a 3-2-3-2 or 3-1-3-3 or 1-2-1-3-3 will work better than a 4-4-2 or a 4-3-3. The reason is that most Rec teams and their opponents lack the skill to use the entire width of the field when attacking and the greatest danger for Rec teams is giving up easy goals by opponents attacking straight to goal. 
Unless your team has the speed and stamina to defend the entire field, you should just try to defend the most important part. The most important part of the field is the Center of the Field (the Center is an imaginary line between the 2 goals). If you control the Center, you will probably win the game - if you lose the Center, you will probably lose the game. You can give up the sidelines and even the corners of your Defensive Third if your opponents can’t score from there, but you MUST defend the Center. In fact, encourage your opponents to attack down the sidelines - they will run more than your players and your players will have time to “recover” to defensive positions when your team loses the ball.
Too much width when you are on defense is bad. The wider your defense is, the more spread out and the easier it is for opponents to penetrate straight to your goal. Your defenders should stay close enough together to support each other, but not too close (if they are too close, they lose effectiveness and can't cover enough space). Your defense should be just wide enough to slow down the attack (i.e., just wide enough that the attackers can't easily go around you) and should shift and sag as the ball moves so there are multiple layers of defenders between the ball and the goal. As your team gets older and plays better teams, the attackers will start to "switch fields" and use a wide attack as a way to get around your defense and to loosen it up.
As attackers move the ball around the field, defenders should be constantly shifting to maintain good defensive coverage and the players farthest from the ball should "sag" back so they are in position to stop an attack on goal. This shifting & sagging compacts the defense and provides additional depth and a concentration of defenders between the ball and the goal. This creates multiple layers of defenders in a position to stop an attack on goal. Depth on defense means having several defenders (ideally, multiple layers of defenders) spaced between the ball and the goal who are in a position to "recover" in time to stop an attack on their goal. This and First Defender/Second Defender are the most important defensive concepts. Depth is the opposite of a "flat" defense.
More Advantages of Formations that Have Depth and Center Positions
Formations that have an extra "line" of players with more Center positions are better for Rec coaches. An example is a 2-1-3-1 (which has 3 Center positions - a Stopper, a Center Mid, and a Forward) versus a 3-2-2 (that has one Center position - a Center Fullback). A 2-1-3-1 is also much easier to teach than a 3-2-2 and much better for coaches who have some slow, unskilled, or timid players, because it allows you to put your best players at Center Mid and Forward, a fast and aggressive athlete (even if unskilled) at Stopper, slow players at Fullback (if they are Brave and if you Defend Deep), and timid players at Right and Left Mid (until you train them to be Brave). If you have doubts, read the section below titled "How Much Difference Can a Formation Make?" As your players improve, they can be successful at more positions and you can change your Formation and Style of Play to the one that is best for your team.
The most important position for most Rec teams is Center Mid. If you have a player who can be a strong Center Midfielder, it will be an advantage to use a formation that has a Center Mid so your Center Mid can control the Center of the Midfield and also join in your attack. A strong Center Mid will prevent opponents from attacking straight to your goal and can support your Forward(s) and join in attacks.
How Much Difference Can a Formation and Style of Play Make? 
Coaches say the right formation and Style of Play can make a HUGE difference. There is a great letter about this on SoccerHelp from a U12 Rec coach whose team didn't win a game for 3 seasons, but then he changed the formation and his team started playing better, winning, and the players were much happier. He said "Now, when my kids are on the field, they have fun, play hard, get aggressive, and their CONFIDENCE SOARS!! I will never again put myself or a young team through the heartache and frustration of trying to play a system that is simply beyond our experience and skill level." You can read Coach Glenn's letter and tips for 8v8 formations at www.soccerhelp.com/Soccer_Stopper_Soccer_Formation_8v8.shtml  There are lots more letters like this from coaches at Soccer Coaching Success Stories .
The Style of Play you use is as important as the soccer formation you choose. For example, many Rec teams are better off Defending Deep instead of Pushing Up when they attack. If you haven't thought about your Style of Play, read the article at the above link, or go to "S" in the SoccerHelp Dictionary  
Losing every game isn't any fun and can cause kids to feel like failures and quit soccer. Like Coach Glenn, many Rec coaches make the mistake of choosing a Formation and Style of Play that doesn't suit their team, and then try to make their team fit that Formation and Style of Play. Instead, you should choose a Formation and Style of Play that will give your team the best chance of being successful and having fun. As your team improves, continue to evaluate your formation and Style of Play and do what is best for your team. (If you are an Academy coach, then you have a different situation from Rec coaches and this advice may not apply to you.) DON'T just rely on tactics - use the SoccerHelp No Lines Drills to improve your players soccer skills. 
Diagrams of Soccer Formations
You can see diagrams of soccer formations at Soccer Positions Diagrams  We only show a few diagrams of soccer formations as examples because the specifics depend on coaching preferences and the ability of the players -- there are hundreds of possibilities. Also, where players should be depends on where the ball is, whether they are on offense or defense, and whether the Fullbacks Push Up on the attack or Defend Deep.
Tips for Assigning and Rotating Positions (the tips below are based on discussions with hundreds of coaches)
Rec coaches have a very different situation from Select Team coaches. Select Team coaches have all great players who can play any position, but Rec coaches (even at U10) usually have some players who are unskilled, slow, timid, don't practice, or don't hustle. What works for a Select Team coach might not work for a Rec coach. The purpose of youth soccer is fun and if it isn't fun players will quit. 
A few Tips for U8 and older (there are a lot more Tips at the Links below) -
1. Why Teaching Positions Matters and How to Win Games (this only applies to U8 and older and not to Academy Teams). Youth soccer is a team sport and the coach has a responsibility to try to make it fun for the players. It isn't fun to lose every game or suffer humiliating losses. If your players don't know how to play their positions, you will lose against equal teams that are better coached (don't worry about positions at U6). Some people say "it doesn't matter if you lose". That is true if a team has played well and given its best effort. But if your team always loses because they play poorly, don't try, aren't improving, or because you make bad coaching decisions, the players and parents will become unhappy. If your team is playing teams that have the same athletic ability as your team, and you teach skills using SoccerHelp No Lines Drills , and motivate your players, and choose a Formation and Style of Play that gives your team a chance to be successful, and if you put your players in positions where they have a chance to be successful and contribute to the team, then your team will win more games than it loses and your players will have fun and love being on your team. There are hundreds of Testimonials from coaches at 1,000 Testimonials 
2. Some positions are more important than others and some players can't be successful at some positions or in some Styles of Play. For example, the most important position for most youth Recreational teams is Center Mid and the second most important is Stopper - great players at those 2 positions can make a huge difference. Another example - if you put timid players at Fullback, they will give up lots of goals and feel like a failure - it is better to teach them to be Brave before putting them at Fullback. Another example - if you ask slow Fullbacks to Push Up against fast opposing Forwards, the slow Fullbacks simply aren't fast enough to stop fast counterattacks (but you can Push them Up if you put a fast Sweeper behind them) - a slow Fullback can be successful IF you don't ask them to win a foot race against a fast opposing Forward. 
3. About Rotating Players - If you coach a Select Team or a Developmental Team, it makes sense to rotate your players because they are athletic, motivated, and have the skill to play lots of positions. By rotating them you can see which position is best for them. But if you coach a Rec team and practice once a week, it is hard enough to teach your players one position and impossible to teach them 3 positions. Your practice time should be mostly spent teaching skills, not teaching positions. This doesn't apply to U6 - just have fun. At U8 and older, if a player asks to play a different position, think about if the player has any chance to be successful there. Tell the player that if he comes to practice and works hard that he can EARN a chance to try that position - if there are specific things the player needs to do such as being Brave and not afraid of contact, tell him to work on those things. If he wants to play Goalie, see number 4 below. When I first started coaching Rec, I rotated players. But over time I saw the problems and when I started using the approach described above my players and parents were happier and the team played better. I think a coach has a responsibility to the team and putting players in a position that will cause the team to be unsuccessful isn't good for the team. 
4. Training Kids to Play Goalie - If you coach a Rec team, try to keep your best field players on the field and not in Goal. Some kids who are slow or large and aren't great at other positions can be good Goalies if they are able to stop the ball and punt the ball to clear it. If a kid wants to play Goalie, spend at least 10 or 15 minutes before or after practice training the kid to play Goalie. How to do this is explained in detail in SoccerHelp Premium. 
5. Make All Positions Equally Important - Avoid giving Forwards more praise than other positions and don't reward a kid for scoring a goal unless you reward the entire team - goal scoring should be "we", not "I", because it is a team effort. If the only praise you give is for scoring a goal, then every kid is going to want to score goals, and no one will want to play Fullback. Find ways to praise ALL positions. You can praise hustle, effort, Bravery, winning the ball, assists, a great defensive play, a great pass, a great reception, team spirit, etc. - those are the things needed to have a good team. Show your players that playing Fullback is as important as playing Forward. 
Don't take these tips to mean that you can rely on a Formation and shouldn't keep teaching skills - use the SoccerHelp No Lines Drills to teach skills at every practice and have fun.
Articles About Soccer Formations are Below
Links to More Articles About Formations and Positions
How to Select a Soccer Formation and Assign Positions - Tips for selecting a formation and assigning positions. 
Youth Soccer Positions - How to Teach, Coach & Assign 
How to Choose a Soccer Formation 22 questions to help you choose the best soccer formation 
How to Assign Soccer Positions 25 tips for assigning soccer positions
6v6 Soccer Formations (SoccerHelp Premium has 12 articles about 6v6 soccer formations, 2 about 5v5, and 6 about 4v4 and 3v3) 
7v7 Soccer Formations (SoccerHelp Premium has 13 articles about 7v7 soccer formations) 
8v8 Soccer Formations (SoccerHelp Premium has 39 articles about 8v8 soccer formations, 6 about 9v9 and one about 10v10) 
9v9 Soccer Formations 
11v11 Soccer Formations (SoccerHelp Premium has 21 articles about 11v11 soccer formations) 
Soccer Formation Basics
Soccer Positions Basics & Soccer Kick-Offs 
Soccer Positions Overview

Save $5 on SoccerHelp Premium. This free site has 400 pages. SoccerHelp Premium has 1,500 pages, including 200 pages about Formations and how to teach and assign positions. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. Sign up at  www.soccerhelp.com/members/signup 

Samples of the 100 Soccer Formations Articles on SoccerHelp Premium. Read about Premium or Sign-Up
1.	11v11 Soccer Formations - This link is to one of the 21 articles on Premium about 11v11 soccer formations. It discusses how to assign and teach players to play 3-2-2-3 and 3-2-3-2 formations. In addition to the 3-2-2-3 and 3-2-3-2, the other 20 articles on Premium discuss formations such as 4-3-3, 4-4-2, 3-3-3-1, 1-3-1-3-2, 3-2-1-2-2, 3-3-2-2, 3-1-4-2, 3-1-1-4-1, 3-3-4, 4-1-3-2, 4-3-2-1, 1-2-1-3-3, 3-1-3-3, 3-1-2-1-3, 1-2-1-3-3, 4-1-2-2-1, 3-1-3-3 and 1-3-4-2. 
2.	8v8 Soccer Formations - This link is to some of the 40 articles from Premium about 8v8 soccer formations. Among the formations discussed are 2-1-3-1, 2-1-2-2, 3-3-1, 2-3-2, 2-2-1-2, 1-2-2-2, 3-2-2, 3-1-2-1, 1-3-2-1, 1-3-3, 3-1-3 and a 1-2-1-2-1. NOTE: Most Rec teams will do better using a 2-1-3-1 instead of a 2-1-2-2, because a 2-1-3-1 provides more strength in the center of the field and allows you to put weak players at RMF or LMF. 
3.	Formation ideas for U-9 playing 11 v 11 and how to teach positional play, "support" and "shape". Also, what is the best scrimmage method to get a team ready to play. 3-2-2-3, 3-2-3-2, 3-3-4 and 4-3-3 are discussed.
4.	Comparison of 3-2-3-2, 3-2-2-3 and 3-3-3-1 formations and how to teach 3-2-2-3 and 3-2-3-2 formations.
5.	Teaching 3-2-2-3 and 3-2-3-2 formations.
6.	More about teaching 3-2-2-3 and 3-2-3-2 formations (most of the concepts apply to any formation that uses 4 "layers" of players).
7.	9 v 9 formations. Comparison of a 3-2-3 and 3-3-2. How to teach a 3-3-2.
8.	8 v 8 formations. Discussion of a 3-1-3, 3-2-2 and 2-1-2-2.
9.	How to teach U-9 and U-10 players to not "bunch up". (Also, see Letter No. 2 in "Letters From Coaches and More Soccer Formations and Soccer Positions").
10.	Read this if you play 11 v 11. Which formation and "style of play" is best for a U-14 Girls Rec team playing 11 v 11? Discussion of a 3-2-2-3, 3-2-3-2 and 3-3-4. How to assign and teach players to play a 3-2-2-3 and a 3-2-3-2. Many tips and strategies. 3 pages of discussion.
11.	Formations for U-8 playing 6 v 6. 3-2 and 2-2-1 are discussed. Practice Games are recommended for U-8. 
12.	Tips for U-12, 11v11, 3-2-3-2, 3-1-4-2, 3-1-1-4-1 Formations.

**Comment by dustinschaerer** [comment]
@david-huddleston This is ALL completed! :)
