### ISSUE TITLE
Changes to "Evaluating Soccer Players and Teams" article, 6-30-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#122]
Dustin, I sent you this email on 6-30-17 at 5:52 PM. This is a low priority. Use the email so you can see colors. 

Dustin, on http://www.soccerhelp.com/Evaluating_Soccer_Players_And_Teams.shtml ,

1. The top Title is >

How to Choose a Soccer Formation
Evaluating Soccer Players and Teams
Soccer Team Evaluation Checklist and Questionnaire
22 Questions that Will Help You Evaluate Your Team
These questions will help you decide which formation and style of play is best for your team
A format for evaluating your players
Guidelines for Which Positions Players Can Best Play

Replace it with what below in Bold Green that is the same size font as the text >

How to Evaluate Soccer Players and Assign Positions

Soccer Team Evaluation Checklist
22 Questions to Evaluate Your Team
Guidelines for Assigning Positions
Select a Formation and Style of Play

2. Add a new first sentence >

How to evaluate soccer players and assign positions.

So the first para reads >

How to evaluate soccer players and assign positions. The questions below will help you evaluate your team and players so you can decide which Soccer Formation and Style of Play might be best for you. Remember that you want to choose the Soccer Formation and Style of Play that give your team the best chance of being successful. To a degree, this means a Soccer Formation and Style of Play that works to your advantage so your best and most athletic players are in the most important positions and your timid and slow players are in positions that give them a chance of being successful and don't doom them to failure. This only applies to U8 and older. (Just have fun if you coach U4 or U6 soccer).

3. In the Code, Change the Title Tag, Meta Description, and Key Words to > 

<title>How to Evaluate Soccer Players and Assign Positions</title>

<meta name="description" content="How to Evaluate Soccer Players and Assign Positions"> 

<meta name="keywords" content="How to Evaluate Soccer Players and Assign Positions">

4. Change the H1 to be the Top Line of the Title> How to Evaluate Soccer Players and Assign Positions 

5. Make the H2 > Soccer Team Evaluation Checklist

6. Make the H3 > Use this Format to evaluate your players:

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
