### ISSUE TITLE
Changes to 6yearoldsoccerdrills.com , 7-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#123]
Dustin, I emailed you this on 7-1-17 at 4:15 PM - use the email so you can see colors.

This is a total re-do of that website, except you can leave the style.

Dustin, on    http://6yearoldsoccerdrills.com/ 

1. W3C this

2. On the bottom, Delete the image of the soccer patches.

3. In the Code, Change the >

<title>Soccer Drills for 6 Year Olds and U6 Soccer</title>
<meta name="description" content="Soccer drills for 6 year olds who play U6 soccer should be fun and teach fundamental soccer skills." />
<meta name="keywords" content="Soccer Drills for 6 Year Olds, U6 Soccer Drills" />

4. Make the H1 the Title >

Soccer Drills for 6 Year Olds and U6 Soccer

5. Make the H2 the Sub-Title >

The Best U6 Soccer Drills are Fun Practice Games

6. Make the H3 >

Fun Soccer Drills for Kids

7. Change the title to >

Soccer Drills for 6 Year Olds and U6 Soccer

8. Replace the text with below  (Dustin,  make the links the old underlined blue, like below  - both links go to www.soccerhelp.com/soccer-drills.shtml )  >

Soccer drills for 6 year olds who play U6 soccer should be fun and teach fundamental soccer skills.
The best soccer drills for 6 year olds, U4 and U6 are not actually drills, they are Practice Games.
The Best U6 Soccer Drills are Fun Practice Games
Soccer Practice Games are games that are fun and are designed to teach soccer skills. The difference between Practice Games and a lot of soccer games is that a lot of soccer games are fun but don't teach skills. For example, crawling on the ground, using elbows, or picking up the ball might be fun, but that isn't teaching skills and can actually teach bad habits - it is hard enough to teach kids to NOT pick up the ball without encouraging it in practice. Soccer Help Soccer Practice Games are great fun, teach the most important soccer skills, and keep kids active because there are No Lines. That's right - No Lines. Whatever you do, AVOID drills that have young kids standing in line - that is the WORST way to practice and kids will start to hate coming to practice because it isn’t fun. 
Fun Soccer Drills for Kids
The SoccerHelp training program is the best way to train young players. It is also more fun. That's why there are over 1,000 Testimonials from coaches. That isn't a misprint - there are 1,000 unsolicited Testimonials from coaches. Read them for yourself and see what youth soccer coaches say.
You can check out the SoccerHelp soccer drills and games at this link soccer drills and practice games

**Comment by dustinschaerer** [comment]
This is completed.  All validated and replaced.
