### ISSUE TITLE
Changes to SoccerDrills.net , 7-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#124]
Dustin, I emailed you this on 7-1-17 at 7:57 PM. Use the email so you can see the Bold.

The changes to SoccerHelp are a higher priority.

Dustin, 

1. on http://www.soccerdrills.net/ > 

(a). W3C this page (not the other pages of this domain, only this one )

(b).  Change the code to what is below >

<meta name="description" content="No Lines soccer drills and games for ages 4 to 18. No lines means less standing, more practice and more fun. Dribbling, Passing, Aggressive Play, Positions, Tips, Tactics and Rules."/> 

(c). The second para is > There 40 free soccer coaching videos. 
> Just below that  add a new Sub-Title >
Try the Free Soccer Drills and You Will See the Difference
1.(D). The current H2 is > Recent Articles
> Change the H2 to the new Sub-title >  Try the Soccer Drills Below and You Will See the Difference
1.(E). The codes says the H3 is <h3>Soccer Drills</h3>
but I don't see that anywhere - is that a mistake?
1.(f). Add another Sub-Title just above >
Soccer Bees Soccer Drill ™ (age 3, 4, 5, 6, U4, U5, U6) A simple, fun soccer drill that is a game.
> Have it say >
More Soccer Drills
1.(g). Make the  H3 be > More Soccer Drills
1.(h). Just above "Recent Articles" delete >  There are 1,000 Testimonials from coaches at http://soccerhelp.com/soccershop/testimonials

2. On the top of http://www.soccerdrills.net/soccer-drills-passing-receiving/index.html is a link named > Best Free No Lines Soccer Drills

that goes to > http://www.soccerhelp.com/soccer-drills.shtml 

Change the link name to >   Soccer Drills that Really Work

3. On the top of http://www.soccerdrills.net/soccer-drills-not-bunch-up/index.html   is a link named > Best Free No Lines Soccer Drills

Delete that link 

4. On the top of  http://www.soccerdrills.net/soccer-drills-soccer-bees-u4-u6/index.html   is a link named > Best Free No Lines Soccer Drills

that goes to > http://www.soccerhelp.com/soccer-drills.shtml 

Change the link name to > More Kids Soccer Drills

5. On the top of  http://www.soccerdrills.net/soccer-drills-chase-u4-u5-u6/index.html   is a link named > Best Free No Lines Soccer Drills

Delete that link 

6. On the top of  http://www.soccerdrills.net/soccer-drills-aggressive-shoulder-tackle/index.html   is a link named > Best Free No Lines Soccer Drills

Delete that link 

7. On the top of  http://www.soccerdrills.net/soccer-drills-dribbling/index.html   is a link named > Best Free No Lines Soccer Drills

that goes to > http://www.soccerhelp.com/soccer-drills.shtml 

Change the link name to > Soccer Drills that Teach Dribbling

8. On the top of  http://www.soccerdrills.net/soccer-drills-monsters-age-4-5-6/index.html   is a link named > 40 Free Soccer Coaching Videos - Drills, Skills, Tactics

Delete that link

9. On the top of  http://www.soccerdrills.net/how-to-motivate-soccer-players-advice-from-famous-coaches/index.html there  is a link named > 40 Free Soccer Coaching Videos - Drills, Skills, Tactics 

Delete that link

10. Also on  http://www.soccerdrills.net/how-to-motivate-soccer-players-advice-from-famous-coaches/index.html > Delete the first 2 paras, which are >
It is critical to motivate soccer players. Below is some of the best advice from famous coaches, players and motivational experts. Click this link for over 400 Testimonials about how to motivate soccer players.
"Competition is key to developing soccer players. The only practice environment in which you truly develop a soccer player is a competitive arena." Anson Dorrance Watch Video Clips of Anson Dorrance & Tom Stone Soccer Clinic DVD and Read an article about how Anson Dorrance uses Competition during practice to develop each player's potential and the importance of competition, pressure and keeping score during practice.) Anson Dorrance is possibly the greatest college soccer coach in history and one of the most successful coaches in any sport. His teams have won 20 NCAA Women's Soccer Championships. Yes, this isn't a misprint - 20 NCAA Soccer Championships.

11. On the top of  http://www.soccerdrills.net/soccer-positions/index.html   is a link named > Best Free No Lines Soccer Drills

Delete that link

12. On the top of  http://www.soccerdrills.net/soccer-formations/index.html   is a link named > Best Free No Lines Soccer Drills

Delete that link

13. Also on   http://www.soccerdrills.net/soccer-formations/index.html  > on the bottom, delete the last sentence that is >

All of this is explained in detail at Soccer Formations, Styles of Play and Diagrams for Youth Soccer and Soccer Formations

14. On http://www.soccerdrills.net/soccer-rules/index.html , at the top, delete the link > 40 Free Soccer Coaching Videos - Drills, Skills, Tactics

**Comment by dustinschaerer** [comment]
@david-huddleston This is all completed and validated!
