### ISSUE TITLE
Changes to /soccer-articles/100712-soccer-moves-teaching , 7-2-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#128]
Dustin, I emailed you this on 7-2-17 at 1:22 PM - use the email so you can see colors

Dustin, on http://www.soccerhelp.com/soccer-articles/100712-soccer-moves-teaching.shtml >

2 Changes >

1. Replace the Title with (Green font that is the same size as the text) >

6 Tips to Improve Soccer Practice
How to Teach Receiving
How to Teach Soccer Moves  
Prepare Players for Real Games
 Train to Play Fast, Not Slow
Advice from Coach Doug

2. Fix the 2 weird fonts at the top >

Note From David. Coach Doug and I recently watched a short video on You Tube that was about Soccer Drills that teach soccer skills. Below are Coach Doug�s comments and a list of 6 questions that will help you self-evaluate your soccer practices.
________________________________________
Coach Doug and I recently watched a short video on You Tube that was about Soccer Drills that teach soccer skills. Below are Coach Doug�s comments and a list of 6 questions that will help you self-evaluate your soccer practices.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
