### ISSUE TITLE
One change to  /soccer-articles/100913-play-fast-soccer , 7-2-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#129]
Dustin, I sent this as an email on 7-2-17 at 7:15 PM

Dustin, on   www.soccerhelp.com/soccer-articles/100913-play-fast-soccer.shtml  

at the top, delete > 

SoccerHelp Newsletter

**Comment by dustinschaerer** [comment]
@david-huddleston Completed.
