### ISSUE TITLE
Remove Facebook Link on SH Home & change the text, 7-4-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#132]
Dustin, I sent this email on 7-4-17 at 1:45 PM

Dustin, we talked about this - on SH Home, on the right side is  the Facebook link >

It says the words below and has a "F" link > 

For Soccer Coaching Tips, Like Us on Facebook. 
Over 40,000 likes!
 
1. Delete the Facebook link button (the "F" button)

2. Replace the text with >

SoccerHelp has 50,000 Facebook Followers

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
