### ISSUE TITLE
Third Version - SoccerRules.org - changes to 4 pages, 7-4-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#133]
Dustin, I emailed you this version on   7-4-17 at 3:51 PM 

Delete the 2 versions I sent you on 7-4-17 at 2:46 PM and at 3:36 PM and use this version that I emailed you on 7-4-17 at 3:51 PM 

Dustin, make the changes to the 4 pages below (the links go to http://www.soccerhelp.com/simplified-soccer-rules.shtml and  http://www.soccerhelp.com/soccer-drills.shtml  )>

Dustin, If it is easier, let the new links be blue and underlined, like below. 

1. on http://soccerrules.org/index.shtml , 2 changes >

(a). The 5th para is >

Simplified Soccer Rules and Over 400 Definitions are at www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml 

Replace it with the link below  (not bold - the link goes to http://www.soccerhelp.com/simplified-soccer-rules.shtml )  >

70 Youth Soccer Rules  

(b). Add a new Last Para that says >

If you coach youth soccer and want to train your players faster and better, check out No Lines Soccer Drills & Games  

2. On http://soccerrules.org/soccer-fouls.shtml > 2 changes

(a). The 3rd para is >

For detailed explanations of over 70 soccer rules visit Soccer Rules at www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml

Replace it with (not bold and the link goes to  http://www.soccerhelp.com/simplified-soccer-rules.shtml  ) > 

Explanations of over 70 soccer rules are at Simplified Soccer Rules

(b). Have the link go to  http://www.soccerhelp.com/simplified-soccer-rules.shtml

(c). at the bottom of the page, delete >

For over 70 soccer rules and regulations visit www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml

3. On http://soccerrules.org/soccer-cards.shtml > 2 changes

(The links go to http://www.soccerhelp.com/simplified-soccer-rules.shtml  and  http://www.soccerhelp.com/soccer-drills.shtml 

(a).  The 3rd para is > 

For detailed explanations of over 70 soccer rules visit Soccer Rules at www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml

Replace it with  (NOT bold) >

For detailed soccer rules visit Youth Soccer Rules and visit Youth Soccer Drills for the best soccer drills and games. 

(b). At the bottom of the page, delete >

For more detailed soccer rules visit www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml

4. On http://soccerrules.org/soccer-age-rules.shtml , one change >

At the bottom of the page, delete >  
For detailed soccer rules visit www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
