### ISSUE TITLE
Dustin - SoccerRules.org - fix a link, 7-4-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#134]
Dustin, I emailed you this on 7-4-17 at 5:34 PM

Dustin, 

On http://soccerrules.org/soccer-cards.shtml > 

(The links go to http://www.soccerhelp.com/simplified-soccer-rules.shtml  and  http://www.soccerhelp.com/soccer-drills.shtml 

>  In the 3rd para, the Drills link should go to http://www.soccerhelp.com/soccer-drills.shtml   > 

For detailed soccer rules visit Youth Soccer Rules and visit Youth Soccer Drills for the best soccer drills and games.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
