### ISSUE TITLE
Change title of /soccer-articles/100712-soccer-moves-teaching , 7-4-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#135]
Dustin, I emailed you this on 7-4-17 at 5:42 PM. See the email for colors

Dustin, on http://www.soccerhelp.com/soccer-articles/100712-soccer-moves-teaching.shtml >

Replace the Title with (Green font that is the same size as the text) >

6 Tips to Improve Soccer Practice
How to Teach Receiving
How to Teach Soccer Moves  
Prepare Players for Real Games
 Train to Play Fast, Not Slow
Advice from Coach Doug

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
