### ISSUE TITLE
Soccer Formations title - add a line,  7-4-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#136]
Dustin, I emailed you this on 7-4-17 at 6:44 PM

Dustin, on http://www.soccerhelp.com/soccer-formations.shtml

the title is >

Soccer Formations
How to Choose a Formation 
What the Numbers Mean 
How to Teach a Formation 
Depth versus Width 
Why the Center is Critical 
Diagrams 
Tips for Assigning Positions

Add another line >

6v6, 7v7, 8v8, 9v9, 11v11

So it reads >

Soccer Formations
How to Choose a Formation 
What the Numbers Mean 
How to Teach a Formation 
Depth versus Width 
Why the Center is Critical 
Diagrams 
Tips for Assigning Positions
6v6, 7v7, 8v8, 9v9, 11v11

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
