### ISSUE TITLE
Second version - Soccer Drills changes - Dustin, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#137]
Dustin, I emailed you this on 7-5-17 at 10:41 AM - use the email.

Dustin, delete the version I sent you on 7-4-17 at 7:43 PM and use this one

Dustin,

Below are some changes to make to  http://www.soccerhelp.com/soccer-drills.shtml > 

1. The Title is > 

Soccer Drills
Free No Lines Drills, U6 to U18

Players Improve Twice as Fast - Guaranteed

Replace it with in Bold (the top line is the same and is the H1 - all lines are bold - put some space where shown) >

Soccer Drills
with Videos
Free No Lines Drills, U4-U18
Players Improve Twice as Fast
No Standing in Line

2. The first sentence is >

Use our free No Lines Soccer Drills and your players will improve twice as fast. 

Remove the underline and bold No Lines Soccer Drills , so it reads >

Use our free No Lines Soccer Drills and your players will improve twice as fast. 

3. The first sub-title is >

Comments About Our No Lines Soccer Drills

Replace it with   (in bold ) >

What Coaches Say 

4. The Links List is >

Soccer Journal article about SoccerHelp Practice Games
29 Soccer Practice Tips
70 Soccer Tactics and Tips
18 Tips for U4 and U6 Soccer Coaches
Free Soccer Practice Plans 

(a). Move the First Link to the end 

(b). Change the name of  18 Tips for U4 and U6 Soccer Coaches  to  18 Tips for U6 Coaches

(c ). Add a new 5th link that goes to www.soccerhelp.com/Soccer-Videos-Premium.shtml > 

Videos of Best Drills 

(d). Change the last link name to  (same destination) >

Soccer Journal article about our No Lines Drills

So the Links List reads >

29 Soccer Practice Tips
70 Soccer Tactics and Tips
18 Tips for U6 Coaches
Free Soccer Practice Plans
Videos of Best Drills
Soccer Journal article about our No Lines Drills

5.   The second Sub-Title is >
Free Soccer Drills

Replace it with below (bold, not underlined) >

Free No Lines Drills

6. Delete the image on the bottom left that says >

Soccer Drills

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
