### ISSUE TITLE
Videos Navigation Page Changes, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#139]
Dustin, I emailed this on 7-5-17 at 9:59 AM - use the email so you can see colors and fonts.

Dustin, on   www.soccerhelp.com/Soccer-Videos-Premium.shtml 

1. The Title is >

Free Soccer Training & Coaching Videos - Drills, Skills, Tactics
and Videos on SoccerHelp Premium

Change it to the standard size (19 points? ) and to > 

Best Soccer Coaching Videos 
Free Drills, Skills, Tactics
and Premium Videos

2.  Change the Names 2 of the Top Promo Links as shown below (destinations stay the same) >

(a). Change  Streaming Video of Coach Doug's Video for U6 Coaches or SoccerHelp Foot Skills  to Streaming Video for U6 Coaches and SoccerHelp Foot Skills

(b).  In  Over 700 Testimonials for Our Training Program  Delete "Over" and change  700 to 1,000 so it reads >     1,000 Testimonials for Our Training Program 

3. The first sub-title is >

Free Soccer Training & Coaching Videos (Scroll Down for 30 More Free Videos and for Videos for Premium Members)

Delete the word "30" so it reads> 

Free Soccer Training & Coaching Videos (Scroll Down for More Free Videos and for Videos for Premium Members)

4. Move the section on the bottom about Coach Doug Videos up to be the second section, just below the section mentioned above

The section to move up is > 
Free U4 and U6 Soccer Coaching Videos (from the Coach Doug DVD)
1.	How to Have Fun Practices that Teach Soccer 
2.	"Hit the Coach" Soccer Practice Game 
3.	Soccer Dribbling and "Go Score" Practice Game 
4.	A Better Way To Teach Dribbling and Soccer Skills 
5.	Shy Soccer Player Gains Confidence -- Watch This! 
6.	Soccer Shooting and Kicking from Coach Doug

5. On the Bottom, where the Coach Doug videos was before you moved it, put a copy of the list from http://www.soccerhelp.com/premium/Videos_Navigation_Page.shtml that is titled > 

Video Clips from Soccer Coaching DVDs we Sell - for Age 7 and older

But make 2 changes > 

(a). Under "Passing" delete > The Dribble Around Cone & Pass Race game teaches One Touch. 
                                                                                                   
(b). And Change the Title of the List to (have the title the same size as the other sub-titles) >  More Free Coaching Videos for U8 & older (these are great coaching tips from DVD's we sell)

The section you are adding to   www.soccerhelp.com/Soccer-Videos-Premium.shtml  should look like this >
More Free Coaching Videos for U8 & older (these are great coaching tips from DVD's we sell)
Defending
Individual Defending Technique: Deny the Turn 
Intermediate 1v1 Defending (excellent!) 
Team Defense: Pressure, Cover Defensive Triangle 
Dribbling, Moves, Foot Skills & 1v1 Attacking 
Basic Moves and Foot Skills Workout 
Beating Your Opponent 1 v 1 
Brazilian Foot Skills Tips 
Emerson Move (Christian Ronaldo's favorite move) 
Foot Skills Training, Inside of Foot 
Freestyle - Watch This, it's Amazing! 
Intermediate & Advanced Moves and Foot Skills Workout 
Intermediate & Advanced Foot Skills and Moves 
"Outstep Touches" and "Stepovers" 
Free Kicks
Free Kicks (David Beckham and Alan Shearer) 
Movement off the Ball (Attacking)
Forward Runs in Front of the Ball 
Passing 
Beginner's Passing (great for young girls!) 
One Touch Passing This is EXCELLENT - Watch this. 
Receiving & Controlling the Ball
Advanced Receiving and Moving to Beat a Defender 
Receiving and Controlling the Ball 
Shooting & Finishing
Intermediate Shooting and Determination to Score (excellent!) 
Shooting and Finishing 
Shooting: Power and Its Use 
Team Possession Training
Possession Football 
Turning
Turning With the Ball

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
