### ISSUE TITLE
Soccer Practice - bold a sub-title, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#140]
Dustin, I emailed this on 7-5-17 at 1:54 PM

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml >

The 2nd sub-title is >

Things to Avoid at Practice:

Delete the colon and Bold it, so it looks like >

Things to Avoid at Practice

**Comment by dustinschaerer** [comment]
@david-huddleston Completed
