### ISSUE TITLE
Soccer Practice - Questions, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#141]
Dustin, on http://www.soccerhelp.com/soccer-practice.shtml >

1. Why doesn't this page do like the Soccer Drills page on mobile? Is it hard to make it do that or to have a mobile version? 

2. Can you move the indented numbers to the left so they don't squeeze down so much? (Can you move the 1, 2, 3, etc. left so they are under the "T" in "Things" -- you can leave the numbers in # 12 and # 13 indented. )

**Comment by dustinschaerer** [comment]
@david-huddleston This is resolved.

That page didn't look right but it didn't have the meta viewport tag added on it, which is needed for Bootstrap. The numbers are alighned well now.
