### ISSUE TITLE
Soccer Drills - 7 changes, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#143]
Dustin, I emailed you this on 7-5-17 at 3:21 PM

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml

1. The 4th line of the title is >

Players Improve Twice as Fast

Change the word "Improve" to "Learn" so it reads >

Players Learn Twice as Fast

2. In the Links List >

(a). Change the name of  18 Tips for U4 and U6 Soccer Coaches  to  18 Tips for U6 Coaches

(b ). in the 4th link, delete "Free" so it reads Soccer Practice Plans

(c). Change the last link name to  (same destination) >

Soccer Journal article about our No Lines Drills

3. On the bottom, bold these 2 links >

Coaching Tips Worth 2 Goals Per Game

and

SoccerHelp Premium

4. In the last para, turn the  Soccer Drills  link into plain black text, like >  Soccer Drills

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
