### ISSUE TITLE
Question about H2 and H3 size on cell phone, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#144]
Dustin, 

The H2 and H3's on    www.soccerhelp.com/Soccer-Videos-Premium.shtml look good but on my cell phone they look smaller than the text - is there any way to change that?

David

**Comment by dustinschaerer** [comment]
@david-huddleston I see what you mean, and I wrote some styles that target only certain device sizes and pushed those up. On cell phones, text is shrunk from 16 pixels to 13 pixels, which allows for good reading on a small device.
