### ISSUE TITLE
Soccer Drills - one change, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#145]
Dustin, I emailed this on 7-5-17 at 4:34 PM

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml

In the last para, turn the  Soccer Drills  link into plain black text (so it isn't a link) , like >  

Soccer Drills

**Comment by dustinschaerer** [comment]
@david-huddleston COMPLETED.
