### ISSUE TITLE
On Soccer Drills change the Tests, 7-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#146]
Dustin, I emailed you this on 7-5-17 at 4:51 PM

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml

Near the top are 5 Tests >

"The Practice Games are AMAZINGLY EFFECTIVE!! Parents tell me their girls cannot wait to go to practice." Coach M.J., Premium subscriber
"Our regional director says I'm the most requested coach she's ever seen. SoccerHelp is the reason!!! Every practice game, etc. came from SoccerHelp....WELL DONE!" Mark, MI
"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses (19 Goals scored and gave up 25 Goals). Last season our record was 9 Wins 1 Tie (60 Goals scored and gave up 5 Goals)." Coach T, U12 Boys travel team
"Thank you for the amazing fundamentals that my daughter and her teammates have been taught. 5 of those girls (my daughter included) are Freshmen starting on their VARSITY high school soccer team." Coach Aaron, OH, Premium subscriber for 6 years
"My kids love earning the patches and you can see the pride gushing out of them. Thank you!" John, Soccer Academy, PA

1. In the first one, delete the comma and >

, Premium subscriber

2. Delete the 5th one >

"My kids love earning the patches and you can see the pride gushing out of them. Thank you!" John, Soccer Academy, PA

3. Delete the third one

4. Make the 4th one Blue, like below.

After the changes, it should look like >

"The Practice Games are AMAZINGLY EFFECTIVE!! Parents tell me their girls cannot wait to go to practice." Coach M.J.
"Our regional director says I'm the most requested coach she's ever seen. SoccerHelp is the reason!!! Every practice game, etc. came from SoccerHelp....WELL DONE!" Mark, MI
"Thank you for the amazing fundamentals that my daughter and her teammates have been taught. 5 of those girls (my daughter included) are Freshmen starting on their VARSITY high school soccer team." Coach Aaron, OH, Premium subscriber for 6 years

**Comment by dustinschaerer** [comment]
@david-huddleston COMPLETED
