### ISSUE TITLE
Dustin - Try a New Soccer Drills pages format

### ISSUE THREAD

**Issue by dustinschaerer** [soccerhelp/soccerhelp#150]
@david-huddleston Do you like this a little better for the drills?  I still it can be dressed up some more, but the video helps out.

http://www.soccerhelp.com/soccer_drills/Hit.shtml

**Comment by david-huddleston** [comment]
Dustin, we just talked.

Yes, and go ahead and on that page do as you suggested by making the page more traditional using Bold H3 Headers like we did on Soccer Formations..

Try it on the Hit the Coach page first

**Comment by dustinschaerer** [comment]
@david-huddleston I dressed up the Hit the Coach drill page by getting rid of the table view on the lower portion of the page and making  bold h3 headers instead.

Do you like this better?  I do :)

http://www.soccerhelp.com/soccer_drills/Hit.shtml
