### ISSUE TITLE
Move 3 patch tests to the end, 7-6-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#151]
Dustin, I emailed you this on 7-6-17 at 3:17 PM

Dustin, move the Patch Tests below to the end of the list >

A.  move the # 12 test to the end >

"Here is a bit of an update on soccer patches, etc. I found once again that, even with patches, it is difficult to get young players to do meaningful practice at home. I did find, however, that they will do it at the beginning of practice. I allow 15-20 minutes at the start of each practice (90 minute practice) to earn patches by doing some specified skills activities. If a player comes early, she gets even more time. Then at the end of practice, we have a brief awards ceremony for the girls who earned patches. It motivates the girls to be on time (or early) and they get 100's of touches on the ball before practice even starts. I am glad to find a way to have the girls be excited about earning patches on worthwhile activities. It eliminates the horsing around and standing around that usually happens as the players trickle in. Team tryouts were Monday and Tuesday of this week and there is a tournament this coming weekend. In August, I will be starting with a new bunch of U8 academy players."
Ken, U8 soccer academy coach

B. Move the # 21  test to the end >

The patches are working great. Our PE students are working hard to improve their scores and earn them.
Our school loves what we are doing with the patches and has given me a $2000 budget to reorder more patches every year. We are starting to talk about next year. Thanks for all of your help.
--Ronnie, CA, Somerset Middle School

C. Move the # 24  test to the end >

I read through your site and thought you would be interested that we are ordering 200 of your lightning bolt iron on patches for our kids Bible club at church. We had thought about stars but saw the lightning bolts and thought they were great. Thank you!
--G.W., NE

**Comment by dustinschaerer** [comment]
This is completed.
