### ISSUE TITLE
For Sept - 2 Premium videos to make YouTube versions of, 7-7-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#153]
Dustin, I emailed you this on 7-7-17 at 3:57 PM

Dustin, 

Are there YouTube versions of the 2 videos below? 

If not, put the videos below on YouTube like http://www.soccerhelp.com/premium/videos/Dribble_Across_A_Square_Game_Intro.shtml is and have the link go to the YouTube version - the AWS version can be a back-up. On YouTube, have them be the highest quality video (HD?) 

Put the YouTube versions on > 

http://www.soccerhelp.com/premium/videos/Tick_Tock_Game_Demo.shtml  

http://www.soccerhelp.com/premium/videos/Tap_On_Top_Game_Demo.shtml

The reason to have YouTube versions is because I'm going to put the Tick Tock video on the Tick Tock drills that is on Basic.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
