### ISSUE TITLE
How long to finish the new servers?  7-8-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#154]
Dustin, How long to finish up the new servers and turn in the old ones? 

I think it would be a good idea to finish that up. No rush on turning in the old ones if we need to keep them for a while for some reason. 

Is BIR-1 finished?

If it is going to be a while, turn in the IPs below. 

Below says there are still 64 IPs on BIR-1

VPS-2 - host.bir-1.com (Jul 15, 2017 - Aug 15, 2017) 1 $35.00
Control Panel - Plesk (Not Automatic Setup) (unavailable for new orders) 1 $5.00
Additional IPs - Additional IPs 64 1.00 $64.00

Coupon kh25off - 25% 1 -26.00 

Subtotal 78.00
Total $78.00

**Comment by dustinschaerer** [comment]
@david-huddleston This will be completed today!

**Comment by dustinschaerer** [comment]
Bir-1.com is setup for termination. Here is the reply from Knownhost:

Dustin,
I've marked the host.bir-1.com VPS for cancellation at the end of the current billing period, July 15, and I have voided the pending renewal invoice for that package. When the VPS is terminated, all IPs will be deleted.
Let me know if there's anything else I can do to assist.
Regards,
Deborah Poole

**Comment by dustinschaerer** [comment]
@david-huddleston I just requested that Knownhost go ahead and shutdown the old "soccerhelpserver2.com" server, and remove the IPs from that account too.

That should do it for turning off the old systems.

**Comment by dustinschaerer** [comment]
@david-huddleston THe old SoccerHelpserver2.com is also scheduled for shutdown through Knownhost.
