### ISSUE TITLE
On 6 Formation Diagrams, delete reference to Sketch Tool, 7-8-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#155]
Dustin, 

1. On http://www.soccerhelp.com/soccer-formations-diagrams-8v8.shtml under the 3 diagrams, delete in 3 places >

The diagram was produced using the Soccer Sketch tool from SoccerSketch.com 

2. On http://www.soccerhelp.com/soccer-positions-diagrams-11v11.shtml   under the 3 diagrams, delete in 3 places >

The diagram was produced using the Soccer Sketch tool from SoccerSketch.com

**Comment by dustinschaerer** [comment]
This is completed.
