### ISSUE TITLE
Dustin - read this First about Image SEO, 7-8-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#156]
Dustin, I emailed you this on 7-8-17 at 1:47 PM. It will be easier to read in the email.

Dustin, read this >

From https://yoast.com/image-seo/ 

Take these things in mind when adding an image to an article:
	Use a relevant image that matches your text 
	Use a PNG image if possible or JPG if not PNG
	Pick the right file name for your image (use a file name that describes the image ) 
	Make sure image dimension match the image size as displayed
	Be sure images are Responsive for mobile
	Reduce file size for faster loading
	Add a caption for easier scanning of the page
	Use an image alt text, title text is optional
	Add OpenGraph and Twitter Card tags for the image
	Don’t break the left reading line using an image
	Use images in your XML sitemaps

Preparing images for use in your article
When you have found the right image to use, either an illustration, chart or photo, the next step is to optimize that image for use on your website. There are a number of things that you should think about:

**Choose the right file name**

Image SEO starts with the right file name. Of course, this is the first location to use that keyword. Without even looking at the actual image, you want Google to know what the image is about. It’s simple: if your image is a sunrise in Paris showing the Notre Dame, the file name shouldn’t be DSC4536.jpg, but notre-dame-paris-sunrise.jpg. The main keyword would be Notre Dame, as that is the main subject of the photo, that is why I added that at the beginning of the file name.

**Scale for image SEO**

Loading times are important for UX and SEO. The faster the site, the easier to visit and index a page is. Images can have a huge impact on loading times, especially when you load a huge image and show it really small, like using a 2500×1500 pixels image and showing it at 250×150 pixels size. The entire image still has to be loaded. Scale the image to the size you want to show it. WordPress helps by providing the image in multiple sizes after upload already. Unfortunately, that doesn’t mean the file size is optimized as well, that’s just the image size.

**Use responsive images**

This one is essential for SEO as well. Images might ruin the mobile experience and could increase bounce rate. Go check Bruce Lawson‘s talk at WordCamp London (2015) about responsive images and the use of the picture attribute. He also brought this plugin to my attention as an alternative: RICG Responsive Images For WordPress. The plugin adds the srcset attribute to your images, making it possible to serve a different image per screen width. Note that WordPress adds this behavior by default from version 4.4 and they urge you to update the RICG plugin to the latest version in that same article. If we can automate this process like that, it might be the future of web images, IMHO. I like it.

**Reduce file size**

The next step in image SEO should be to make sure that scaled image is served in the smallest file size possible. There are tools for that. Of course, you could just export the image and test what percentage of quality is acceptable, but I prefer (especially with retina and similar screens) to use 100% quality images.
 
Optimize image file size, for instance using JPEGMini
You can still reduce the file size of these images by, for instance, removing the EXIF data. We recommend using tools like ImageOptim or websites like JPEGMini, PunyPNG or Kraken.io.
Next to using tools like the ones mentioned above, please use tools like YSlow to check if your image optimization succeeded.

**Image Type**

Google generally advises to use PNG if you want to preserve the most detail with the highest resolution. If your users have limited bandwidth though, JPEG would be preferable, as the file size is smaller.

Adding the image to your article
Don’t just stuff it in somewhere. I already mentioned adding it close to related textual content. That simply helps a lot. It makes sure the content is relevant for the image as well, as it is the other way around. 
Captions
The caption of the image is the text that accompanies the image. If you look at the images in this article, it’s the text in the gray box below it. Why is that text important for image SEO as well? People use that text in scanning an article. Next to headings, people tend to scan the image and include the caption as well in that scan. Nielsen actually wrote back in 1997: “Elements that enhance scanning include headings, large type, bold text, highlighted text, bulleted lists, graphics, captions, topic sentences, and tables of contents.” In 2012, KissMetric even stated that “Captions under images are read on average 300% more than the body copy itself, so not using them, or not using them correctly, means missing out on an opportunity to engage a huge number of potential readers.”
Do we add captions to all images? No. As mentioned, sometimes images just serve another purpose. Decide whether the image at hand is an image you want to use for SEO as well or not. Keeping over-optimization in mind, I’d say you should add a caption if it would make sense to the visitor if that caption is added. Think about the visitor first, don’t add a caption just for image SEO.
Alt text and title text
The alt text (or alt tags) is added to an image so there will be a descriptive text when the image for whatever reason can’t be displayed to the visitor. I can’t put it any better than Wikipedia: “In situations where the image is not available to the reader, perhaps because they have turned off images in their web browser or are using a screen reader due to a visual impairment, the alternative text ensures that no information or functionality is lost.” Be sure to add alt texts. Make sure the alt text includes the SEO keyword for that page and relates to / describes the image.
When hovering an image, IE shows the alt text as a ‘tooltip’. Chrome shows the title text like it was intended. Title text for images is similar and a lot of people that use these simply copy the alt text. More and more people simply leave these out. What is it for? “The title attribute can be very useful, but it is not a safe way of providing crucial information. Instead, it offers a good way to provide non-essential information, for example, the mood of the image, or what it means in context.” it’s nice to have information indeed, and isn’t taken into account for image SEO.
Read more: ‘Read more about alt tag and title tag optimization’ »
OpenGraph and Twitter Cards
I mentioned using the image for social sharing. If you add the right image tag to your <head> section like this:
<meta property="og:image" content="http://example.com/link-to-image.jpg" />
That will make sure the image is included in your share on Facebook (and OpenGraph is also used for Pinterest, for instance).
 
Our WordPress SEO plugin has a Social section where you can set and even preview your Facebook post when you use Premium. Make sure to use a high-quality image, like the original image you use in the post, as higher quality / larger images tend to be used by the social platforms more often. If you have set this up correctly, and it doesn’t work, try to flush Facebook’s cache in the URL Debugger.
Twitter Cards do the same for Twitter and are also generated by our plugin.
XML image sitemaps
If you are a web developer, you might wonder about XML image sitemaps. I’d rather say images in XML sitemaps. Google is pretty clear about this:
To give Google information about images on your site, you’ll need to add image-specific tags to a sitemap. You can use a separate sitemap to list images, or you can add image information to an existing sitemap. Use the method that works for you!
Every now and then, people ask us about XML image sitemaps. We don’t generate these in our plugin, but as Google states, instead, these images are included in the page or post sitemaps. Just scroll down in our post sitemap and find that we have added images to all our latest posts (there is a column telling you that). Adding images to your XML sitemaps help Google index your images, so be sure to do so for better image SEO.

**Comment by dustinschaerer** [comment]
Got it!
