### ISSUE TITLE
Soccer Formations - Add 2 images and change Diagrams, 7-8-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#157]
Dustin, I emailed you this on 7-8-17 at 2:10 PM - use the email so you can see the images.

Dustin, on http://www.soccerhelp.com/soccer-formations.shtml 

1. The Diagrams para is >

Diagrams of Soccer Formations
You can see diagrams of soccer formations at Soccer Positions Diagrams. We only show a few diagrams of soccer formations as examples because the specifics depend on coaching preferences and the ability of the players -- there are hundreds of possibilities. Also, where players should be depends on where the ball is, whether they are on offense or defense, and whether the Fullbacks Push Up on the attack or Defend Deep.

Replace the first sentence with (BOLD the 2 links - the links go to  www.soccerhelp.com/soccer-formations-diagrams-8v8.shtml   and  www.soccerhelp.com/soccer-positions-diagrams-11v11.shtml   )  >

You can see diagrams of 8v8 formations at 8v8 Soccer Formations and 11v11 formations at 11v11 Soccer Formations . 

So it reads >

Diagrams of Soccer Formations
You can see diagrams of 8v8 formations at 8v8 Soccer Formations and 11v11 formations at 11v11 Soccer Formations . We only show a few diagrams of soccer formations as examples because the specifics depend on coaching preferences and the ability of the players -- there are hundreds of possibilities. Also, where players should be depends on where the ball is, whether they are on offense or defense, and whether the Fullbacks Push Up on the attack or Defend Deep.

2. Dustin, On the bottom of the page add the new section below that has 2 Diagrams (make the diagrams Responsive - first, read the article I sent you about Image SEO). The 2 diagrams are from  www.soccerhelp.com/soccer-formations-diagrams-8v8.shtml   and  www.soccerhelp.com/soccer-positions-diagrams-11v11.shtml .

Dustin, before doing this, read the article I sent you about SEO for Images - it discusses the importance of file names. 

Make a copy of the 2 images and give them new file names >

For the 8v8 image have the file name be > soccer-formations-8v8-diagram

For the 11v11 image have the file name be > soccer-formations-11v11-diagram

ALT Tags > 

Have the Alt Tag for the 8v8 image say >  8v8 Soccer Formations

Have the Alt Tag for the 11v11 image say >  11v11 Soccer Formations

>>> Dustin, the new section is below > 

Soccer Formations Diagrams for 8v8 and 11v11

Below are 2 examples. For more diagrams, explanations of positions and how to teach the formations below see 8v8 Soccer Formations Diagrams and 11v11 Soccer Formations Diagrams

8v8 Soccer Formation Diagram for a 2-1-3-1, Attacking, 2 Fullbacks Deep, One Stopper, 3 Midfielders, One Forward. The ball is in the opponent's Penalty Box. A link is above to how to teach this formation.
 

11v11 Soccer Formation Diagram for a 3-2-3-2, Attacking, 3 Fullbacks Deep, 2 Stoppers, 3 Midfielders, 2 Forwards. The ball is in the opponent's Penalty Box. A link is above to how to teach this formation.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
