### ISSUE TITLE
On soccerdrills.net change the size of H2 and H3 , 7-8-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#158]
Dustin, I emailed you this on 7-8-17 at  3:24 PM

Dustin, on http://soccerdrills.net , change the size of the H2 and H3 to be the same sizes we are using in the SoccerHelp Style Sheet. 

The H2 is too large - the H3 is okay but can be one size smaller if it needs to 

You can make the H2 the size the H3 is and make the H3 one point smaller than the H2

The other pages are okay

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
