### ISSUE TITLE
On SH Home, delete the link to 21 Tips in Alphabet List, 7-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#160]
Dustin, on SH Home, in the Alphabet List, 

delete the link to 21 Tips

It is the 2nd link and goes to http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml 

Just delete the link, NOT the article

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed. completed
