### ISSUE TITLE
In 70 Tips, 2 changes, 7-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#161]
Dustin, I emailed you this on 7-9-17 at 10:53 AM - use the email to see colors.

Dustin, in http://www.soccerhelp.com/soccer-tactics.shtml >

1. In # 3, delete the 2nd test, which is >

"I tried hard to emphasize Passing To Space rather than passing to feet. The girls weren't good enough at passing and trapping to pass to feet." Corey, U12G

2. In # 1, 2 and 3, change the Tests from Green to Blue, so they look like >

"At every practice we do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA

"This is working beyond belief. Some of my timid girls are now amongst the toughest on the team." Mark, U1OG
"This made an immediate improvement on how to fight for a ball." Coach Chuck, U10B

"We played Dribble Across a Square and Dribble Around the Cone and Pass Relay Race at every practice, and the results were phenomenal." Greg, U9

**Comment by dustinschaerer** [comment]
@david-huddleston COMPLETED.
