### ISSUE TITLE
Make 18 Tips for U6 Responsive, 7-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#162]
Dustin, I emailed you this on 7-9-17 at 11:13 AM

Dustin, delete the email I just sent - I forgot to include the URL.

Dustin - Make 18 Tips for U6 Responsive

The URL is http://www.soccerhelp.com/U4-U6-soccer-coaching.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.

**Comment by david-huddleston** [comment]
Dustin, the page isn't responsive

**Comment by dustinschaerer** [comment]
@david-huddleston It's definitely responsive. Here is a screen shot.  Try Ctrl + F5.

![screenshot from 2017-07-12 07 36 04](https://user-images.githubusercontent.com/1232192/28123074-dfc3a07e-66d4-11e7-9845-d8c950c427fd.png)
