### ISSUE TITLE
Priority - Changes to U4, U6, U8 Navigation Page, 7-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#164]
Dustin, See the Fourth Version of this emailed on 7-9-17 at 4:56 PM - use the email for colors

Dustin, delete the 3 prior versions I emailed you on 7-9-17 at 2:30 PM, 3:57 PM, and 4:05 PM

Dustin, on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml  >

1. The Title is Dark Green >

How To Coach U4, U6, U8 Soccer
Ages 3, 4, 5, 6, 7 and 8
Navigation Page

Replace it with  (Dustin, make the top 2 lines Dark Green, like the title currently is) >

Kids Soccer U4, U6, U8 
How to Coach & Videos

No Lines Drills & Games
Navigation Page

2. The current 4th line is >

Watch Coach Doug DVD Video Clips of How to Coach Ages 3, 4, 5 and 6

- Change the font size to the same as the Text

- Replace the Text with (the link goes to http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml )> 

7 Free U4-U6 Videos

3. Delete the 5th, 6th and 7th lines, which are >

Click here to read about, subscribe to or Log In to Coach Doug's Site for Coaches of Ages 3, 4, 5 and 6
Membership to Coach Doug's site is as low as $11.95. Click here to Sign-Up
Buy Coach Doug DVD in Streaming Video

4. Above the Links List (see below) add a H3 Header Flush Left >

U4, U6, U8 Links

5. In the Links List, LEAVE the destinations the same BUT change the Text as shown below >

U4, U6, U8 Links
•	U4 Soccer Coaching
•	U6 Soccer Coaching
•	U8 Soccer Coaching (read U-6 above first)
•	Recommendations for U4 & U6 Coaches and Leagues
•	U4 Soccer Drills
•	U6 Soccer Drills
•	U8 Soccer Drills

6. After you do # 5 above, move the Bottom 3 links to the top and the Top 3 to the bottom - LEAVE the MIDDLE Link. So the List looks like >

U4, U6, U8 Links
•	U4 Soccer Drills
•	U6 Soccer Drills
•	U8 Soccer Drills
•	Recommendations for U4 & U6 Coaches and Leagues
•	U4 Soccer Coaching
•	U6 Soccer Coaching
•	U8 Soccer Coaching (read U-6 above first)

7. the 4th link is >

•	Recommendations for U4 & U6 Coaches and Leagues

Replace it with the 2 links below NOT BOLD (18 Tips goes to  http://www.soccerhelp.com/U4-U6-soccer-coaching.shtml   and 29 Tips goes to http://www.soccerhelp.com/soccer-practice.shtml   > 

•	18 Tips for U4-U6 Coaches
•	29 Soccer Practice Tips
SO, the Final List will Look Like (the middle 2 links are NOT Bold but the others are)  >

U4, U6, U8 Links
•	U4 Soccer Drills
•	U6 Soccer Drills
•	U8 Soccer Drills
•	18 Tips for U4-U6 Coaches
•	29 Soccer Practice Tips
•	U4 Soccer Coaching
•	U6 Soccer Coaching
•	U8 Soccer Coaching (read U-6 above first)

8. Add a Video on the page - Above " Testimonials from U6 Soccer Coaches" add a copy of the YouTube Video that is on http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-how-to-have-fun-practices-that-teach-soccer.shtml - the title of it is >  Kids Soccer Coaching 3, 4, 5, 6, U4, U6

Have the Alt Tag say > How to Coach Kids Soccer

9. Make the H1 be >  Kids Soccer U4, U6, U8

10. Make the H2 be >  No Lines Drills & Games

11. Make the H3 be >  U4, U6, U8 Links

12. Go ahead and WC3 the page

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed and validated!
