### ISSUE TITLE
Coach Doug Free Videos Clips page changes. 7-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#165]
Dustin, I emailed you this on 7-9-17 at 10:24 PM - use the email to see colors and bolding

Dustin, on http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml >

1. The Title is >

Free Coach Doug Soccer Video Clips

Replace it with >

U4-U6 Soccer Videos

Free Coaching & Drills Videos
How to Teach U4 & U6

2. The first link is >

Click here to read about, subscribe to or Log In to Coach Doug's Site for Coaches of Ages 3, 4, 5 and 6

Replace it with this Unbold link to the same destination >

Read about or subscribe to Coach Doug's Website for U4-U6 Coaches

3. Delete the 2nd and 3rd links, which are > 
Log In to Streaming Video of Coach Doug's DVD
Buy Coach Doug DVD in Streaming Video

4. Delete the 3rd Test, which is >

Great video. Our little boys sat and watched most of it with me!!! Thanks!!! Coach Don

5. Unbold the remaining 3 tests and make them Blue, like >

"I loved Coach Doug's video. I struggled coaching my son's U6 until I watched his video. It made all the difference in the world. I now make all our U6 coaches watch his video and they love it as well." Amy, coach and league administrator
"I recently ordered the Coach Doug DVD and I can't say enough about it. It is worth every penny (and more) that I paid for it." Coach David, WA
"Best $20 bucks I have ever spent on soccer. I just wanted to thank you for your video. I have been 4 weeks into soccer season when I came up on your site. I used your techniques and the kids loved it. Thanks again." Coach Ben (he bought the Coach Doug Streaming Video)

6. Make the H1 >  

U4-U6 Soccer Videos

7. Make the H2 >

Free Coaching & Drills Videos

8. Change the Code to >

<title>U4 and U6 Soccer Drills Videos</title>
<meta name="description" content="U4 and U6 Soccer Coaching and Drills Videos">
<meta name="keywords" content="U4 and U6 Soccer Coaching and Drills Videos">

**Comment by dustinschaerer** [comment]
@david-huddleston Do you want this one W3C validated too?  It'll take another 10 -15 minutes.

**Comment by david-huddleston** [comment]
No, don't worry about it.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
