### ISSUE TITLE
Changes to Youth Soccer Positions, 7-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#169]
Dustin, I emailed this on 7-10-17 at 2:30 PM - use the email so you can see the image - the image is from  http://www.soccerhelp.com/soccer-formations-diagrams-8v8.shtml

Dustin, on http://www.soccerhelp.com/youth-soccer-positions.shtml >

1. Bold the 2nd line of the title >
Where to Play Best and Weakest Soccer Players

2. In 1 thru 4, the first sentence is underlined - change that to Bold

3. Delete the link >

Diagrams of Soccer Positions & Soccer Formations

4. Below # 20, delete > 

David at soccerhelp

5. Add the following Links List below # 20 (the first link is http://www.soccerhelp.com/soccer-formations.shtml  and the others are from the Links List in that article) >

Soccer Formations Explained - Choose and Teach 
Soccer Positions Basics & Soccer Kick-Offs
How to Choose a Soccer Formation
How to Assign Soccer Positions 
6v6 Soccer Formations 
7v7 Soccer Formations
8v8 Soccer Formations
9v9 Soccer Formations 
11v11 Soccer Formations 

6. Below the links you added (in number 5 above) add above the Patch Photos what is below - Dustin - have the link go to www.soccerhelp.com/soccer-formations-diagrams-8v8.shtml - Make the link Bold 
AND make the Image a link to www.soccerhelp.com/soccer-formations-diagrams-8v8.shtml  . The link below the diagram goes to http://www.soccerhelp.com/soccer-formations-diagrams.shtml >

Soccer Formations Diagram for 8v8

For more 8v8 diagrams, how to teach positions, and how to teach 8v8 formations visit  8v8 Soccer Formations Diagrams 

The Diagram below is for a 2-1-3-1 soccer formation and shows a team Attacking with 2 Fullbacks Defending Deep, One Stopper, 3 Midfielders, One Forward. The ball is in the opponent's Penalty Box. This formation and Style of Play is good for a Rec team that has some slow and timid players. 
 

For more soccer formations diagrams visit Soccer Formations Diagrams

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.  I made the image responsive too!
