### ISSUE TITLE
Duplicate Content Ideas & 4 Things to Do When You Start SEO

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#17]
Dustin, I think there might be too much duplicate content on SH.

After you finish the new servers, when you run the SEO Audits, let me know if you come up with duplicate content on SH - we need to look at Duplicate content that might be holding back rankings.

Do the 4 things below AFTER you have done the new Servers – do them when you start the SEO work.

Below are 4 things to do >

1. I noticed that SoccerXpert has their duplicate content that is on every page as Images instead of text, and they are killing the rankings. So, I wonder if Google is seeing the content that is on every SoccerHelp page as “Duplicate Content”  - So, can you turn the 2 things listed below into Images and use the alt tags that describe what they are – don’t use soccer terms >

 - Copyright 1999-2017, David and Kay Huddleston  (use the alt tag Copyright)

 - And the Legal Notice that appears on every page (use the alt tag “Legal Notice” and don’t worry about the links working – I know they won’t work )

2. On SH Home page, the Copyright is already an image. Leave the “TERMS OF USE:” section at the bottom BUT turn the 2  www.Soccerhelp.com  links into text so they are NOT links.

3. Delete the page https://www.soccerhelp.com/u10-u12-Soccer-Drills.shtml  - delete this page and re-direct the link to go to https://www.soccerhelp.com/Soccer_Drills.shtml 

4. Let me know if the Audit Reports show Duplicate Content.

**Comment by david-huddleston** [comment]
DELETE THE BLOG - I think we should get rid of  http://soccer.soccerhelp.com/  because it is spam.  How can we delete all the articles that are on that page without leaving a lot of broken links?  The only link to it might be on SH Home page - "Soccer Blog" is the link.  Can you find any links and delete them?

**Comment by david-huddleston** [comment]
Dustin, will any of the Audits identify Duplicate Content?

**Comment by david-huddleston** [comment]
It looks like you deleted the Soccer Blog that was at  http://soccer.soccerhelp.com/ .

Did you delete all links to it?

**Comment by dustinschaerer** [comment]
@david-huddleston Yes, I deleted links to the soccer blog subdomain.

**Comment by dustinschaerer** [comment]
@david-huddleston Items 1, 2, 3 amd 4 are ALL COMPLETED.

Website Auditor shows several forms of Duplicate Content, braking them up into separate categories.

I'm removing or changing the Duplicate Content as needed.
