### ISSUE TITLE
Soccer Drills- changes to the page, 7-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#170]
Dustin, I emailed this on 7-10-17 at 5:21 PM - use the email so you can see colors and links.

Dustin, On  www.soccerhelp.com/soccer-drills.shtml >

Do what is below and THEN you can add images after below is finished. After you make the changes below, then you can add the images that you copy from the videos - there are 8 places to add images (7 drills and the last Blurb) - make the images Links to the pages. I changed the link names, but the destinations don't change. Nonetheless, for convenience, I put a list of the links and their destinations at the end. 
1. Add 2 videos near the bottom.
Just above the last para that starts "SoccerHelp Premium contains over 70 No Lines Soccer Drills " , add 2 videos >
(a). Add the video on http://www.soccerhelp.com/soccer-videos/best-soccer-dribbling-drill.shtml 

The Title above the video is > Best Soccer Dribbling Drill - Dribble Across Square Video Preview

Replace that title with >  Best Soccer Dribbling Drill for U8 & Older
If you can add an Alt tag, have it say > Soccer Drill to Teach Dribbling

(b). Below that video, add the Hit the Coach video from http://www.soccerhelp.com/soccer_drills/Hit.shtml 
Add a title above it that says >
Best Soccer Drill for U4 & U6

If you can add an Alt tag, have it say > Best Soccer Drill for U4 & U6

2. Under Free No Lines Drills , you can go ahead and replace the Drills numbered 1 thru 72 and also the para that starts Coaching Tips Worth 2 Goals Per Game with the new text that is below (the link names have changed, but the destinations are the same - the Link Destinations are at the end ) >
Dustin, Leave the Video and the last para, which is >
SoccerHelp Premium contains over 70 No Lines Soccer Drills that are designed to train fundamental soccer skills. Most are Practice Games that train players to play fast while under pressure. Players learn skills by playing the Practice Games. There are 29 soccer drills for U4 and U6 (age 3, 4 and 5), 45 soccer drills for U8 (age 6 and 7), 52 soccer drills for U10 (age 8 and 9) and 50 soccer drills for U12 (age 10 and 11). There are 400 Testimonials from Coaches. If you aren't completely satisfied, just send us an e-mail during the first 10 days and we will give you a full refund with no questions asked. Premium now contains over 1,500 pages and 5,000 internal links. Over 15,000 coaches have subscribed to Premium.

>>>> Dustin - BELOW IS THE NEW TEXT  - the destinations stay the same, but I put a list of link destinations at the end >>>> 

The Free No Lines Drills below are from SoccerHelp Premium. They are only on SoccerHelp.
Dribble Across a Square ™ Instructions and Video U8 & up, Rec & Select. Definitely try this. The BEST way to teach dribbling to U8 and older, which is the most important soccer skill. Fast results. Play this at every practice as a warm-up - it develops tremendous skill. Teaches players to dribble with both feet in traffic while looking up. Fast to set up - only 4 cones. No Lines and every player has a ball. Watch the Video. Below is what coaches say -
"At every practice we religiously do Dribble Across a Square, Dribble Around Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 Boys travel team
"We played Dribble Across a Square and Dribble Around Cone and Pass Relay Race at every practice, and the results were phenomenal." Greg, U9
Hit The Coach ™ Instructions and Video U4-U6. Definitely try this. This is the BEST drill for U4 and U6 - kids love it. No Lines, every kid has a ball, and fast set-up. Teaches tremendous skills - dribbling, kicking the ball while running, looking up while dribbling and kicking the ball, getting used to contact and chaos (very important things for young players). Watch the Video.
Aggressive Play & Bravery Game ™ Instructions and Video  U8 & up, Rec & Select. Soccer is a physical game and you don’t want your players get pushed around. This teaches bravery and aggressive play. It quickly makes a difference. Watch the Video. Below is what coaches say - 
"This is working beyond belief. Some of my timid girls are now amongst the toughest on the team." Mark, CA, U1OG
"The other team was bigger and trying to play very aggressively against us and, although they really tried, the other team could not push my boys around." Stephanie, U10B
Dribble Around Cone & Pass ™ Instructions and Video U8 & up, Rec & Select. Definitely try this. This teaches Aggressive Receiving, passing while running, speed dribbling, turning, the importance of first-touch, one-touch control, and teaches receivers to move to the ball and how to receive the ball at game speed. You will see fast results, set-up is easy and every player is either a dribbler/passer or a receiver. This will teach your players to play faster. Watch the Video.
"We do Dribble Around Cone & Pass Relay Race every practice and it's a huge help in teaching that both the passer and receiver have a responsibility on a pass." Nick, U14
Go Score ™ Instructions and Video U4-U10 Rec. This teaches how to kick the ball while running. A simple, fun game for U4 and U6 and beginners up to U10. Every player has a ball and easy set-up. Watch the Video.
Throw-Ins Teaching Game Instructions and Video ™   U8 & up, Rec & Select. A quick and effective way to teach or practice throw-ins. If you are a beginning coach, review How to Teach Throw-Ins at Skills on SoccerHelp.com. Watch the Video.
Tick Tock ™ (aka "The Foundation") Instructions and Video U8 & up, Rec & Select. A simple drill that practices fast feet and ball control using inside-of-feet. Fast set-up and every player has a ball. Watch the Video.
Monster Invasion ™ Instructions  U4-U6 definitely try this. A simple, always fun game for U4 and U6. Every player has a ball and everyone, including the coach, has fun.
Small Sided Scrimmage Without A Goalie ™ Instructions  U8 & up, Rec & Select. This is a better way for most teams to scrimmage. At most, Rec teams should only scrimmage for about 10 minutes of each hour they practice. This game is a good way to evaluate players - you will be able to quickly tell a lot about a player's skills, natural abilities, and where they prefer to play. This game is better than a regular scrimmage in 2 ways: (1) All players learn to defend and play tough defense and block shots, and not rely on the Goalie, and (2) To score, they must work the ball close to the goal and not take long shots, so control, dribbling, passing, and movement off the ball in the Attacking Third are encouraged. This game has the disadvantage of a low ball per player ratio (only one ball for all the players), which is why we discourage scrimmaging.
Chips/Lofted Passes Game ™ Instructions U9 & up, Rec & Select. An effective way to practice "lofted passes with backspin". Every player should know how to "loft" the ball for shots, for long "over-the-top" passes & as a way to clear the ball. Easy set-up, lots of touches and a game format. 50% onball.
Kick A Crossed Ball Game ™ Instructions U8 & up, Rec & Select. A "crossed ball" is a ball coming from the side. This game is an effective, efficient way to practice timing the run and how to kick a crossed ball, which is not an easy thing to do. It will teach the player to take a short backswing, to keep his head down, eyes on the ball, and to start out by blocking the ball using the inside of the foot.
Driving School ™ Instructions U6-U10 Rec. This game is a way to teach control dribbling, using the bottom of foot to stop the ball, pullbacks, and using outside of right foot and left foot. Easy set-up and every player has a ball. This isn't as good as Hit the Coach or Dribble Across a Square but can provide some variety.
Coaching Tips Worth 2 Goals Per Game Video U8 & up, Rec & Select. Definitely try this. This isn't a drill, but it is important. It is a way to teach players to mark up on opponent's throw ins, goal kicks and punts. Watch the Video. Below is what coaches say -

"Coaching Rule No. 1 really is worth a couple goals a game. Super easy to teach, and super easy to coach from the sidelines." Bob, U10

"For about 2 weeks, we worked on nothing other than soccer Coaching Rules 1 - 3. We won our next 5 games scoring 20 goals and giving up none, we won 6 - 0, 3 - 0, 4 - 0, 3 - 0 and 4 - 0." Tony, U16

===== Dustin, links and destinations are below ========

Dribble Across a Square ™ Instructions and Video   goes to  http://www.soccerhelp.com/soccer_drills/Dribble.shtml 

Hit The Coach ™ Instructions and Video   goes to  http://www.soccerhelp.com/soccer_drills/Hit.shtml 

Aggressive Play & Bravery Game ™ Instructions and Video    goes to  http://www.soccerhelp.com/strength-on-ball-report.shtml 

Dribble Around Cone & Pass ™ Instructions and Video    goes to  http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml 

Go Score ™ Instructions and Video    goes to  http://www.soccerhelp.com/soccer_drills/Kids-Soccer-Go-Score-Practice-Game.shtml 

Throw-Ins Teaching Game Instructions and Video ™      goes to  http://www.soccerhelp.com/soccer_drills/Throw-ins_Game.shtml 

How to Teach Throw-Ins     goes to http://www.soccerhelp.com/Throw.shtml 

Tick Tock ™ (aka "The Foundation") Instructions and Video    goes to  http://www.soccerhelp.com/soccer_drills/Tick_Tock.shtml 

Monster Invasion ™ Instructions     goes to  http://www.soccerhelp.com/soccer_drills/Monster_Invasion.shtml 

Small Sided Scrimmage Without A Goalie ™ Instructions     goes to  http://www.soccerhelp.com/soccer_drills/Small_Sided_Scrimmage.shtml 

Chips/Lofted Passes Game ™ Instructions     goes to  http://www.soccerhelp.com/soccer_drills/Chip.shtml 

Kick A Crossed Ball Game ™ Instructions     goes to  http://www.soccerhelp.com/soccer_drills/Kick_Crossed_Ball.shtml 

Driving School ™ Instructions     goes to  http://www.soccerhelp.com/soccer_drills/Driving.shtml 

Coaching Tips Worth 2 Goals Per Game Video     goes to  http://www.soccerhelp.com/22-coaching-rules-report.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed!
