### ISSUE TITLE
Changes to U4, U6, U8 Navigation Page, 7-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#172]
Dustin, I emailed you on 7-10-17 at 6:50 PM - use the email so you can see bold and formatting.

Dustin, on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml  >

1. Replace the first para with the 2 paras below >

SoccerHelp No Lines Drills are Practice Games and the ideal way to teach these age groups. They are fun, No Lines, all the players are involved and active, and they are "self-teaching" - players learn by simply playing the Practice Games. The Practice Games are carefully designed to teach fundamental soccer skills and concepts. Read the 400 Testimonials from coaches and you will see that the SoccerHelp program is fun and develops better soccer players. 

Watch the video below for how to be a great U4 and U6 soccer coach.

2. Above the Video add a title >

How to Coach U4 & U6 Kids Soccer

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
