### ISSUE TITLE
Fifth Version - Changes to Soccer Practice, 7-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#173]
Dustin, I emailed you the changes below on 7-11-17 at 10:37 AM - use the email so you can see colors, bold and links

Dustin, delete the 4 prior versions that I sent on 7-7-17 at 2:29 PM, on 7-10-17 at 7:37 PM, 9:30 PM, and 9:32 PM, and use this one.

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml >

1. The 2nd and 3rd lines of the Title are >

Soccer Practice Can Be Fun
Players Can Improve Twice as Fast
Replace them in Bold with >

Use No Lines Drills
Players Learn Twice as Fast
No Standing in Line

So the entire title will look like >

Soccer Practice
Use No Lines Drills
Players Learn Twice as Fast
No Standing in Line
29 Practice Tips and
Tips from 3 Famous Coaches

2. The first para is >

Soccer practice tips, plans, Free No Lines Soccer Drills, and a training program that is fun and really works. Use our No Lines Drills and your players will improve Twice as Fast because they will be practicing instead of standing in line. Most SoccerHelp drills are Practice Games that train players to play fast - try the free drills below and you will see the difference. There are over 400 Testimonials and Success Stories from coaches at the link below.

Replace it with the 2 paras below  (Soccer Drills goes to www.soccerhelp.com/soccer-drills.shtml  and  U4 U6 Soccer Drills & Tips   goes to http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml )  >

Soccer practice tips, Free No Lines Soccer Drills, and a training program that is fun and teaches great skills. Use our No Lines Drills and your players will improve twice as fast because they will be practicing instead of standing in line. 

U4, U6 coaches, go to U4 U6 Soccer Drills & Tips for how to coach U4 and U6, practice tips and drills. 

3. Change all the places that are underlined to be bold instead of underlined . For example >

Be sure each child has a ball

4.  add a new first section above >  Things to Do at Soccer Practice

The new section to add is below (the link goes to http://www.soccerhelp.com/soccer-formations.shtml )>

4 Most Important Things a Youth Soccer Coach Can Do

1. Teach Fundamental Skills - If you use SoccerHelp No Lines Drills your players will develop tremendous skills and have fun. 

2. Motivate Your Players to Come to Practice, Hustle, and Be Brave.

3. Make Soccer Fun - Players will quit soccer if it isn't fun. Don't make players stand in line - that isn't fun and wastes time.

4. Use the Formation and Style of Play that Best Fits Your Team - How to choose and teach the best Formation and Style of Play is explained on SoccerHelp at Soccer Formations . The wrong Formation and Style of Play can make a huge difference in your team's fun and success. If you coach U6, don't worry about this - just use SoccerHelp No Lines Drills and have fun.

5. In the 4th Section Header, delete >  (these are links)

So it reads > 

If you want to read more about this subject, try these related topics:

6. Make the 4 Section Headers Bold Blue , like below >

4 Most Important Things a Youth Soccer Coach Can Do

Things to Do at Soccer Practice
Things to Avoid at Practice

If you want to read more about this subject, try these related topics:

7. Number 4 is >

The best way to teach your players is by using SoccerHelp No Lines Practice Drills. Our Practice Drills are much better than line drills or scrimmaging. A good soccer drill is one that is fun, that teaches skills, concepts, team play, or field awareness, where everyone is active, where there are lots of touches on the ball, and that is quick and easy to set up and simple to explain and manage. The very best No Lines Practice Drills, such as our Dribble Across A Square™ and Dribble Around Cone & Pass Relay Race™ drills that are practice games, are self teaching, and players learn by playing the game. If you are spending too much time on set-up or instruction, simplify it. If it's not fun, it's not a good drill. There are thousands of drills and practice games available on the Internet, but less than 5% meet the criteria established by SoccerHelp. Try our No Lines Soccer Drills - most are original and copyrighted by us. They really work and your team will improve MUCH more quickly. You will notice the difference after just one practice. See the Testimonials and Success Stories for comments by coaches.

Replace it with (bold the 2 links and the place shown - they go to  www.soccerhelp.com/soccer-drills.shtml  and  http://www.soccerhelp.com/soccershop/testimonials  )  >

Use SoccerHelp No Lines Drills. Do NOT make players stand in line - lines are boring and waste time. Players will learn twice as fast if they don't stand in lines. Try our Free No Lines Drills . There are 1,000 Testimonials about the SoccerHelp Program. A typical example is >

"The Practice Games are AMAZINGLY EFFECTIVE!! Parents tell me their girls cannot wait to go to practice." Coach M.J.

8. Move the above section that was # 4 so it is # 1 (the section that starts Use SoccerHelp No Lines Drills that don't have lines  )

9. Replace # 6 with (the link goes to http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml ) >

If your team is U4 or U6, watch the 7 Free U4-U6 Videos. The videos show the perfect way to coach U4 and U6, how to teach basic soccer skills, how to avoid lines, and there is a great No Lines Practice Game named Hit the Coach. Players learn skills by playing SoccerHelp Practice Games like Hit the Coach - the games are "self-teaching". At U4 and U6, we recommend you focus on teaching dribbling, how to kick the ball, and basic rules (such as not using hands) but NOT passing. Passing is too confusing for U4 and U6 players and teaching it will hold back their development of other skills such as dribbling. The USYSA recommends this approach and we agree.

10. Number 8 is >

If your team is U8 or older, you should teach control dribbling, speed dribbling into Open Space (acceleration into Open Space), how to "chip" the ball, how to make a Throw-in, passing, and Aggressive Receiving. SoccerHelp has No Lines Drills to teach all of these.

Replace it with  (make the link Bold, like below ) >

If your team is U8 or older, you should teach control dribbling, speed dribbling into Open Space (acceleration into Open Space), how to "chip" the ball, how to make a Throw-in, passing, and Aggressive Receiving. There are Free No Lines Drills to teach all of these.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
