### ISSUE TITLE
Priority - look at the Mercola article on Desktop and Cell and discuss with David, 7-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#175]
Dustin, I emailed this on 7-11-17 at 1:13 PM

Dustin,

Look at http://articles.mercola.com/sites/articles/archive/2017/07/11/brazilian-beef-scandal.aspx 

- On a desktop it looks to be the same size as SoccerHelp and the Blackness seems the same

-  But on a Cell phone, the text is larger and easier to read

Can you make the following changes for mobile?

1. Notice that the Mercola article has less white space on the right and left sides - can you make the SH pages (the Responsive pages) that way? He has as much text as me in a line even though his text is larger.

2. Make the text larger so it is one point larger than the size of the text in Mercola's "Story at-a-glance"

3. Make the H2 and H3 the same size as the Text and make the H1 one point larger than the H1 and H2

On Desktop, can you make the Responsive pages a little narrower? BUT leave SH Home page alone?

- Hopefully, SH Home and the pages like Soccer Drills use different Style Sheets. If no, can you put SH Home on its own Style Sheet?

**Comment by dustinschaerer** [comment]
This is completed.
