### ISSUE TITLE
Soccer Drills changes, 7-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#176]
Dustin, I emailed this on 7-11-17 at 3:44 PM - use the email so you can see colors and links

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml >

1. Add a new 2nd para above  What Coaches Say  >

U4 & U6 coaches, go to U4-U6 Drills & Videos for drills, videos, and how to coach U4 and U6.

2. The Links List is >

29 Soccer Practice Tips
70 Soccer Tactics and Tips
18 Tips for U6 Coaches
Soccer Practice Plans
Videos of Best Drills
Soccer Journal article about our No Lines Drills

2(a). Delete the link >   18 Tips for U6 Coaches

2(b). Change the name of  Videos of Best Drills  to  Best Soccer Coaching Videos

2(c). In Soccer Journal article about our No Lines Drills delete the word "article" so it reads  Soccer Journal about our No Lines Drills

2(d). Add as the first link (it goes to http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml  ) >

U4-U6 Soccer Drills & Videos

So the links list looks like >

U4-U6 Soccer Drills & Videos
29 Soccer Practice Tips
70 Soccer Tactics and Tips
Soccer Practice Plans
Best Soccer Coaching Videos
Soccer Journal about our No Lines Drills

3. At Hit the Coach, add >

U4-U6.

after the link, so it looks like >

Hit The Coach ™ Instructions and Video U4-U6. Definitely try this. This is the BEST drill for U4 and U6 - kids love it. No Lines, every kid has a ball, and fast set-up. Teaches tremendous skills - dribbling, kicking the ball while running, looking up while dribbling and kicking the ball, getting used to contact and chaos (very important things for young players). Watch the Video.

4. At Dribble Around Cone & Pass, change >

 (Definitely try this)
to Definitely try this  , so it looks like > 
Dribble Around Cone & Pass ™ Instructions and Video U8 & up, Rec & Select. Definitely try this. This teaches Aggressive Receiving, passing while running, speed dribbling, turning, the importance of first-touch, one-touch control, and teaches receivers to move to the ball and how to receive the ball at game speed. You will see fast results, set-up is easy and every player is either a dribbler/passer or a receiver. This will teach your players to play faster. Watch the Video.

5. At Coaching Tips, 3 changes >

(a). Underline > Definitely try this

(b). in the first test, delete the 2nd sentence, which is > 

Super easy to teach, and super easy to coach from the sidelines.

(c ) . Replace the 2nd test with > 

"For about 2 weeks, we worked on nothing other than Coaching Rules 1 - 3. We won our next 5 games scoring 20 goals and giving up none." Tony, U16

So it looks like >

Coaching Tips Worth 2 Goals Per Game Video U8 & up, Rec & Select. Definitely try this. This isn't a drill, but it is important. It is a way to teach players to mark up on opponent's throw ins, goal kicks and punts. Watch the Video. Below is what coaches say -

"Coaching Rule No. 1 really is worth a couple goals a game." Bob, U10

"For about 2 weeks, we worked on nothing other than Coaching Rules 1 - 3. We won our next 5 games scoring 20 goals and giving up none." Tony, U16

6.  The Title above the Top video is > Best Soccer Dribbling Drill - Dribble Across Square Video Preview

Replace that title with >  Best Soccer Dribbling Drill for U8 & Older
If you can add an Alt tag, have it say > Soccer Drill to Teach Dribbling

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
