### ISSUE TITLE
Soccer Practice changes, 7-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#177]
Dustin, I emailed you this on 7-11-17 at 5:51 PM - use the email

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml >

1. Change the color of the 4 sub-headings from Blue to the same green as the Top Title, like >

Soccer Practice

2. In the 2nd para, it says > 

U4, U6 coaches

Change it to >

U4 and U6 coaches

So it reads >

U4 and U6 coaches, go to U4 U6 Soccer Drills & Tips for how to coach U4 and U6, practice tips and drills. 

3. In the first # 2, add 2nd and 3rd sentences in NON-bold >

By Brave we mean tough and not afraid of contact. A free drill that can teach this is at Aggressive Play and Bravery Game

So it reads (the link goes to  http://www.soccerhelp.com/strength-on-ball-report.shtml   ) >

Motivate Your Players to Come to Practice, Hustle, and Be Brave. By Brave we mean tough and not afraid of contact. A free drill that can teach this is at Aggressive Play and Bravery Game

4.  In the first # 4, second sentence, Soccer Formations should be a link to http://www.soccerhelp.com/soccer-formations.shtml , like below >

Use the Formation and Style of Play that Best Fits Your Team - How to choose and teach the best Formation and Style of Play is explained on SoccerHelp at Soccer Formations . The wrong Formation and Style of Play can make a huge difference in your team's fun and success. If you coach U6, don't worry about this - just use SoccerHelp No Lines Drills and have fun.

5. In the first # 7, the last sentence is >

You can see them at Motivational Patch Incentives

Change the link destination to >

www.soccerhelp.com/soccershop/ 

Like >

You can see them at Motivational Patch Incentives

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
