### ISSUE TITLE
One Soccer Drills change, 7-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#179]
Dustin, I emailed this on 7-11-17 at 6:18 PM

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml >

In the 2nd para, the link should go to www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml  >

U4 & U6 coaches, go to U4-U6 Drills & Videos for drills, videos, and how to coach U4 and U6.

**Comment by dustinschaerer** [comment]
completed
