### ISSUE TITLE
aMember Video starts with http - Is that okay?

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#18]
Dustin, the Premium aMember and Coacu Doug aMember admin pages both start with https but the aMember video is http://soccerhelp.com/members-video/admin 

Is it supposed to be that way?

Premium is https://www.soccerhelp.com/members/admin

Coach Doug is https://www.soccerhelp.com/members-doug/admin 

David

**Comment by dustinschaerer** [comment]
yes its fine for now
