### ISSUE TITLE
2 changes to U4-U6 Navigation, 7-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#180]
Dustin, I emailed this on 7-12-17 at 8:43 AM

Dustin, on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml >

1. Add below as the first thing on the Links List (just below U4, U6, U8 Links ) . The link goes to   http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml  >

7 Free U4-U6 Videos - Watch these if you coach U4-U6. Great tips and fun No Lines Practice Games that teach skills. 

Dustin, make the Link Bold but NOT the text

2. Remove the extra "s" on  29 Soccer Practice Tipss

**Comment by dustinschaerer** [comment]
@david-huddleston COMPLETED.
