### ISSUE TITLE
Streaming Video Sign-up page change, 7-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#182]
Dustin, I emailed you this on 7-12-17 at 11:17 AM

Dustin,

on http://www.soccerhelp.com/members-video/signup .

At the top, below >

NOTE: Visit Premium Navigation if you want to sign up for Coach Doug's website, SoccerHelp Premium, or Advanced Soccer Tactics.

Add a second NOTE > 

NOTE: There are 4 choices below - Coach Doug for U4-U6, Foot Skills, and Individual and League subscriptions.

**Comment by dustinschaerer** [comment]
This is completed.
