### ISSUE TITLE
U4-U6 Navigation - add Promo Links, 7-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#183]
I emailed this on 7-12-17 at 11:28 AM - use the email to see colors

Make the 3 links bold 

Dustin, on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml >

Just below the video (above  "Testimonials from U6 Soccer Coaches  ) add the 3 paras below. The 3 links go in order to  http://www.soccerhelp.com/coachdoug-promo/Doug-Navigation.shtml  , http://soccerhelp.com/soccershop/coach-doug-soccerhelp-method-coaching-dvd-review   ,  http://www.soccerhelp.com/Premium_Sites_Navigation.shtml   >

Coach Doug's Website - Become a great U4 or U6 coach. Read about or Subscribe to Coach Doug's Website for U4 and U6 coaches. As low as $12. It has 200 pages and 26 Drills for U4-U6. 10 day Money Back Guarantee. We don't auto-renew or keep your credit card.

Coach Doug's Streaming Video or DVD - Read about or buy the Streaming Video or DVD. The full video is 57 minutes long, includes 26 Drills fur U4-U6, and is available as Streaming Video for $20 or a DVD for $31 (which includes shipping). There is a 5 day Money Back Guarantee. We don't auto-renew or keep your credit card.

Log In or Subscribe to Coach Doug's Website or Streaming Video.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
