### ISSUE TITLE
U4-U6 Videos page changes, 7-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#184]
I emailed this on 7-12-17 at 11:57 AM - use the email

Dustin, on http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml > 

1. Delete the first link, which is >

Read about or subscribe to Coach Doug's Website for U4-U6 Coaches

2. Replace the 3rd test with >

"Best $20 bucks I have ever spent on soccer. I have been 4 weeks into soccer season when I came up on your site. I used your techniques and the kids loved it. Thanks again." Coach Ben (he bought the Coach Doug Streaming Video)

3. Delete >
Read More Testimonials for Coach Doug
Should you buy the Coach Doug DVD or join his website? This is a frequent question. The DVD demonstrates 26 Practice Games and shows you how to practice. However, the website tells you what to do before, during and after the game, how to deal with parents and players, and explains the 26 Practice Games in more detail -- you can print the Practice Game instructions and take them to practice, which is very convenient and will save time. So, there is different information on each. The ideal thing is to buy the DVD and also use the website. Both carry a money-back guarantee, and you can purchase the DVD and a 120 day membership for about $50. The DVD and website will save you a great deal of time and make your coaching experience MUCH more enjoyable. If you join Coach Doug's website, or SoccerHelp Premium, there is a coupon on both sites for $5 off the Coach Doug DVD.
Membership to Coach Doug's site is as low as $11.94. Click here to Sign-Up 
Red Links Below are to Video Clips
Review of the Coach Doug DVD for Coaching U4 & U6 Soccer

4. In place of what you deleted put >

Red Links Below are to 7 Video Clips from the Coach Doug Streaming Video

5. Move the 7 Red Links to be Flush Left - leave them Bold  > 
How to Have Fun Practices that Teach Soccer Video 
"Hit the Coach™" Soccer Practice Game Video 
Dribbling and "Go Score" Soccer Practice Game Video 
A Better Way To Teach Dribbling and Soccer Skills Video 
Shy Soccer Player Gains Confidence Video -- Watch This! 
Soccer Shooting and Kicking Video 
How to Use Soccer Patches for Fun and to Motivate Players Video 

6. Add below the 7 Links (above the Buy Buttons) > 

Coach Doug's Streaming Video or Website Can Make You a Great U4 or U6 Coach

Coach Doug's Website - Read about or Subscribe. As low as $12 - 200 pages and 26 Drills for U4-U6. 10 day Money Back Guarantee. We don't auto-renew or keep your credit card.

Coach Doug's Streaming Video or DVD - Read about or buy the Streaming Video or DVD. The full video is 57 minutes long, includes 26 Drills fur U4-U6, and is available as Streaming Video for $20 or a DVD for $31 (which includes shipping). There is a 5 day Money Back Guarantee. We don't auto-renew or keep your credit card.

Log In or Subscribe to Coach Doug's Website or Streaming Video. They are separate subscriptions. 

(Dustin, The above 3 links go in order to  http://www.soccerhelp.com/coachdoug-promo/Doug-Navigation.shtml  , http://soccerhelp.com/soccershop/coach-doug-soccerhelp-method-coaching-dvd-review   ,  http://www.soccerhelp.com/Premium_Sites_Navigation.shtml   )

**Comment by dustinschaerer** [comment]
@david-huddleston COMPLETED.  This is also validated and responsive.
