### ISSUE TITLE
U4-U6 Videos - 6 more changes, 7-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#185]
I emailed this on 7-12-17 at 12:59 PM - use the email to see colors and lnks.

Dustin, on http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml > 

1. Replace the 3rd test with >

"Best $20 bucks I have ever spent on soccer. I used your techniques and the kids loved it." Coach Ben (he bought the Coach Doug Streaming Video)

2. The first sub-title is >

Red Links Below are to 7 Video Clips from the Coach Doug Streaming Video
Add to the end of it >

for U4 and U6 Coaches

So it reads >

Red Links Below are to 7 Video Clips from the Coach Doug Streaming Video for U4 and U6 Coaches

3.  Unbold the 7 links to video clips, like >

How to Have Fun Practices that Teach Soccer Video
"Hit the Coach™" Soccer Practice Game Video
Dribbling and "Go Score" Soccer Practice Game Video
A Better Way To Teach Dribbling and Soccer Skills Video
Shy Soccer Player Gains Confidence Video -- Watch This!
Soccer Shooting and Kicking Video
How to Use Soccer Patches for Fun and to Motivate Players Video

4. Above " Coach Doug's Website - Become a great U4 or U6 coach. " add >

Coach Doug's Streaming Video or Website Can Make You a Great U4 or U6 Coach

So it reads >

Coach Doug's Streaming Video or Website Can Make You a Great U4 or U6 Coach

Coach Doug's Website - Read about or Subscribe. As low as $12 - 200 pages and 26 Drills for U4-U6. 10 day Money Back Guarantee. We don't auto-renew or keep your credit card.

Coach Doug's Streaming Video or DVD - Read about or buy the Streaming Video or DVD. The full video is 57 minutes long, includes 26 Drills for U4-U6, and is available as Streaming Video for $20 or a DVD for $31 (which includes shipping). There is a 5 day Money Back Guarantee. We don't auto-renew or keep your credit card.

Log In or Subscribe to Coach Doug's Website or Streaming Video. They are separate subscriptions. 

5. In the para, 2 changes >

Coach Doug's Streaming Video or DVD - Read about or buy the Streaming Video or DVD. The full video is 57 minutes long, includes 26 Drills for U4-U6, and is available as Streaming Video for $20 or a DVD for $31 (which includes shipping). There is a 5 day Money Back Guarantee. We don't auto-renew or keep your credit card.

(a). Change the Link Destination to http://www.soccerhelp.com/soccershop/soccer-dvd 

(b). In the 2nd sentence, change "fur" to "for"

6. Below the Buy Buttons and above ""I recently bought your soccer DVD on coaching Ages 3, 4, 5, and 6 and was really amazed by your training techniques." Michael, TX, USA " >

add 2 centered UNBOLD links that go to  http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml and http://www.soccerhelp.com/coachdoug-promo/Doug-Testimonials.shtml   > put a line between the 2 links > 

U4 - U6 Navigation Page

More Coach Doug Testimonials

**Comment by dustinschaerer** [comment]
@david-huddleston COMPLETED.
