### ISSUE TITLE
Soccer Drills, add videos to 7 pages, 7-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#186]
I emailed this on 7-12-17 at 1:44 PM

Dustin, as discussed add the videos to the 7 pages below. Below shows the page to add the video to and the source of the video.

Add them to the top below the Title, like you did on Hit the Coach.  

For example, on Dribble Across, add it below >

Dribble Across A Square ™
No Lines Soccer Drill 
that is a Practice Game

- [x] Dribble Across ( http://www.soccerhelp.com/soccer_drills/Dribble.shtml ) add the Premium version of the video at http://www.soccerhelp.com/premium/videos/Dribble_Across_A_Square_Game_Demo.shtml 
**Also W3C Valid**

- [x] Aggressive Play  (http://www.soccerhelp.com/strength-on-ball-report.shtml  ) add the video from http://www.soccerhelp.com/soccer-videos/how-to-train-soccer-players-aggressive.shtml 
**Also W3C Valid**

- [x] Dribble Around Cone (http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml  ) add the video from http://www.soccerhelp.com/soccer-videos/soccer-drill-receiving-one-touch-pass-running.shtml 

- [x] Go Score  (http://www.soccerhelp.com/soccer_drills/Kids-Soccer-Go-Score-Practice-Game.shtml  ) add the video from http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-dribbling-and-go-score-practice-game.shtml 

- [x] Throw Ins  (http://www.soccerhelp.com/soccer_drills/Throw-ins_Game.shtml  ) add the video from http://www.soccerhelp.com/soccer-videos/teach-soccer-throw-in.shtml 

- [x] Tick Tock  (http://www.soccerhelp.com/soccer_drills/Tick_Tock.shtml  ) add the Premium video from http://www.soccerhelp.com/premium/videos/Tick_Tock_Game_Demo.shtml 
**Notice this video needs some help, its not truly responsive bc of the JavaScript from the JWPlayer**

- [x] Coaching Tips (http://www.soccerhelp.com/22-coaching-rules-report.shtml  ) add the video from http://www.soccerhelp.com/soccer-videos/defend-soccer-goal-kicks-punts-throw-ins.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston Are these pages worth W3C validating?

**Comment by david-huddleston** [comment]
No.

**Comment by dustinschaerer** [comment]
@david-huddleston Alright, all videos added :)
