### ISSUE TITLE
Site Map Generator and Link-Assistant

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#19]
Dustin, I agree that we need a good site map generator. Link-Assistant might work for you now - I had accidentally left WebAuditor open yesterday when you got the "License Violation" message, so that might have been the problem - I have closed it and can delete it from my computer if you want me to.

If Link-Assistant can't produce the Site Map we need, find a Site Map generator and let me know the cost and I will buy it.

David

**Comment by dustinschaerer** [comment]
Website Auditor has a good sitemap generator.
