### ISSUE TITLE
Soccer Formations - fix a link, 7-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#190]
I emailed this on 7-12-17 at 4:27 PM - use the email

Dustin, on http://www.soccerhelp.com/soccer-formations.shtml 

toward the bottom of the page, above the first image, it says > 

Below are 2 examples. For more diagrams, explanations of positions and how to teach the formations below see 8v8 Soccer Formations Diagrams and 11v11 Soccer Formations Diagrams

The link  8v8 Soccer Formations Diagrams  doesn't work - it should go to >

http://www.soccerhelp.com/soccer-formations-diagrams-8v8.shtml  

Below is the location > 

Soccer Formations Diagrams for 8v8 and 11v11

Below are 2 examples. For more diagrams, explanations of positions and how to teach the formations below see 8v8 Soccer Formations Diagrams and 11v11 Soccer Formations Diagrams

8v8 Soccer Formation Diagram for a 2-1-3-1, Attacking, 2 Fullbacks Deep, One Stopper, 3 Midfielders, One Forward. The ball is in the opponent's Penalty Box. A link is above to how to teach this formation.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
