### ISSUE TITLE
Fifth Version - Changes to Coach Doug Navigation page, 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#191]
I emailed this on 7-18-17 at 4:37 PM - use the email so you can see colors and bold.

Dustin, delete the versions dated 7-12-17 at 6:15 PM, on 7-17-17 at 5:15 PM and 6:57 PM, and 7-18-17 at 4:26 PM

Dustin, on http://www.soccerhelp.com/coachdoug-promo/Doug-Navigation.shtml >

1. Bootstrap the page and make it Responsive

2. The Title is >

Coach Doug Introduction And Navigation Page
Soccer Coaching Kids U4, U5, U6, U7
Soccer Coaching Kids Ages 3, 4, 5, 6, 7

Replace it with >

Coach Doug's Website, DVD & Streaming Video

How to Coach Kids Soccer U4-U6
No Lines Drills & Games, U4 & U6

3. Replace the Links List with >

Subscribe to Coach Doug Website
Buy Coach Doug Streaming Video
Read About Coach Doug Video & DVD
7 Free Coach Doug Video Clips

The links go to in order >

http://www.soccerhelp.com/members-doug/signup 
http://www.soccerhelp.com/soccershop/streaming-video 
http://www.soccerhelp.com/soccershop/soccer-dvd
http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml

4. The first para is >

Membership to Coach Doug's site is as low as $11.95. Click here to Sign-Up

Delete it and Replace it with > 

Coach Doug's website is described below. There is also a Coach Doug DVD that is available as Streaming Video. Membership to Doug's website is as low as $12 and the Streaming Video is $20. The links above provide information about the 57 minute DVD and the video (there is a detailed list of contents) and you can watch 7 free video clips from the DVD. There is a 5-Day Money Back Guarantee for the website, the DVD, and the Coach Doug Streaming Video. Testimonials are below.

5. In the 2nd para, delete the 2nd sentence >

We are proud to announce that Coach Doug Burgoyne 's new membership site for coaches of soccer ages 3, 4, 5 and 6 is now on SoccerHelp.

6. The first sentence of the 3rd para is >

I honestly believe that Coach Doug's method of coaching U4 and U6 soccer players (ages 3, 4, 5 and 6) is the best in the world.

Bold it, so it is like >

I honestly believe that Coach Doug's method of coaching U4 and U6 soccer players (ages 3, 4, 5 and 6) is the best in the world.

7. Change the Testimonials at the bottom of the page into a Block Quote

8. On the very bottom (above the bottom links) delete >

Remember: There is a 30-Day "No Questions Asked" Money Back Guarantee.

**Comment by dustinschaerer** [comment]
@david-huddleston Is this one worth W3C Validating? It'll take about 10 minutes

**Comment by david-huddleston** [comment]
No, it won't get ranked.

**Comment by dustinschaerer** [comment]
@david-huddleston This is pretty much completed, but there is one more big testimonial that spans multiple lines  before the big blockquote.  Should I delete it ?

http://www.soccerhelp.com/coachdoug-promo/Doug-Navigation.shtml
