### ISSUE TITLE
Third Version - Changes to U4-U6 Navigation Page, 7-13-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#192]
Dustin, The changes didn't get done on the page.

I emailed this on 7-13-17 at 11:07 AM - use the email.

Dustin, delete the 2 earlier versions I sent on 7-13-17 at 9:50 AM and 10:58 AM

Dustin, on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml > 

1. Delete the Centered link that is just below the title >

7 Free U4-U6 Videos

2. The First link on the Links List is > 

7 Free U4-U6 Videos

Change the hyphen to &, so it reads >

7 Free U4 & U6 Videos

3. Bold the 2 Links >

•	18 Tips for U4-U6 Coaches
•	29 Soccer Practice Tips

4. In the Links List, the last link is >

U-8 Soccer Coaching (read U-6 above first)

Delete the 2 hyphens, so it looks like >

U8 Soccer Coaching (read U6 above first)

5. Move the 2 links >

18 Tips for U4-U6 Coaches
29 Soccer Practice Tips

So they are the 2nd and 3rd links and the Links List looks like >

•	7 Free U4 & U6 Videos - Watch these if you coach U4-U6. Great tips and fun No Lines Practice Games that teach skills.
•	18 Tips for U4-U6 Coaches
•	29 Soccer Practice Tips
•	U4 Soccer Drills
•	U6 Soccer Drills
•	U8 Soccer Drills
•	U4 Soccer Coaching
•	U6 Soccer Coaching
•	U8 Soccer Coaching (read U6 above first)

**Comment by dustinschaerer** [comment]
@david-huddleston - This is completed.

**Comment by dustinschaerer** [comment]
@david-huddleston This is complete.

**Comment by dustinschaerer** [comment]
@david-huddleston Now this is completed and uploaded for sure. :1st_place_medal:
