### ISSUE TITLE
Third Version -  Doug Video Clips page changes, 7-13-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#193]
I emailed this on 7-13-17 at 12:23 PM - use the email to see colors and links.

Dustin, delete the 2 prior version I sent on 7-13-17 at 10:08 Am and 10:34 AM

Dustin, on  http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml >

1. The Top Title is >
U4-U6 Soccer Videos
Change it to >
U4 & U6 Soccer Videos

The 2nd and 3rd lines of the title are >
Free Coaching & Drills Videos
How to Teach U4 & U6
Add "7" to the 2nd line, so it reads >

7 Free Coaching & Drills Videos
Add "Soccer" to the 3rd line so it reads >
How to Teach U4 & U6 Soccer
AND Add a new 3rd line >
Fun No Lines Drills & Games
So the title reads >
U4 & U6 Soccer Videos
7 Free Coaching & Drills Videos
Fun No Lines Drills & Games
How to Teach U4 & U6 Soccer

2. Delete the 2 "Buy" buttons at the top - leave them at the bottom. 

3. Move the 3 Blue Tests so they are below the Links List (and above " Coach Doug's Streaming Video or Website Can Make You a Great U4 or U6 Coach
" ) >

"I loved Coach Doug's video. I struggled coaching my son's U6 until I watched his video. It made all the difference in the world. I now make all our U6 coaches watch his video and they love it as well." Amy, coach and league administrator
"I recently ordered the Coach Doug DVD and I can't say enough about it. It is worth every penny (and more) that I paid for it." Coach David, WA
"Best $20 bucks I have ever spent on soccer. I used your techniques and the kids loved it." Coach Ben (he bought the Coach Doug Streaming Video)

4. As a new first para  add (underline the first sentence) >

The free soccer coaching videos below will help any U4 or U6 coach. They show No Lines Drills and Games and the best way to coach U4 and U6 players so your players will love coming to practice and develop tremendous skills. The video clips are from the Coach Doug DVD for U4 and U6 coaches, which is available in Streaming Video at the link below. Coach Doug also has a website that is described below. Testimonials are below.

5. Replace the first sub-title with >

7 Video Clips from the Coach Doug Streaming Video for U4 and U6 Coaches

6. Add out beside the Links the text shown below > 

How to Have Fun Practices that Teach Soccer Video - 2 minutes
"Hit the Coach™" Soccer Practice Game Video - 1 minute
Dribbling and "Go Score" Soccer Practice Game Video - 2 minutes
A Better Way To Teach Dribbling and Soccer Skills Video - 2 minutes
Shy Soccer Player Gains Confidence Video -- Watch This! - 2 minutes
Soccer Shooting and Kicking Video - 2 minutes
How to Use Soccer Patches for Fun and to Motivate Players Video - 4 minutes

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
