### ISSUE TITLE
Ninth Version - Doug Video Clips page changes, 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#194]
I emailed you this on 7-18-17 at  6:03 PM - use the email.

Delete the 8 versions I sent you on 7-13-17 at 2:46 PM AND on 7-14-17 at 10:17 AM, 4:33 PM, 9:35 PM, 9:39 PM and 10:15 PM, on 7-16-17 at 7:26 PM, and 7-18-17 at 5:58 PM

Dustin, on  http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml >

1. The Title is >

U4 & U6 Soccer Videos
7 Free Coaching & Drills Videos
Fun No Lines Drills & Games
How to Teach U4 & U6 Soccer

Replace the 3rd and 4th lines and add a 5th line >

No Lines Soccer Drills & Games
How to Coach U4 & U6 Soccer
18 Tips for U4 & U6 Coaches

So it reads >

U4 & U6 Soccer Videos

7 Free Coaching & Drills Videos
No Lines Soccer Drills & Games
How to Coach U4 & U6 Soccer
18 Tips for U4 & U6 Coaches

2. Make the 3rd line a H2 (No Lines Soccer Drills & Games )

3. In the first para, add the word Soccer to the 2nd sentence between "Lines" and "Drills", so it reads > 

They show No Lines Soccer Drills and Games and the best way to coach U4 and U6 players so your players will love coming to practice and develop tremendous skills. 

4. Add the black text (the minutes) beside the Links, as shown below > 

How to Have Fun Practices that Teach Soccer Video - 2 minutes
"Hit the Coach™" Soccer Practice Game Video - 1 minute
Dribbling and "Go Score" Soccer Practice Game Video - 2 minutes
A Better Way To Teach Dribbling and Soccer Skills Video - 2 minutes
Shy Soccer Player Gains Confidence Video -- Watch This! - 2 minutes
Soccer Shooting and Kicking Video - 2 minutes
How to Use Soccer Patches for Fun and to Motivate Players Video - 4 minutes

5. Move the 2nd and 3rd links to be 1st and 2nd, so it looks like >

"Hit the Coach™" Soccer Practice Game Video - 1 minute
Dribbling and "Go Score" Soccer Practice Game Video - 2 minutes
How to Have Fun Practices that Teach Soccer Video - 2 minutes
A Better Way To Teach Dribbling and Soccer Skills Video - 2 minutes
Shy Soccer Player Gains Confidence Video -- Watch This! - 2 minutes
Soccer Shooting and Kicking Video - 2 minutes
How to Use Soccer Patches for Fun and to Motivate Players Video - 4 minutes

6. Change the link destinations of the first and second links to >

"Hit the Coach™" Soccer Practice Game Video  (change the destination to   http://www.soccerhelp.com/soccer_drills/Hit.shtml 
Dribbling and "Go Score" Soccer Practice Game Video (change the destination to   http://www.soccerhelp.com/soccer_drills/Kids-Soccer-Go-Score-Practice-Game.shtml  

7. Just below the Links List where the first Test currently is, add what is below  ( the link goes to  http://www.soccerhelp.com/U4-U6-soccer-coaching.shtml ) > 

18 Tips for U4 & U6 Coaches - 18 Tips for U4 & U6 Coaches What to do and NOT do.

8. In the list of 3 Tests below the Links List >

(a).  Delete the 2nd link so only the 2 below are left > 

"I loved Coach Doug's video. I struggled coaching my son's U6 until I watched his video. It made all the difference in the world. I now make all our U6 coaches watch his video and they love it as well." Amy, coach and league administrator
"Best $20 bucks I have ever spent on soccer. I used your techniques and the kids loved it." Coach Ben (he bought the Coach Doug Streaming Video)

(b). Turn the 2 Tests that are above into a "Block Quote" like you did the Tests on Soccer Drills.

9. In the section titled > Coach Doug's Streaming Video or Website Can Make You a Great U4 or U6 Coach

Switch places with the first 2, so the section reads >

Coach Doug's Streaming Video or DVD - Read about or buy the Streaming Video or DVD. The full video is 57 minutes long, includes 26 Drills for U4-U6, and is available as Streaming Video for $20 or a DVD for $31 (which includes shipping). There is a 5 day Money Back Guarantee. We don't auto-renew or keep your credit card.
Coach Doug's Website - Become a great U4 or U6 coach. Read about or Subscribe to Coach Doug's Website for U4 and U6 coaches. As low as $12. It has 200 pages and 26 Drills for U4-U6. 10 day Money Back Guarantee. We don't auto-renew or keep your credit card.
Log In or Subscribe to Coach Doug's Website or Streaming Video.

10. Change the Button that says "Purchase Streaming Video Now"   to say "Buy Streaming Video"

11. Add a 3rd Button to the left of "Buy DVD" that says > Subscribe

and goes to http://www.soccerhelp.com/Premium_Sites_Navigation.shtml 

12. Delete the 2 Tests on the bottom of the page and in their place put what is below as a Block Quote 

(Dustin, have  More Testimonials be the Title above the Block Quote )>

More Testimonials

"I loved Coach Doug's video. I struggled coaching my son's U-6 until I watched his video. It made all the difference in the world. I now make all our U-6 coaches watch his video and they love it as well." Amy, coach and league administrator

"I require all of our U4 and U6 coaches to watch the Coach Doug DVD." Steven, IL, Coaching Director, Rec Soccer

"Doug, First of all, your site is a gold mine of information. This is my second season using the SoccerHelp method and it is unbelievable how well it works. We just started a week ago and already my team is looking great!" U6 Coach

"I recently bought your soccer DVD on coaching Ages 3, 4, 5, and 6 and was really amazed by your training techniques." Michael, TX

"Been a user of your site for years and it is great! Has helped all three of my boys, plus the hundred or so kids I've coached, so thanks!” Ron, MD

"I am coaching my 5 year old daughter this year for the first time and this stuff is absolutely priceless." Clint, KS

"I've been coaching my 5-year old daughter's soccer team for 3 or 4 weeks now. I saw great success and improvement in use of skills by many of the kids in our last game this past Saturday (i.e. changing ball direction on command, stealing the ball, much more control dribbling, better scoring accuracy, no hand balls, no own goals, and even an intentional pass to share the ball. SoccerHelp turned me all around in my way of thinking about coaching little kids, and I think it's the best method I've seen."
Sincerely, 
Danny, CA

“I've been impressed by your approach and methods since the moment I came across them. I coach U5 soccer and have been using exclusively your methods since I started. They have lots of fun in practices as each of them is constantly with a ball at their feet. I'm also using practice patches as well as patches to reward in game efforts such as attitude, defense, assists, hustle and teamwork. Thanks.” I.M.

"I recently purchased Coach Doug SoccerHelp Method of Coaching Ages 3, 4, 5 & 6 DVD and it arrived the day before our first practice. I only had time to watch 25 minutes of the DVD, but I had enough ammo to coach our first 45 minute practice. At the beginning of the practice 2 of the 8 kids were crying asking for their parents. By the end of the practice all of the kids were playing soccer and having a GREAT time. We played the carrot game, hickory dickory dock, follow the leader, and freeze. They LOVED it. My nephew is on the team and one of the parents said to my sister (without knowing she was my sister), "Wow you can tell he's done this before." This was my first time EVER to coach a soccer practice. I would recommend this video to ANY new soccer coach at this age level. I was one of the coaches who was asked to coach because they didn't have enough coaches for all of the teams. I can already tell how the techniques in the video are going to help my kids excel. BUY THIS DVD WITH CONFIDENCE! It made me look like a veteran coach and I watched the DVD 1 hour before our practice." 
Tommy, TX, U5

“I had my first practice on Friday night using information that I learned on Coach Doug's website and what a difference it made. Last season, I felt lost and just plodded through it all and now I am more confident and it is a whole new environment. Best investment I have made for soccer.” Janet, TX

"The SoccerHelp Coach Doug Program really worked well on two girls, who at the beginning of the year, I wouldn't have picked to play on my team. One cried every time she fell and the other just stood there. It was Doug's Video that gave me the tools and encouragement to train these two and help them obtain the confidence to play at a level beyond anyone's expectations. The examples Doug showed of the various personalities on his team were tremendous. Doug showed me that patience and fun works in the long run. These girls never scored a goal but they always stopped the ball and turned it around and helped the team. They were always in the right place at the right time. In the semi final, when it really counted, they performed and because of them the other team did not score a goal. The patch rewards and fun games worked extremely well for these girls. Thanks again and again." Troy, Member of Coach Doug's Website

"Hey all - Coach Greg here. What an awesome site. I discovered Soccerhelp.com back about 6 years ago when my now 9 year old son started playing soccer and me coaching. I can tell you - there is nothing even close. That little soccer team back then, The Hurricanes - they were awesome!! Many of those kids still play soccer to this day and I run into many of them who still remember the good ol Hurricane days. Well, here it is several years later, and I now have a 3 year old daughter. We just started soccer and yep - I coach but not without Soccer Help and Coach Doug's infinite fun!! We play our 4th game of the season tomorrow and the improvement game after game is astonishing. Last weeks game - all I saw were elbows and smiles. Lots of big smiles. Thanks Coach Doug - Thanks SoccerHelp - My children continue to benefit from your passion! Play Hard - Play Fair - Have Fun!"  Greg

"I can go on and on about the success stories. But I will leave you with one - my own Daughters. Last Year my daughter played soccer as a almost 3 Year old. The coaches did nothing but throw the ball out there and let them run around. They did not engage that much at all. My daughter was so disinterested that, on game day, she did not even want to get into the game and play. She even got to the point where she did not want to go to practice. It was a grind. For games and practice, She would stay on the side and dig in the dirt and pick flowers. THIS YEAR - I said I am going to coach and use the SoccerHelp methods - WOW...WHAT A DIFFERENCE. My daughter is now one of the better players on the team, has scored goals and dribbles the ball down the field with both feet w/o looking down!! WOW...I AM SHOCKED!!! Anyway...A success STORY!!! I am behind this website 100%!! THANK YOU THANK YOU!!!!"

"I've played soccer forever but I'm coaching my son's U6 team for the very first time this season. Of course I've been online hunting for tips on how to do it, and discovered your page. It took me about five minutes to figure out that it would be worth it to pay for a Coach Doug subscription, and it's taken about five minutes of me looking through the Coach Doug's site to know that I made the right decision. Thanks so much for providing this information, especially for newbies like me. I love soccer, I want my kids to love it to, and I'm glad there's people who can help make that happen. Thanks." Alexander, Coach Doug Member

"I NEVER played soccer before. My daughter's team needed a coach and no one stepped forward. The team was going to be canceled - that's how it started for me. I now coach two teams each season and 'learned' how to coach all on SoccerHelp. PLAY THE GAMES and read the helps. You will be amazed. I use the patches, too. I love the current suggestions found on the website, but previously I had used them only for assists." 

“First and foremost I want to thank you for all the information provided on SoccerHelp and a special thanks to Coach Doug. I have been coaching a rec league now for about 2 1/2 yrs. I started out with 3-5 Year olds with my Daughters team and then added 6-8 yr olds my next year when some of my kids moved up and I am now coaching 9-12 yr olds. With the practice games and information provided on SoccerHelp, I have managed to create an incredible atmosphere for my young players to really enjoy the game of soccer at the same time having almost every coach in the league stopping by once or twice a season to watch how I run my practices. When I get new additions to my teams I always take the ones that need the most work or the youngest of the group. By the time our first game is here we are a team that is unbeatable. Anyways I could go on for hours with this type of praise that the site has." Coach Gregg GA, 3-5, 6-8, 9-12, Premium Member for 2 years”

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
