### ISSUE TITLE
Second Version - 500 Soccer Coaching Tips Navigation page, 7-13-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#196]
I emailed you this on 7-13-17 at 7:44 PM - use the email so you can see colors and bold

Delete the version I sent on 7-13-17 at 6:56 PM and use this one - some links were wrong

Dustin, on    www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml  > 

This is a major re-do of this page >

1. Change the Title to  (make  500 Soccer Coaching Tips  the H1 )  >

500 Soccer Coaching Tips

Navigation Page

2. Delete the 1st and 2nd paras AND the Links List  -  BUT leave the article below the Links List that starts  >
Soccer Coaching Tips and Tactics
Importance of a Stopper
2-1-2-2 vs. 2-3-2 Soccer Formation
Analysis, Evaluation and Tips
How to Beat a Pushed Up Defense

3. In place of what you deleted, add what is below (the Dictionary link is BOLD and goes to www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_A.shtml  ) >

How to Use this Page to Help Your Team - Scan the list of links to look for the Topic that interests you. The Topics are best articles are first and others are in alphabetical order.

Another Way to Find Topics - You can navigate the 400 free pages using the SoccerHelp Dictionary or use the links on the Home Page. There are 400 Topics in the Dictionary.

Below are links to over 500 Soccer Coaching Tips - 

Attacking Tips and Tactics - 37 Soccer Attacking Tips, Tactics & Strategies, How to Score More Goals, How to Determine Why Your Team Isn't Scoring More Goals, 7 Ways Most Soccer Goals Are Scored  (goes to http://www.soccerhelp.com/how-to-score-more-goals-report.shtml 

Bunching Up - 7 Ways to Stop It  (goes to http://www.soccerhelp.com/Coaching_Soccer_To_Not_Bunch.shtml )

Defense - 3 Things to Teach   (goes to http://www.soccerhelp.com/terms/soccer-support.shtml  

Dehydration - 9 Tips to Avoid It   (goes to  http://www.soccerhelp.com/Sportsdrinks_Hydration_Athleticperformance.shtml 

Dribbling - How to Teach - 4 Tips  (goes to http://www.soccerhelp.com/newsletter_archive/Soccer_Drills_8_17_2009.shtml 

Evaluate Players and Assign Positions - 25 Tips      (goes to http://www.soccerhelp.com/Evaluating_Soccer_Players_And_Teams.shtml   ) 

Fast Play  - 7 Tips, How to Teach Fast Play  (goes to http://www.soccerhelp.com/soccer-articles/100913-play-fast-soccer.shtml  

Formations  - 11 Tips. Best article. Basics, How to Choose the Best Formation and Style of Play, How to teach a Formation, Depth versus Width, Why the Center is Critical  (goes to http://www.soccerhelp.com/soccer-formations.shtml   

Formations, 7v7 - 5 Tips  (goes to http://www.soccerhelp.com/newsletter_archive/1.19.2009.shtml 

Formations, 8v8 - 8 Tips   (goes to  http://www.soccerhelp.com/Soccer_Stopper_Soccer_Formation_8v8.shtml )

Formations, 8v8 - 14 Tips  (goes to http://www.soccerhelp.com/soccer-articles/100823-8v8-soccer-formations.shtml 

Formations, 9v9  - 9 Tips (goes to  http://www.soccerhelp.com/9v9-Soccer-Formations.shtml 

Formations, 11v11 - 5 Tips  (goes to http://www.soccerhelp.com/Soccer_Formations_Soccer_Positions.shtml 

Fullbacks - How to Motivate - 4 Tips   (goes to http://www.soccerhelp.com/Motivating_Rec_Fullbacks.shtml 

Goal Kicks - 3 Tips  (goes to  http://www.soccerhelp.com/soccer-articles/090413-soccer-goal-kick.shtml 

Goalkeepers - 5 Tips   (goes to http://www.soccerhelp.com/terms/soccer-goalkeeper.shtml 

Hot Days Tips - 14 Tips that are Worth a Goal or Two on a Hot Day    (goes to http://www.soccerhelp.com/soccer-articles/100902-soccer-coaching-tips.shtml

Indoor Soccer - 31 Tips   (goes to http://www.soccerhelp.com/Indoor_Soccer_Tips_From_Coaches.shtml 
 
Kick Soccer Ball - How to Teach - 23 Tips      (goes to http://www.soccerhelp.com/kick-shoot-soccer-ball.shtml )

Kick-Offs - 3 Tips   (goes to  http://www.soccerhelp.com/Kick-Offs_Navigation_Page.shtml  ) 

Motivate Players - 12 Ways  (goes to http://www.soccerhelp.com/soccer-articles/130212-12-ways-to-motivate-players.shtml )

Motivational Plan - 4 Tips   (goes to http://www.soccerhelp.com/Motivational-Plan-Players-Students.shtml 

New Coaches - 19 Tips  (goes to  http://www.soccerhelp.com/Basic_Info.shtml )

Passing & Receiving - 10 Tips, How to Teach  (goes to http://www.soccerhelp.com/Overview.shtml  )

Positions, Assigning - 17 Tips, Best Positions for Players who are Skilled, Fast, Slow and Timid (goes to  http://www.soccerhelp.com/soccer-articles/120824-Select-Soccer-Formation.shtml   )

Positions Basics & Soccer Kick-Offs - 3 Tips  (goes to http://www.soccerhelp.com/Soccer_Positions_Basics.shtml

Positions - Evaluate & Assign Players - 25 Tips   (goes to http://www.soccerhelp.com/soccer-articles/120316-soccer-positions-assigning-players.shtml

Positions - How to Teach, Coach & Assign - 30 Tips   (goes to  http://www.soccerhelp.com/youth-soccer-positions.shtml  )

Positions - Rotating   (goes to http://www.soccerhelp.com/soccer-articles/090309-rotate-soccer-positions.shtml 

Practice - 10 Things you Need    (goes to http://www.soccerhelp.com/Soccer-Practice-Needs.shtml )

Practice - 12 Tips  (goes to http://www.soccerhelp.com/Soccer-Practice-Tips.shtml )

Practice - 18 Tips  (goes to http://www.soccerhelp.com/soccer-articles/110712-soccer-practice-plans-tips-1.shtml )

Practice - 29 Tips    (goes to   http://www.soccerhelp.com/soccer-practice.shtml  )

Practice - Competitive Training - 7 Tips  (goes to http://www.soccerhelp.com/soccer-articles/090831-soccer-drills.shtml

Practice Plans - 5 Tips    (goes to http://www.soccerhelp.com/soccer-practice-plans.shtml 

Praise - How to Give - 8 Tips   (goes to http://www.soccerhelp.com/Motivational-Plan-Players-Students.shtml 

Push Up Fullbacks on Attack? - 7 Tips   (goes to http://www.soccerhelp.com/Coach_Soccer_Offense_Push_Up.shtml )

Receiving - Teach Aggressive Receiving  (goes to http://www.soccerhelp.com/terms/soccer-aggressive-receiving.shtml 

Scrimmaging - 4 Tips   (goes to http://www.soccerhelp.com/soccer_drills/Small_Sided_Scrimmage.shtml  

Skills - 12 Tips  (goes to http://www.soccerhelp.com/Soccer_Skills.shtml )

Stopper Importance - 7 Tips (goes to http://www.soccerhelp.com/Soccer_Stopper_Soccer_Formation_8v8.shtml

Styles of Play - 10 Tips Your Style of Play is as important as your Formation and can make a huge difference. (goes to http://www.soccerhelp.com/terms/soccer-styles-of-play.shtml )

Tactics - 70 Tips and Tactics for U8-U18    (goes to  http://www.soccerhelp.com/soccer-tactics.shtml   )

Tactics, Advanced - 20 Tips    (goes to  http://www.soccerhelp.com/soccer_tactics_advanced/Advanced_Soccer_Tactics_Preview.shtml   )

Tactics for Select and High School - 14 Tips (this goes to http://www.soccerhelp.com/Soccer_Tactics_Select_Travel_High_School_Soccer.shtml

Teach Players - 20 Things to Teach (goes to  http://www.soccerhelp.com/22-coaching-rules-report.shtml  ) 

Throw-Ins - How to Teach - 8 Tips  (goes to http://www.soccerhelp.com/Throw-ins_Navigation_Page.shtml )

Toughness - How to Teach  (goes to http://www.soccerhelp.com/strength-on-ball-report.shtml )

Tryouts - 10 Tips  (goes to http://www.soccerhelp.com/soccer-articles/121120-Soccer-Tryout-Drills.shtml 

Tryouts - 14 Tips - Tryouts Evaluation Form (goes to http://www.soccerhelp.com/Soccer_Tryouts_Evaluation_Form.shtml

Tryouts - 19 Tips   (goes to http://www.soccerhelp.com/Soccer_Tryouts_Select_Soccer_Travel_Soccer.shtml

U4 & U6 - 18 Tips  (goes to http://www.soccerhelp.com/U4-U6-soccer-coaching.shtml

U4 & U6 - More Touches, New Ball - 10 Tips (goes to http://www.soccerhelp.com/soccer-articles/130322-soccer-new-ball-method.shtml 

Weak Teams - 21 Tips  (goes to http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml )

World Cup Lessons - 5 Tips, Defense, Finishing, Tactics  (goes to http://www.soccerhelp.com/soccer-articles/100719-soccer-defense-tips.shtml 

World Cup Lessons - 5 Tips, Attacking, Shooting, One-Touch, Brave Defenders   (goes to http://www.soccerhelp.com/soccer-articles/100726-soccer-shooting-tips.shtml 

World Cup Lessons - 6 Tips, Attacking Support, Corner Kick Tactics, Defense, Long Balls as a Tactic     (goes to http://www.soccerhelp.com/soccer-articles/100802-soccer-corner-kick-tactics.shtml )

World Cup Lessons - 6 Tips, (goes to http://www.soccerhelp.com/soccer-articles/100809-soccer-coaching-tips.shtml 

Another Way to Find Topics - You can navigate the 400 free pages using the SoccerHelp Dictionary or use the links on the Home Page. There are 400 Topics in the Dictionary.

**Comment by dustinschaerer** [comment]
@david-huddleston This is ready!
