### ISSUE TITLE
Fourth Version - U4-U6 Navigation Page Changes, 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#198]
I emailed you this on 7-18-17 at 3:22 AM - use the email

Delete the versions I sent on 7-14-17 at 11:28 AM and 12:51 PM and on 7-18-17 at 11:22 AM

Dustin,

on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml >

1. Change the code to >

<title>Fun Kids Soccer Drills & Games - SoccerHelp</title> 
<meta name="keywords" content="Kids Soccer Drills Games U4, U6, U8">
<meta name="description" content="Fun No Lines Soccer Drills and Games for kids U4, U6 and U8 and how to coach kids soccer">

2. The current title is > 

Kids Soccer U4, U6, U8
How to Coach & Videos
No Lines Drills & Games
Navigation Page

Change it to > 

Kids Soccer Drills

Fun No Lines Drills & Games
Videos of How to Coach
Navigation Page

3. Have the H1 be both the Top line

Kids Soccer Drills

and

- Have the H2 be > 
Fun No Lines Drills & Games
 

4. The first para is >

SoccerHelp No Lines Drills are Practice Games and the ideal way to teach these age groups. They are fun, No Lines, all the players are involved and active, and they are "self-teaching" - players learn by simply playing the Practice Games. The Practice Games are carefully designed to teach fundamental soccer skills and concepts. Read the 400 Testimonials from coaches and you will see that the SoccerHelp program is fun and develops better soccer players.

Replace it with (Dustin, the link Soccer Drills goes to http://www.soccerhelp.com/soccer-drills.shtml and  500 Coaching Tips  goes to ) >

Kids soccer drills, games, videos, and how to coach kids soccer. SoccerHelp No Lines Soccer Drills are Practice Games and the ideal way to teach kids U4 and U6. They are fun, No Lines, all the players are active, and they are "self-teaching" - players learn soccer skills by simply playing the Practice Games. There is NO standing in line so kids have more fun and improve faster. Read the Testimonials below from coaches and you will see that the SoccerHelp program is fun and develops better soccer players.
For U9 and older, visit Soccer Drills or 500 Coaching Tips

>>> After the changes, the top text will be >

Kids soccer drills, games, videos, and how to coach kids soccer. SoccerHelp No Lines Soccer Drills are Practice Games and the ideal way to teach kids U4 and U6. They are fun, No Lines, all the players are active, and they are "self-teaching" - players learn soccer skills by simply playing the Practice Games. There is NO standing in line so kids have more fun and improve faster. Read the Testimonials below from coaches and you will see that the SoccerHelp program is fun and develops better soccer players.

For U9 and older, visit Soccer Drills or 500 Coaching Tips

Watch the video below for how to be a great U4 and U6 soccer coach.

5. The first Sub-Title is >   U4, U6, U8 Links

- Change it to >  U4, U6, U8 Soccer Drills, Games, Videos & How to Coach

(it is the H3) 

6. The 3rd link is >

29 Soccer Practice Tips
Add black text beside it so it reads >

29 Soccer Practice Tips for all youth coaches

7. Change the destination of  Coach Doug's Streaming Video or DVD  to http://www.soccerhelp.com/soccershop/soccer-dvd 

8. In the 4th test (the Tests are on the bottom of the page) , 2nd para, delete " on Sat 03-17-07 ", so it reads  >

In fact, I had a Dad come up to me after the game. he had not been to a game since the 1st game and here we are at game 5. He advised he cannot believe how much of a progression all the girls have shown.

9. Add the 5 Tests below to the top of the Testimonials List AS A BLOCK QUOTE , like you are doing on the Drills page (some are already in the Tests list, but that is okay).

It is okay to leave the existing quotes in colors OR if it is easy, put them in the Block Quote  >

"I struggled coaching my son's U-6 until I watched his video. It made all the difference in the world. I now make all our U-6 coaches watch his video and they love it as well." Amy, coach and league administrator

"Best $20 bucks I have ever spent on soccer. I used your techniques and the kids loved it." Ben (he bought the Coach Doug Streaming Video)

"I require all of our U4 and U6 coaches to watch the Coach Doug DVD." Steven, IL, Coaching Director

"I recently bought your soccer DVD on coaching Ages 3, 4, 5, and 6 and was really amazed by your training techniques." Michael, TX

"I've already started implementing the great ideas in my practices, and they are 110% better!!!!" -Olivia, TX

**Comment by dustinschaerer** [comment]
@david-huddleston Is this good?
