### ISSUE TITLE
W3C the  two U4-U6 Navigation Pages

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#199]
Dustin, W3C two pages >

1. www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml 

2. www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed. They are both W3C Valid.
