### ISSUE TITLE
Set up the renewed SSL for SoccerHelp.com by June 7

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#2]
Dustin, we discussed this - try to do this the first week in June. My GoDaddy login is below and links to how to set up the SSL.

See below for how to set it up.

I just bought a 3-year SSL for SoccerHelp today. **I'm NOT going to use the 5-domain SSL** and asked them to refund me for that. The 

STANDARD MULTIPLE DOMAIN (UCC) SSL UP TO 5 DOMAINS - 2 YEARS (ANNUAL)
Standard Unified Communications Certificate Up to 5 Domains - 2 years

It is still listed under my SSL certificates, BUT IGNORE the SSL for Up To 5 Domains and instead click on 

www.soccerhelp.com
Standard SSL
Options
Manage
6/24/2020

Go to https://certs.godaddy.com/cert/details/lmeeb7ndqrtmkzpxfuuruenlxf7o0ma1 and it shows you >

Certificate Details
Status	Certificate issued (Revoke)

Domain name	www.soccerhelp.com

Encryption Strength	GoDaddy SHA-2
Validity Period	5/24/2017 - 6/24/2020
Serial Number	3c:e9:07:ab:85:32:6c:72

>> **My login in to GoDaddy is** >>

Customer # = 21063669 
Username =    dhudleston127
Support PIN is 1217 
Pass = Morse127@

David

From: David Huddleston [mailto:dhuddleston@comcast.net] 
Sent: Wednesday, May 24, 2017 9:57 AM
To: dhuddleston@comcast.net
Cc: SoccerHelp at Gmail
Subject: GoDaddy SSL Set-Up Installation Instructions, Has Been Renewed for 3 years, 5-24-17

Receipt Number #1138208364

Term: 3 Years
Purchase Price: $209.97
ICANN Fee: $0.00
Discount: $0.00
Subtotal: $209.97
Taxes: $0.00
Total: $209.97

From: Secure Certificate Services [mailto:donotreply@godaddy.com] 
Sent: Wednesday, May 24, 2017 9:31 AM
To: dhuddleston@comcast.net
Subject: Your SSL Certificate Has Been Renewed

Dear Secure Certificate Customer,

Congratulations on renewing your SSL certificate for the domain: www.soccerhelp.com! We're delighted to have you on board. 

Wait, You're Not Done Yet! What's Next? 

Step 1 
•	Download your renewed certificate by logging in to your account at https://certs.godaddy.com/home.pki?AccountUid=26875129-6624-4319-817e-47fc14bb75c1.
Step 2 
•	Click here to follow our easy instructions to install your certificate.
Step 3 
•	If you haven't already, let your website visitors know you offer secure transactions on your site by inserting our free Secure Site Seal. 

To add the seal to your site, log in to your SSL account at https://certs.godaddy.com/home.pki?AccountUid=26875129-6624-4319-817e-47fc14bb75c1, select your certificate, then click the "Site Seal" button.

If you have any trouble or questions, contact us and let us know. We are available to help around-the-clock, seven days a week. 

Customer Support:
E-Mail: ra@godaddy.com
Phone: 480.463.8887
Fax: 480.393.5009

**Comment by dustinschaerer** [comment]
@david-huddleston I rekeyed the new SSL and after generating a CSR and pasting it into GoDaddy. They  issued us a new SSL and I installed it on the Plesk server for Soccerhelp.com.  Restarting the Apache server flushed the settings, and its valid now!  Notice the ne3w expiration date in the screen capture:
![sh_ssl_2017](https://cloud.githubusercontent.com/assets/1232192/26691960/e2444844-46b3-11e7-84e4-14fe4e6cc5dc.png)
