### ISSUE TITLE
Second Version - Dribble Across Changes, 7-14-17 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#200]
I emailed you this on 7-14-17 at 2:35 PM - Use the email - it has the Diagram

Delete the version I sent on 7-14-17 at 2:24 PM

Dustin, on http://www.soccerhelp.com/soccer_drills/Dribble.shtml > 

1. The first para is >

(Play this as a warm-up at every practice and your players will develop amazing dribbling skills - read the Testimonials below.Control dribbling, speed dribbling, to look up while dribbling, turning, peripheral vision, instinctive reactions, getting used to traffic and shielding the ball in traffic, looking for "Open Space" & how to use Open Space, acceleration into Open Space, how to "Breakaway", "Field Vision", to naturally dribble with both feet, poise & confidence when dribbling the ball. This drill teaches players to subconsciously recognize every possible dribbling situation so they can react instinctively. It is like Muscle Memory Training where repetitive practice leads to correct reactions. It is VERY effective. U8 & up) 

(a). Remove the ( )

(b). Move U8 & up to the first with a period after it. 

(c ). Put a space after the first sentence

So it looks like >

U8 & up. Play this as a warm-up at every practice and your players will develop amazing dribbling skills - read the Testimonials below. Control dribbling, speed dribbling, to look up while dribbling, turning, peripheral vision, instinctive reactions, getting used to traffic and shielding the ball in traffic, looking for "Open Space" & how to use Open Space, acceleration into Open Space, how to "Breakaway", "Field Vision", to naturally dribble with both feet, poise & confidence when dribbling the ball. This drill teaches players to subconsciously recognize every possible dribbling situation so they can react instinctively. It is like Muscle Memory Training where repetitive practice leads to correct reactions. It is VERY effective. 

2. Make the 7 Tests a Block Quote

3. Under the Premium Promo para 9the 2nd para), delete the first 2 Links, only leaving >

See the List of 70 Premium Soccer Practice Games

4. Move up the 8th or 9th para, to be the 3rd para (below the Premium Promo). It is >

Set-up:
•	Use 4 disk cones to make a square about 10 steps wide (smaller or larger depending on age & number of players) -- make your "steps" the size of your players; so a "step" for U-8 is shorter than a "step" for U-14... by doing this, the square will always be about the correct size for your players.
•	Every player has a ball
•	Spread players around the square, all facing inward (like below)
•	Play this game 3 times to 6 with the Square about 10 steps wide (use a "step" the length of your players steps) AND 3 MORE TIMES to 6 with the Square 50% larger (e.g., about 15 of your player's steps wide). That will create over twice as much Open Space.

5. Replace it with (the diagram can be Flush Left, like below ) > 

Summary & Set-up:
•	Players dribble across a square and back from 4 directions. First to make 6 turns wins. Play 3 times with a small square and 3 more times with a larger square.
•	Use 4 disk cones to make a square about 10 steps wide (smaller or larger depending on age and number of players) - make your "steps" the size of your players - so a "step" for U8 is shorter than a "step" for U12 - by doing this, the square will always be about the correct size for your players.
•	Every player has a ball.
•	Spread players around the square on all 4 sides, all facing inward (like the diagram below). 
•	On "Go", players dribble across to the opposite side of the square and turn, go back and turn, etc.
•	Every turn is one point. Players keep their own score. Tell them to raise their hand and yell "Done" when they get to 6.
•	After each game ask every player their score so you can monitor improvement.
•	Give a Tip after each game about how players can improve (for example - "When you are in traffic, you must keep the ball near your feet." and "You must keep control of the ball when you turn or you will lose." and "You must look up while you are dribbling in traffic and don't run into other players." and "If you see Open Space, accelerate into it, BUT don't lose control of the ball."). Watch the mistakes players make for ideas for Tips. 
•	Play this game 3 times to 6 with the Square about 10 steps wide (use a "step" that is the length of your player's steps) AND 3 MORE TIMES to 6 with the Square about 50% wider (e.g., about 15 of your player's steps wide). That will create over twice as much Open Space so you can teach players to look for Open Space and accelerate into it (that is important and this game trains them to do that instinctively).
 

6. Near the Bottom delete the para below >

How to Get Your Players to Listen to You (Tips for This Game):
This is easier than you think: Let's say you're playing "Dribble Around Cone & Pass Relay Race". Play it once and ask "Who wants to win this game?" Tell them you will give them a tip that will help them win. Here's an example of a tip: Tell them that the player who starts with the ball can kick the ball in front and run to it as a way to go faster. Tell them they will just have to be sure to not kick it too hard. (Demonstrate or have a player demonstrate). Another tip: Pass the ball as soon as you can after you have rounded the cone. Another tip: The Receiver must stay on his toes and watch for whether the pass is going to his left or right and start to immediately move that way - the Receiver's most important job is to STOP the pass, because if one pass gets by him his team will lose the game (this will start to teach Receiver's that they can't just stand still and wait for the ball to come to their feet - the Receiver MUST stop the pass, just as they must in a real game). >Another tip: The Receiver can start moving toward the ball as soon as it is passed (that's the rule in this game and probably would also be how you want the receiver to play in a real game), but the Receiver can't just rush at the ball... it's not that simple... he must be sure the ball is coming at him, because if it's a bad pass he may have to move sideways to stop it. Another tip:The Receiver can block the ball in front of him and run to it as a way to speed up (again, this is good training for a real game). Another one: The pass MUST be accurate... one bad pass can lose the game... the pass needs to not be too hard, but it can't be too easy either... they will learn the proper "weight" by playing this game. These are some of the things this game teaches, and your players will learn by playing the game. If you use this approach, it changes your role from a nagging coach to a guy who is giving his players tips so the can improve. The reason it works is that when they are playing our games they will see IMMEDIATE results... so they are getting immediate positive feedback and seeing that your "tips" really work. They will see that the players who follow the coaches' tips win more games than those who don't... those who listen will win, and those who don't listen will lose.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
