### ISSUE TITLE
Soccer Drills Alt Tags, 7-14-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#201]
I emailed this on 7-14-17 at 4:01 PM

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml > 

Did you add Alt tags to the images?

1. For the Dribble Across Image add the Alt Tag > Soccer Drill Dribbling

2. For the  Hit the Coach   Image add the Alt Tag > U6 Soccer Drill Dribbling

3. For the   Aggressive Play  Image add the Alt Tag > Soccer Drill Aggressive Play

4. For the  Dribble Around Cone   Image add the Alt Tag > Soccer Drill Passing Receiving

5. For the  Go Score   Image add the Alt Tag > U6 Soccer Drill Shooting

6. For the  Throw Ins   Image add the Alt Tag > Soccer Throw Ins 

7. For the  Defense Tips (was Coaching Tips)   Image add the Alt Tag > Soccer Defense Drill 

8. For the   Tick Tock  Image add the Alt Tag > Soccer Footwork Drill

**Comment by dustinschaerer** [comment]
@david-huddleston How does this look?

**Comment by dustinschaerer** [comment]
@david-huddleston Yes, I added the alt tags.  I'll show you how you can see it.
