### ISSUE TITLE
On Dribble Across page, 3 changes, 7-16-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#204]
I emailed you this on 7-16-17 at 10:41 AM

Dustin, on    >

1.  Move the first para so it is above the video. The 1st para is > 

U8 & up. Play this as a warm-up at every practice and your players will develop amazing dribbling skills - read the Testimonials below. Control dribbling, speed dribbling, to look up while dribbling, turning, peripheral vision, instinctive reactions, getting used to traffic and shielding the ball in traffic, looking for "Open Space" & how to use Open Space, acceleration into Open Space, how to "Breakaway", "Field Vision", to naturally dribble with both feet, poise & confidence when dribbling the ball. This drill teaches players to subconsciously recognize every possible dribbling situation so they can react instinctively. It is like Muscle Memory Training where repetitive practice leads to correct reactions. It is VERY effective.

2. Move the Diagram so it is above > Summary & Set-up:
and just below See the List of 70 Premium Soccer Practice Games > 

3. In the 4th bullet, change the word "below" to "above", so the sentence reads >

Spread players around the square on all 4 sides, all facing inward (like the diagram above).

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
