### ISSUE TITLE
on Aggressive Play Drills, 2 changes to the 8 Tests, 7-16-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#205]
I emailed you this on 7-16-17 at 11:16 AM

1. Put Quotation marks at the front of the 7 Tests (the 8th Test already has them)

2. Change all 8 Tests to be a Block Quote, like you did on the Soccer Drills page and Dribble Across

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
