### ISSUE TITLE
Do a 301 Re-direct for 2 U6 Video pages, 7-16-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#206]
I emailed you this on 7-16-17 at 2:03 PM

Dustin, 

Do a 301 Re-direct for the 2 URL's below, to the addresses shown >

1. Redirect http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-hit-the-coach-practice-game.shtml  to http://www.soccerhelp.com/soccer_drills/Hit.shtml 

2. Redirect  http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-dribbling-and-go-score-practice-game.shtml  to http://www.soccerhelp.com/soccer_drills/Kids-Soccer-Go-Score-Practice-Game.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
