### ISSUE TITLE
Change 5 Coach Doug videos pages, 7-16-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#208]
I emailed you this on 7-16-17 at 2:37 PM

Dustin, change 5 Coach Doug videos pages as shown below.

Do the things listed below on ALL 5 pages.  >

1. the 5 pages and links to them are >

How to Have Fun Practices that Teach Soccer Video   http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-how-to-have-fun-practices-that-teach-soccer.shtml 
A Better Way To Teach Dribbling and Soccer Skills Video   http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-better-way-to-teach-dribbling-and-soccer-skills.shtml 
Shy Soccer Player Gains Confidence Video -- Watch This!   http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-shy-player-gains-confidence.shtml 
Soccer Shooting and Kicking Video   http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-shooting-and-kicking.shtml 
How to Use Soccer Patches for Fun and to Motivate Players Video  http://www.soccerhelp.com/soccer-videos/coach-doug-how-to-use-soccer-patches-to-motivate-players.shtml  

2. On all 5 pages, delete the link that is below the video  >

Or watch it on YouTube

3. Change the "Purchase Streaming Version Now" button to say > Buy Streaming Video

4. Make the 2 Buy Buttons better, with a blue background like you did on http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml 

5. Move the 2 Buttons up to where the Or watch it on YouTube  link was 

6. Below the 2 Buttons , add a link that goes to http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml    >

U4 & U6 Coaching Videos

7. Delete rest of the page and in its place put what is below. Put it below  U4 & U6 Coaching Videos   (Dustin, the link  Coach Doug U4 & U6 Video  goes to  http://www.soccerhelp.com/soccershop/soccer-dvd   and  Read a Detailed Review goes to  http://www.soccerhelp.com/soccershop/coach-doug-soccerhelp-method-coaching-dvd-review ). Have what is below be Flush Left  >

The above video clip is from the Coach Doug U4 & U6 Video which is 57 minutes long, includes 26 Drills for U4-U6, and is available as Streaming Video for $20 or a DVD for $31 (which includes shipping). This is the most amazing soccer coaching video I've ever seen. It will change the way you coach soccer. We offer a 10 day Money Back Guarantee on this DVD and Streaming Video. This DVD will open your eyes to a better way to coach, your players will improve faster, and players, coaches and parents will have more fun. It shows how to teach dribbling, kicking the ball, passing, how to teach kids to dribble toward the opponent's goal instead of their own, how to teach defense, how to teach kids to only use their feet (not hands), how to motivate and encourage proper behavior, how to deal with negative behavior, how to teach teamwork and "soccer sharing", how to get your players to bounce back up when they fall down, how to get players involved with practice, the equipment you need, how to deal with parents and more. It also spotlights 9 different types of players and shows their progress and how Coach Doug dealt with their individual needs, such as the very young player, the great player who is cocky, the new player who is scared and shy, the very small player, the large player, the player who doesn't want to participate, the player who won't pass, and others. It is a 100% fun and positive approach that any coach can use, even if you have never played soccer. Read a Detailed Review

8. Dustin, Below is only for reference =============

(The current bottom of the page is >

Coach Doug SoccerHelp Method of Coaching Ages 3, 4, 5 & 6 DVD  This is the most amazing soccer coaching DVD I've ever seen. It will change the way you coach soccer. We offer a Money Back Guarantee on this DVD. Every coach of ages 3, 4, 5 and 6 should own this DVD. If you are a parent, buy this and give it to your child's coach as a present - you will be doing everyone a favor. This DVD will open your eyes to a better way to coach, your players will improve faster, and players, coaches and parents will have more fun. You will be amazed at the results Coach Doug's methods achieve with normal kids. Coach Doug has taken the SoccerHelp methods and improved them with spectacular results. The DVD demonstrates 27 Practice Games, including new games that Coach Doug invented that are not on SoccerHelp. It shows how to teach dribbling, kicking the ball, passing, how to teach kids to dribble toward the opponent's goal instead of their own, how to teach defense, how to teach kids to only use their feet (not hands), how to motivate and encourage proper behavior, how to deal with negative behavior, how to teach teamwork and "soccer sharing", how to get your players to bounce back up when they fall down, how to get players involved with practice, the equipment you need, how to deal with parents and more. It also spotlights 9 different types of players and shows their progress and how Coach Doug dealt with their individual needs, such as the very young player, the great player who is cocky, the new player who is scared and shy, the very small player, the large player, the player who doesn't want to participate, the player who won't pass, and others. It is a 100% fun and positive approach that any coach can use, even if you have never played soccer. Young children are mesmerized by this DVD. We offer a Money-Back Guarantee on this DVD. Includes 15 complimentary iron-on incentive patches. Read a Detailed Review
This will play in any DVD player worldwide. The only DVDs we ship to addresses outside the U.S. are the Coach Doug DVD and the SoccerHelp Foot Skills DVD.
$27.95 plus $5.95 shipping in the US. (First Class Mail in the US)
Back to the Free Soccer Coaching Videos Navigation Page

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
