### ISSUE TITLE
Change a link destination on Youth Soccer Drills page, 7-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#210]
Dustin, on http://www.soccerhelp.com/Soccer_Drills_Youth_Soccer_Drills.shtml

Change the destination of the first link in the Links List, which is > 

Free Youth Soccer Drills for Players U4 to U16 

to  http://www.soccerhelp.com/soccer-drills.shtml

**Comment by dustinschaerer** [comment]
This is completed.
