### ISSUE TITLE
500 Soccer Coaching Tips - Changes, 7-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#212]
I emailed this on 7-17-17 at 12:42 PM - use the email to see colors and bold

Dustin, on    www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml  > 

1. In the first para, the 2nd sentence is >

The Topics are best articles are first and others are in alphabetical order.

Replace it with >

The Topics are in Alphabetical order. 

2. In the 2nd para >

- In the 1st sentence, the first sentence is > 

You can navigate the 400 free pages using the SoccerHelp Dictionary or use the links on the Home Page. 

- Make SoccerHelp Dictionary  a BOLD link to www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_A.shtml ) 

- So it reads > 

You can navigate the 400 free pages using the SoccerHelp Dictionary or use the links on the Home Page.

3. Add to the link Goal Kicks the word Tactics. so it reads > 

Goal Kicks Tactics

4. The last link is >

World Cup Lessons - 6 Tips

Add more text > What makes a great scorer? Pushing Up on Attack, Formations and Tactics, Pressuring the Keeper

So it reads >

World Cup Lessons - 6 Tips, What makes a great scorer? Pushing Up on Attack, Formations and Tactics, Pressuring the Keeper

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
