### ISSUE TITLE
Start Here page, one change, 7-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#214]
I emailed you this on 7-17-17 at 5:55 PM

Dustin, on http://www.soccerhelp.com/Start_Here.shtml  ,

number 4 starts >

The "Dictionary Search" is a Way to Navigate 

make Dictionary Search a link that goes to  http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_A.shtml 

So it looks like >

The "Dictionary Search" is a Way to Navigate

**Comment by dustinschaerer** [comment]
This is completed.
