### ISSUE TITLE
Read this about making Mobile searches faster 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#215]
Dustin, 

Go to https://developers.google.com/speed/pagespeed/insights/?url=soccerhelp.com and read the results.

It says > "This page is not optimized and is likely to deliver a slow user experience. Please prioritize and apply the recommendations below."

Do you need to do any of these things for the main pages line Sh Home and Soccer Drills? 

Google AdWords ran a report on Mobile loading time and SH did good, but it said > 

"Enabling gzip compression can minimize the size of the transferred response by up to 90%. This can significantly reduce the time to download the resource, decrease data usage for the client, and improve your loading time."

Do you know anything about gzip? gzip was also mentioned in the Audit Report.

I don't want to do it if it is hard or if there is any chance it could mess something up.

**Comment by dustinschaerer** [comment]
@david-huddleston There were two parts to this. I had to install the Apache Module: 'mod_defalte' into our server's apache configuration. Then I had to enable it on our virtual host domain soccerhelp.com

You can see here it is working now:
https://checkgzipcompression.com/?url=http%3A%2F%2Fwww.soccerhelp.com%2Findex.html

It is saving us a bunch of bandwidth!
