### ISSUE TITLE
Links on top of the Bootstrapped pages, 7-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#217]
I emailed you this on 7-17-17 at 7:04 PM

Dustin, on top of the links on the Bootstrapped pages like http://www.soccerhelp.com/soccer-drills.shtml    > 

on the right side >

1. Change "Coaching" to "Index"

2. swap places with "Index"  and "Drills"

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
