### ISSUE TITLE
W3C Markup Validation Service and other Tools

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#22]
Dustin,  free high-quality tools  are below funded by Mozilla and HP >

- you might check out https://validator.w3.org/

- they also have other free tools such as Nu HTML Checker , Link Checker and Mobile Checker at https://w3c.github.io/developers/tools/

**Comment by dustinschaerer** [comment]
@david-huddleston Yes, I'm aware of those.  Check this out for example: 
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.soccerhelp.com%2F
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.soccerhelp.com%2Fsoccer-drills.shtml
