### ISSUE TITLE
Streaming Videos Navigation page Changes, 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#220]
I emailed you this on 7-18-17 at 1:06 PM - use the email

Dustin, on http://www.soccerhelp.com/soccershop/streaming-video

1. Delete the 3rd subtitle, which is>

Our Videos Now Also Play on Mobile Devices (Android & Apple)

2. At the end of the 3rd para, delete >

 For your convenience, our videos now also play on mobile devices (Android & Apple) as well as all computers.

3. The first para is >

Save money and watch 2 videos now, right here on SoccerHelp.com. This option is great if you don't want to wait for the DVD in the mail and you save Shipping Fees. You don't have to worry about losing a DVD or it getting scratched. Coupon codes do not apply to this. We offer a 5 day money back guarantee on these two streaming videos, if the videos don't play properly, contact us within 5 days and we will refund the purchase price.

Replace it with (in Unbold) >

We offer a 5 day money back guarantee on these two streaming videos. 

4. Change the 4 "Purchase" Buttons >

(a). Change the word "Purchase" to "Buy"

(b). Make the Buttons more visible 

5. The Link below is on 2 places. Turn it into Blue Bold text so it is NOT a link BUT leave it Bold >

Coach Doug SoccerHelp Method of Coaching Ages 3, 4, 5 & 6 DVD - Online Streaming Video Access

6. The Link below is on 2 places. Turn it into Blue Bold text so it is NOT a link BUT leave it Bold >

SoccerHelp Foot Skills and Soccer Moves Training Program (Motor Memory Training and Aerobic Workout) - Online Streaming Video Access

7. Under Individual Subscriptions (family) , change the Coach Doug blurb to >
Coach Doug SoccerHelp Method of Coaching Ages 3, 4, 5 & 6 DVD - Online Streaming Video Access - $19.97 for 100 days - You will login and watch the Streaming Video here on SoccerHelp.com. Individual subscriptions are for one household. The number of users is limited and will automatically shut down if more than 5 IP addresses try to log in, so do not share your password with friends. If you want to share, buy a League Subscription below.

8. Under Individual Subscriptions (family) , change the SoccerHelp Foot Skills blurb to >
SoccerHelp Foot Skills and Soccer Moves Training Program (Muscle Memory Training and Aerobic Workout) - Online Streaming Video Access - $19.97 for One Year (365 days) - You will login and watch the Streaming Video here on SoccerHelp.com. Individual subscriptions are for one household. The number of users is limited and will automatically shut down if more than 5 IP addresses try to log in, so do not share your password with friends. If you want to share, buy a League Subscription below.

9. Under League Subscriptions (2 to 20 coaches)  , 

Unbold the text below AND make it the same size as the other text below it (it is smaller) >

League Subscriptions for up to 20 Users (coaches, parents or players), are below. IMPORTANT TIP: Do NOT use your personal password when setting up a League Subscription. Use your league name or website name for BOTH the username and password - make it easy to remember and ALL lower case with NO spaces. ALSO, put a link to SoccerHelp.com on your website so you don't get lots of calls. Users can easily Log In by clicking "Premium" on SoccerHelp and following the links. If you have more than 20 users you should buy more than one League Subscription and only allow 20 users per subscription. The software will shut down your subscription if limits are exceeded, so don't post the password on your website where it can get on the internet. If you are going to share your subscription or travel a lot and sign in as a Guest to Wi-Fi, then you should buy a League Subscription to be safe. When you subscribe, you are accepting these conditions.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
