### ISSUE TITLE
Changes to Coach Doug DVD Review Page Button for DVD and Streaming link, 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#222]
I emailed you this on 7-18-17 at 2:27 PM - use the email

Dustin, on http://www.soccerhelp.com/soccershop/coach-doug-soccerhelp-method-coaching-dvd-review

1. The "Add to Cart - $24.95" button doesn't work.

2. Change the Button to say >

Buy DVD - $24.95

Be sure the Button Works

3. Above the video is a link that goes to the Streaming Video page and says >

Click Here for Immediate Access to this Video for $19.99

Change the Link Text to >

Buy Streaming VIDEO for $19.99

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed and Tested.
