### ISSUE TITLE
Soccer Drills - Replace the 70 Tips Link with 500 Coaching Tips link 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#225]
Dustin, on http://www.soccerhelp.com/soccer-drills.shtml >

In the Links List, replace the link > 70 Soccer Tactics and Tips

With > 500 Coaching Tips

That goes to >

http://www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
