### ISSUE TITLE
Change to Doug Navigation Promo page, 7-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#226]
Dustin, on http://www.soccerhelp.com/coachdoug-promo/Doug-Navigation.shtml >

2 things >

1. In the Block Quote, separate the Tests from Gregg and Richard

2. Add the last test that is still in green to the end and make it regular text, NOT italics.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
