### ISSUE TITLE
U4-U6 Navigation page change to a Test , 7-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#228]
I emailed this on 7-19-17 at 11:19 AM

Dustin, on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml > 

In the Block quote, the first test is >

"I struggled coaching my son's U-6 until I watched his video. It made all the difference in the world. I now make all our U-6 coaches watch his video and they love it as well." Amy, coach and league administrator

Replace it with >

"I loved Coach Doug's video. I struggled coaching my son's U-6 until I watched his video. It made all the difference in the world. I now make all our U-6 coaches watch his video and they love it as well." Amy, coach and league administrator

**Comment by dustinschaerer** [comment]
This is completed.
