### ISSUE TITLE
Premium Promo page - Bootstrap & Responsive - put Tests in a Block quote, 7-19-17 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#229]
I emailed this on 7-19-17 at 11:37 AM

Dustin, for http://www.soccerhelp.com/New_Articles_On_Soccerhelp_Premium.shtml >

1. Bootstrap and Responsive it

2. Put the Tests in a Block Quote

3. Don't W3C it - its ranking doesn't matter

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
