### ISSUE TITLE
Change the destination & name of the Google Plus link

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#23]
Dustin,

No. 1 - It goes to +David Huddleston   (which is the Google Plus for David Huddleston)

BUT, as discussed, replace the link text with"SoccerHelp.com Google Plus Articles"

that goes to the URL >

https://plus.google.com/u/0/117041441406804669285

Enter that link and you will see. 

That is the Google Plus page I post on.

No. 2 - add the +SoccerHelp.com Google Plus link on the SH Home page where the old SH Logo is (the one you are going to delete that is below the Copyright language

**Comment by dustinschaerer** [comment]
@david-huddleston Holy cow, you gotta see this: http://searchengineland.com/goodbye-google-authorship-201975

So I say we remove the +David Huddleston nonsense altogether. Is that OK?

**Comment by dustinschaerer** [comment]
@david-huddleston - OK this is completed.
