### ISSUE TITLE
Bootstrap and Responsive the Patches Navigation page, 7-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#230]
II emailed you this on 7-19-17 at 11:46 PM

Dustin, make http://www.soccerhelp.com/Motivational_Patches_Navigation_Page.shtml >

Bootstrap and Responsive

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed, and W3C validated. It only took another couple minutes.
