### ISSUE TITLE
Attacking page - 3 changes, 7-19-17 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#231]
I emailed this on 7-19-17 at 12:11 Pm - use the email

Dustin, on http://www.soccerhelp.com/how-to-score-more-goals-report.shtml >

1. In the 1st para, change  $17.99 to $15

2. In the 1st para, change the Destination of the link    Premium  to  http://www.soccerhelp.com/Premium_Sites_Navigation.shtml 

3. Replace the link Patches Navigation Page 

with >  Motivational Soccer Patches 

that goes to >  http://www.soccerhelp.com/soccershop/

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
