### ISSUE TITLE
More Bunching Up article changes, 7-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#232]
I emailed this on 7-19-17 at 1:19 PM

Dustin, on http://www.soccerhelp.com/Coaching_Soccer_To_Not_Bunch.shtml >

4 things to do >

1. Change the Title Tag and Description to >

<title>How to Soccer Players To Not Bunch Up</title>

<meta name="keywords" content="coach teach soccer players bunch up bunching">

2.  Near the top, below the Title, add 2 links  (they go to http://www.soccerhelp.com/Premium_Sites_Navigation.shtml    and  http://www.soccerhelp.com/soccershop/   ) >

Premium has 1,500 Pages 
Motivational Soccer Patches

3. At the end of # 2, delete the last sentence >

See more at http://soccerhelp.com/Coaching_Soccer_To_Not_Bunch.shtml

4. In # 8, make the link work >

http://www.soccerhelp.com/premium/practice_games/Handball_Soccer.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
