### ISSUE TITLE
Second Version -  Soccer Positions basics - Bootstrap, Responsive, W3C,  7-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#233]
Dustin, I added the images to this one in case they get lost when you Bootstrap the page .

Dustin, make http://www.soccerhelp.com/Soccer_Positions_Basics.shtml 

Bootstrap, Responsive AND W3C

>>>> Be sure the images aren't lost - I pasted the images below >

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed, W3C Validated, and Responsive.  I had to remove the Google Ad block from the bottom of the page bc it was too wide and prevented the mobile view from shrinking down to the right size.
