### ISSUE TITLE
Coach Doug DVD - change the title, 7-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#234]
I emailed this on 7-19-17 at 3:40 PM

Dustin, on http://www.soccerhelp.com/soccershop/soccer-dvd 

The title of  the Coach Doug DVD is > 

Coach Doug SoccerHelp Method of Coaching for U4 & U6 Coaches DVD

Change it to >

Coach Doug DVD for U4 & U6 Coaches

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
