### ISSUE TITLE
Remove the Facebook link from Dictionary pages (A, B, C, etc), 7-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#240]
Dustin,

Remove the Facebook link from Dictionary pages (A, B, C, etc) 

If you can, delete the link from all the pages.

**Comment by dustinschaerer** [comment]
@david-huddleston What about the Google+ link that was with the Facebook link? You can still see it here:
http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_A.shtml

**Comment by dustinschaerer** [comment]
I removed the Google+ link as well from the Dictionary Pages bc it affected mobile.
