### ISSUE TITLE
Youth Soccer Positions - add a 3rd para, 7-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#242]
I emailed this on  7-19-17 - see the email to see the link

Dustin, on  http://www.soccerhelp.com/youth-soccer-positions.shtml >

add a new 3rd para >

Soccer positions basics are at Soccer Positions Basics

(Dustin, the link goes to http://www.soccerhelp.com/Soccer_Positions_Basics.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
