### ISSUE TITLE
Check terms/soccer-fouls.shtml on cell phone , 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#245]
Dustin,  http://www.soccerhelp.com/terms/soccer-fouls.shtml looks fine on my desktop but on my iPhone 5 it is too skinny and isn't like the other Responsive pages

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.

**Comment by dustinschaerer** [comment]
@david-huddleston This had to do with some custom css classes written for those "terms" pages.  As we bootstrap those pages I'll  make sure to remove that (now) extraneous class call.
