### ISSUE TITLE
Changes to U4 Coaching page, 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#252]
I emailed this on 7-20-17 at 1:44 PM - use the email to see Bold and colors and spacing

Dustin, on http://www.soccerhelp.com/U-4_Coaching_Ages_2_3_4_5.shtml >

1. Bootstrap and Responsive it

2. Change the title to >

U4 & U6 Soccer Coaching

Coach Doug Method of Coaching U4 & U6 Soccer

 A Better Way to Coach Kids Soccer
No Lines Drills and Games 
More Fun & Great Skills

3. H1 and H2 >
Make the top Line be the H1 > U4 & U6 Soccer Coaching
and have the H2 be > Coach Doug Method of Coaching U4 & U6 Soccer

4. Change the code to >
<title>U4 & U6 Soccer Coaching - the Coach Doug Method</title>
<meta name="keywords" content="U4 U6 Soccer Coaching, Fun Drills & Games for U6 Soccer">
<meta name="description" content="A better way to coach U4 & U6 Soccer. More fun and better skills by using No Lines Soccer Drills and Games.">

5. In the Links List at the top, delete the first link and the last  link >
Return to "U-4, U-6, U-8 Navigation Page"
Recommendations for U4 & U6 Coaches and Soccer Leagues

6. The remaining 3 links are >

Coach Doug's Site for Coaches of Age 3, 4, 5 and 6
Coach Doug DVD Video Clips of Soccer Coaching Ages 3, 4, 5 and 6
Buy Coach Doug DVD in Streaming Video

(a). Leave the destinations but Unbold the links, remove the spaces between, and change the words to >

Read about Coach Doug Website
Watch Coach Doug Video Clips
Buy Coach Doug Streaming Video

(b). Add 4th & 5th Links  (that go to http://www.soccerhelp.com/soccershop/soccer-dvd and http://www.soccerhelp.com/members-doug/signup  ) > 
Read About Doug Video & DVD
Subscribe to Coach Doug Website

(c ). So the 5 Links List looks like >
Read about Coach Doug Website
Watch Coach Doug Video Clips
Buy Coach Doug Streaming Video
Read About Doug Video & DVD
Subscribe to Coach Doug Website
(d). THEN, change the order of the links to >
Watch Coach Doug Video Clips
Read about Coach Doug Website
Read About Doug Video & DVD
Subscribe to Coach Doug Website
Buy Coach Doug Streaming Video

7. Delete the 1st para, which is >
U4, U5, U6 soccer drills for under 4, under 5 and under 6 soccer coaches.

8. The 2nd para is >

Should you buy the Coach Doug DVD or join his website? This is a frequent question. The DVD demonstrates 26 Practice Games and shows you how to practice. However, the website tells you what to do before, during and after the game, how to deal with parents and players, and describes the Practice Games. So, there is different information on each. The ideal thing is to buy the DVD and also use the website. Both carry a money-back guarantee, and you can purchase the DVD and a 120 day membership for about $50. The DVD and website will save you a great deal of time and make your coaching experience MUCH more enjoyable. Membership to Coach Doug's site is as low as $11.95. Click here to Sign-Up

Replace the 2nd para with below - leave the 1st sentence Bold  (the link goes to http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml   ) >

Coach Doug's Streaming Video and Website - The Streaming Video ($20) demonstrates 26 Practice Games and show you how to teach and coach young kids (the Streaming Video is the same as the DVD but is less expensive and immediately available, and can be watched on mobile devices). However, the website ($12 to $30) tells you what to do before, during and after the game, how to deal with parents and players, and describes the Practice Games in more detail. So, there is different information on each, and the video is not part of the website subscription. The ideal thing is to buy the Streaming Video ($20) and also use the website ($12 for 30 days, $20 for 120 days, or $30 for a year). Both have a 5-day money back guarantee. The Streaming Video and website will save you a great deal of time and make your coaching experience MUCH more enjoyable. You can subscribe at the links that are above. Watch the 7 free video clips at Coach Doug Video Clips to see how Coach Doug teaches soccer skills to young kids.

9. Delete the link >

Testimonials for Coach Doug's DVD and Site

10. Delete the 6 Blue Tests at the top and replace them with the 3 below in a Block Quote >

"I loved Coach Doug's video. I struggled coaching my son's U-6 until I watched his video. It made all the difference in the world. I now make all our U-6 coaches watch his video and they love it as well." Amy, coach and league administrator
"The differences in our practices and games is amazing. All the kids have had more touches the first two games and practices than all last season. Thanks so much!" Tony, WA
"The Coach Doug website has been fantastic and I've received good feedback from all of the coaches. I've used the video plus the drills on the website to create the drill schedules each week. The patches have been a big hit. They all want to get the special hustle patch and defense patch so it's doing a good job reinforcing those areas." Jim, U6 Coordinator

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
