### ISSUE TITLE
Soccer Positions Basics - Replace the Premium Promo para  7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#255]
I emailed you this on 7-20-17 at 2:05 PM - use the email to see colors and bold

Dustin, on  http://www.soccerhelp.com/Soccer_Positions_Basics.shtml 

The second para is >

SoccerHelp Premium has over 1,500 pages and 100 articles about soccer positions and formations. The cost is only $14.94 for 30 days or $24.94 for 120 days. We do NOT automatically renew subscriptions. There is a 30-day refund policy. Read about SoccerHelp Premium

Replace it with >

SoccerHelp Premium has over 1,500 pages and 100 articles about soccer positions and formations. The cost is only $15 for 30 days, $25 for 120 days, or $40 for 365 days. We do NOT automatically renew subscriptions. There is a 10-day refund policy. Read about SoccerHelp Premium

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
