### ISSUE TITLE
Changes to Tryouts Evaluation Form, 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#258]
I emailed you this on 7-20-17 at 4:13 PM - use the email to see colors

Dustin, on http://www.soccerhelp.com/Soccer_Tryouts_Evaluation_Form.shtml > 

1. H1 and H2  -  There are 2 H1's - the Top Title is a H1 BUT > 

Soccer Tryout Evaluation Form
is also a H1 (it is the title above the form) . 

Make a H2 of >  Soccer Tryout Evaluation Form

2.  Below the Top title, add a line for separation (when you view the page, there isn't any separation)

3. The first para is >

Soccer tryouts, soccer tryout evaluation form and criteria for evaluating soccer players are discussed. These are usually for high school, select, travel or advanced soccer players ages 10 and older. An evaluation form is sometimes called a scorecard or rating form.

Make it like below - make the 1st sentence bold, black and regular text size, like >

Soccer tryouts, soccer tryout evaluation form and criteria for evaluating soccer players are discussed. These are usually for high school, select, travel or advanced soccer players ages 10 and older. An evaluation form is sometimes called a scorecard or rating form.

4. The Links List has 7 Links >

(a). Un bold the links

(b). Delete the 4th link which is > 

Free Videos of Some of Our Soccer Tryout Drills & Training Methods

(c ). Delete the last link, which is >

700 Testimonials for Our Training Program from Soccer Coaches

(d). Add a new last link that goes to  http://www.soccerhelp.com/New_Articles_On_Soccerhelp_Premium.shtml   >

Read about SoccerHelp Premium

>>> The Links List will then look like >

Soccer Drills and Soccer Practice Games
Soccer Tryouts Tips For Select Soccer and Travel Soccer
Soccer Tactics For Select Travel and High School Soccer
Soccer Journal Articles About Our Training Program
Soccer Tryout Drills
Read about SoccerHelp Premium

5. In # 4, delete the last sentence, which is >

There is a video of this game atSoccer Drill to Teach Receiving, One Touch & how to Pass While Running Video

6. In # 5, delete the last sentence, which is >

There is a video of this game at Best Soccer Dribbling Drill - Dribble Across Square Video Preview

7. In # 6 > 

- Delete > Dribble Across A Square™ and

- Capitalize "The"

- So it reads >

"Strength on the Ball" This is different from physical strength. It is the ability to retain the ball when under pressure. It has to do with skill, positioning and physical strength. The Premium games 2 Team Keep Away and Small Sided Scrimmage Without A Goalie can help evaluate this.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
