### ISSUE TITLE
Basic Info - 2 changes, 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#261]
I emailed you this on 7-20-17 at 4:56 PM - use the email

Dustin, on http://www.soccerhelp.com/Basic_Info.shtml >

1. The 1st link is >

View Video Clips of The Coach Doug Soccerhelp Method of Coaching U4, U6 and U8

- Change the words to (same destination) > 

7 Videos, How to Coach U4 & U6

2. The 1st para is >

NOTE: If you want the best and fastest results, we strongly recommend you buy our iron-on incentive soccer patches and subscribe to Premium. Many coaches see immediate results from the patches - their players try harder, hustle and come to practice. Read Letters from Coaches about the results they have achieved and how they used the patches. Drills train players to play slow -- our Practice Games train players to play fast. Think about it - drills aren't at "Game Speed" and aren't under pressure. Our Practice Games involve competition and players want to win the Practice Games, so they can earn a patch, so they learn to play fast and under pressure. As a result, players learn faster and play better. See Soccer Practice Plans.

- Unbold it and remove the underline, so it looks like >

NOTE: If you want the best and fastest results, we strongly recommend you buy our iron-on incentive soccer patches and subscribe to Premium. Many coaches see immediate results from the patches - their players try harder, hustle and come to practice. Read Letters from Coaches about the results they have achieved and how they used the patches. Drills train players to play slow -- our Practice Games train players to play fast. Think about it - drills aren't at "Game Speed" and aren't under pressure. Our Practice Games involve competition and players want to win the Practice Games, so they can earn a patch, so they learn to play fast and under pressure. As a result, players learn faster and play better. See Soccer Practice Plans.

**Comment by dustinschaerer** [comment]
This is completed.
