### ISSUE TITLE
Check www.soccerdrillsandgames.com , 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#262]
Dustin, about www.soccerdrillsandgames.com >

I own this domain and it used to be a page but it says the "DNS record can't be found"

**Comment by dustinschaerer** [comment]
GoDaddy is acting funny, I'll have to revisit this in the morning

**Comment by dustinschaerer** [comment]
@david-huddleston This is all setup now.   http://soccerdrillsandgames.com/
