### ISSUE TITLE
Add URL's that are links to 6 pages, 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#263]
I emailed this on 7-20-17 at 5:50 PM 

Dustin, add the URL's below to the bottom of 6 pages >

>> The 6 pages to add them to the bottom of are >

http://www.soccerhelp.com/terms/soccer-terms.shtml 

http://www.soccerhelp.com/soccer-drills-positions-formations-newsletters.shtml

http://www.soccerhelp.com/newsletter_archive/soccer_archive.shtml

http://www.soccerhelp.com/patches/soccer-patch.html 

http://www.soccerhelp.com/Links_Two.shtml 

http://www.soccerhelp.com/soccer-articles/index.shtml

>>> The list of URL's to add as links on the bottom of the 6 pages are >

http://www.soccerhelp.com/newsletter_archive/soccer_archive.shtml 

http://www.soccerhelp.com/soccer-drills-positions-formations-newsletters.shtml

http://www.soccerhelp.com/soccer-articles/index.shtml 

http://www.soccerhelp.com/soccer-articles/drills.shtml 

http://www.soccerhelp.com/soccer-articles/rules.shtml

http://www.soccerhelp.com/soccer-articles/formations.shtml

http://www.soccerhelp.com/soccer-articles/games.shtml

http://www.soccerhelp.com/soccer-articles/patch.shtml 

http://www.soccerhelp.com/soccer-articles/patches.shtml

http://www.soccerhelp.com/soccer-articles/positions.shtml

http://www.soccerhelp.com/terms/soccer-terms.shtml

http://www.soccerhelp.com/patches/soccer-patch.html

**Comment by dustinschaerer** [comment]
@david-huddleston What text do you want me to use for these links?  Should I just guess by infering from the link address?

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed. Is that the way you want the links to look?

http://www.soccerhelp.com/terms/soccer-terms.shtml
