### ISSUE TITLE
Dribble Around Cone - 4 changes, 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#265]
I emailed this on 7-20-17 at 6:33 PM - use the email

Dustin, on  http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml  >

1. Delete the link below in 2 places - above the Tests and above "Summary" > 

Best Free Soccer Drills and Practice Games

2. Make the Tests a Block Quote (be sure to leave a spacing line between each one)

3.  Add the image below just below the "Summary" section (above "Teaches") - the image is from  http://soccerdrills.net/soccer-drills-passing-receiving/   >

4. There are 2 Premium Promo paras > the 2nd para and below "Set-Up" > 

At the end of both add the link (Unbold) >  Read about SoccerHelp Premium

that goes to http://www.soccerhelp.com/New_Articles_On_Soccerhelp_Premium.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
