### ISSUE TITLE
Videos Page - change 5 links, 7-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#267]
I emailed this on 7-20-17 at 10:46 PM - use the email

Dustin, on http://www.soccerhelp.com/Soccer-Videos-Premium.shtml >

Change the links as described below (the numbers are the same they are numbered on the page) >

1. Replace  Best Soccer Dribbling Drill - Dribble Across Square Video Preview  with   Dribble Across a Square Practice Game Demonstration  that goes to http://www.soccerhelp.com/soccer_drills/Dribble.shtml 

2. Change the destination of  Soccer Drill to Teach Faster Play, Aggressive Receiving, One Touch & how to Pass While Running Video  to go to http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml  

3. Change the destination of  How to Train Soccer Players to be Aggressive Video   to go to http://www.soccerhelp.com/strength-on-ball-report.shtml    

4.   Change the destination of   How to Defend Soccer Goal Kicks, Punts and Throw Ins Video      to go to http://www.soccerhelp.com/22-coaching-rules-report.shtml 

9.   Change the destination of   How to Teach a Soccer Throw In & Throw In Rules Video    to go to http://www.soccerhelp.com/soccer_drills/Throw-ins_Game.shtml

**Comment by dustinschaerer** [comment]
This is completed.
