### ISSUE TITLE
Premium Dribble Around Cone Game, delete a para, 7-21-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#268]
I emailed this on 7-21-17 at 10:23 AM

Dustin, on http://www.soccerhelp.com/premium/practice_games/Dribble_Around_Cone_Pass.shtml 

Delete the para above "Summary", which  is >

It is difficult to explain soccer skills in print. For demonstrations that you and your players can watch to learn the skills, and that show how to teach the skills, we recommend the following DVD's. You can read detailed reviews by clicking the links: SoccerHelp Foot Skills and Soccer Moves Training Program (Motor Memory Training and Aerobic Workout) DVD, Mia Hamm Soccer Secrets, Coerver Play Great Soccer2-DVD Set, England Skills Uncovered (19 skills are demonstrated by professional players), Soccer Success One On One Coaching, Gol! (Brazilian Foot Skills and Ball Control Training Program), Super Soccer Skills and Just Kickin' It

**Comment by dustinschaerer** [comment]
This is completed.
