### ISSUE TITLE
Delete a Block of Links from Several Pages

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#27]
Dustin,

Don't let this interfere with your work on moving SH to a new Server.

there is a block of links to delete from the bottom of >
http://www.soccerhelp.com/Soccer_Positions.shtml
and 
http://www.soccerhelp.com/Soccer_Formations.shtml
and
http://www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml

The links  are >

Soccer Links - FIFA, National Soccer Coaches Association of America, U.S. Youth Soccer, Soccer Association for Youth , American Youth Soccer Organization, Major League Soccer, English Premier League, Liga MX, U.S. Women's National Soccer Team, U.S. Men's National Soccer Team

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed. I also got all 3 of these pages running valid code on the W3 validator.
