### ISSUE TITLE
SH Home page - changes to Bars, 7-21-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#271]
I emailed  you this on 7-21-17 at 4:49 PM

Dustin, on SH Home >

1.  In the 3rd Bar >

- Change the words "Soccer Coaching" to "Index"

2. In the 4th Bar, Remove the Word "Incentive" in all 4 places AND change the destination in 2 places >

(a). Change "Incentive Soccer Patches" to "Soccer Patches" and change the link Destination to the Soccer Patches page > http://soccerhelp.com/soccershop/soccer-patches 

(b). Change "Incentive Sports Patches" to "Sports Patches"  (don't change the destination)

(c ). Change " Incentive Baseball Patches " to "Baseball Patches" and change the link Destination to the Baseball Patches page > http://soccerhelp.com/soccershop/baseball-softball-patches 

(d). Change " Incentive School Patches " to "School Patches " (don't change the destination)

**Comment by dustinschaerer** [comment]
This is completed.
