### ISSUE TITLE
Second Version - Navigation Index page Changes, 7-21-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#272]
I emailed this on 7-21-17 at 7:26 PM - use the email to see colors and links

Dustin, delete the version I sent you on 7-21-17 at 7:03 PM and use this one.

Dustin, on http://www.soccerhelp.com/Soccer-Coaching-Navigation.shtml >

1. The Links List is currently indented > move them left so they line up with the text instead of being indented

2. Replace the first para with (you know where the 2 links go) >

Below are some of the more popular topics on SoccerHelp. Most of the links below take you to navigation pages for those coaching topics. You can also navigate using the Home Page, by using the SoccerHelp Dictionary, or by checking the topics on 500 Coaching Tips. There are 400 pages of information on this free version of SoccerHelp and over 1,500 pages on Premium.

3. Below is a revised Links List. I think you know where the links below go - most are the same destination they currently go to - where I added links I put the destination to the right) 

Drills & Games
U4 - U6   (goes to http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml 
500 Coaching Tips
29 Soccer Practice Tips (goes to http://www.soccerhelp.com/soccer-practice.shtml 
New Coaches & Basic Info   (goes to http://www.soccerhelp.com/Soccer_Coaching_Tips_New_Soccer_Coach.shtml  )
1,000 Testimonials
Attacking Tips and Tactics   (goes to http://www.soccerhelp.com/how-to-score-more-goals-report.shtml  )
Bunching Up - 7 Ways to Stop It   (goes to http://www.soccerhelp.com/Coaching_Soccer_To_Not_Bunch.shtml )
Dictionary - 400 Topics   (goes to http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_A.shtml 
DVDs
Formations
Indoor Soccer  (goes to http://www.soccerhelp.com/Indoor_Soccer_Tips_Index.shtml 
How to Motivate Players  (goes to http://www.soccerhelp.com/Motivational-Plan-Players-Students.shtml  
Patches
Positions
Premium Sites  (goes to http://www.soccerhelp.com/Premium_Sites_Navigation.shtml 
Rules
Skills
Streaming Video
Tips from Coaches   (goes to http://www.soccerhelp.com/soccer-articles/120927-Soccer-Coaching-Tips-Success-Stories.shtml 
Travel, Select & High School   (goes to http://www.soccerhelp.com/Soccer_Tactics_Select_Travel_High_School_Soccer.shtml 
U8 Soccer   (goes to http://www.soccerhelp.com/U-8_Coaching_Ages_7_8.shtml 
Video Clips

**Comment by dustinschaerer** [comment]
This is completed.
