### ISSUE TITLE
Aggressive Play Drill changes, 7-22-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#274]
I emailed you this on 7-22-17 at 1:02 PM - use the email

Dustin, on http://www.soccerhelp.com/strength-on-ball-report.shtml >

1. At the top is a Premium Promo para.

Move it below the Tests (above "Summary") 

The para to move is >
Save $5 on SoccerHelp Premium - This free site has 300 pages. SoccerHelp Premium has 1,500 pages. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. Sign up at http://soccerhelp.com/members/signup

2. Make Changes to the Premium Promo para (the link  400 Testimonials   goes to http://soccerhelp.com/soccershop/soccerhelp-premium-reviews-testimonials )  >

- Delete the 1st black sentence >  This free site has 300 pages. 

- Before the last "Sign up" sentence add >  5-day money back guarantee. 400 Testimonials 

SO it reads >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages. Use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

3. There are 2 links below the video >
Best Free Soccer Drills and Practice Games
Patches Navigation Page
Replace them with the Bold Link (the link goes to http://soccerhelp.com/soccershop/  )  >
Motivational Soccer Patches

4. Below "Summary" is >

Teaches:
"Shoulder Tackle", "Shielding", "Strength on the Ball".

>>>Delete that

5. Below "Set-up", delete the link >

Watch a Video of How to Set This Up - it is Much Easier to Understand

6. In the last 2 paras, delete the link in both paras (twice) >

Watch a Video about How to Train Soccer Players to be Aggressive and Not Get Pushed Off the Ball

**Comment by dustinschaerer** [comment]
This is completed.
