### ISSUE TITLE
Soccer Practice article change - patches promo 7-22-17 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#275]
I emailed this on 7-22-17 at 1:35 PM

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml >

- The first # 2 is >

Motivate Your Players to Come to Practice, Hustle, and Be Brave. By Brave we mean tough and not afraid of contact. A free drill that can teach this is at Aggressive Play and Bravery Game.

Add a new sentence on the end (the link goes to  http://www.soccerhelp.com/soccershop   )  >

Coaches use our Motivational Soccer Patches to motivate players to come to practice, hustle and be brave. 

So it reads >

Motivate Your Players to Come to Practice, Hustle, and Be Brave. By Brave we mean tough and not afraid of contact. A free drill that can teach this is at Aggressive Play and Bravery Game. Coaches use our Motivational Soccer Patches to motivate players to come to practice, hustle and be brave.

**Comment by dustinschaerer** [comment]
This is completed.
