### ISSUE TITLE
Fifth Version -  Add Premium Promo to 8 pages, 7-26-17, 9:44 AM

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#276]
I emailed this on 7-26-17 at 9:44 AM - use the email

Dustin, delete the versions I sent you on 7-22-17 at 2:05 PM 7-23-17 at 10:44 AM, and 7-26-17 at 9:33 AM - I added # 8 and added "& 5,000 links for easy navigation "

Dustin, add the "Save $5" Premium Promo below to the pages listed below (you can copy and paste the code  - make  Save $5 on SoccerHelp Premium  bold blue - Dustin, notice that there is Bold in 5 places >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. Use the Coupon 5offpremium to subscribe for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials  Sign up at http://soccerhelp.com/members/signup

1. Add it to  http://www.soccerhelp.com/soccer-practice.shtml just above the 2nd Sub-title, which is > Things to Do at Soccer Practice

2. On http://www.soccerhelp.com/how-to-score-more-goals-report.shtml , in the 1st para, leave the 1st sentence and replace the rest with the Promo, so it reads >

The Premium version of this article has 115 links to Premium articles and definitions. Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. Use the Coupon 5offpremium to subscribe for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials  Sign up at http://soccerhelp.com/members/signup
                                                                                                                                                     

3. Add it on the bottom  of   http://www.soccerhelp.com/terms/soccer-support.shtml  , Just below C. (above See prices for our iron on Motivational Soccer Patches 

4. Add it to  http://www.soccerhelp.com/Evaluating_Soccer_Players_And_Teams.shtml , above See prices for our iron on Motivational Soccer Patches

5. Add it to  http://www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml , just after > Fast Play - 7 Tips, How to Teach Fast Play 

6, On http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml , the 1st para is a similar Promo. Replace that Promo with the newer version above.

7. Add it to http://www.soccerhelp.com/Soccer_Coaching_Tips_New_Soccer_Coach.shtml as a new 3rd para, above the link Basic Information & Tips for Beginning Coaches 

8. Add it to http://www.soccerhelp.com/youth-soccer-positions.shtml after # 20 and just above the Links List.

**Comment by dustinschaerer** [comment]
This is completed.
