### ISSUE TITLE
New Coaches page changes to links, 7-22-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#277]
I emailed this on 7-22-17 at 2:35 PM

Dustin, on http://www.soccerhelp.com/Soccer_Coaching_Tips_New_Soccer_Coach.shtml > 

1. The first link is >

View Video Clips of The Coach Doug Soccerhelp Method of Coaching Ages 3, 4, 5 and 6

Change the words so it reads >

Videos of How to Coach U4 & U6

2. Delete the 2nd and 3rd links, which are >

Watch Soccer Video Clips
Free Soccer Patches

3. At the end of the 3rd para (that starts " NOTE:  " ) , delete the link > See Soccer Practice Plans.

**Comment by dustinschaerer** [comment]
This is completed.
