### ISSUE TITLE
Basic Info - 2 changes, 7-22-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#279]
I emailed this on 7-22-17 at 2:54 PM - use the email

Dustin, on http://www.soccerhelp.com/Basic_Info.shtml  , 

1.  number 5 is >

5. Soccer Practice Tips & Soccer Practice Plans. See Things You Need For A Good Practice & 18 Soccer Practice Tips. See "Soccer Practice Plans.

Dustin, those links go to the wrong pages, so delete the 2nd and 3rd sentences.

Replace the 2nd and 3rd sentences with (  29 Soccer Practice Tips goes to  http://www.soccerhelp.com/soccer-practice.shtml  and Soccer Practice Plans goes to http://www.soccerhelp.com/soccer-practice-plans.shtml    ) >

See 29 Soccer Practice Tips and Soccer Practice Plans

So it reads > 

Soccer Practice Tips & Soccer Practice Plans. See 29 Soccer Practice Tips and Soccer Practice Plans 

2. number 21 is looks like a link BUT it isn't supposed to be a link - it should be text. 

It looks like > 

21. At the End of the Game. At the end of the game, players & coaches usually line up facing each other on the halfway line, walk past each other & touch hands & say "good game". Coaches are usually last in line & shake hands. It is also a nice gesture & sets a good example for the coach to seek out the referee & assistant referees & thank them. Parents usually take turns providing refreshments after games.

**Comment by dustinschaerer** [comment]
Completed.
