### ISSUE TITLE
Second version - Youth Soccer Positions changes, 7-23-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#280]
I emailed this on 7-23-17 at 12:21 PM - use the email so you see colors & links

Dustin, delete the version I sent on 7-23-17 at 11:52 AM

Dustin, on http://www.soccerhelp.com/youth-soccer-positions.shtml > 

1. Put the 2 Tests below as the 4th para above # 1  as a Block Quote (leave some space between each Test) >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"I have learned more in the two weeks since subscribing to Premium than I learned in seven years of coaching.” Coach Rion, SC

2. number 11 is >

Teach your Fullbacks "First Defender/Second Defender". How to teach this is explained at "Quick Team Improvement Program No. 3"
Replace it with (the links go to http://www.soccerhelp.com/terms/soccer-support.shtml  and http://www.soccerhelp.com/premium/Quick_Team_Improvement.shtml#3  )   >

Teach your Fullbacks First Defender/Second Defender. How to teach this is explained in the Premium article "Quick Team Improvement Program No. 3" at First Defender/Second Defender - How To Teach

3. In 14.b., the last sentence is >

See "Defending Deep Basics" For How To Teach Defending Deep and "Should You Push Up When You Attack? Or Should You Defend Deep?".

---  Replace it with (make the 2 links BOLD - the links go to, in order,  http://www.soccerhelp.com/premium/Defending_Deep_Basics.shtml  and http://www.soccerhelp.com/premium/Should_You_Push_Up.shtml     ) > 

See the Premium articles Defending Deep Basics and Should You Push Up When You Attack? 
 

4.  In 14.c., in the 2nd para >

(a).  make  First Defender/Second Defender  a link to > http://www.soccerhelp.com/terms/soccer-support.shtml 

First Defender/Second Defender

(b). The next to last sentence is >

See First Defender - How To Teach for how to teach "First Defender/Second Defender".

Replace it with (the link goes to   http://www.soccerhelp.com/premium/Quick_Team_Improvement.shtml#3   )   > 

For how to teach First Defender/Second Defender see the Premium article "Quick Team Improvement Program" at First Defender/Second Defender - How To Teach . 

--- So the para reads > 

Slow down the attack by playing "First Defender/Second Defender" and staying between the ball and the goal, and try to "toe poke" away the ball. DO NOT jump at the attacker or rush the attacker -- they MUST not get beaten and MUST stay between the ball and the goal, and MUST play "First Defender/Second Defender". For how to teach First Defender/Second Defender see the Premium article "Quick Team Improvement Program" at First Defender/Second Defender - How To Teach . Use our red iron-on bravery patches to encourage tough, brave play.

**Comment by dustinschaerer** [comment]
This is completed.
