### ISSUE TITLE
Soccer Positions - change destination of 3 links to Premium Promo, 7-23-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#281]
I emailed this on 7-23-17 at 2:08 PM

Dustin, on http://www.soccerhelp.com/Soccer_Positions.shtml 

The same link is in 3 places, at A, B.1. and C >

Click here to read about SoccerHelp Premium

Change the destination of all 3 links to > 

http://www.soccerhelp.com/New_Articles_On_Soccerhelp_Premium.shtml

**Comment by dustinschaerer** [comment]
This is completed.
