### ISSUE TITLE
Bunching Up - change Title Tag - add Teach, 7-24-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#282]
Dustin, on http://www.soccerhelp.com/Coaching_Soccer_To_Not_Bunch.shtml >

Change the Title Tag to (add the word "Teach" ) >

<title>How to Teach Soccer Players To Not Bunch Up</title>

**Comment by dustinschaerer** [comment]
Completed.

**Comment by david-huddleston** [comment]
Dustin, this didn't get done.

**Comment by dustinschaerer** [comment]
It is completed now for sure.
