### ISSUE TITLE
SoccerPatch.net, change a link destination, 7-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#283]
I emailed this on 7-26-17 at 10:01 AM

Dustin, on    www.soccerpatch.net/ , 

change the link destination of  400 Testimonials for our Soccer Patches 

to go to http://soccerhelp.com/soccershop/soccer-patches-reviews-testimonials

**Comment by dustinschaerer** [comment]
This is completed.
