### ISSUE TITLE
Re-direct soccerhelp.com/U4U5U6_SoccerDrills_Under4Under5Under6.shtml , 7-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#284]
I emailed this on 7-26-17 at 3:59 PM

Dustin, do a 301 re-direct to send www.soccerhelp.com/U4U5U6_SoccerDrills_Under4Under5Under6.shtml to http://www.soccerhelp.com/u6-Soccer-Drills.shtml   

Be sure the re-direct goes to   www.soccerhelp.com/u6-Soccer-Drills.shtml  - that is the page I want to keep.

**Comment by dustinschaerer** [comment]
This is completed.
