### ISSUE TITLE
Aggressive Play article changes, /How_To_Play_Soccer_Aggressive_Play.shtml , 7-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#285]
I emailed this on 7-26-17 at 5:08 PM

Dustin, on    www.soccerhelp.com/How_To_Play_Soccer_Aggressive_Play.shtml >

2 changes >

1. at the top, delete the link See Aggressive Play No. 2  and replace it with a link that goes to http://www.soccerhelp.com/strength-on-ball-report.shtml    >

Aggressive Play & Bravery Drill

2. In no. 2, change the destination of the link Click here to try 10 free SoccerHelp Practice Games   to >

http://www.soccerhelp.com/soccer-drills.shtml

**Comment by dustinschaerer** [comment]
Completed.
