### ISSUE TITLE
Add links to the 2 Links pages, 7-26-17 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#286]
I emailed this on 7-26-17 at 6:33 PM

Dustin, 

Add the links below to the bottom of http://www.soccerhelp.com/Links.shtml  AND also to the bottom of  http://www.soccerhelp.com/Links_Two.shtml    >

www.soccerhelp.com/soccer-articles/130503-aggressive-soccer-players.shtml 

www.soccerhelp.com/Brave_And_Aggressive_Play.shtml 

www.soccerhelp.com/soccer-articles/090206-soccer-drills-aggressive.shtml 

www.soccerhelp.com/April_Heinrichs_Interview.shtml 

www.soccerhelp.com/newsletter_archive/Soccer_Drills_8_06_2009.shtml 

www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml 

www.soccerhelp.com/newsletter_archive/1.19.2009.shtml

www.soccerhelp.com/ironon-patches.shtml 

www.soccerhelp.com/Kids_Kid_Soccer_Drill.shtml

www.soccerhelp.com/Motivational_Quotes_Coaches_Sports_Inspirational_Coaching_Quotes.shtml 

www.soccerhelp.com/members/login 

www.soccerhelp.com/Motivational_Coaching_Quotes_Players.shtml 

www.soccerhelp.com/Soccer_Patches.shtml 

www.soccerhelp.com/Motivational_Quotes_Coaches_Sports_Inspirational_Coaching_Quotes.shtml 

www.soccerhelp.com/U4U5U6_SoccerDrills_Under4Under5Under6.shtml

**Comment by dustinschaerer** [comment]
This is completed.
