### ISSUE TITLE
4th Version - Changes to SH Home Page Alphabet List, 7-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#287]
I emailed you this on 7-28-17 at 11:33 AM - use the email

Dustin, delete the 3 versions I sent on 7-26-17 at 6:40 PM and on 7-27-17 at 11:05 AM and on 7-28-17 at 11:01 AM

Dustin, on SH Home page, in the Alphabetical List, add, change, and delete the links listed below > 

1. Add the 4 links below in Alphabetical Order >

- add a new link >  Aggressive Receiving that goes to    www.soccerhelp.com/terms/soccer-aggressive-receiving.shtml

- add a new link > Aggressive Soccer Drill  that goes to    www.soccerhelp.com/strength-on-ball-report.shtml 

- add a new link >  Premium Sites   that goes to  www.soccerhelp.com/Premium_Sites_Navigation.shtml 

- add a new link >  Subscriptions   that goes to  www.soccerhelp.com/Premium_Sites_Navigation.shtml 

2. 6 Links to change name or destination of >

- Change the name of the link "Soccer Dictionary" to " Dictionary - 400 Topics" , and Move it so it is in Alphabetical order after "Diagrams" 

- Change the name of the link "Soccer Drills and Skills Training Videos" to "Videos" and move it to be just before the link  "Weak Soccer Players & Teams"  (don't change the destination)

- Change the name of the link "U4, U5, U6 Soccer DVD Review" to "U4-U6 Coaching Videos" (don't change the destination)

- Change the link named "U-4 Soccer Coaching" to  "U4 Soccer Coaching" (remove the hyphen) and change the destination to  www.soccerhelp.com/U-4_Coaching_Ages_2_3_4_5.shtml 

- Change the link named "U-6 Soccer Coaching " to  "U6 Soccer Coaching" (remove the hyphen) and change the destination to  www.soccerhelp.com/U6-Soccer-Drills.shtml 

- Change the link named " U-8 Soccer Coaching" to  "U8 Soccer Coaching" (remove the hyphen) and change the destination to  www.soccerhelp.com/U-8_Coaching_Ages_7_8.shtml 

3. In the Alphabetical list, delete the following 18  links  >

Aggressive, Brave Soccer Players"   that goes to    www.soccerhelp.com/soccer-articles/130503-aggressive-soccer-players.shtml 

Aggressive Soccer No. 2"   that goes to   www.soccerhelp.com/Brave_And_Aggressive_Play.shtml 

Aggressive Soccer - How to Teach Girls"   that goes to   www.soccerhelp.com/soccer-articles/090206-soccer-drills-aggressive.shtml 

April Heinrichs Interview"   that goes to   www.soccerhelp.com/April_Heinrichs_Interview.shtml 

DVDs for Soccer Training"   that goes to    www.soccerhelp.com/newsletter_archive/Soccer_Drills_8_06_2009.shtml 

Improve Team in 2 Practices"   that goes to   www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml 

Indoor Soccer Formations, Positions, Tips”  that goes to   www.soccerhelp.com/newsletter_archive/1.19.2009.shtml

“Iron On Patches”  that goes to   www.soccerhelp.com/ironon-patches.shtml 

“Kids Soccer Drills”  that goes to   www.soccerhelp.com/Kids_Kid_Soccer_Drill.shtml

“Motivational Quotes for Coaches ”    that goes to  www.soccerhelp.com/Motivational_Quotes_Coaches_Sports_Inspirational_Coaching_Quotes.shtml 

Premium Log In"   that goes to  www.soccerhelp.com/members/login 

Quotes to Motivate Players"   that goes to   www.soccerhelp.com/Motivational_Coaching_Quotes_Players.shtml 

“Soccer Patches Home ”    that goes to  www.soccerhelp.com/Soccer_Patches.shtml 

“Sports Inspirational Quotes ”     that goes to  www.soccerhelp.com/Motivational_Quotes_Coaches_Sports_Inspirational_Coaching_Quotes.shtml 

“2 Practices Improvement ”     that goes to  www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml 

"U4, U5, U6 Soccer Drills U-4, U-5, U-6" that goes to    www.soccerhelp.com/U4U5U6_SoccerDrills_Under4Under5Under6.shtml

“U12 Soccer Drills Under 12 ”    that goes to  www.soccerhelp.com/soccer-drills.shtml 

“Under 4, Under 5, Under 6 DVD Review ”    that goes to   www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml

**Comment by dustinschaerer** [comment]
This is completed.
