### ISSUE TITLE
Coach Doug Buy Buttons - add 3 Buttons in 3 places, 7-27-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#292]
I emailed this on 7-27-17 at 8:50 AM

Dustin,

On http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml , about half-way down are 3 Buy Buttons > 

"Subscribe"   "Buy DVD"   and   "Buy Streaming Video"

Add those 3 Buttons in 3 places >

1. On http://www.soccerhelp.com/soccer_drills/Hit.shtml  just below the video

2. On  http://www.soccerhelp.com/coachdoug-promo/Doug-Navigation.shtml >

just above the sub-title >  Coach Doug's site contains about 200 pages and includes the following:

3. On http://www.soccerhelp.com/soccer_drills/Kids-Soccer-Go-Score-Practice-Game.shtml , add it just below the first para, above the last para that is Titled "The Game"

**Comment by dustinschaerer** [comment]
This is completed.
