### ISSUE TITLE
Add a link to Formations on Youth Soccer Positions, 7-27-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#293]
I emailed this on 7-27-17 at 9:33 Am

Dustin,

on http://www.soccerhelp.com/youth-soccer-positions.shtml ,

The 3rd para is >

Soccer positions basics are at Soccer Positions Basics.

> Add a second sentence to it  that says (have the link go to http://www.soccerhelp.com/soccer-formations.shtml   ) >

For How to Choose and Teach Formations, see Formations

So it reads >

Soccer positions basics are at Soccer Positions Basics. For How to Choose and Teach Formations, see Formations

**Comment by dustinschaerer** [comment]
This is completed.
