### ISSUE TITLE
2nd Version - SH Home page - 4 changes, 7-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#294]
I emailed this on 7-28-17 at 10:52 AM - use the email

Dustin, delete the version I sent on 7-27-17 at 10:43 AM

Dustin, on SH Home >

1. at the top right in the Navigation links>

(a).  Change the name of the link  "Premium" to "Subscriptions"

(b). Replace the Link "U6" with the link > 
 
Dictionary 

that goes to  http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_A.shtml 

2. Also on the top right but a little lower, it says > "Login To Paid Services" 

Replace that with >

Subscriptions

3. Near the top, Under the title is >

Premium Sites 
Motivational Soccer Patches 
5 Million Sold - 50 Cents

Change Premium Sites  to   Subscriptions

**Comment by dustinschaerer** [comment]
This is completed.
