### ISSUE TITLE
SH Home, Important Site Links - 2 changes, 7-27-17 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#295]
I emailed this on 7-27-17 at 11:00 AM

Dustin, on SH Home is a box titled "Important Site Links".

In the box is a list of links.

2 of the Link Names are >
Subscribe to Subscription Sites
Re-Subscribe to Subscription Sites

Change the words to >

Subscribe to Websites & Video
Re-Subscribe to Subscriptions

**Comment by dustinschaerer** [comment]
This is completed.
