### ISSUE TITLE
Second Version - Changes to Doug Website - 4 changes to Links, 7-27-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#298]
I emailed this on 7-27-17 at 1:12 PM - use the email

Dustin, let me know if it is a problem to do numbers 1, 2 or 3 or takes more than 30 minutes .

Dustin, on http://soccerhelp.com/coachdoug/

1. one of the top links (in the Navigation bar at the top) is > 

"Coach Doug DVD" 

Change the words to >

DVD & Video

2 & 3. Add 2 new links to the right of it (between it and "Dictionary" >

Coupons

that goes to >  http://soccerhelp.com/coachdoug/coupons 

AND

Patches

that goes to >  http://www.soccerhelp.com/soccershop/ 

4. In the Alphabet List, add a new link >

DVD & Video 

That goes to >  http://soccerhelp.com/soccershop/soccer-dvd

**Comment by dustinschaerer** [comment]
This is completed.
