### ISSUE TITLE
Broken Links to fix after the SoccerHelp SSL is set up

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#3]
Dustin, see the email I sent you today (5-31-17 at 11:50 Am CST). There was too much info to paste all of it here and some screen shots.  The Subject is the same as this Issue. 

I pasted some of it below >

Dustin,  After the SoccerHelp SSL is set up, then > 

1st - First fix the broken links to Video Clips in the Shopping Cart

2nd - Add back the links on  http://www.soccerhelp.com/premium/Videos_Navigation_Page.shtml  and fix those links that go to the Video Clips

3rd - Look at the 3 lists of Broken Links below (from deadlinkchecker.com/, brokenlinkcheck.com,   and from Website Auditor)  

Just fix the internal links OR do a 301 to the correct URL - don't worry about links that go to off-site domains EXCEPT for the 5 listed below (soccerdrills.net, soccerformations.net, etc. )

BUT some like those below need to be changed from https to http >

https://soccer.soccerhelp.com

https://www.soccerdrills.net

https://www.soccerformations.net

http://www.christianpatches.net    - Dustin, delete this link - it is to a domain I didn't renew

https://www.soccerpatchesforkids.com

https://www.youthsoccerdrills.com

https://www.soccerpositions.net

There are 3 lists below > (Dustin, the rest is in the email I am about to send on 5-31-17 at 11:50 CST)

**Comment by dustinschaerer** [comment]
Do you know where the page is for this?
Soccer Patches - Where to Put

**Comment by dustinschaerer** [comment]
@david-huddleston I've got the first two items all finished and have fixing broken links all over.  It didn't realize that the Google Search Console link linter is absically useless now. It used to be great, but currently didn't have any links reported as broken :/

I'll make sure to keep us up to snuff with a few external linters from now on.  I'll finish the links in the AM.

**Comment by david-huddleston** [comment]
Dustin, I found a link named that on https://www.soccerhelp.com/How_To_Use_Patches.shtml 

 

If you find that link, just have it go to https://www.soccerhelp.com/How_To_Use_Patches.shtml 

 

David

**Comment by david-huddleston** [comment]
Dustin,

If you find that link, just have it go to https://www.soccerhelp.com/How_To_Use_Patches.shtml 

David

**Comment by david-huddleston** [comment]
Dustin, at 10:30 CST on 6-2-17 I emailed you an email I got from Google - see below - so you could click the links.  

NOTE that it is addressed to   http://soccerhelp.com/  , not https:

What do you think it means? 

Subject is > Increase in “soft-404” pages on http://soccerhelp.com/  

David

----------------

From: Google Search Console Team [mailto:sc-noreply@google.com] 
Sent: Friday, June 02, 2017 4:12 AM
To: dhudleston127@gmail.com
Subject: Increase in “soft-404” pages on http://soccerhelp.com/ 

Message type: [WNC-655200] 
 Search Console 
Increase in “soft-404” pages on http://soccerhelp.com/
To: Webmaster of http://soccerhelp.com/, 
Googlebot identified a significant increase in the number of URLs on http://soccerhelp.com/  that should return a 404 (not found) error, but currently don't. This can cause a bad experience for your users, who might have been looking for a specific page, but end up elsewhere on your website. This misconfiguration can also prevent Google from showing the correct page in search results. 
Recommended Actions:
1	Identify the URLs with errors
Open the Crawl Errors report in your Search Console account to review the list of sample URLs. 	Check Crawl Errors 

2	Fix the issue
Check your server and CMS settings to make sure that these URLs return a 404 (Not Found) or 410 (Gone) HTTP response code in response to requests for non-existent pages. You may need help from your server administrator or hoster for this step. 
3	Verify the fix
Once you've fixed the URLs with errors, make sure that Googlebot can access and see your content properly, or that they return a proper error result code. You can verify this using Fetch as Google. 	Fetch as Google 

Need more help?
•	See the Crawl Errors - Soft 404 Help Center article. 

•	Ask questions in our forum for more help - mention message type [WNC-655200].

**Comment by dustinschaerer** [comment]
@david-huddleston I moved the above comment into its own issue since its not related to this thread, you can it here: #6

**Comment by dustinschaerer** [comment]
@david-huddleston I've made really good progress on this today and will wrap up next week with the server change.

**Comment by dustinschaerer** [comment]
@david-huddleston All broken links **ARE FIXED**!
