### ISSUE TITLE
Add 2 notes about Https in the Shopping Cart

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#30]
Dustin,

No. 1 - On https://soccerhelp.com/soccershop/ 
Just below 

We accept Visa, MC, Discover, AMEX, PayPal
Free Priority Mail Worldwide on Orders over $100

add >

Our Checkout Uses a https Secure Connection

No. 2 - On http://soccerhelp.com/soccershop/index.php?route=checkout/cart 
Just below
We accept Visa, MC, Discover, AMEX, PayPal

add>

The Next Page is a https Secure Connection

**Comment by dustinschaerer** [comment]
@david-huddleston This is COMPLETED.
