### ISSUE TITLE
SH Home Alphabetical list - move Formations articles, 7-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#301]
I emailed this on 7-28-17 at 11:31 AM

Dustin, on SH Home, in the Alphabetical List are 7 Links about Formations (see below ) .

Remove the word "Soccer" from all 7 and move them to Alphabetical order before "Free Soccer Drills"

•	Soccer Formation Basics
•	Soccer Formation - Choosing
•	Soccer Formations Diagrams
•	Soccer Formations Overview
•	Soccer Formations 8v8
•	Soccer Formations 11v11
•	Soccer Formations, 11v11, Large Field

**Comment by dustinschaerer** [comment]
This is completed.
