### ISSUE TITLE
Ideas for End-of-Season Soccer Awards article changes, 7-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#302]
I emailed this on 7-28-17 at 4:33 PM - use the email _ for some reason, some of the text below is large and bold but it isn't that way in the email.

Dustin, on http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml >

1. Delete the bottom part of the article below "David at SoccerHelp"  , which is >>
-------------------------------------------
(Following is a reply from Coach J., who has some excellent ideas)
Hi Coach C.H.,
I've always gone above and beyond here. A couple of seasons I have gone to the website mentioned above and downloaded templates to print off trading cards. I have done certificates. Last season we did pennants and put the patches on them. The kids really loved the pennants because the patches showed all of their hard work. You can buy the pennants pre-cut at Hobby Lobby if you have one local. 
Coach J.

2. Between the Title and Here are some of the Awards you can give:  delete what is below >>

Hi SoccerHelp,
I'm looking for a unique/different idea for presenting trophies at the end of the year. I've been coaching youth soccer and basketball for years now and every year at the party I say a few words about the player before handing them the trophy. I am getting bored with this and have had some players multiple years, so am running out of things to say. Plus, this year I have two players about which I cannot think of anything positive to say (bad attitudes/behavior and no skills). I would be interested in hearing some ideas that could help me avoid it this year.
Thanks,
Coach C.H.
--------------------------------
Hi Coach C.H.,
There's an article about Certificate Award Ideas on SoccerHelp.
In the article is a link where you can go to print a "Certificate".

3. Replace what you deleted in # 2 with what is below (the patches link goes to http://www.soccerhelp.com/soccershop/ and Certificate Award Ideas on SoccerHelp goes to http://www.soccerhelp.com/Soccer_Certificate_Award_Roster.shtml  ) - it will be between the Green title and  Here are some of the Awards you can give: >

Hi SoccerHelp,
Last season we did pennants and put the patches on them. The kids really loved the pennants because the patches showed all of their hard work. You can buy the pennants pre-cut at Hobby Lobby if you have one local.
I've been coaching youth soccer and basketball for years now and at the end of season party I say a few words about the player before handing them the trophy. I have had some players multiple years and am running out of things to say. Any ideas?
Thanks,
Coach C.H.
--------------------------------
(Note from SoccerHelp - We sell 35 kinds of the iron-on Motivational Patch Rewards that Coach C.H. mentions for all sports - soccer, baseball, basketball, camps, school, etc. There are 400 Testimonials from coaches. The cost is 10 for $5 with free shipping.)
Hi Coach C.H.,

Thanks for being our customer. Some coaches use patches instead of trophies. Most of the time the patches are ironed on a jersey or practice shirt so everyone can see the patches the players have earned, but if that isn't possible the pennant idea is great.

If you want to give out certificates, there is a link to free certificates that you can personalize for each player at Certificate Award Ideas on SoccerHelp.

=============================
Dustin, after the changes, the top will look like >>

Ideas for End-of-Season Soccer Awards
Alternatives to Soccer Trophies 
Soccer certificates, trading cards and pennants 
Idea for putting soccer patches on pennants (this would work for baseball too) 
50 different awards you can choose from 
Most Improved Awards 
Awards for doing the Best or the Most 
Awards for Attitude, Effort, Character or Leadership 
Awards for Attendance and for Parents, Coaches and Sponsors 
Awards for Soccer, Baseball and All Sports
Hi SoccerHelp,
Last season we did pennants and put the patches on them. The kids really loved the pennants because the patches showed all of their hard work. You can buy the pennants pre-cut at Hobby Lobby if you have one local.
I've been coaching youth soccer and basketball for years now and at the end of season party I say a few words about the player before handing them the trophy. I have had some players multiple years and am running out of things to say. Any ideas?
Thanks,
Coach C.H.
--------------------------------
(Note from SoccerHelp - We sell 35 kinds of the iron-on Motivational Patch Rewards that Coach C.H. mentions for all sports - soccer, baseball, basketball, camps, school, etc. There are 400 Testimonials from coaches. The cost is 10 for $5 with free shipping.)
Hi Coach C.H.,

Thanks for being our customer. Some coaches use patches instead of trophies. Most of the time the patches are ironed on a jersey or practice shirt so everyone can see the patches the players have earned, but if that isn't possible the pennant idea is great.

If you want to give out certificates, there is a link to free certificates that you can personalize for each player at Certificate Award Ideas on SoccerHelp.

Here are some of the Awards you can give:

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
