### ISSUE TITLE
Premium Sites Navigation Page - add 1,500 and 5,000, 8-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#305]
Dustin, on http://www.soccerhelp.com/Premium_Sites_Navigation.shtml , 

the first sub-title is >

SoccerHelp Premium Website

Add after it >

(1,500 pages & 5,000 internal links)

So it reads >

SoccerHelp Premium Website (1,500 pages & 5,000 internal links)

**Comment by dustinschaerer** [comment]
This is completed.
