### ISSUE TITLE
2nd version -  Premium Promo - add "& 5,000 links for easy navigation" in 8 places & the promo to Index, 8-2-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#306]
I emailed this on 8-2-17 at 9:39 AM - use the email

Dustin, delete the version I sent on 8-1-17 at 6:54 PM. I added number 9.

Dustin, change the Premium Promo in 8 places and also add it to the Navigation/Index page >

In the 8 places listed below the Premium Promo says >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

REPLACE the first sentence with >

SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation.

SO IT READS >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

Change it in the 8 places below (also see number 9 below ) > 

1. On  http://www.soccerhelp.com/soccer-practice.shtml just above the 2nd Sub-title, which is > Things to Do at Soccer Practice

2. On http://www.soccerhelp.com/how-to-score-more-goals-report.shtml , in the 1st para, so it reads >

The Premium version of this article has 115 links to Premium articles and definitions. Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials  Sign up at http://soccerhelp.com/members/signup
                                                                                                                                                     

3. On the bottom  of   http://www.soccerhelp.com/terms/soccer-support.shtml  , Just below C. (above See prices for our iron on Motivational Soccer Patches 

4. On  http://www.soccerhelp.com/Evaluating_Soccer_Players_And_Teams.shtml , near the bottom, above See prices for our iron on Motivational Soccer Patches

5. On  http://www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml , just after > Fast Play - 7 Tips, How to Teach Fast Play 

6. On http://www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml , the 1st para

7. On http://www.soccerhelp.com/Soccer_Coaching_Tips_New_Soccer_Coach.shtml in the 3rd para, above the link Basic Information & Tips for Beginning Coaches 

8. On http://www.soccerhelp.com/youth-soccer-positions.shtml after # 20 and just above the Links List.

9. Dustin, ALSO, add the same Premium Promo  to http://www.soccerhelp.com/Soccer-Coaching-Navigation.shtml >

just below the link   Bunching Up - 7 Ways to Stop It

**Comment by dustinschaerer** [comment]
This is completed.
