### ISSUE TITLE
Put a copy of the SoccerHelp website in my DropBox, 8-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#307]
Dustin, we discussed this. Just the website - not all the product information like the Cart and aMember.

David

**Comment by dustinschaerer** [comment]
This is in the works now.

**Comment by dustinschaerer** [comment]
I've pulled it down from the server and am uploading it to Dropbox now.

**Comment by dustinschaerer** [comment]
This is completed.  The backup is in a folder called "Soccerhelp website file system"
