### ISSUE TITLE
Navigation-Index page - 2 Changes, 8-2-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#308]
I emailed this on 8-2-17 at 9:32 AM

Dustin, on  http://www.soccerhelp.com/Soccer-Coaching-Navigation.shtml > 

1. The link  Bunching Up - 7 Ways to Stop It  doesn't work. It should go to http://www.soccerhelp.com/Coaching_Soccer_To_Not_Bunch.shtml 

2. Add as the 6th Link in the Links List a new link >

Subscriptions 

That goes to > http://www.soccerhelp.com/Premium_Sites_Navigation.shtml

**Comment by dustinschaerer** [comment]
This is completed.
