### ISSUE TITLE
Changes to www.soccerhelp.com/Soccer_Practice.shtml 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#31]
Dustin, SEE the EMAIL I sent you about this on 6-11-17 at about 11:55 PM CST with this same title - it will be easier to read because you can see the colors and the formatting.

Delete the 3 prior versions that I emailed you at about 3 PM CST, 7:19 PM and 11:47 CST on 6-11-17.

Don't let this interfere with your work on moving SH to a new Server.

Dustin, 

This Email version will be easier to work from than GitHub because you can see the colors and formatting. 

On www.soccerhelp.com/Soccer_Practice.shtml 

> No. 1 - Delete the first link on the Links List, which is Why SoccerHelp Practice Games are better than drills  

> No. 2 - Delete the 3rd link on the Links List, which is Tips for good practices

> No. 3 - delete the last link on the Links List, which is  "Best soccer drills for age 3 to 16" and goes to http://www.soccerdrills.net/ 

> No. 4 - add below as the first 4 links in the Links List.

18 Soccer Practice Tips  that goes to http://www.soccerhelp.com/soccer-articles/110712-soccer-practice-plans-tips-1.shtml

12 Tips for a Great Soccer Practice    that goes to  http://www.soccerhelp.com/Soccer-Practice-Tips.shtml  

Why Practice Games are Better than Line Drills   that goes to  http://www.soccerhelp.com/Soccer_Journal_Article.shtml 

18 Tips for U4 and U6 Soccer Coaches  that goes to http://www.soccerhelp.com/U4-U6-soccer-coaching.shtml 

> No. 5 - Replace number 5 with below, keeping the same "look" . Motivational Patch Incentives   goes to http://soccerhelp.com/soccershop/ >

5. Practice attendance is CRITICAL. Players won't improve unless they practice. Players are MUCH more likely to attend practice and be on time if your practices are FUN and if you minimize lines and maximize activity. But, if players don't attend practice or are late, motivate and reward them. Praise and reward the things you want your players to do, such as hustling, improving, and giving 100% effort (every player can do those things). We have had great success using small iron-on patches to motivate players - you have probably seen them - we sell soccer balls, Lightning Bolts to reward hustle, a B for Bravery, a D for defense, a Happy Face, T for Team Work, etc. You can see them at Motivational Patch Incentives

6.  The most important fundamental soccer skill is dribbling. Many SoccerHelp No Lines Drills that are Practice Games teach dribbling, but the best one for U8 and older is Dribble Across a Square which I recommend you play at every practice as a warm up for teams U8 and older. The Soccer Help Practice Games are self teaching and players learn by playing the games. 

7.  If your team is U4 or U6, you will greatly benefit from Coach Doug's ideas. Watch the video clips of how Coach Doug coaches and the "Hit the Coach" Practice Game at Coach Doug Video Clips. At U4 and U6, Coach Doug and I recommend you focus on dribbling, defense and movement off the ball but NOT passing. Passing is too confusing for U4 and U6 players and teaching it will hold back their development of other skills such as dribbling. The USYSA recommends this approach and we agree. 

8.  If your team is U8 or older, you should teach control dribbling, speed dribbling into Open Space (acceleration into Open Space), how to "chip" the ball, how to make a Throw-in, passing, and Aggressive Receiving. SoccerHelp has No Lines Drills to teach all of these. 

9. Practice Tips from the Great Anson Dorrance for U8 and Older - The best way to teach skills to U8 and older is by using the SoccerHelp No Lines Soccer Drills that involve pressure and competition (SoccerHelp Drills for U8 and older are designed to create pressure and competition). The reason is because they prepare players to perform those skills in games, at "Game Speed", and while under pressure. Coach Anson Dorrance is one of the greatest soccer coaches ever - he is a college coach and his teams have won over 700 games and 22 national championships. Below are some of his tips that have influenced the SoccerHelp Training Program: 
- In practice, encourage competition. 
- During practice, try to keep score in everything you can -- keeping score encourages competition, 100% effort, game speed, and is more like what player's face in a real game. 
- Competition is critical to developing each player's potential. 
- "Competition is key to developing players. The only practice environment in which you truly develop a player is a competitive arena."

10. At practice, be sure to use Drills or Practice Games that are Age Appropriate. For example, SoccerHelp has different Drills and Practice Games for U6 than for U8. SoccerHelp Games for U6 don't keep score or try to create competition so players practice as fast as possible, but those for U8 and older do.  

11. Summary - SoccerHelp No Lines Practice Games are a better way to train players. The best way to train your players is by using SoccerHelp No Lines Practice Games - that is why there are over 400 Testimonials from coaches.  SoccerHelp Practice Games are effective and for U8 and older they involve competition and pressure. SoccerHelp Practice Games train players to play fast while under pressure. Coaches who use SoccerHelp No Lines Drills and Practice Games achieve 200% to 300% MORE at each practice, because actual practice time is maximized and standing in line is minimized. The result is that your players will improve 2 or 3 times faster and develop better fundamental skills - read the Testimonials from Coaches . Even if you practiced twice as much with Line Drills, your results would be inferior because Line Drills don't create competition and train players to play fast while under pressure. SoccerHelp Drills and Practice Games are a better way to train and train players to play fast while under pressure, so they are able to play better in real matches. 

12. 8 Practice Tips from the Great April Heinrichs - No one can match April Heinrichs' experience and success as a soccer player and coach. She was Soccer America's "Player of the Decade" for the 1980's, a 3 time All American at the University of North Carolina where she scored 87 goals in 90 games and Coach Anson Dorrance said she was one of the best he has ever seen at 1 v 1 attacking, in 1998 she was the first female player voted into the National Soccer Hall of Fame, Captain of the World Cup Championship team in 1991, Head Coach of the U.S. U-16 Girl's National Team, Head Coach at the University of Virginia, and she coached the U.S. Women's National Team. I interviewed her and asked:
"What should coaches of players age 13 and younger emphasize in practice?"
Below are Coach Heinrichs' 8 Practice Tips (SoccerHelp No Lines Soccer Drills let you achieve her recommendations):
1.	Create passion and love for soccer.
2.	Plan practices in advance and keep the practice and all activities "short and crisp" (not long and dull).
3.	The practice length should be about the same length as the real games or matches (e.g., about 1 hour if games last 1 hour). This way the players will look forward to the next practice.
4.	Keep practices fun and interesting by maximizing activity and minimizing lines.
5.	Have a ball for every player and try to involve as many players as possible in practice activities so as many players as possible are active.
6.	Plan the amount of time you will spend on an activity and stick to it, don't let it linger. End practices on time. Wear a watch and use it.
7.	Spend 80% or more of the practice time on activities with a ball that have a "high ball ratio", such as dribbling, passing and shooting drills or games, and small-sided attacking and defending (such as 1v1, 2v1 or 1v2) where 25% to 100% of the players have a ball, and less than 20% on things that don't involve a ball or activities that have a "low ball ratio" (such as scrimmages that involve a lot of players and one ball).
8.	Build competition into the practice. It's more fun and better prepares players for real soccer matches.

**Comment by dustinschaerer** [comment]
@david-huddleston This is COMPLETED.
