### ISSUE TITLE
Old Navigation Bar - changes to Link Names, 8-3-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#310]
I emailed this on 8-3-17 at 11:39 AM

Dustin, on the old pages like http://www.soccerhelp.com/new-login-page.shtml 

at the top in the Navigation Bar, change the names of the following links >

1. change "Premium Sites" to "Subscriptions"   (don't change the destination)

2. Change "Videos" to "Drills" AND ALSO change the destination to http://www.soccerhelp.com/soccer-drills.shtml  

3. change "Coaching" to "Index"    (don't change the destination)

**Comment by dustinschaerer** [comment]
This is completed.
