### ISSUE TITLE
5th Version - Premium Promo on 8 pages, 8-3-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#311]
I emailed this on 8-3-17 at 5:05 PM

Dustin, delete the versions I sent you on 8-3-17 at 12:02 PM, 12:26 PM, 12:27 PM and 12:39 PM - I added # 6, 7 and 8

Dustin, the Premium Promo to use below is the same one you put on the bottom of  http://www.soccerhelp.com/terms/soccer-support.shtml (you can copy and paste the code) >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

1. On  http://www.soccerhelp.com/soccer_drills/Throw-ins_Game.shtml , replace the current Premium Promo that is above the 1st para with the one above

2. On http://www.soccerhelp.com/soccer_drills/Tick_Tock.shtml , add it just below the video (Dustin, also look at the amount of white space below the video - there is too much) 

3. Add it to http://www.soccerhelp.com/soccer_drills/Small_Sided_Scrimmage.shtml , just above the 1st para (above the "Summary")

4. Add it to   http://www.soccerhelp.com/soccer_drills/Chip.shtml  , just above the 1st para (above the "Summary") AND

AND Dustin, while you are there, delete 2 links >
See "Just Kickin It" for a DVD about How to Teach Kicking and Shooting
"Mia Hamm Soccer Secrets" also has Good Instruction for Teaching Kicking and Shooting

5. Add it to  http://www.soccerhelp.com/soccer_drills/Kick_Crossed_Ball.shtml   , just above the 1st para AND 

AND Dustin, while you are there, delete the link >

See More Soccer Drills

6. Add it to http://www.soccerhelp.com/soccer_drills/Driving.shtml , above the 1st para

7. Add it on http://soccerdrills.net/soccer-drills-not-bunch-up/ , above the 4th para, which is "Things Needed"

8. Add it to http://www.soccerhelp.com/Coaching_Soccer_To_Not_Bunch.shtml  after number 6 AND

AND also delete the Premium Promo that is below # 10

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
