### ISSUE TITLE
Hit the Coach, change Soccer Bees link destination, 8-3-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#312]
I emailed this on 8-3-17 at 12:18 PM

Dustin, on http://www.soccerhelp.com/soccer_drills/Hit.shtml, in the 1st para is a link named Soccer Bees 

Change the link destination to > http://soccerhelp.com/coachdoug/soccer-bees

**Comment by dustinschaerer** [comment]
COMPLETED.
