### ISSUE TITLE
Fix the 3 Coach Doug Buy Buttons on SoccerDrills.net Soccer Bees, 8-7-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#313]
Dustin, fix the 3 Doug Buy buttons that are on  http://soccerdrills.net/soccer-drills-soccer-bees-u4-u6/ , just above the 4th para, which is "The Game" - they don't work

**Comment by dustinschaerer** [comment]
COMPLETED.

**Comment by dustinschaerer** [comment]
This is completed now, the button definitely work.
