### ISSUE TITLE
Formations page - add a Premium Promo , 8-7-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#314]
Dustin,  this is the same promo you added to http://www.soccerhelp.com/youth-soccer-positions.shtml AFTER number 6  and on http://www.soccerhelp.com/soccer-articles/120824-Select-Soccer-Formation.shtml below the second number 2 (above the 2nd # 3 that starts " Put your most dominant player at Stopper ) (it was in the August 3 email at 4:19 PM) 

Add the Promo to >

http://www.soccerhelp.com/soccer-formations.shtml just below the 2nd section (above What Soccer Formations Numbers Mean )

AND delete  the version of it that is just below the Links List

Here is the email to add (copy the one that you added to the pages listed above so you get the Bold, colors and Links) >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages, 5,000 links & 100 articles about positions and formations. Use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 5-day money back guarantee. 15,000 Coaches have subscribed. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
