### ISSUE TITLE
Videos page - change Black to Green, 8-4-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#315]
I emailed this on 8-4-17 at 10:11 AM

Dustin, on  http://www.soccerhelp.com/Soccer-Videos-Premium.shtml  , the Premium Promo is > 

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

Make the title of it Green, so it looks like >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
