### ISSUE TITLE
Premium Alphabetical Drills List - add "(definitely play this)", 9-15-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#316]
I emailed this on 8-4-17 at 1:17 PM - use the email

Dustin, on http://www.soccerhelp.com/Soccer-Games-Drills-List.shtml , 

the 3rd link is > "Aggressive Play Game" * * * * Video of This

To the right of it add >

(definitely play this) 

So it reads >

"Aggressive Play Game" * * * * Video of This (definitely play this)

**Comment by dustinschaerer** [comment]
This is completed.
