### ISSUE TITLE
One More Streaming Video Sign-up page change, 8-7-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#319]
I emailed this on 8-7-17 at 10:39 AM

Dustin,

on http://www.soccerhelp.com/members-video/signup .

Near the top, the 2nd NOTE is>

NOTE: There are 4 choices below - Coach Doug for U4-U6, Foot Skills, and Individual and League subscriptions. 

**Replace it with** > 

NOTE: There are 3 choices for the Coach Doug U4-U6 Video (one coach for 100 days or 365 days, & a League Subscription) and 2 choices for the Foot Skills Video (one coach for a year & a League Subscription).

**Comment by dustinschaerer** [comment]
This is completed.

**Comment by dustinschaerer** [comment]
This is completed.
