### ISSUE TITLE
Another Block of Links to Delete

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#32]
Dustin,  Don't let this interfere with your work on moving SH to a new Server.

This block of links looks like something that might be on several pages >

it is on the bottom of  http://www.soccerhelp.com/soccer-articles/110712-soccer-practice-plans-tips-1.shtml   >

soccer formations soccer formations for 7v7 to 11v11 soccer positions assigning and coaching soccer positions Soccer Drills soccer drills that are fun and really work Soccer Rules soccer rules and rules of soccer soccer patches soccer patches and soccer patch Soccer Positions soccer positions basics Soccer Patches soccer patches motivation rewards

**Comment by dustinschaerer** [comment]
@david-huddleston This link group and all references to it are removed altogether.
