### ISSUE TITLE
3 More 6yearoldsoccerdrills.com changes,  8-7-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#320]
I emailed this on 8-7-17 at 11:07 AM - use the email to see bold

Dustin - look at it on screen when you finish to see if the 1st Sub-Title looks right. 

Dustin, on    http://6yearoldsoccerdrills.com/ 

1. In the Code, Change the Description and Key Words  to what is below >

meta name="description" content="Soccer drills for kids who play U4 and U6 soccer should be fun and teach fundamental soccer skills."

meta name="keywords" content="U6 Soccer Drills for Ages 4, 5, 6" 

2.  The Title is >

Soccer Drills for 6 Year Olds and U6 Soccer

**Change the Title to** >

Soccer Drills for U4 and U6 Soccer - Ages 4, 5, 6

3. The first Sub-Title looks weird (it is indented and italics). Make it > 

The Best U6 Soccer Drills are Fun Practice Games

**Comment by dustinschaerer** [comment]
This is completed.

**Comment by dustinschaerer** [comment]
This is completed again.  I think that sub-title didn't appear revised b/c it was a stylesheet change. Please Control + F5 to force reload the page, and you'll see the changes. :)
