### ISSUE TITLE
For Sept - Be sure Doug Website is backed up on BlogVault before you upgrade WordPress,  8-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#322]
Dustin,  No rush on this.

Be sure the Doug website is backed up and the Test restore works on BlogVault before you upgrade it. 

It looks like you upgraded it in December 2014.

The Dashboard says We are in WordPress 4.0.1 running Coach Doug Twenty Fourteen Child theme.

By the way, you can't sign into the Coach Doug Admin using Firefox - it keeps re-directing to a https - it is a known bug - it works fine using Chrome. Don't worry about fixing that - It is easy to sign in from Chrome - I'm just pointing it out.

David

**Comment by dustinschaerer** [comment]
Yes, I'll update this when I get back next week.

**Comment by dustinschaerer** [comment]
The Coach Doug test restore is working great!  I'll move forward with the backup / upgrade of wordpress.

**Comment by dustinschaerer** [comment]
@david-huddleston Wordpress for Doug's site is updated to the latest release, 4.8.1, and works beautifully!
