### ISSUE TITLE
U6 Videos Page - change a link name, 8-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#326]
I emailed this on 8-9-17 at 10:27 AM

Dustin, on  http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml , 

the 6th link is >

Soccer Shooting and Kicking Video - 2 minutes

Change the link name to >

Kicking a Soccer Ball Video - How to Teach Kids - 2 minutes

**Comment by dustinschaerer** [comment]
This is completed.
