### ISSUE TITLE
Fix or Make 5 Drills Responsive, 8-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#328]
Dustin, fix or make the 5 drills below responsive -

- [x]  http://www.soccerhelp.com/soccer_drills/Tick_Tock.shtml  - the Video doesn't shrink

- [x]  http://www.soccerhelp.com/soccer_drills/Monster_Invasion.shtml  - the page isn't right (words are narrow)

- [x] http://www.soccerhelp.com/soccer_drills/Small_Sided_Scrimmage.shtml  - not responsive

- [x] http://www.soccerhelp.com/soccer_drills/Chip.shtml - not responsive

- [x] http://www.soccerhelp.com/soccer_drills/Kick_Crossed_Ball.shtml - not responsive

**Comment by dustinschaerer** [comment]
This is completed.
