### ISSUE TITLE
Changes to www.soccerhelp.com/soccer-articles/110712-soccer-practice-plans-tips-1.shtml 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#33]
Dustin, on http://www.soccerhelp.com/soccer-articles/110712-soccer-practice-plans-tips-1.shtml >

No. 1 -  just below the Title , DELETE the link >  Free Soccer Patches

and in its place put a link named >   Soccer Practice Tips and Ideas

that goes to  http://www.soccerhelp.com/Soccer_Practice.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
