### ISSUE TITLE
U6 Navigation page - add a link to New Coaches page, 8-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#330]
Dustin, on http://www.soccerhelp.com/U-4_U-6_U-8_Soccer_Coaching.shtml , add a new 5th link that goes to  http://www.soccerhelp.com/Soccer_Coaching_Tips_New_Soccer_Coach.shtml  

Have the link name be  >

New Coaches Tips & Basic Info

Add the new link to the Links List just below >

29 Soccer Practice Tips for all youth coaches

The link should be bold, like the other links

**Comment by dustinschaerer** [comment]
This is completed.
