### ISSUE TITLE
Second version -  Basic Info page changes, 8-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#331]
I emailed this on 8-9-17 at 12:10 PM - use the email so you can see colors

Dustin, delete the version I sent you on 8-9-17 at 11:56 AM

Dustin, on http://www.soccerhelp.com/Basic_Info.shtml >

1. Near the top, delete the link named >

The SoccerHelp System and Philosophy

2. Replace the 2nd para with what is below  (the Premium Promo is the same one on  http://www.soccerhelp.com/soccer-practice-plans.shtml   )  >

If you use SoccerHelp No Lines Drills that are Practice Games your players will improve twice as fast and have more fun because they aren't standing in line. So, one practice will be like 2 practices, 2 practices like 4 practices, etc.

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
