### ISSUE TITLE
Add Buttons on 8 Coach Doug Video Clips pages, 8-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#332]
I emailed this on 8-9-17 at 12:22 PM

Dustin, on the 8 pages listed below there are Buttons.

3 of the pages have 3 buttons and 5 pages have 2 buttons.

I want there to be 4 buttons , in the order shown below  > 

Subscribe     Buy DVD     Buy Streaming Video     Patches

Below are the 8 pages to change the buttons on. The top group already have 3 buttons and you only need to add the Patches" button on the far right .

1.  PAGES THAT HAVE 3 BUTTONS (add a "Patches" button to the right of  "Buy Streaming Video"  that goes to http://soccerhelp.com/soccershop/soccer-patches - if you have to put the buttons closer together, that is ok )

http://www.soccerhelp.com/Soccer_Video_Clips_Coach_Doug_DVD.shtml 
"Hit the Coach™" Soccer Practice Game Video - http://www.soccerhelp.com/soccer_drills/Hit.shtml 
Dribbling and "Go Score" Soccer Practice Game Video - http://www.soccerhelp.com/soccer_drills/Kids-Soccer-Go-Score-Practice-Game.shtml 

2.  PAGES THAT HAVE 2 BUTTONS  (Dustin, either replace the 2 buttons with the 4 buttons, or add the "Subscribe" and "Patches" buttons in the same order as on the 4 buttons )

How to Have Fun Practices that Teach Soccer Video - http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-how-to-have-fun-practices-that-teach-soccer.shtml 
A Better Way To Teach Dribbling and Soccer Skills Video - http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-better-way-to-teach-dribbling-and-soccer-skills.shtml 
Shy Soccer Player Gains Confidence Video -- Watch This! - http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-shy-player-gains-confidence.shtml 
Soccer Shooting and Kicking Video - http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-shooting-and-kicking.shtml 
How to Use Soccer Patches for Fun and to Motivate Players Video - http://www.soccerhelp.com/soccer-videos/coach-doug-how-to-use-soccer-patches-to-motivate-players.shtml

**Comment by dustinschaerer** [comment]
This is completed.
