### ISSUE TITLE
Five U6 Video pages, change a "10" to "5", 8-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#333]
Dustin, on the 5 pages listed below, in the para below the video, the 4th sentence is >

We offer a 10 day Money Back Guarantee on this DVD and Streaming Video.

In that sentence, change the "10" to "5", so it reads >

We offer a 5 day Money Back Guarantee on this DVD and Streaming Video.

Below are the 5 pages to change >

1. http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-how-to-have-fun-practices-that-teach-soccer.shtml
2. http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-better-way-to-teach-dribbling-and-soccer-skills.shtml
3. http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-shy-player-gains-confidence.shtml
4. http://www.soccerhelp.com/soccer-videos/coach-doug-dvd-shooting-and-kicking.shtml
5. http://www.soccerhelp.com/soccer-videos/coach-doug-how-to-use-soccer-patches-to-motivate-players.shtml

**Comment by dustinschaerer** [comment]
This is completed.
