### ISSUE TITLE
Second version - Soccer Practice - add a test, 8-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#334]
I emailed this on 8-10-17 at 11:31 AM

Dustin, delete the version I sent on 8-10-17 at 11:21 AM

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml

Under the 2nd # 1 that starts > Use SoccerHelp No Lines Drills.

Add a second test and put both Tests in a Block Quote .

1. Add the test below as the 2nd test >

"At every practice we do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

2. Make the 2 tests a Block quote >

"The Practice Games are AMAZINGLY EFFECTIVE!! Parents tell me their girls cannot wait to go to practice." Coach M.J.

"At every practice we do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

**Comment by dustinschaerer** [comment]
This is completed.
