### ISSUE TITLE
Soccer Drills page - 3 changes, 8-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#335]
I emailed this on 8-10-17 at 6:28 PM - use the email to see colors, bold, links

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml , make 3 changes >

1. Under "Free No Lines Drills" it says >

The Free No Lines Drills below are from SoccerHelp Premium. They are only on SoccerHelp. 

Replace it with below (the link  SoccerHelp Premium   goes to http://www.soccerhelp.com/New_Articles_On_Soccerhelp_Premium.shtml   and the link  Coach Doug's Website goes to http://www.soccerhelp.com/coachdoug-promo/Doug-Navigation.shtml   > 

The Free No Lines Drills below are from SoccerHelp Premium. There are over 70 copyrighted No Lines Drills like these for players from U4 to U18 (30 for U6, 50 for U8, and 60 for U10 and older). Premium has 1,500 pages. Coach Doug's Website has 200 pages and 26 Practice Games like those below for U4, U5 and U6 players.

2. Delete the text and link to Monster Invasion > 

Monster Invasion ™
Instructions
U4-U6 definitely try this A simple, always fun game for U4 and U6. Every player has a ball and everyone, including the coach, has fun.

3. The text at "Driving School" is wrong. It says >

U8 & up, Rec & Select. A "crossed ball" is a ball coming from the side. This game is an effective, efficient way to practice timing the run and how to kick a crossed ball, which is not an easy thing to do. It will teach the player to take a short backswing, to keep his head down, eyes on the ball, and to start out by blocking the ball using the inside of the foot.

Replace it with >

U6 to U10 Rec. Teaches control dribbling, using bottom of foot to stop, pullbacks, using outside of right foot & left foot. Every player has a ball. Easy Set-up.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
