### ISSUE TITLE
Dribble Across - replace the premium Promo, 8-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#336]
I emailed this on 8-10-17 at 6:45 PM - use the email

Dustin, on http://www.soccerhelp.com/soccer_drills/Dribble.shtml , there is a Premium Promo below the Video. 

Replace the Premium Promo that is below the video with the 2 paras below (The Premium Promo below the same one on  http://www.soccerhelp.com/soccer-practice-plans.shtml  )   >

If you use SoccerHelp No Lines Drills that are Practice Games your players will improve twice as fast and have more fun because they aren't standing in line. So, one practice will be like 2 practices, 2 practices like 4 practices, etc.

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
