### ISSUE TITLE
aMember Pro - Security Problem, 8-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#337]
I emailed this on 8-11-17 at 6:59 PM

Dustin, fix this ASAP.

David

---------- Forwarded message ----------
From: aMember PRO <support@cgi-central.net>
Date: Fri, Aug 11, 2017 at 3:42 PM
Subject: aMember Pro - Security Note
To: Kay Huddleston <soccerhelpshop@gmail.com>
Dear Kay Huddleston

There is a serious security problem found in aMember Pro version 4.x.x and 5.x.x. This issue may be potentially critical and we recommend to take actions as soon as possible.
You may find more details about the problem on the Security Note post on aMember Pro website ( http://www.amember.com/p/2017/08/security-note-10/  ) 
As always, you can ask us any questions via aMember HelpDesk ( https://www.amember.com/support/ ) . 

Because of the high volume of tickets, it may take up to 48 hours to respond on this week. We are sorry for possible inconvenience.

Talk soon,
Alex Scott
Founder, CGI-Central / aMember Pro
We are sending this e-mail to you because our records shows you ordered aMember Pro and subscribed to "aMember Pro - Important Security Notes" mailing list. 
Thank you for your business!
aMember Pro Team
All-in-One Membership Solution
support@cgi-central.net

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.  I've applied the fix to all 3 Amember installations.  No reason to worry really.
