### ISSUE TITLE
New Patch Tests, Dan, 8-14-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#338]
Dustin, add below >

1.  as a new # 2 Patch test >

"Thank you for creating these patches. This is the first time I have used them and the difference in the kids with these is staggering."

-Coach Dan, Ohio, U8 soccer

2. Add below as a new # 4 Premium Test >

"I coach U8 and discovered your site a few games into the season last year. On a team with 11 players, I had 5 or 6 players that ranged from average to skilled, with the rest being either unskilled, didn't want to be there, bad attitudes, or all of the above. After finding your site I immediately started Dribble Across the Square, and implemented your defensive strategy on throw ins and goal kicks. The changes were dramatic. This summer I found out that parents were making requests to have their players put on my team."

-Dan, OH, Premium member and patch customer

**Comment by dustinschaerer** [comment]
This is completed.
