### ISSUE TITLE
Soccer Rules changes, 8-13-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#339]
Dustin, on http://www.soccerhelp.com/simplified-soccer-rules.shtml >

1. in the code, change the Keywords to >

meta name="keywords" content="Soccer rules, rules of soccer"

2. In the 1st para, the 3rd sentence is  >

There are even simplified and detailed versions of complex rules such as the "Offside Rule". 

Replace it with >

Soccer Rules are also called the Rules of Soccer and Laws of Soccer. 

So it reads >

The official soccer rules are often difficult to understand. Below are 70 simplified rules and definitions of commonly used terms such as "Hand Ball", "Linesmen" and "Obstruction". Soccer Rules are also called the Rules of Soccer and Laws of Soccer. The official rules are often modified for recreational, youth and indoor leagues. IMPORTANT - Check with your League or Club to see if they have modified the official rules. Typical modifications include field sizes, the number of players on the field, the offside rule, and at young ages whether a Goalkeeper is allowed.

**Comment by dustinschaerer** [comment]
This is completed.
