### ISSUE TITLE
Changes to  www.soccerhelp.com/soccer-drills.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#34]
Dustin, SEE the EMAIL I sent you about this on 6-11-17 at about 3:05 PM CST with this same title - it will be easier to read because you can see the colors.

Don't let this interfere with your work on moving SH to a new Server.

Dustin, on www.soccerhelp.com/soccer-drills.shtml 

About 5 paragraphs down is a Links List.

> No. 1 - the last link on the List is a link named 20 Ways to Quickly Improve Your Soccer Team

change the name of that link to   70 Soccer Coaching Tips  (it still goes to http://www.soccerhelp.com/Soccer_Tactics_Weak_Teams.shtml )

> No. 2 - add the link below >

18 Tips for U4 and U6 Soccer Coaches  that goes to http://www.soccerhelp.com/U4-U6-soccer-coaching.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
