### ISSUE TITLE
In Sept, add "Sample 10-Pack Gold/Blue Soccer Ball Patches" to the Cart, 8-13-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#341]
Dustin,

In Sept, add "Sample 10-Pack Gold/Blue Soccer Ball Patches" to the Cart, as a new Product. 

Have them show up on http://soccerhelp.com/soccershop/patch-sample-packs after >

Sample 10-Pack Green/Yellow Soccer Ball Patches

**Comment by dustinschaerer** [comment]
This is completed.
