### ISSUE TITLE
Reply from aMember about Income Report (Custom) Payments minus refunds, 8-15-17, 9-5-17, 9-7-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#343]
9-7-17 Dustin, below is the latest reply from aMember >

Dustin,
just copy reports.php to that two setups.

On Wed, 06 Sep 2017, Kay Huddleston wrote:
> Thank you for the fix!  However, we have 2 more installations of this custom report, and I need to fix those also. If you tell me what you did, I can make the changes.  Otherwise, the 2 others folders are here:
>
> http://www.soccerhelp.com/members-video/admin
>
> With these credentials: admin / ***
>
> Here is the report in question:
> http://www.soccerhelp.com/members-video/admin-reports/run/report_id/income_Custom
>
> and
>
> http://www.soccerhelp.com/members-doug/admin
>
> With these credentials: admin / ***
>
> Here is the report in question:
> http://www.soccerhelp.com/members-doug/admin-reports/run/report_id/income_Custom
>
> Thank you,
> Dustin

=============

Dustin, below is the reply from aMember >

--------

Dustin,
please allow ftp connections for our IP 93.81.244.3.

On Thu, 31 Aug 2017, Kay Huddleston wrote:
> Hello,
>
> This modification you made to our reports has stopped working, and after reviewing the files, I'm not sure what the problem is.  Could there be a specific PHP library we need to add support for on our server?
>
> Here is the exact error:
>
> Fatal error: Call to a member function getSqlExpr() on a non-object in /home/dkljj/public_html/members-video/application/configs/reports.php on line 29
>
>
> To sign in to our amember account, please sign in here.
>
> http://www.soccerhelp.com/members/admin
>
> With these credentials: admin / ***
>
> Here is the report in question:
> http://www.soccerhelp.com/members/admin-reports/run/report_id/income_Custom
>
> Thank you!
> Dustin

--
Anton Orlov
Support Specialist
MemberSoftware LLC
http://www.amember.com/

=====

I emailed this on 8-15-17 at 11:19 AM

Dustin, see the email so you can see the screen print

The Income Report (Custom) Payments minus refunds in A-member Premium, Streaming and Coach Doug is not working.  I get an error message when I try to run the report. 

This report allows me to select each subscription service so that I can separate the memberships by type and then get the payments minus refunds for that particular membership.

(In the email there is a screen print here) 

The error message says > 

Fatal error: Call to a member function getSqlExpr() on a non-object in /home/dkljj/public_html/members-video/application/configs/reports.php on line 29

**Comment by dustinschaerer** [comment]
@david-huddleston I ended up having to send a ticket in to Amember.  All of the modded files from them look fine, and I compared them against  my backups.  I sent a fullt ticket in to Amember support with the admin password so they can get in to look. 

I'll update this ticket when I hear back.

**Comment by dustinschaerer** [comment]
I checked on this today and don't have a response yet.

**Comment by dustinschaerer** [comment]
I sent over the SFTP connection information to them.  I'll check for a response tomorrow morning.

**Comment by dustinschaerer** [comment]
@david-huddleston All 3 of the Amember installations have the CUSTOM income Payment - Refunds working now!
