### ISSUE TITLE
Practice Plans - change a link, 8-16-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#346]
I emailed this on 8-16-17 at 3:04 PM

Dustin, on http://www.soccerhelp.com/soccer-practice-plans.shtml >

the 4th section is >

Tips for Your Soccer Practice Plans
Before you start, read "18 Soccer Practice Tips" and "Things You Need For A Good Practice".

Replace the link 18 Soccer Practice Tips  with 29 Soccer Practice Tips  (that goes to http://www.soccerhelp.com/soccer-practice.shtml   ) .

So it reads >

Tips for Your Soccer Practice Plans
Before you start, read "29 Soccer Practice Tips" and "Things You Need For A Good Practice".

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
