### ISSUE TITLE
Aggressive Soccer article changes, 8-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#347]
I emailed this on 8-17-17 at 12:28 PM  - use the email to see links and colors. 

Dustin, on http://www.soccerhelp.com/How_To_Play_Soccer_Aggressive_Play.shtml >

1. Make it responsive - look at it on a cell phone - it doesn't look right

2. In number 1, at the end delete >

(see "Letters From Coaches & More Soccer Formations & Soccer Positions" number 2). For example, ask several of the moms to cut stars out of gold, silver or red iron-on fabric and give them to the players who play tough. (The players can iron the stars on their jersey sleeves). Or, give out small iron-on soccer ball patches or anything you think your players might like. Most players love to earn these types of rewards.

and replace it with (the link goes to http://soccerhelp.com/soccershop/ ) >

. Many coaches give either a B for Bravery patch or a red soccer ball patch that they call a "Blood Patch". See Motivational Soccer Patches

So it reads >

1.	Teach your players that it is good to be brave, tough and aggressive. One of the most important things you can do is to encourage your players and praise them when they are brave and tough. Try to do so in a positive way, such as: "Way to hustle Mary!" or, "Win the ball Matt, you can do it!" or, "Way to fight for the ball Tommy!" One idea that SoccerHelp subscribers have had good luck with is to give rewards for tough, brave play. Many coaches give either a B for Bravery patch or a red soccer ball patch that they call a "Blood Patch". See Motivational Soccer Patches 

3. In number 2, delete the last 2 sentences but leave the link.

Delete >

This will help teach players to do their best and that winning is fun. We believe it is important to teach players to "do their very best and give it their all", and that although we don't like to lose, it's okay to lose if we've done our very best, and we're good sports whether we win or lose.

So it reads >

SoccerHelp Premium Practice Games Teach Hustling, Aggressive Play, Winning The Ball and the Desire To Win. SoccerHelp Premium Practice Games involve competition, pressure and winning and losing. Our Practice Games teach hustling, aggressive play, winning the ball and the desire to win. Players learn they must hustle and play hard or they will lose. In these respects, SoccerHelp Practice Games simulate real "match" conditions and encourage players to hustle and perform soccer activities under pressure at "game speed". Click here to try 10 free SoccerHelp Practice Games

4. In Number 3, at the end, make SoccerHelp Premium a link to  http://www.soccerhelp.com/New_Articles_On_Soccerhelp_Premium.shtml 

So it reads>
We strongly recommend teaching Coaching Rule No. 3 from "22 Coaching Rules". It teaches your players how to position themselves to defend and win the ball on your opponent's throw-ins, goal kicks and punts. How to teach this is described in section 2 of the "Quick Team Improvement Program", in Soccerhelp Premium

5. In number 4, do 3 things >

- in the first sentence, delete (Premium version) and replace  Dribble Across A Square Game  with  Dribble Across a Square No Lines Drill   (have the  link go to http://www.soccerhelp.com/soccer_drills/Dribble.shtml 

- and delete the last sentence, which is > See "How To Teach Soccer Dribbling" for more ideas and games that teach dribbling.

So it reads >

We also strongly recommend you play the "Dribble Across a Square No Lines Drill" 3 times to start each practice and ask each player his or her score at the end of each game. This will let you monitor each player's progress. This is the single best game you can play. I promise you that your players will develop outstanding dribbling skills and exceptional "field vision" and "field awareness" if you play this game a lot. It isn't the most fun game, and your players may complain a little, but it is worth it. As your players see that the game is causing them to improve, they won't complain about it. You will see dramatic improvement after 4 or 5 practices. Being able to dribble and shield the ball is critical. Your players will have a lot more confidence and will play with more enthusiasm if they know they can dribble and protect the ball. One of the great things about the "Dribble Across A Square Game" is that it is "self-teaching" and playing the game teaches players how to "control dribble", "speed dribble", "shield the ball" and turn. 

6. Replace number 5 with (the link goes to  http://www.soccerhelp.com/strength-on-ball-report.shtml  AND put the Tests in a Block Quote ) >

Play the Aggressive Play and Bravery Game until your players are used to contact Aggressive Play & Bravery Drill

"My team went undefeated this Fall, 7 - 0, scoring 40 goals to opponents 4. My girls knocked off a U10 boys rec team in a scrimmage that were undefeated. The coach said he had never seen girls play that aggressive." Derik, U10G, Premium subscriber
"This Game made an immediate improvement on my boys on how to fight for a ball." Coach Chuck, U10B
"The Shoulder Tackling game is working beyond belief. Some of my timid girls are now amongst the toughest on the team." Mark, U1OG
"The other team was bigger and trying to play very aggressively against us, but we have been playing the Strength on the Ball game since the beginning of the season, and, although they really tried, the other team could not push my boys around." Coach Stephanie, U10
"The "Shoulder Tackle & Strength on the Ball" drill has HUGE benefits. It paid off this past weekend when we played a team from another league. Their girls were very aggressive until we got on their shoulders and then they generally went to pieces and we took away the ball." Coach Tony, U16G, Premium Member for 6 years

7. Near the end, Delete >

Subscriptions to SoccerHelp Premium support the continued improvement of SoccerHelp. Premium is "The Next Step" and contains over 800 pages of additional material that is not on SoccerHelp Basic. Click here to view a copy of the Premium Home Page

**Comment by dustinschaerer** [comment]
This is completed.

**Comment by dustinschaerer** [comment]
This is completed again after making these other changes.
