### ISSUE TITLE
Change a word - Aggressive Soccer article, 8-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#348]
Dustin, on http://www.soccerhelp.com/How_To_Play_Soccer_Aggressive_Play.shtml >

In the 1st para, the 5th sentence is >

It is critical that your defenders be tough and not afraid of contact

Replace that sentence with >

It is critical that your defenders are Brave and not afraid of contact - Bravery is an effective motivational word because all kids want to be Brave, and you can motivate Bravery.

**Comment by dustinschaerer** [comment]
@david-huddleston This is working correctly now. Sorry for the confusion, it was missing the meta viewport declaration.

**Comment by dustinschaerer** [comment]
> In the 1st para, the 5th sentence is >
It is critical that your defenders be tough and not afraid of contact

I have replaced that sentence.
