### ISSUE TITLE
Change Shopping Cart and aMember to https, 9-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#349]
I forwarded the email from Google on 8-17-17 at 6:08 PM

Dustin, what do you think about what I pasted below from Google? Let me know.

In **November**, I want to change SoccerHelp over to https

It is pasted below >

Google Search Console

Chrome will show security warnings on http://www.soccerhelp.com
To owner of http://www.soccerhelp.com, 
Starting October 2017, Chrome (version 62) will show a “NOT SECURE” warning when users enter text in a form on an HTTP page, and for all HTTP pages in Incognito mode. 
The following URLs on your site include text input fields (such as < input type="text" > or < input type="email" >) that will trigger the new Chrome warning. Review these examples to see where these warnings will appear, so that you can take action to help protect users’ data. This list is not exhaustive. 
http://www.soccerhelp.com/ 
The new warning is part of a long term plan to mark all pages served over HTTP as “not secure”. 

Here’s how to fix this problem:

Migrate to HTTPS
To prevent the “Not Secure” notification from appearing when Chrome users visit your site, only collect user input data on pages served using HTTPS.

**Comment by david-huddleston** [comment]
Dustin, we talked about this - just focus on the Shopping Cart and aMember for this.

David

**Comment by dustinschaerer** [comment]
- [x] Amember
- [x] Amember - Doug
- [x] Amember - Videos
- [x] Shopping Cart

Forcing HTTPS doesn't really matter for the login pages, we just want people to get there via HTTPS.  It was easy enough to change the links in to the login amember pages, and that should be sufficient.

We will want the entire shopping cart to FORCE SSL though.

**Comment by dustinschaerer** [comment]
Switching over some hard coded links to the shopping cart to be https://www style links now.

**Comment by dustinschaerer** [comment]
@david-huddleston I guess I should also update the links in the sitemaps, eh?

**Comment by david-huddleston** [comment]
Yes

**Comment by dustinschaerer** [comment]
Sitemaps also cleaned!

This is completed.
