### ISSUE TITLE
Priority - 404 Errors Report Increase - Google Search Console

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#35]
Dustin, 

Check this out to see which URL's they can't find - could this be due to changes you made? Of is it due to deleting the sub-domain?

I got an email from Google Search Console that says >

"Googlebot identified a significant increase in the number of URLs on http://www.soccerhelp.com/ that return a 404 (not found) error. This can be a sign of an outage or misconfiguration, which would be a bad user experience. This will result in Google dropping those URLs from the search results. If these URLs don't exist at all, no action is necessary.

**Comment by dustinschaerer** [comment]
@david-huddleston - No need to worry, its the errors from pages we don't them to have indexed, many where spam pages.  I'm taking care of this now.
