### ISSUE TITLE
Soccer Drills - add a new test, 8-22-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#352]
Dustin, add a new test on http://www.soccerhelp.com/soccer-drills.shtml >

Add below as the 3rd test in the block quote >

"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

**Comment by dustinschaerer** [comment]
@david-huddleston  This is completed.
