### ISSUE TITLE
Soccer Drills page - replace the blurb for Go Score game, 8-22-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#353]
I emailed this on 8-22-17 at 6:43 PM 

Dustin, on http://www.soccerhelp.com/soccer-drills.shtml >

The blurb for the Go Score game is wrong.

It says >

U8 & up, Rec & Select. Definitely try this This teaches Aggressive Receiving, passing while running, speed dribbling, turning, the importance of first-touch, one-touch control, and teaches receivers to move to the ball and how to receive the ball at game speed. You will see fast results, set-up is easy and every player is either a dribbler/passer or a receiver. This will teach your players to play faster. Watch the Video.

It should say >

U4 to U10 Rec. A simple, fun game for U4 & U6 and beginners up to U10. Every player has a ball and easy set-up. Teaches dribbling and kicking the ball with both feet while looking up, getting used to chaos, dribbling in a crowd and being bumped, how to kick a soccer ball. Watch the Video.

**Comment by dustinschaerer** [comment]
This is completed.
