### ISSUE TITLE
"Forgot Password" link isn't working for all 3 aMembers, 8-24-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#354]
Dustin, the Forgot Password link isn't working for all 3 aMembers >

Premium at http://www.soccerhelp.com/members/login 

Doug  at http://www.soccerhelp.com/members-doug/login 

Streaming Video  at http://www.soccerhelp.com/members-video/login

**Comment by dustinschaerer** [comment]
@david-huddleston This is all completed!
