### ISSUE TITLE
The Top "Forgot Password" link on Coach Doug goes to Premium, 8-25-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#356]
Dustin, The Top "Forgot Password" link on Coach Doug goes to Premium - the Bottom link goes to Coach Doug.

The destination of the top link needs to be changed to go to the Coach Doug page, like the bottom link does.

**Comment by dustinschaerer** [comment]
@david-huddleston Sorry about that, it's fixed.
