### ISSUE TITLE
For Sept, New Premium Test, Dan, 8-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#357]
Dustin, add below as the 4th Premium Test > 

"First game today. Our boys simply dominated start to finish. Every one of our opponents throw-ins resulted in a turnover, the ball was on their half 80%+, and the other team had zero shots. Not just shots on goal, I mean ZERO shots. I called off the dogs when we went up 4-0 early in the 3rd quarter. Thank you for your help and guidance."
-Dan, U8 Rec, assigned players, OH, Premium member & patch customer

**Comment by dustinschaerer** [comment]
This is added.
