### ISSUE TITLE
5th version - Premium "Start Here" Page - 14 Changes, 8-27-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#358]
I emailed this on 8-27-17 at 7:08 PM - use the email to see colors and bold and because the GitHub changed the numbering .

Delete the 4 prior versions I sent on 8-26-17 at 9:20 PM and on 8-27-17 at 11:28 AM , 3:34 PM and 4:51 PM

Dustin, 

No. 1 - On Premium Home, near the top in the 2nd row of links, the 4th link is >  Score More Goals

Replace it with >

Start Here 

That goes to >  http://www.soccerhelp.com/premium/Start-Here.shtml  

DUSTIN, the changes listed below are all to >  on http://www.soccerhelp.com/premium/Start-Here.shtml

No. 2 - Replace the 2nd line of the Title with (use about a size 14 font - bold black) >

And the 12 Most Important Coaching Tips 

So the Title reads >

How To Navigate SoccerHelp Premium
And the 12 Most Important Coaching Tips

No. 3 - The first # 6 is >

Sign Up for the Premium Newsletter - It has weekly tips with links to Premium articles - it will add value to your subscription. Sign up at www.soccerhelp.com/free_reports_and_newsletter_signup.shtml or there is a link on the Premium Home Page

Replace it with the new para below (do NOT bold the link) > 

6. Below are the 12 Most Important Coaching Tips - If you coach U8 or older, DEFINITELY teach Coaching Rule No. 3 (# 7 below)  - it is worth 2 goals per game and can let your team control the game. And read # 9 - it can make a HUGE difference in how your team plays.

No. 4 - Below the number 6 above, is >

If you are a new coach start at BASIC INFORMATION & TIPS FOR BEGINNING COACHES AND HOW TO COACH AGES 5 & 6 AND 7 & 8.

4(a). Remove all the Bold so it reads >

If you are a new coach start at BASIC INFORMATION & TIPS FOR BEGINNING COACHES AND HOW TO COACH AGES 5 & 6 AND 7 & 8.

4(b). Move it so it is the number 1 tip in the list of 9 Tips (above the current no. 1 tip that starts "Don't Force U6 or U8 to Pass in Games"), like > 

1. If you are a new coach start at BASIC INFORMATION & TIPS FOR BEGINNING COACHES AND HOW TO COACH AGES 5 & 6 AND 7 & 8.

No. 5 -   Delete the para >

If you aren't sure what to teach, click Most Important (in the center of the top Yellow Bar) which goes to "Most Important Things For A Rec Soccer Coach To Teach and For New Coaches To Read".

No. 6 - Make the test below a Block Quote >

"Thank you for the amazing fundamentals that my daughter and her teammates have been taught. 5 of those girls (my daughter included) are Freshmen starting on their VARSITY high school soccer team." Coach Aaron, OH, Premium subscriber for 6 years

No. 7 - on http://www.soccerhelp.com/premium/Start-Here.shtml , replace

I've pasted some Tips Below.

With>

Read the 12 Tips Below - They Will Help You

No. 8 - on http://www.soccerhelp.com/premium/Start-Here.shtml , Just below >

Read the 12 Tips Below - They Will Help You

Add the following (including the last line, "9 Coaching Tips are Below " >, as shown below) >

You will get the best and fastest success if you do 3 things >

1. Use SoccerHelp No Lines Drills that are Practice Games to teach skills and train players to be able to play fast while under pressure. Your players will improve twice as fast and play better.

2. Motivate your players to Hustle, give 100% effort, be Brave (win the ball and not afraid of contact), and attend every practice (this is critical for most teams). We sell motivational iron-on soccer patches that really motivate players. You can see them at www.soccerhelp.com/soccershop   There are 400 Testimonials from coaches at www.soccerhelp.com/soccershop/soccer-patches-reviews-testimonials  Coach Dan said - "Thank you for creating these patches. This is the first time I have used them and the difference in the kids with these is staggering."

3. For U8 & older - Coaching Rule No. 3 (# 7 below) will make a big difference and is easy to teach. There is a video. AND, read the article at www.soccerhelp.com/premium/Formations-Tips-Rec.shtml#case_study about the best way to teach players positions and how to Shift & Sag - this can make a HUGE difference.

10 Coaching Tips are Below 

 No. 9 - In the list of Tips, there are 9 links that start with http:// (like  http://www.soccerhelp.com/premium/bunching-up-10-ways.shtml  ) . Delete the http://  AND unbold the links, so they are like >

www.soccerhelp.com/premium/bunching-up-10-ways.shtml

No. 10 - In the number 2 Tip, Add at the first >  

For U6 -

AND remove the underlines in the rest of the para AND delete 3 things > "or U8", "and U8", and "and U8"

So it reads >

2. For U6 - Don't Force U6 to Pass in Games - it is okay for U6 to dribble to goal and score (USYSA recommends this approach and Doug and I agree) But DO teach your players to NOT Bunch Up - If U6 pass in a game, great, but don't force it or pressure them to pass in games because some kid's brains aren't ready to make the decision of when to dribble and when to pass and they will get confused and always try to pass instead of dribbling, even if they could score. Dribbling is the most critical skill and if your kids become confident on the ball they will become good players. Explain this approach to the Parents and tell Parents to NOT yell "Pass" during games and to not pressure their kids to pass. You can start to emphasize passing in games more at U9 and U10. You should, of course, teach them not to Bunch Up - there are some great tips about that at www.soccerhelp.com/premium/bunching-up-10-ways.shtml

No. 11 - Re-number the other tips below it so there are 9 Coaching Tips. 

No. 12 - Number 9 is >

9. U8 and older - If you want to read about how to assign & teach Positions, and how to choose & teach the best Formation for your team, start with www.soccerhelp.com/premium/Formations-Tips-Rec.shtml

Replace it with  >

9. U8 and older - Read how to teach positions and how to teach your players Shift & Sag at www.soccerhelp.com/premium/Formations-Tips-Rec.shtml#case_study . This can make a HUGE difference in how your team plays - a U12 coach used this approach to turn his losing team into a tournament-winner. For more about how to assign and teach Positions, and how to choose and teach the best Formation for your team, read www.soccerhelp.com/premium/Formations-Tips-Rec.shtml

No. 13 - Add a number 10 >

10. All ages - Think About How to Motivate Your Players So It Is More Fun and to Get Better Results - For example, Coach Dan coaches U8 boys and none of them wanted to play "defense". So, he renamed "defense" and started calling it "The Wrecking Crew". He says that has worked great and that all his players now want to be on The Wrecking Crew. There are lots of motivational ideas at www.soccerhelp.com/Motivational-Plan-Players-Students.shtml 

No. 14 - If you can, turn all the Tests into Block Quotes

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.

**Comment by david-huddleston** [comment]
Great job - that was complicated.
