### ISSUE TITLE
Premium Most Important - delete 3 sets of Links to DVDs (6 links), 8-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#359]
I emailed this on 8-26-17 at 8:42 PM

Dustin, on http://www.soccerhelp.com/premium/Expanded_Most_Important.shtml , delete the following >

After D.1. >

Read a review of SoccerHelp Foot Skills and Soccer Moves Training Program (Motor Memory Training and Aerobic Workout) DVD
Click here to read a review of the "Super Soccer Skills" video

After D.3 >

Click here to read a review of the "Soccer Success One On One Coaching DVD"
Click here to read a review of the "Just Kickin' It" video

After  D. 7 > 

Click here to read a review of the "Soccer Success One On One Coaching DVD"
Click here to read a review of the "Just Kickin' It" video

**Comment by dustinschaerer** [comment]
This is completed.
