### ISSUE TITLE
Premium Home Page changes, 8-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#360]
Dustin, delete the prior versions that I sent on 8-26-17 at 8:42 PM and 8:53 PM

-------------

Dustin, on Premium Home, 

1. near the top, delete the link to Facebook  >

For Soccer Coaching Tips, Like Us on Facebook at Soccer Drills and Games

2. Near the top delete >

Motivational Iron-on Patches for Soccer, Baseball, Basketball, Softball, Volleyball, Swimming, Students, Churches, Band, Choir, Hockey, Clubs, Flag Football, Martial Arts, Cheer, Dance, Gymnastics, Lacrosse, Skating, Camps, etc. THESE REALLY WORK. 

3. Near the top delete >

The Latest Articles are at New Articles

4. Under "Newsletter" (which is below the Bars and above "Dictionary Search"), delete the link >

•	Free Weekly Coaching Tips for Premium Members

**Comment by dustinschaerer** [comment]
This is completed.
