### ISSUE TITLE
Premium "Start Here" page - fix a link, 8-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#364]
Dustin, 

on  http://www.soccerhelp.com/premium/Start-Here.shtml  You missed one link >

 www.soccerhelp.com/premium/Formations_And_Tips_8v8.shtml#38 

Below is completed -------

I emailed this on 8-28-17 at 4:58 PM - use the email - it shows an underline. 

Dustin, on  http://www.soccerhelp.com/premium/Start-Here.shtml  >

First - In the sub-title "You will get the best and fastest success if you do 3 things:" , change the 3 to a 4, so it reads

You will get the best and fastest success if you do 4 things:

Second - add a new number 4 after number 3 in the sub-section titled "You will get the best and fastest success if you do 4 things:" >

4. For U8 & older - Choose a Formation and Style of Play that fits your players - don't make them play a Formation and Style of Play that dooms them to failure. Your Formation and Style of Play can make a HUGE difference in the success of your team. The best Formation and Style of Play is the one that gives your team the best chance to be successful and that depends on the strengths, weaknesses and skill level of your players, and how many "weak links" you have. A Rec team usually can't play like a Travel team because Rec teams don't practice as much and usually have some unskilled, slow, unathletic, unmotivated and timid players. Most Rec teams need a Formation with more "depth" than Travel teams and good Travel teams usually need more "width" than Rec teams. How to evaluate your team and choose the best Formation and Style of Play is at www.soccerhelp.com/premium/Formations-Tips-Rec.shtml  and www.soccerhelp.com/premium/How_To_Choose_A_Formation.shtml  . The term "Style of Play" means how you attack and defend. For Rec teams, a big question is how far to Push Up Fullbacks when you are attacking and how much of a Possession Style of Play is realistic. Rec teams are often better off to "Defend Deep" instead of "Pushing Up" on attack (see www.soccerhelp.com/premium/Should_You_Push_Up.shtml ). There is a great letter from a U12 coach at www.soccerhelp.com/premium/Formations_And_Tips_8v8.shtml#38  whose Rec team didn't win a game for 3 seasons because the coach used a formation that his team couldn't successfully play - he changed and they started playing better and were much happier. There are over 100 articles about Formations at www.soccerhelp.com/premium/Formations_Index.shtml . If you coach U6, don't worry about formations or Styles of Play.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.

**Comment by dustinschaerer** [comment]
@david-huddleston My bad,it's there now: http://www.soccerhelp.com/premium/Start-Here.shtml
