### ISSUE TITLE
Premium "New Articles" - add a new article, 8-28-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#365]
Dustin, on http://www.soccerhelp.com/premium/newsletter_archive/soccer_archive.shtml , 

add as the first new article (above "How to Get the Best Results and Fastest Skills Improvement at Practice" >

**READ THIS** - The 12 Most Important Coaching Tips and How to Navigate Premium www.soccerhelp.com/premium/Start-Here.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
