### ISSUE TITLE
Premium Drills Lists - add a Link to Aggressive receiving, 8-29-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#366]
I emailed this on 8-29-17 at  2:12 PM  - use the email to see colors.

Dustin, add the link & text below in alphabetical order to the following 5 lists >

- http://www.soccerhelp.com/premium/Alphabetical_Practice_Games.shtml 

- http://www.soccerhelp.com/premium/U-8_Practice_Games.shtml 

- http://www.soccerhelp.com/premium/U-10_Practice_Games.shtml 

- http://www.soccerhelp.com/premium/U-12_Practice_Games.shtml 

- http://www.soccerhelp.com/premium/U-14_Practice_Games.shtml 

The link goes to http://www.soccerhelp.com/premium/practice_games/Dribble_Around_Cone_Pass.shtml 

BELOW IS the link and text (don't bold anything)  >

Aggressive Receiving  (definitely play this)
(This teaches 9 important things - Aggressive Receiving, passing while running, to pass ASAP instead of holding the ball too long, accuracy on passes while playing fast and under pressure, and more. U8 and older)

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.  I only bolded the link to the game so it would match up with the current formatting on those pages.
