### ISSUE TITLE
Put File System folders in DropBox, 9-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#367]
1. SH Web Folder

2. check to be sure we have the Videos in DropBox

3. Put a one-time snapshot of data

**Comment by dustinschaerer** [comment]
- [x] Add public folder to dropbox backups
- [x] Add dkljj user folder to dropbox backups
- [x] Snapshot all DB backups to Dropbox

**Comment by dustinschaerer** [comment]
@david-huddleston We have the videos you shot backed up in Dropbox, but not the video clips we have up there. Do you want me to pull those down from youtube and also back them up?

**Comment by david-huddleston** [comment]
Yes

**Comment by dustinschaerer** [comment]
@david-huddleston This is also ALL completed!
