### ISSUE TITLE
Soccer Drills page, new test for "Defense Tips" Block Quote, 9-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#368]
I emailed this on 9-1-17 at 1:13 PM - use the email

Dustin, on  http://www.soccerhelp.com/soccer-drills.shtml , under 

Defense Tips Worth 2 Goals Per Game

Add below as the 3rd test >

"Every one of our opponents throw-ins resulted in a turnover, the ball was on their half 80%+, and the other team had zero shots." Dan, U8 Rec, OH, Premium member

AND add at the end of the Bob test > PA, Premium member

AND add at the end of the Tony test > GA, Premium member

So the Tests read >

"Coaching Rule No. 1 really is worth a couple goals a game." Bob, U10, PA, Premium member

"For about 2 weeks, we worked on nothing other than Coaching Rules 1 - 3. We won our next 5 games scoring 20 goals and giving up none." Tony, U16, GA, Premium member

"Every one of our opponents throw-ins resulted in a turnover, the ball was on their half 80%+, and the other team had zero shots." Dan, U8 Rec, OH, Premium member

**Comment by dustinschaerer** [comment]
This is completed.
