### ISSUE TITLE
Coaching Rules page on Basic - 4 changes to the Tests, 9-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#369]
Dustin, on http://www.soccerhelp.com/22-coaching-rules-report.shtml 

- First, Put the Tests in a Block quote

- Second, at the end of the 2nd test, delete " since 2004"

- Third, Replace the 4th test with >

"I taught my players Coaching Rule No. 3 from Premium and the results were immediately phenomenal! They stole several balls and it completely changed the flow of the game during several long stretches." Charlie, U10, Premium Member

- Fourth, add a new 5th test >

"Every one of our opponents throw-ins resulted in a turnover, the ball was on their half 80%+, and the other team had zero shots." Dan, U8 Rec, OH, Premium member

**Comment by dustinschaerer** [comment]
This is completed and checked.
