### ISSUE TITLE
Priority - changes to  www.soccerhelp.com/Soccer_Certificate_Award_Roster.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#37]
Dustin, Thanks for pointing this out. 

I sent you an email of this at about 1:30 CST on 6-12-17

The links in the article are out-of-date - I updated them below >

on http://www.soccerhelp.com/Soccer_Certificate_Award_Roster.shtml  

Replace the third paragraph that starts "I downloaded" with >

I downloaded, edited and printed 2 free Certificates from Microsoft and didn't have any problems, and I trust Microsoft. My favorite free editable Award Certificate is https://templates.office.com/en-us/Most-Improved-Player-certificate-editable-title-TM04040165 . I like it because it allows you to change the certificate Title (you can change "Most Improved Player" to whatever you want it to say by highlighting it and typing what you want it to say - like "Best Team Spirit" or "Great Defender Award"), and you can also  fill in the Player's Name, the Team Name, who Presented it, the Date, AND you can customize the font color by highlighting the text and changing the font color. There are more choices at https://templates.office.com/en-us/Certificates - some are in Word but most are in PowerPoint.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed, I also took a minute to make the code W3 valid and responsive.
http://www.soccerhelp.com/Soccer_Certificate_Award_Roster.shtml
