### ISSUE TITLE
Premium "Most Important" page - 3 changes. 9-1-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#370]
I emailed this on 9-1-17 at 2:14 PM - use  the email to see colors and links

Dustin, on http://www.soccerhelp.com/premium/Expanded_Most_Important.shtml

First -  In the Title remove the word "Rec", AND delete the 2nd line, so it looks like 

Most Important Things For A Soccer Coach To Teach

Second - at the top, just below the title, add (Centered but NOT bold) >

FIRST READ The 12 Most Important Coaching Tips

(Dustin, the link goes to http://www.soccerhelp.com/premium/Start-Here.shtml 

SO the top looks like (leave a separator line between each ) >

Most Important Things For A Soccer Coach To Teach

FIRST READ The 12 Most Important Coaching Tips

(The information below is for coaches of players age 7 and older. If you coach U-4 or U-6, see Soccer Coaching Tips and Basic Information for New Soccer Coaches and How to Coach Ages 5&6 and 7&8 and Soccer Coaching, Ages 2, 3, 4, 5 .)

Third -  while you are there, unbold the Red Links down thru B (about the first 4 paras) BUT leave them underlined

**Comment by dustinschaerer** [comment]
@david-huddleston  The links on Premium are a mix of CSS bold and also hard coding.  Simply pulling off the bold tags in the links isn't enough for links on this page, I'll also have to undo the CSS stylings.  Do you want me to try it out for this page and see how much work it is to finish up this one page?
I'd guess it's about 15 minutes.

**Comment by david-huddleston** [comment]
All the links don't have to be changed - just the top of the page. 

 

Change the CSS and see what that does. If that doesn't change the first 4 paras, then go ahead and only the bold tags off the Red Links in the first 4 paras (down thru "B")

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
