### ISSUE TITLE
Move the No. 7. 10 and 16 patch tests, 9-2-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#372]
Dustin, on

- Move the # 7 patch  test to be # 4 > 

"I HAVE NEVER SEEN A BIGGER MOTIVATIONAL RESOURCE THAN THE PATCHES!."

--AB, TN

- And move the # 10 patch test to be # 5 >

"The motivational patches arrived in time for the first game and you would have thought I was passing out $100 bills. The difference in everyone's play since we started with the patches is amazing."

    --Coach Michael, FL

- And move the # 16 patch test to be # 6 >

"My girls absolutely LOVE the patches. We started with them in 1st grade, they are now 4th graders playing competitively, and the biggest thrill is still "what patches did we earn Coach?".

--Coach Angie, NJ

**Comment by dustinschaerer** [comment]
This is completed.
