### ISSUE TITLE
Soccer Formations article - add a sentence, 9-2-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#374]
I emailed this on 9-2-17 at  1:12 PM - use the email so you can see the link. 

Dustin, on http://www.soccerhelp.com/soccer-formations.shtml 

Add a new 4th para >

For Basics see Soccer Formations Basics and Soccer Positions Basics & Kick-Offs  

(Dustin - Soccer Formations Basics goes to > http://www.soccerhelp.com/Soccer_Formation_Basics.shtml 

Soccer Positions Basics & Kick-Offs  goes to > http://www.soccerhelp.com/Soccer_Positions_Basics.shtml

**Comment by dustinschaerer** [comment]
This is completed.
