### ISSUE TITLE
October - Run Traffic reports for Sept. for BIR-2 server, 9-3-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#375]

**Comment by dustinschaerer** [comment]
@david-huddleston I've went to check on these stats yesterday and couldn't find any data collected on the server.  I've been researching this and think I have it all properly configured, and it is now running the stats processing, which should take awhile, as it's a background process on the server.

**Comment by dustinschaerer** [comment]
@david-huddleston I'm working on this today.  I have to rewrite a good portion of the stats collecting program because our server's vhost configuration is different than it was on Plesk.

I'll be in touch later about this.

**Comment by dustinschaerer** [comment]
@david-huddleston I should be able to finish this up tomorrow.  I ended up having to rewrite most of the stats collecting program.

**Comment by dustinschaerer** [comment]
@david-huddleston I've been trying to get this project finished up, but it seems like its one step forward and two steps back.  There are somehow quite a few sites that don't have the same folder structure / files as the other sites, and I'm having to jump through hoops to accommodate for it.  I've been trying to automate the process of setting up the stats gathering stuff, but I'm not quite there yet.  

I'll give you a call tomorrow (Thursday) to discuss the progress.

**Comment by dustinschaerer** [comment]
@david-huddleston Here you go!  I got the stats collecting program dialed in.

bir-2.com Domain Traffic Report - September 2017

Domain  -  Unique Visitors  -- Pages

6yearoldsoccerdrills.com/  - 342 -- 393
academicpatches.com/  - 318 -- 409
accidentattorneymurfreesboro.com/  - 293 -- 368
accidentattorneynashville.net/  - 301 -- 403
accidentattorneypanamacity.com/  - 241 -- 283
accidentattorneysmurfreesboro.com/  - 217 -- 303
accidentattorneysnashville.com/  - 267 -- 347
accidentlawyermurfreesboro.com/  - 281 -- 342
accidentlawyernashville.com/  - 336 -- 403
accidentlawyerpanamacity.com/  - 173 -- 205
accidentlawyersmurfreesboro.com/  - 263 -- 323
accidentlawyersnashville.com/  - 324 -- 422
aggressivereceivingsoccer.com/  - 405 -- 725
allsoccerdrills.com/  - 285 -- 349
applemanandtrucks.com/  - 239 -- 294
applemanandtruckslaw.com/  - 252 -- 296
applemanandtruckslawoffices.com/  - 200 -- 232
applemantrucks.com/  - 248 -- 273
applemantrucksdisabilitylaw.com/  - 265 -- 295
applemantruckslaw.com/  - 232 -- 254
applemantruckslawoffices.com/  - 230 -- 274
applemantruckssocialsecuritylaw.com/  - 241 -- 262
aptitudeassessmenttesting.com/  - 385 -- 425
arrestedpanamacity.com/  - 174 -- 214
arrestedpanamacitybeach.com/  - 255 -- 286
attorneyjkarltrucks.com/  - 186 -- 220
attorneykarltrucks.com/  - 224 -- 275
autoaccidentattorneymurfreesboro.com/  - 279 -- 345
autoaccidentattorneynashville.com/  - 299 -- 398
autoaccidentattorneypanamacity.com/  - 229 -- 271
autoaccidentattorneysnashville.com/  - 300 -- 398
autoaccidentlawyermurfreesboro.com/  - 225 -- 312
autoaccidentlawyernashville.net/  - 248 -- 345
autoaccidentlawyersnashville.com/  - 405 -- 495
autoinjurylawyernashville.com/  - 316 -- 432
bandrewards.net/  - 248 -- 295
baseballincentive.com/  - 273 -- 320
baseballincentivepatches.com/  - 285 -- 383
baseballincentives.com/  - 331 -- 400
baseballincentives.net/  - 274 -- 328
baseballmotivation.com/  - 922 -- 1058
baseballrewards.net/  - 344 -- 372
basketballincentivepatches.com/  - 262 -- 339
basketballincentives.com/  - 309 -- 340
basketballmotivation.com/  - 393 -- 482
basketballpatch.com/  - 323 -- 363
basketballpatches.com/  - 330 -- 403
basketballpatches.net/  - 478 -- 828
basketballpatches.org/  - 263 -- 319
basketballreward.net/  - 245 -- 295
beginnersoccerdrills.com/  - 325 -- 359
behaviorrewards.org/  - 414 -- 511
bestaccidentlawyernashville.com/  - 232 -- 318
bestaccidentlawyerpanamacity.com/  - 145 -- 160
bestaccidentlawyersnashville.com/  - 266 -- 339
bestdisabilitylawyernashville.com/  - 250 -- 308
bestdisabilitylawyerpanamacity.com/  - 176 -- 186
bestinjurylawyernashville.com/  - 358 -- 467
bestinjurylawyersnashville.com/  - 272 -- 357
bestsocialsecuritylawyernashville.com/  - 271 -- 344
bestsocialsecuritylawyerpanamacity.com/  - 167 -- 178
bir-2.com/  - 197 -- 256
braverypatch.com/  - 228 -- 258
caraccidentattorneymurfreesboro.com/  - 321 -- 381
caraccidentattorneynashville.com/  - 437 -- 673
caraccidentattorneysnashville.com/  - 297 -- 396
caraccidentlawyermurfreesboro.com/  - 254 -- 306
caraccidentlawyernashville.com/  - 281 -- 386
caraccidentlawyersnashville.com/  - 242 -- 318
caraccidentlawyerspanamacity.com/  - 177 -- 192
careerscopeonline.com/  - 570 -- 646
careerscopeonline.net/  - 270 -- 314
careerscopeonline.org/  - 205 -- 248
carinjurylawyernashville.com/  - 256 -- 360
carinjurylawyerpanamacity.com/  - 257 -- 313
carwrecklawyernashville.com/  - 291 -- 374
cheerleadermotivation.com/  - 319 -- 381
classroombehavior.net/  - 312 -- 391
coachdougsoccer.net/  - 232 -- 262
coachdougsoccer.org/  - 289 -- 333
communitycorrectionsassessment.com/  - 265 -- 311
criminalattorneypanamacity.com/  - 241 -- 267
criminaldefenseattorneypanamacity.com/  - 232 -- 293
criminaldefenselawyerpanamacity.com/  - 213 -- 251
criminaldefenselawyerpanamacitybeach.com/  - 169 -- 220
criminallawyerpanamacity.com/  - 176 -- 190
dancepatches.net/  - 206 -- 265
dancerewards.com/  - 298 -- 349
defenseattorneypanamacity.com/  - 205 -- 263
defenseattorneypanamacitybeach.com/  - 213 -- 241
defenselawyerpanamacity.com/  - 179 -- 205
defenselawyerpanamacitybeach.com/  - 164 -- 201
defensepatch.com/  - 262 -- 323
denieddisabilitypanamacity.com/  - 215 -- 269
deniedsocialsecuritypanamacity.com/  - 182 -- 233
disabilityappeallawyerspanamacityflorida.com/  - 222 -- 271
disabilityassistancenashville.com/  - 304 -- 427
disabilityassistancepanamacity.com/  - 189 -- 231
disabilityattorneymurfreesboro.com/  - 254 -- 336
disabilityattorneynashville.com/  - 297 -- 394
disabilityattorneynashville.net/  - 260 -- 357
disabilityattorneypanamacity.com/  - 204 -- 239
disabilityattorneysinpanamacityfl.com/  - 204 -- 252
disabilityattorneysnashville.com/  - 265 -- 385
disabilityattorneysnashville.net/  - 240 -- 312
disabilityhelppanamacity.com/  - 178 -- 243
disabilitylawapplemantrucks.com/  - 229 -- 266
disabilitylawyermurfreesboro.com/  - 206 -- 308
disabilitylawyernashville.com/  - 367 -- 487
disabilitylawyernashville.net/  - 249 -- 338
disabilitylawyersinpanamacityfl.com/  - 201 -- 315
disabilitylawyersnashville.com/  - 328 -- 460
disabilitylawyersnashville.net/  - 302 -- 380
dribbleacrossasquare.com/  - 348 -- 408
dribbleacrossasquaresoccergame.com/  - 272 -- 301
dribblearoundcone.com/  - 253 -- 311
dribblearoundconeandpassrelayrace.com/  - 319 -- 358
dribblearoundconesoccergame.com/  - 232 -- 264
drugattorneypanamacity.com/  - 174 -- 202
druglawyerspanamacity.com/  - 158 -- 189
duiattorneypanamacity.com/  - 249 -- 276
duiattorneyspanamacity.com/  - 217 -- 257
duilawyerpanamacity.com/  - 321 -- 379
footballincentive.com/  - 248 -- 284
footballincentives.net/  - 301 -- 349
footballrewards.net/  - 336 -- 394
funbasketballdrills.com/  - 215 -- 243
funbasketballdrills.net/  - 347 -- 654
gradesincentives.com/  - 302 -- 406
gradesrewards.com/  - 210 -- 251
happyfacepatch.net/  - 235 -- 262
highschoolsoccerdrills.com/  - 430 -- 741
hitthecoach.com/  - 225 -- 276
hitthecoachsoccergame.com/  - 230 -- 283
hockeyincentives.com/  - 266 -- 308
hockeyreward.com/  - 320 -- 352
hockeyrewards.com/  - 270 -- 331
injuredcaraccidentpanamacityattorney.com/  - 205 -- 234
injuredtruckwreckpanamacityattorney.com/  - 204 -- 249
injuryattorneymurfreesboro.com/  - 234 -- 298
injuryattorneynashville.net/  - 310 -- 394
injuryattorneysmurfreesboro.com/  - 219 -- 268
injuryattorneysnashville.net/  - 300 -- 386
injurylawyermurfreesboro.com/  - 225 -- 323
injurylawyernashville.net/  - 282 -- 355
injurylawyersmurfreesboro.com/  - 284 -- 399
injurylawyersnashville.net/  - 315 -- 389
interestinventory.net/  - 480 -- 548
interestinventory.org/  - 230 -- 306
jamesjackhuddleston.com/  - 1548 -- 2348
jkarltrucks.com/  - 192 -- 233
karltrucks.com/  - 250 -- 286
karltruckslaw.com/  - 228 -- 263
lightningpatch.com/  - 377 -- 420
martialartsmotivation.com/  - 333 -- 375
monsterinvasionsoccergame.com/  - 240 -- 290
motivatebaseballplayers.com/  - 274 -- 361
motivatebasketballplayers.com/  - 258 -- 323
motivatefootball.com/  - 234 -- 283
motivatefootballplayers.com/  - 306 -- 382
motivatelacrosse.com/  - 209 -- 260
motivationalpatches.com/  - 550 -- 701
motorcycleaccidentattorneynashville.com/  - 282 -- 403
motorcycleaccidentattorneypanamacity.com/  - 199 -- 264
motorcycleaccidentlawyernashville.com/  - 352 -- 456
motorcycleaccidentlawyerpanamacity.com/  - 177 -- 245
motorcycleaccidentlawyersnashville.com/  - 299 -- 405
motorcyclewrecklawyernashville.com/  - 358 -- 480
mudax.com/  - 422 -- 489
murfreesboroaccidentattorney.com/  - 251 -- 337
murfreesboroaccidentattorneys.com/  - 216 -- 281
murfreesboroaccidentlawyer.com/  - 213 -- 279
murfreesboroaccidentlawyers.com/  - 239 -- 328
murfreesboroautoaccidentattorney.com/  - 244 -- 328
murfreesboroautoaccidentattorneys.com/  - 245 -- 341
murfreesboroautoaccidentlawyer.com/  - 249 -- 319
murfreesboroautoaccidentlawyers.com/  - 226 -- 320
murfreesborocaraccidentattorney.com/  - 248 -- 315
murfreesborocaraccidentattorneys.com/  - 277 -- 350
murfreesborocaraccidentlawyer.com/  - 228 -- 322
murfreesborocaraccidentlawyers.com/  - 212 -- 317
murfreesborodisabilityattorney.com/  - 237 -- 347
murfreesborodisabilitylawyer.com/  - 257 -- 323
murfreesboroinjuryattorney.com/  - 309 -- 417
murfreesboroinjuryattorneys.com/  - 204 -- 288
murfreesboroinjurylawyer.com/  - 203 -- 296
murfreesboroinjurylawyers.com/  - 235 -- 309
murfreesboromotorcycleaccidentlawyer.com/  - 249 -- 337
murfreesborosocialsecurity.com/  - 369 -- 439
murfreesborosocialsecurityattorney.com/  - 221 -- 303
murfreesborosocialsecurityattorneys.com/  - 297 -- 384
murfreesborosocialsecuritydisabilityattorney.com/  - 313 -- 399
murfreesborosocialsecuritydisabilitylawyer.com/  - 216 -- 282
murfreesborosocialsecuritylawyer.com/  - 220 -- 303
murfreesborotruckaccidentattorney.com/  - 243 -- 347
murfreesborotruckaccidentlawyer.com/  - 230 -- 335
narcoticsarrestattorneypanamacity.com/  - 200 -- 230
narcoticsarrestlawyerpanamacity.com/  - 171 -- 231
nashvilleaccidentattorney.net/  - 320 -- 446
nashvilleaccidentattorney.org/  - 261 -- 345
nashvilleaccidentattorneys.net/  - 265 -- 374
nashvilleaccidentattorneytn.com/  - 227 -- 316
nashvilleaccidentattorneytn.net/  - 208 -- 274
nashvilleaccidentattorneytn.org/  - 257 -- 332
nashvilleaccidentlawyer.org/  - 232 -- 311
nashvilleaccidentlawyers.net/  - 233 -- 307
nashvilleaccidentlawyertn.com/  - 223 -- 323
nashvilleaccidentlawyertn.net/  - 243 -- 302
nashvilleaccidentlawyertn.org/  - 219 -- 299
nashvilleautoaccidentattorney.net/  - 387 -- 504
nashvilleautoaccidentattorneys.net/  - 273 -- 376
nashvilleautoaccidentlawyer.com/  - 189 -- 267
nashvilleautoaccidentlawyer.net/  - 345 -- 465
nashvilleautoaccidentlawyers.net/  - 333 -- 452
nashvilleautoinjurylawyer.com/  - 280 -- 378
nashvillecaraccidentattorney.net/  - 290 -- 389
nashvillecaraccidentattorneys.com/  - 341 -- 453
nashvillecaraccidentattorneys.net/  - 279 -- 398
nashvillecaraccidentlawyer.net/  - 286 -- 371
nashvillecaraccidentlawyers.net/  - 265 -- 386
nashvillecarinjurylawyer.com/  - 308 -- 408
nashvillecarwrecklawyer.com/  - 285 -- 390
nashvillecommercialrealestatenews.com/  - 1220 -- 1885
nashvilledisabilityattorney.com/  - 281 -- 387
nashvilledisabilityattorney.net/  - 258 -- 332
nashvilledisabilityattorneys.com/  - 272 -- 356
nashvilledisabilityattorneys.net/  - 278 -- 370
nashvilledisabilitylawyer.com/  - 280 -- 393
nashvilledisabilitylawyer.net/  - 291 -- 390
nashvilledisabilitylawyers.com/  - 272 -- 378
nashvilledisabilitylawyers.net/  - 240 -- 317
nashvilleinjuryattorneystn.com/  - 300 -- 410
nashvilleinjuryattorneytn.com/  - 252 -- 330
nashvilleinjurylawyerstn.com/  - 236 -- 300
nashvilleinjurylawyertn.com/  - 375 -- 489
nashvillemotorcycleaccidentattorneys.com/  - 291 -- 377
nashvillemotorcycleaccidentlawyer.net/  - 304 -- 418
nashvillemotorcycleaccidentlawyers.net/  - 229 -- 308
nashvillemotorcyclewrecklawyer.com/  - 427 -- 546
nashvillesocialsecurity.com/  - 295 -- 394
nashvillesocialsecurity.net/  - 326 -- 418
nashvillesocialsecurityattorney.com/  - 248 -- 332
nashvillesocialsecurityattorney.net/  - 300 -- 396
nashvillesocialsecurityattorneys.com/  - 336 -- 418
nashvillesocialsecurityattorneys.net/  - 339 -- 401
nashvillesocialsecuritydisabilityapplication.com/  - 342 -- 430
nashvillesocialsecuritydisabilityassistance.com/  - 327 -- 450
nashvillesocialsecuritydisabilityattorney.com/  - 284 -- 392
nashvillesocialsecuritydisabilityattorney.net/  - 266 -- 358
nashvillesocialsecuritydisabilityattorneys.com/  - 278 -- 362
nashvillesocialsecuritydisabilityattorneys.net/  - 268 -- 350
nashvillesocialsecuritydisabilitylaw.com/  - 321 -- 463
nashvillesocialsecuritydisabilitylawyer.com/  - 279 -- 336
nashvillesocialsecuritydisabilitylawyer.net/  - 227 -- 306
nashvillesocialsecuritydisabilitylawyers.com/  - 278 -- 340
nashvillesocialsecuritydisabilitylawyers.net/  - 239 -- 337
nashvillesocialsecuritylaw.com/  - 261 -- 339
nashvillesocialsecuritylawyer.com/  - 298 -- 419
nashvillesocialsecuritylawyer.net/  - 257 -- 349
nashvillesocialsecuritylawyers.net/  - 312 -- 402
nashvillesocialsecuritylawyers.org/  - 227 -- 315
nashvilletnaccidentattorney.com/  - 244 -- 329
nashvilletnaccidentattorney.net/  - 315 -- 386
nashvilletnaccidentattorney.org/  - 296 -- 390
nashvilletnaccidentlawyer.com/  - 333 -- 426
nashvilletnaccidentlawyer.net/  - 265 -- 332
nashvilletnaccidentlawyer.org/  - 192 -- 267
nashvilletractor-traileraccidentattorneys.com/  - 274 -- 377
nashvilletractor-traileraccidentlawyers.com/  - 270 -- 387
nashvilletractortraileraccidentattorneys.com/  - 271 -- 392
nashvilletractortraileraccidentlawyers.com/  - 253 -- 355
nashvilletruckaccidentattorneys.com/  - 279 -- 376
nashvilletruckaccidentlawyer.com/  - 296 -- 408
nashvilletruckaccidentlawyers.com/  - 329 -- 469
nashvilletruckwrecklawyer.com/  - 294 -- 409
panama-city-dui.com/  - 197 -- 222
panamacityautoaccidentattorney.com/  - 199 -- 240
panamacityautoaccidentlawyer.com/  - 197 -- 243
panamacityautoaccidentlawyerattorney.com/  - 208 -- 254
panamacityautoaccidentlawyers.com/  - 177 -- 217
panamacitybeachautoaccidentattorney.com/  - 215 -- 285
panamacitybeachautoaccidentlawyer.com/  - 158 -- 203
panamacitybeachcaraccidentattorney.com/  - 179 -- 245
panamacitybeachcaraccidentlawyer.com/  - 166 -- 225
panamacitybeachcaraccidentlawyerattorney.com/  - 183 -- 230
panamacitybeachdefenseattorney.com/  - 166 -- 206
panamacitybeachdefenselawyer.com/  - 159 -- 213
panamacitybeachdisabilityattorney.com/  - 267 -- 350
panamacitybeachdisabilitylawfirm.com/  - 200 -- 293
panamacitybeachdisabiltylawyer.com/  - 185 -- 240
panamacitybeachdruglawyer.com/  - 147 -- 199
panamacitybeachdruglawyerattorney.com/  - 213 -- 280
panamacitybeachdui.com/  - 221 -- 275
panamacitybeachduilawyer.com/  - 278 -- 349
panamacitybeachpersonalinjuryattorney.com/  - 188 -- 213
panamacitybeachpersonalinjurylawyer.com/  - 161 -- 222
panamacitybeachsocialsecurity.com/  - 273 -- 323
panamacitybeachsocialsecuritydisabilityassistance.com/  - 197 -- 266
panamacitybeachsocialsecuritylawyerattorney.com/  - 198 -- 247
panamacitybeachwrongfuldeathlawyerattorney.com/  - 207 -- 260
panamacitycaraccidentattorney.com/  - 206 -- 245
panamacitycaraccidentattorneys.com/  - 258 -- 385
panamacitycaraccidentlawyer.com/  - 179 -- 228
panamacitycaraccidentlawyers.com/  - 250 -- 329
panamacitycarinjurylawyer.com/  - 187 -- 229
panamacitycriminalattorney.com/  - 183 -- 220
panamacitycriminaldefenselawyer.com/  - 205 -- 238
panamacitycriminaldefenselawyers.com/  - 155 -- 190
panamacitycriminallawyer.com/  - 169 -- 201
panamacitycriminallawyers.com/  - 159 -- 190
panamacitydefenselawyer.com/  - 204 -- 235
panamacitydisabilityappeal.com/  - 167 -- 206
panamacitydisabilityappealattorneys.com/  - 201 -- 236
panamacitydisabilityappeallawyers.com/  - 164 -- 193
panamacitydisabilityattorney.com/  - 184 -- 238
panamacitydisabilityattorneys.com/  - 206 -- 240
panamacitydisabilityclaimlawyers.com/  - 195 -- 268
panamacitydisabilitylawfirm.com/  - 183 -- 216
panamacitydisabilitylawyer.com/  - 198 -- 245
panamacitydisabilitylawyers.com/  - 173 -- 196
panamacitydrugattorney.com/  - 188 -- 245
panamacitydruglawyer.com/  - 156 -- 193
panamacitydruglawyerattorney.com/  - 181 -- 232
panamacitydruglawyers.com/  - 151 -- 186
panamacitydui.com/  - 189 -- 219
panamacityduidefense.com/  - 145 -- 161
panamacityduilawyerattorney.com/  - 187 -- 217
panamacitydwi.com/  - 155 -- 183
panamacityflsocialsecurity.com/  - 196 -- 218
panamacityflsocialsecurityattorney.com/  - 191 -- 234
panamacityflsocialsecuritylawyer.com/  - 219 -- 259
panamacitymotorcycleaccidentattorney.com/  - 216 -- 267
panamacitymotorcycleaccidentlawyer.com/  - 185 -- 214
panamacitypersonalinjurylawyer.com/  - 193 -- 231
panamacitypersonalinjurylawyerattorney.com/  - 170 -- 203
panamacityprobationviolationattorney.com/  - 174 -- 213
panamacityprobationviolationlawyer.com/  - 179 -- 212
panamacitysocialsecurity.com/  - 213 -- 247
panamacitysocialsecurityattorney.com/  - 244 -- 288
panamacitysocialsecurityattorneys.com/  - 244 -- 288
panamacitysocialsecuritydisabilitylawyer.com/  - 298 -- 353
panamacitysocialsecuritydisabilitylawyers.com/  - 215 -- 263
panamacitysocialsecuritylawyer.com/  - 235 -- 302
panamacitysocialsecuritylawyers.com/  - 221 -- 285
panamacityssidisabilityattorneys.com/  - 197 -- 242
panamacityssidisabilitylawyers.com/  - 194 -- 221
panamacitytriallawyer.com/  - 217 -- 268
panamacitytruckaccidentlawyer.com/  - 202 -- 233
personalinjuryattorneypanamacity.com/  - 207 -- 251
personalinjuryattorneypanamacitybeach.com/  - 171 -- 226
personalinjurylawyermurfreesboro.com/  - 242 -- 325
personalinjurylawyernashville.net/  - 237 -- 313
personalinjurylawyerpanamacity.com/  - 169 -- 234
personalinjurylawyerpanamacitybeach.com/  - 195 -- 274
personalinjurylawyersnashville.com/  - 269 -- 360
rewardpatches.com/  - 318 -- 392
schoolincentive.com/  - 231 -- 276
schoolincentives.net/  - 287 -- 388
schoolmotivation.com/  - 1667 -- 1980
schoolrewardpatches.com/  - 223 -- 296
schooltoworktransition.com/  - 292 -- 345
shamrockpatch.com/  - 235 -- 286
soccer-help.com/  - 525 -- 589
soccer-patches.com/  - 558 -- 884
soccerballpatch.net/  - 190 -- 227
soccerballpatches.com/  - 300 -- 365
soccerballpatches.net/  - 194 -- 222
soccerballpatches.org/  - 208 -- 274
soccerdrills.net/  - 11272 -- 18976
soccerdrills.org/  - 8602 -- 18566
soccerdrills1.com/  - 618 -- 684
soccerdrillsandgames.com/  - 476 -- 526
soccerformation.com/  - 461 -- 502
soccerformations.com/  - 2525 -- 18544
soccerformations.net/  - 791 -- 1039
soccerformations.org/  - 308 -- 337
soccerhelp.biz/  - 191 -- 220
soccerhelppracticegames.com/  - 223 -- 275
soccerhelppremium.com/  - 221 -- 259
soccerincentives.com/  - 258 -- 314
soccerpassingdrills.net/  - 777 -- 931
soccerpatch.net/  - 1528 -- 16496
soccerpatchesforkids.com/  - 581 -- 750
soccerpositiondiagram.com/  - 577 -- 656
soccerpositions.net/  - 2946 -- 19646
soccerpractice.org/  - 578 -- 647
soccerrules.org/  - 5727 -- 30494
soccertactic.com/  - 336 -- 364
soccertechnique.com/  - 385 -- 433
soccertryoutdrills.com/  - 615 -- 786
soccertryoutdrills.org/  - 365 -- 448
socialsecurityattorneyinpanamacity.com/  - 205 -- 249
socialsecurityattorneymurfreesboro.com/  - 217 -- 304
socialsecurityattorneynashville.com/  - 285 -- 392
socialsecurityattorneynashville.net/  - 265 -- 357
socialsecurityattorneypanamacity.com/  - 191 -- 237
socialsecurityattorneysinpanamacity.com/  - 199 -- 248
socialsecurityattorneysnashville.com/  - 269 -- 361
socialsecurityattorneysnashville.net/  - 242 -- 331
socialsecuritydisabilityattorneymurfreesboro.com/  - 261 -- 337
socialsecuritydisabilityattorneynashville.com/  - 294 -- 385
socialsecuritydisabilityattorneynashville.net/  - 270 -- 384
socialsecuritydisabilityattorneypanamacity.com/  - 222 -- 251
socialsecuritydisabilityattorneysnashville.com/  - 204 -- 286
socialsecuritydisabilityattorneysnashville.net/  - 254 -- 343
socialsecuritydisabilitylawapplemantrucks.com/  - 251 -- 278
socialsecuritydisabilitylawyermurfreesboro.com/  - 248 -- 345
socialsecuritydisabilitylawyernashville.com/  - 259 -- 344
socialsecuritydisabilitylawyernashville.net/  - 280 -- 342
socialsecuritydisabilitylawyersnashville.com/  - 275 -- 341
socialsecuritydisabilitylawyersnashville.net/  - 254 -- 324
socialsecuritydisabilitynashville.com/  - 279 -- 363
socialsecurityhelppanamacity.com/  - 201 -- 231
socialsecuritylawapplemantrucks.com/  - 266 -- 318
socialsecuritylawyerinpanamacity.com/  - 165 -- 201
socialsecuritylawyermurfreesboro.com/  - 211 -- 279
socialsecuritylawyernashville.com/  - 250 -- 325
socialsecuritylawyernashville.net/  - 242 -- 308
socialsecuritylawyerpanamacity.com/  - 222 -- 272
socialsecuritylawyersinpanamacity.com/  - 196 -- 223
socialsecuritylawyersnashville.com/  - 270 -- 380
socialsecuritylawyersnashville.net/  - 258 -- 355
socialsecuritylawyerspanamacity.com/  - 133 -- 174
socialsecuritynashville.com/  - 215 -- 299
socialsecuritynashville.net/  - 519 -- 594
socialsecuritynashville.org/  - 261 -- 356
socialsecuritypanamacityfl.com/  - 245 -- 305
softballmotivation.com/  - 592 -- 651
softballpatch.com/  - 270 -- 289
softballpatches.com/  - 290 -- 343
ssidisabilitylawyerspanamacityfl.com/  - 168 -- 200
starpatch.us/  - 442 -- 544
starpatches.com/  - 470 -- 813
studentmotivationalrewards.com/  - 334 -- 430
swimmingmotivation.com/  - 368 -- 401
teachingsoccer.com/  - 592 -- 641
tractor-traileraccidentattorneynashville.com/  - 310 -- 402
tractor-traileraccidentlawyernashville.com/  - 227 -- 329
tractortraileraccidentattorneynashville.com/  - 386 -- 476
tractortraileraccidentlawyernashville.com/  - 244 -- 336
transitionassessmenttools.com/  - 248 -- 316
truckaccidentattorneynashville.com/  - 338 -- 459
truckaccidentlawyernashville.com/  - 302 -- 400
truckaccidentlawyersnashville.com/  - 282 -- 357
truckwrecklawyernashville.com/  - 362 -- 458
u4soccer.com/  - 314 -- 416
u6soccer.com/  - 510 -- 559
victorypatch.org/  - 250 -- 295
vocationalassessment.net/  - 320 -- 363
vocationalrehabilitationassessment.com/  - 371 -- 421
vocrehabassessment.com/  - 271 -- 335
volleyballmotivation.com/  - 363 -- 424
volleyballpatches.com/  - 282 -- 329
youthsoccercoaching.com/  - 294 -- 333
youthsoccerdrills.com/  - 1335 -- 15978
youthsoccerformations.com/  - 297 -- 358
youthsoccerpositions.com/  - 291 -- 361
youthsoccerrules.net/  - 315 -- 372

Invalid Domains
------------------------
