### ISSUE TITLE
Priority - Shopping Cart Coupons and Change Quantity don't work - says "Insecure Connection", 9-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#376]
I emailed  this on 9-5-17 at 9;53 AM

There are 3 problems with the Cart >

First - when I try to change the quantity of an item, it says 

"Security Warning - The information you have entered on this page will be sent over an insecure connection and could be read by a third party.

Are you sure you want to send this information?"

2nd - Further, if you try to change the quantity, it doesn't change the price.

3rd - when I tried to use a Coupon, I got the same message and it wouldn't take the Coupon.

I was on https://www.soccerhelp.com/soccershop/index.php?route=checkout/cart buying the  Coach Doug DVD

**Comment by dustinschaerer** [comment]
This is completed.
