### ISSUE TITLE
Back up the video clips in DropBox, 9-5-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#377]
Dustin, in answer to your question "Yes" >

@david-huddleston We have the videos you shot backed up in Dropbox, but not the video clips we have up there. Do you want me to pull those down from youtube and also back them up?

**Comment by dustinschaerer** [comment]
OK will do today.

**Comment by dustinschaerer** [comment]
@david-huddleston I've gone through all our videos I didn't have copies of and downloaded them, then uploaded them to Dropbox.
