### ISSUE TITLE
Priority - Add Block Quote of Tests to 500 Tips and Index page, 9-7-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#378]
I emailed this on 9-7-17 at 1:29 PM

Dustin, add the tips below to the 2 places listed below.

Add >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member
"I have learned more in the two weeks since subscribing to Premium than I learned in seven years of coaching.” Coach Rion, SC
"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member
"Thank you for the amazing fundamentals that my daughter and her teammates have been taught. 5 of those girls (my daughter included) are Freshmen starting on their VARSITY high school soccer team." Coach Aaron, OH, Premium subscriber for 6 years

Add those 4 tests as a Block Quote to > 

1st - add Block Quote as a new 3rd para to  http://www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml   (just above Below are links to over 500 Soccer Coaching Tips - )

2nd - add that Block Quote as a new 2nd para to http://www.soccerhelp.com/Soccer-Coaching-Navigation.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
