### ISSUE TITLE
Switch out video in 3 places, 9-8-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#379]
Dustin, you made YouTube versions of the Tick Tock and Tap on Top videos.

Replace the current version with the YouTube versions in 3 places >

http://www.soccerhelp.com/premium/videos/Tick_Tock_Game_Demo.shtml

http://www.soccerhelp.com/premium/videos/Tap_On_Top_Game_Demo.shtml

http://www.soccerhelp.com/soccer_drills/Tick_Tock.shtml 

Have them be the highest possible quality.

**Comment by dustinschaerer** [comment]
This is completed.
