### ISSUE TITLE
Disavow Spam Links

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#38]
Dustin, we talked about this.

Please let me know how you can identify the bad links without disavowing good links. 

Is it easy to do?

David

**Comment by dustinschaerer** [comment]
@david-huddleston 
Its not difficult, but it is dangerous and permanent. 

The main issue is how much time it's taking to run the SEO Spyglass Tool.  When trying to work on the whole backlink profile some operations queue up at over 24 hours long, and My computer won't stay up that long overnight.  I'm having to work in intervals on that, so it might be a few days before we can disavow links confidently.  I'm sure I could disallow some just from reading the domain name, but I'd rather have a systematic way using the software to manage that list.

**Comment by dustinschaerer** [comment]
In order to identify the "bad" links I have to run a huge report in SEO SpyGlass. Hopefully it will become faster as we start disavowing domains of links.  Once the report is run, there are several factors to consider. One easy criteria to disavow is if the domain name contains the word "porn" or any other blatantly obvious "porn" related terms (I don't need to spell those out).

**Comment by david-huddleston** [comment]
6-19-17 - We just talked about this and Dustin is going to start working on this.  He can't run the entire report - it is at 10,000 backlinks. He said 682 of the links have "Penalty" but there are obviously other Spam links that say "zero" risk.  Whereas , "Inglewood Soccer" is a "Penalty Risk".

He has 9,500 links completed or 45,000.

**Comment by dustinschaerer** [comment]
@david-huddleston I disavowed several entire domains, not just their links.  WHe the tool finishes, I'll disavow more.

**Comment by dustinschaerer** [comment]
@david-huddleston I added more domains to the disavow list and re-submitted successfully to Google.

**Comment by david-huddleston** [comment]
Dustin, see the post I just made asking if you have disavowed any domains that I own.
