### ISSUE TITLE
2nd version -  Priority - Changes to the 9v9 formations page, 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#380]
I emailed this on 9-10-17 at 10:38 PM - use the email so you can see Bold and links . 

Delete the prior version from 9-9-17 at 10:42 AM

Dustin, Use this email instead of GitHub.

on http://www.soccerhelp.com/9v9-Soccer-Formations.shtml >

1st. Near the top (above "Dear SoccerHelp), delete > 

Free Soccer Patches 
Want to become a great soccer coach? Check out SoccerHelp Premium and Coach Doug's Site for U4, U5 and U6 Coaches. There is a "no questions asked" money back guarantee. Over 15,000 soccer coaches have become Members. Subscriptions are as low as $11.95 for Coach Doug and $17.99 for Premium.

2nd . My first reply ends >
Good luck. 
David at SoccerHelp 

Dustin, just below "David at SoccerHelp " add the 4 Tests below as a Block Quote AND add the Promo that is on  http://www.soccerhelp.com/soccer_drills/Dribble.shtml - you can copy that promo from there (Dustin, save that Promo, I'm going to have you add that Promo to several other popular pages)  >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we religiously do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

So it reads >

Good luck. 
David at SoccerHelp

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we religiously do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
@david-huddleston I'm in the process on this one, but I also have to add Bootstrap to get the blockquote styles.

**Comment by dustinschaerer** [comment]
@david-huddleston This is ready, but I can also get it validated in about 4 minutes of work if you'd like that too.

**Comment by david-huddleston** [comment]
Yes, do that

**Comment by dustinschaerer** [comment]
Completed.
