### ISSUE TITLE
Priority - u8-Soccer-Drills - 8 changes, 9-9-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#381]
II emailed this on 9-9-17 at 1:14 PM - use the email to see colors and links.

Dustin, on http://www.soccerhelp.com/u8-Soccer-Drills.shtml >

1st - In the first para, replace the 2nd sentence with >

These U8 soccer drills are No Lines Practice Games that teach skills - there are No Lines, so your players will improve TWICE AS FAST and have more fun.

2nd - In the 2nd para, the 3rd sentence is >

There are many testimonials for our drills from U8 soccer coaches and you can read them at Testimonials.

Replace it with  >

There are 400 Testimonials for our No Lines Drills.

3rd - delete >
Dribble Across a Square is a great U8 soccer drill - you will see results within one practice and your players will develop AMAZING dribbling skill.
The Dribble Around Cone and Pass Relay Race soccer will teach your U8 players to be aggressive receivers, passing, speed dribbling, one touch play, and more.
At U8, soccer becomes more aggressive. The Strength on the Ball soccer drill will teach your players how to be strong on the ball and how they can legally steal the ball from the other team.

AND Replace it with below and put these 4 Tests in a Block Quote >

"I was a college soccer player and had coached club U17 girls and HS varsity women's soccer teams in the past. I chose to experiment and ONLY do drills I got from your site. Happy to report that we only got scored on 3 times all season, and most of our players were very comfortable dribbling through traffic!" Nicole, U8, Premium member, posted on Facebook
"Using the SoccerHelp concepts and the incentive patches, my U8 soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal. My kids and parents could not be happier! I am just about to place my third order for more patches, so man did they work!!" Coach Dan, GA, Premium member
"I took on my son's U8 soccer team because they were short a coach. I stepped up even though I had never before played soccer. My team won all but one game my first season! My son's improvement is far beyond what I could have ever imagined." Steph, Premium Member and soccer patch customer
"I had 5 or 6 players that ranged from average to skilled, with the rest being either unskilled, didn't want to be there, bad attitudes, or all of the above. After finding your site I immediately started Dribble Across the Square, and implemented your defensive strategy on throw ins and goal kicks. The changes were dramatic. This summer I found out that parents were making requests to have their players put on my team." Dan, OH, U8 soccer coach, Premium member and patch customer

4th  - More Free, Fun Soccer Drills and Practice Games goes to  /Soccer-Drills.shtml  > change it to go to http://www.soccerhelp.com/soccer-drills.shtml  so it isn't a re-direct

5th - the 2nd link is > Strength on the Ball, Aggressive Play & Bravery Soccer Drill ™
Delete the first words > Strength on the Ball,
So it reads >
Aggressive Play & Bravery Soccer Drill ™

6th - add the black text below beside the links >
Dribble Across A Square ™ U8 Soccer Drill that is a Game - The best way to teach control dribbling and how to recognize Open Space and accelerate into it (how to Breakaway). You will see results within one practice and your players will develop AMAZING dribbling skills. What coaches say - "The Dribble Across a Square game is genius, it teaches so much." John, KY, U8, Premium Member. And - "My U12 daughter has played it at every practice since U8 and is well known in our rec league as someone you have to double and triple team if you don't want her to score. This past week she was offered a spot on a U13 travel team. My advice to coaches is to play Dribble Across a Square at every practice." Coach Jason, Premium member for 4 years
Aggressive Play & Bravery Soccer Drill ™ - At U8, soccer becomes more physical and it is a big disadvantage to be afraid of contact. The Aggressive Play soccer drill will teach your players to not be afraid of contact so they don't get pushed around, and how they can legally steal the ball from the other team. What coaches say - "The other team was bigger and trying to play very aggressively against us and, although they really tried, the other team could not push my boys around." Stephanie, U10
Dribble Around Cone & Pass Relay Race ™ U8 Soccer Drill - This will teach your U8 players to be aggressive receivers, passing while running, one touch play, and more. What coaches say - "We played Dribble Across a Square and Dribble Around the Cone and Pass Relay Race at every practice, and the results were phenomenal." Coach Greg, U9, Premium Member
More Free, Fun Soccer Drills and Practice Games 

7th - add a new 5th link to the list above >
Defense Tips Worth 2 Goals Per Game - Definitely try this. This is a better way to defend opponent's throw ins, goal kicks and punts. It is worth 2 or more goals per game. A U8 coach said - "Every one of our opponents throw-ins resulted in a turnover, the ball was on their half 80%+, and the other team had zero shots." Dan, U8 Rec Soccer, OH, Premium member
(Dustin, have the link go to  http://www.soccerhelp.com/22-coaching-rules-report.shtml   ) 

8th -  Delete the last part > 
What U8 Soccer Coaches Say
"About two years ago, I took on my son's U8 soccer team because they were short a coach. I stepped up even though I had never before played soccer. I subscribed to your site and my team won all but one game my first season! My son's improvement is far beyond what I could have ever imagined."
--Steph, Premium Member and soccer patch customer
"Using the SoccerHelp concepts and the incentive patches, my U8 team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal. My kids and parents could not be happier! I am just about to place my third order for more patches, so man did they work!!
--Coach Dan, U8 soccer coach, GA

**Comment by dustinschaerer** [comment]
This is completed.
