### ISSUE TITLE
3rd Version - Soccer fouls - add the Premium Promo, 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#383]
I emailed this on 9-10-17 at  1:56 PM - use the email version so you can see colors, bold and links

Delete the 2 versions I sent you on 9-9-17 at 1:35 PM and the version I sent on 9-10-17 at 1:41  and use this version

Dustin, on 

http://www.soccerhelp.com/terms/soccer-fouls.shtml

1st - In the last para, change the destination of the link "Rules"  to http://www.soccerhelp.com/simplified-soccer-rules.shtml 

2nd - Near the end, just below the "Advantage Clause" para (just above the para that starts "(See "Cards", "Rules", "Hand Ball", "Offside Rule",

Add  the Tests and Premium Promo below - this is exactly the same that you are adding to http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml  (the 5 Tests are a Block Quote and the it contains the link  1,000 Testimonials  >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member
"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member
"Thank you for the amazing fundamentals that my daughter and her teammates have been taught. 5 of those girls (my daughter included) are Freshmen starting on their VARSITY high school soccer team." Coach Aaron, OH, Premium subscriber for 6 years

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL
"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA, U8
Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
