### ISSUE TITLE
2nd version -  Soccer Awards article - add Tests and Promo to the end, 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#384]
I emailed this on 9-10-17 at 2:04 Pm - use the email to see colors and links

Delete the version I sent on 9-10-17 at 1:32 PM and use this one

Dustin, 

Below are 5 Tests (to go in a Block Quote) and a revised Premium Promo. SAVE THE Block Quote & Promo - you will use it in several places. 

Except for one difference, the Premium Promo below the Tests is the same as the one that you are adding to http://www.soccerhelp.com/9v9-Soccer-Formations.shtml - the one difference is that  I changed the link to 1,000 Testimonials (that link goes to https://www.soccerhelp.com/soccershop/index.php?_route_=testimonials ) - save this version, I will use it in several places. 

> On http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml , add what is below AND Make the 5 Tests a Block Quote. Add it below "David at SoccerHelp" >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"Thank you for the amazing fundamentals that my daughter and her teammates have been taught. 5 of those girls (my daughter included) are Freshmen starting on their VARSITY high school soccer team." Coach Aaron, OH, Premium subscriber for 6 years

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA, U8

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
