### ISSUE TITLE
Priority - SH Home - add the "35 years" quote", 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#385]
I emailed this on 9-10-17 at 3:18 PM

Dustin, on SH Home,

add as the first Test in the Block Quote near the top >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

So the Block Quote reads >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"The Practice Games are AMAZINGLY EFFECTIVE!! Parents tell me their girls cannot wait to go to practice." M.J.
"The patches are the absolute best motivational tool I have found in seven years of coaching." Chad, CA
"At every practice we do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
