### ISSUE TITLE
Soccer Formations - 2 changes - add the 5 Tests and Promo, 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#386]
I emailed you this on 9-10-17 at 5:13 PM - use the email 

Dustin, on http://www.soccerhelp.com/soccer-formations.shtml ,

1st - Add the 5 tests and the Premium Promo (the same stuff you added to the "soccer-fouls" article and http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml ) 

Add them at the end of the first section, just above >

How to Choose the Best Soccer Formation and Style of Play

Below is what to add (exactly the same that you added on http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml ) >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"Thank you for the amazing fundamentals that my daughter and her teammates have been taught. 5 of those girls (my daughter included) are Freshmen starting on their VARSITY high school soccer team." Coach Aaron, OH, Premium subscriber for 6 years

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA, U8

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

2nd - Delete the Promo that is at the end of the 2nd section >

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages, 5,000 links & 100 articles about positions and formations. Use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 5-day money back guarantee. 15,000 Coaches have subscribed. 400 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
