### ISSUE TITLE
Positions Basics -  add 2 Tests and change the Promo, 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#387]
I emailed this on 9-10-17 at 5:25 PM

Dustin, on   http://www.soccerhelp.com/Soccer_Positions_Basics.shtml 

the 2nd para is a Premium Test. 

Replace it with (the Promo is the same one you used on soccer-fouls and http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml  ) - make the 3 Tests a Block Quote  >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"I have learned more in the two weeks since subscribing to Premium than I learned in seven years of coaching.” Coach Rion, SC

"At every practice we religiously do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
