### ISSUE TITLE
Tryouts Evaluation Form, add 3 Tests, 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#388]
I emailed this on 9-10-17 at 7:06 PM

Dustin, on   http://www.soccerhelp.com/Soccer_Tryouts_Evaluation_Form.shtml >

Add the 3 tests below as a Block Quote just above the Premium Promo (the Promo is just above the Soccer Tryout Evaluation Form > 

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"My kids love earning the patches and once they've earned them you can see the pride they feel gushing out of them. Thank you!" Coach John, Soccer Academy, PA

**Comment by dustinschaerer** [comment]
This is completed.
