### ISSUE TITLE
Soccer Positions - add Tests and Promo, 9-10-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#389]
I emailed this on 9-10-17 at 7:28 PM - use the email

Dustin, on http://www.soccerhelp.com/Soccer_Positions.shtml >

1st -  Delete the 5th para, which is a Premium Promo

2nd -  In its place put the 4 tests below as a Block Quote AND the Promo below, which is the same Promo you put on http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml   >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

**Comment by dustinschaerer** [comment]
This is completed.
