### ISSUE TITLE
One change to www.soccerhelp.com/Soccer_Practice.shtml 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#39]
Dustin, I sent you an email about this on 6-13-17 at  5:14 PM CST - you can see the link a lot better in the email.

on www.soccerhelp.com/Soccer_Practice.shtml

in # 11, change  "Testimonials from Coaches" to  Testimonials from Coaches about Results   and have it link to http://soccerhelp.com/soccershop/soccerhelp-premium-reviews-testimonials 

So it is like >

Summary - SoccerHelp No Lines Practice Games are a better way to train players. The best way to train your players is by using SoccerHelp No Lines Practice Games - that is why there are over 400 Testimonials from coaches. SoccerHelp Practice Games are effective and for U8 and older they involve competition and pressure. SoccerHelp Practice Games train players to play fast while under pressure. Coaches who use SoccerHelp No Lines Drills and Practice Games achieve 200% to 300% MORE at each practice, because actual practice time is maximized and standing in line is minimized. The result is that your players will improve 2 or 3 times faster and develop better fundamental skills - read the Testimonials from Coaches about Results . Even if you practiced twice as much with Line Drills, your results would be inferior because Line Drills don't create competition and train players to play fast while under pressure. SoccerHelp Drills and Practice Games are a better way to train and train players to play fast while under pressure, so they are able to play better in real matches.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
