### ISSUE TITLE
7v7 Soccer Formations changes, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#391]
I emailed this on 9-11-17 at 12:12 PM - use the email

Dustin, on http://www.soccerhelp.com/soccer-articles/110125-7v7-soccer-formations-breakaways.shtml

1st - Replace the 2nd , 3rdm 4th and 5th lines of the title with >

2-3-1, 1-1-3-1, 3-1-2, 2-2-2, 2-1-1-2
Sweeper and Stopper 
Stopping Breakaways 
Preparing for Tournament

So it reads >

7v7 Soccer Formations 
2-3-1, 1-1-3-1, 3-1-2, 2-2-2, 2-1-1-2
Sweeper and Stopper 
Stopping Breakaways 
Preparing for Tournament

2nd - at the top delete the 2 links >

DVD Close-Out Sale 
Free Soccer Patches 

3rd - add as a new first para >

Tips from SoccerHelp - If you have a team with some timid, slow, unathletic, and unskilled players, and use a 7v7 soccer formation, consider a 2-3-1 and put your most skilled Brave player at Center Mid and your best scorer at Forward. At Fullback you must have Brave players who aren't afraid of contact or of being hit by the ball (scared or timid players aren't good at Fullback) - your Fullbacks can both be slow IF they don't Push Up too far when you attack (have them stop at the Penalty Box Line). If one of your Fullbacks is fast, you can Push Up the fast Fullback to the Halfway Line and leave the slow Fullback Deep. If both of your Fullbacks are as fast as opposing forwards, you can Push them both Up when you attack. Pushing Up one or both Fullbacks when you attack is good because they can support your attack, BUT if your Fullbacks are slow and you Push them Up against fast forwards, you risk giving up a lot of goals on Breakaways. Put your unathletic, unskilled and timid players at Right and Left Mid until they improve enough to play other positions. It is critical to control the Center of the Field (an imaginary line between the 2 goals) and to not give up goals on breakaways. Encourage opponents to attack down the sidelines instead of the down the Center - that will give your players time to recover to defensive positions and opponents will run more - but you can't let opponents easily attack straight to your goal or they will probably score a lot. There 1,500 pages on SoccerHelp Premium, including 200 pages about formations, positions and tactics. A link and coupon are at the end of this article. SoccerHelp drills are No Lines Practice Games and your players will improve twice as fast and have more fun. There are 1,000 Testimonials and some are at the end. 

4th - Toward the end, replace # 3 with >

3. As a Premium Member, play the  Win the 50/50 Ball or be the First Defender 1v1 Attacking and Defending game (www.soccerhelp.com/premium/practice_games/Win_The_Ball.shtml) That game does what the name says -- it teaches players that IF they can't win a 50/50 ball, they MUST become the First Defender and slow down the attack. IF your players will immediately become First Defenders and slow the attack for even 5 seconds, it will stop a lot of breakaways.

5th - Add to the end of the article the same Tests Block Quote and Premium Promo you added to http://www.soccerhelp.com/Soccer_Positions.shtml >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

6th - Bootstrap and responsive the page (this page is already ranked so don't worry about validating it)

**Comment by dustinschaerer** [comment]
This is completed.
