### ISSUE TITLE
7v7 article, replace the first para, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#392]
Dustin, on

Replace the first para with > 

Tips from SoccerHelp - Choose the 7v7 soccer formation and Style of Play that gives your team the best chance of success. For example, if you have a team with some timid, slow, unathletic, and unskilled players, consider a 2-3-1 and put your most skilled Brave player at Center Mid and your best scorer at Forward. Put your timid, unathletic, and unskilled players at Right and Left Mid until they improve enough to play other positions. Timid players are like "weak links" and can't be effective at Fullback, Forward or Center Mid. Try to motivate all your players to be Brave (there are ideas and a drill that teaches Bravery on SoccerHelp). At Fullback you must have Brave players who aren't afraid of contact or of being hit by the ball (scared or timid players aren't good at Fullback) - your Fullbacks can be slow IF they don't Push Up too far when you attack (have them stop at the Penalty Box Line). If one of your Fullbacks is fast and one is slow, you can Push Up the fast Fullback to the Halfway Line and leave the slow Fullback Deeper (like a Sweeper). If both of your Fullbacks are as fast as opposing forwards, you can Push them both Up when you attack. Pushing Up one or both Fullbacks when you attack is good because they can support your attack, BUT if your Fullbacks are slow and you Push them Up against fast forwards, you risk giving up a lot of goals on Breakaways. If you Push Up one Fullback and leave one Deep, at that point a 2-3-1 looks like a 1-1-3-1. It is critical to control the Center of the Field (an imaginary line between the 2 goals) and to not give up goals on breakaways. Encourage opponents to attack down the sidelines instead of the down the Center - that will give your players time to recover to defensive positions and opponents will run more - but you can't let opponents easily attack straight to your goal or they will probably score a lot. There is a lot more about this on SoccerHelp and Premium. There 1,500 pages on SoccerHelp Premium, including 200 pages about formations, positions and tactics. A link and coupon are below. SoccerHelp drills are No Lines Practice Games and are MUCH BETTER than typical drills - your players will improve twice as fast and have more fun. There are 1,000 Testimonials. See the end of this article for more info.

**Comment by dustinschaerer** [comment]
This is completed.
