### ISSUE TITLE
SH Home page - add links to 7v7 and 9v9, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#393]
Dustin, 

**1st** - on SH Home, add a new link named >

Formations 7v7

that goes to  http://www.soccerhelp.com/soccer-articles/110125-7v7-soccer-formations-breakaways.shtml 

Add it just before > Formations 8v8 

**2nd** - on SH Home, add a new link named >

Formations 9v9

that goes to   http://www.soccerhelp.com/9v9-Soccer-Formations.shtml 

Add it just after > Formations 8v8

**Comment by dustinschaerer** [comment]
This is completed.
