### ISSUE TITLE
Delete an article about 7v7 and re-direct the link to 7v7 Formations, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#394]
Dustin, 

1st - Delete the article at  http://www.soccerhelp.com/Soccer_Tips_Soccer_Formations_7v7.shtml 

2nd - redirect that link to go to 

http://www.soccerhelp.com/soccer-articles/110125-7v7-soccer-formations-breakaways.shtml

**Comment by dustinschaerer** [comment]
This is completed.
