### ISSUE TITLE
on Soccer Formations, change the 7v7 link destination, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#395]
Dustin, on   http://www.soccerhelp.com/soccer-formations.shtml , 

In the Links List, the link "7v7 Soccer Formations"  goes to  http://www.soccerhelp.com/Soccer_Tips_Soccer_Formations_7v7.shtml

Change the destination of that link to to > 

http://www.soccerhelp.com/soccer-articles/110125-7v7-soccer-formations-breakaways.shtml

**Comment by dustinschaerer** [comment]
This is completed.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
