### ISSUE TITLE
New Patch test - add as the # 7 test, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#396]
Dustin, add below as the # 7 Patch test >

"Once again, my players are super excited about the Soccer Motivational Patch Program. I have several new players in my youngest age bracket and they are so excited about this program. I cannot tell you how much these mean. This is such a wonderful program and it has been tremendously successful for these several years that I have used them."

Coach Victoria, MO

**Comment by dustinschaerer** [comment]
This is added!
