### ISSUE TITLE
Priority - On SH Home, add some space between the 4 Tests, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#397]
Dustin, on SH Home, add some space between the 4 Tests

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member
"The Practice Games are AMAZINGLY EFFECTIVE!! Parents tell me their girls cannot wait to go to practice." M.J.
"The patches are the absolute best motivational tool I have found in seven years of coaching." Chad, CA
"At every practice we do Dribble Across a Square, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA

**Comment by dustinschaerer** [comment]
@david-huddleston I think you need to just do a hard refresh Control + F5

Dustin
