### ISSUE TITLE
Delete www.soccerhelp.com/Soccer_Rules.shtml and re-direct it, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#398]
Dustin,

1st - delete www.soccerhelp.com/Soccer_Rules.shtml 

2nd - re-direct www.soccerhelp.com/Soccer_Rules.shtml  to http://www.soccerhelp.com/simplified-soccer-rules.shtml 

3rd -  on SH Home, in the Alphabetical List, delete the link    Soccer Rules , which goes to http://www.soccerhelp.com/Soccer_Rules.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.  Do you want me to do a site wide for this link to replace?
