### ISSUE TITLE
Soccer Rules - delete the Top Line of Title, 9-11-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#399]
I emailed this on 9-11-17 at  9:15 PM

Dustin, on http://www.soccerhelp.com/simplified-soccer-rules.shtml >

delete the top line of the Title (which is "Soccer Rules"), so the Title reads >

70 Simplified Soccer Rules
for Youth Coaches

**Comment by dustinschaerer** [comment]
Completed.
