### ISSUE TITLE
In Cart, Endicia CSV Files address clearing option not working - do after SSL & Broken Links

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#4]
Dustin, this needs to be fixed after the SSL is set up and the Broken Links are fixed >

Link to site to pull Shopping cart addresses:
https://www.soccerhelp.com/endicia/opencart_index.php

When we import the addresses from the shopping cart and click the link 

Click this link once you have imported the addresses into Dazzle.

Error Message:
Warning: copy(last_update-undo.txt): failed to open stream: Permission denied in /var/www/vhosts/soccerhelp.com/httpdocs/endicia/opencart_index.php on line 223 Warning: fopen(last_update.txt): failed to open stream: Permission denied in /var/www/vhosts/soccerhelp.com/httpdocs/endicia/opencart_index.php on line 228 Error. The file couldn't be opened. Please contact the system administrator.

This used to clear out the addresses from the time point in which the link was clicked, however now it is not clearing the addresses and is pulling all the shopping cart addresses from when it stopped working.

What they are currently doing is using the  CSV file"import by day", which  is working. That pulls the addresses for that day.  It keeps the addresses from previous days off, but if you pull the addresses in the morning and then again in the afternoon, the morning addresses will duplicate.

**Comment by david-huddleston** [comment]
Mandy's cell number is 615-838-2958

**Comment by dustinschaerer** [comment]
@david-huddleston This problem was due to tightening the permissions on the SH server recently.  I resolved the problem and spoke with Mandy to inform her. She said she would call if she had any further problems.
