### ISSUE TITLE
u8-Soccer-Drills - delete some repeated key words, 9-12-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#400]
I emailed this on 9-12-17 at 12:05 PM

Dustin, on http://www.soccerhelp.com/u8-Soccer-Drills.shtml , 

1st - in the 1st para, in the 2nd sentence and the 4th sentence, delete "U8 Soccer", so it reads > 

Below are U8 Soccer Drills and Practice Games for coaches of ages 7 and 8 (Under 8). These drills are No Lines Practice Games that teach skills - there are No Lines, so your players will improve TWICE AS FAST and have more fun. They maximize touches and train players to play fast while under pressure. We invented these U8 drills and they are only on SoccerHelp.

2nd - in the 2nd para, replace the first sentence, with  > 

SoccerHelp No Lines Drills teach players the most important soccer skills. 

3rd - in the link Dribble Across A Square ™ U8 Soccer Drill that is a Game  , delete "U8 Soccer" so it reads >

Dribble Across A Square ™ Drill that is a Game

**Comment by dustinschaerer** [comment]
This is completed.
