### ISSUE TITLE
7v7 Soccer Formations - change the Meta Description & Keywords, 9-14-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#401]
Dustin, , on http://www.soccerhelp.com/soccer-articles/110125-7v7-soccer-formations-breakaways.shtml >

Replace the Meta Description & Keywords with those below >

<meta name="description" content="7v7 Soccer Formations 2-3-1, 1-1-3-1, 3-1-2, 2-2-2, 2-1-1-2, Soccer Breakaways">
<meta name="keywords" content="7v7 Soccer Formations, 2-3-1, 1-1-3-1, 3-1-2, 2-2-2, 2-1-1-2, Soccer Breakaways">

**Comment by dustinschaerer** [comment]
This is completed.

**Comment by dustinschaerer** [comment]
I found the original email and updated the meta description and keyword now.

**Comment by dustinschaerer** [comment]
Ok, its defintiely there now :)
