### ISSUE TITLE
Priority - check out link on Coach Doug & Foot Skills about Flash, 9-13-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#402]
I emailed this on 9-13-17 at 9:07 AM

Dustin, on http://soccerhelp.com/video_downloads/coach_doug_video/ AND on http://soccerhelp.com/video_downloads/foot_skills_video/ 

In BOTH places, there is a link below the video that says >

•	If you are on a Desktop computer with Flash enabled, click here to watch the video with live streaming.
What does that mean?

When I click it, it says > 

" Error loading player:
No playable sources found

Do we still need that link? Can it be deleted since it doesn't work? If we don't need it, delete it in both places.

David

**Comment by dustinschaerer** [comment]
That link is deleted in both places, we don't need it.
