### ISSUE TITLE
Change destination of 2 links on Dangerous Play, 9-14-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#403]
I emailed this on 9-14-17 at 1:57 PM

Dustin, on  http://www.soccerhelp.com/terms/soccer-dangerous-play.shtml 

Change the destinations of the links >

Change Fouls   to >  http://www.soccerhelp.com/terms/soccer-fouls.shtml 

Change  Cards  to >  http://www.soccerhelp.com/terms/soccer-cards.shtml

**Comment by dustinschaerer** [comment]
This is completed.
