### ISSUE TITLE
Change to http://www.soccerhelp.com/terms/soccer-penalty-kick.shtml , 9-14-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#404]
Dustin, on http://www.soccerhelp.com/terms/soccer-penalty-kick.shtml

In the last para are weird symbols - 

Most of all, remember that Coach Tim and I are VERY proud of you and what you have done in this game, and we both love you all to piecesï¿½so just go do your thing and do it like you have practiced a thousand times.

After the word "pieces" add a comma to make the weird symbols go away.

**Comment by dustinschaerer** [comment]
This is resolved.
