### ISSUE TITLE
Premium Hit the Coach - Change link destination, 9-14-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#405]
I emailed this on 9-14-17 at 4:43 PM

Dustin, on http://www.soccerhelp.com/premium/practice_games/Hit.shtml, 

at  the end of the "Teaches" para, is the link >  Coach Doug video clips.

Change the destination to > http://www.soccerhelp.com/soccer_drills/Hit.shtml

**Comment by dustinschaerer** [comment]
This is completed.
