### ISSUE TITLE
2nd version - Hit the Coach - changes to BOTH Basic and Premium, 9-14-17 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#406]
I emailed this on 9-14-17 at 5:04 PM -- use the email 

Dustin, delete the version I just sent at 5:02 PM and use this one. 

Dustin, on BOTH http://www.soccerhelp.com/soccer_drills/Hit.shtml   and  http://www.soccerhelp.com/premium/practice_games/Hit.shtml ,

Under "The Game",  Replace the 6 Bullets with >

•  Players stand facing Coach who is 4 or 5 steps away - each player has a ball. Put the slow kids closer and fast kids behind the slow kids. (Don't make the balls too hard because hard balls can hurt little feet - let some air out if balls are too hard). 
•  On "Go", run slowly away while players dribble to chase you & try to hit you with the ball by shooting at you (let them hit you enough that it is fun for the kids).
•  When they hit you, they get to choose an animal sound for you to make (like a cow or a chicken - like Doug does in the video).
•  Stay in a small area and have fun with this game
•  Play for 5 to 10 minutes, or until the kids get tired
•  To Make it More Fun and Get Better Results - If some players are faster dribblers, have the fast kids start 2 or 3 steps behind the slow kids so the fast kids have to dribble thru or around the slower players (explain to the fast kids that they can dribble thru or around). Set it up so all players a chance to "Hit the Coach" or at least to take shots at you. If that doesn't work, recruit a parent and split into 2 groups with the slower kids chasing the parent and the fast kids chasing you.

**Comment by dustinschaerer** [comment]
This is completed.
