### ISSUE TITLE
7th Version -  Soccer rules article, 8 changes, 9-18-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#408]
I emailed this on 9-18-17  at 9:59 AM  - use the email so you can see colors and links.

Delete the versions I sent on 9-14-17 at 7:46 PM, 9-15-17 at 6:29 PM, 9-16-17 at 1:18 PM and 1:43 PM, and this morning at 9:51  and 9:56 PM

Dustin, on http://www.soccerhelp.com/simplified-soccer-rules.shtml 

1st -  Replace the top part (above the Links) with >

Below are 70 simplified soccer rules and definitions of terms such as "Hand Ball". Soccer Rules are also called the "Laws of the Game ". The official rules are usually modified for recreational, youth and indoor leagues, and the number of players, offside, and other things can vary. Check with your League or Club to see if they have modified the official rules. 

We have simplified the Rules and made them easy to understand. The official soccer rules and guidebook are complicated, poorly organized, and hundreds of pages long. 

The articles below are cross-linked so you can easily get the answers you need.

Links to 70 Simplified Soccer Rules and Definitions: Except for the first five links, the links are in Alphabetical order.

2nd - Delete the word "Soccer" that is the first word in every link but one. Capitalize the first word that is left (like I did below) 

3rd - The first link is "Fouls". Add to the end of the text > Also see "Cards".

So it reads >

  Fouls - The 10 kinds of Direct Kick Fouls and the 8 kinds of Indirect Kick Fouls are explained. Also see "Cards".
.

4th - Replace the link Soccer offside rule (simplified and detailed versions) 

With (the link destination is the same -  http://www.soccerhelp.com/terms/soccer-offside-rule-detailed.shtml  >

   Offside rule - Detailed  - Start with the Simplified Offside Rule that is below - it is much easier to understand. At this link is a Detailed explanation of the Offside Rule. Offside is a complicated rule. The article includes a coaching tip.

5th - After the 5th Link (just below "Field size" and above "Advantage Clause") , add the same Tests Block Quote and Premium Promo you added to http://www.soccerhelp.com/Soccer_Positions.shtml , like I did below >

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

6th - Add the link below in alphabetical order (just after Offside rule - Detailed ) >

   Offside Rule - Simplified - The Simplified explanation. Read this before reading the Detailed Explanation. Includes a tip about how you can teach attackers to not be Offside.

Have the link destination be http://www.soccerhelp.com/terms/soccer-offside-rule-simplified.shtml )

7th - I want 2 links to "Offside Rule - Simplified". So, add the link below as the 3rd link, just after Cards ) >

   Offside Rule - Simplified - A Simplified Explanation of the Offside Rule. In the Alphabetical List below is a link to a Detailed Explanation. The Offside Rule is complicated. The article Includes a tip about how you can easily teach attackers to not be Offside.

Have the link destination be http://www.soccerhelp.com/terms/soccer-offside-rule-simplified.shtml )

8th - Add text beside the links as shown below 

AND Remove Quotation Marks (like I have done below) 

AND delete from the Links the text that is in Parentheses, like I have done below >

Replace the text beside ALL the links - I changed most of them  

  Fouls - The 10 kinds of Direct Kick Fouls and the 8 kinds of Indirect Kick Fouls are explained.
  Cards - Explains the 7 offenses for which a Yellow Card can be given and the 7 offenses for which a player must be shown a Red Card and sent off the field.

(Dustin - See number 7 above - it is a link to  Offside Rule - Simplified  here ) 

  Field diagram- A diagram of the parts of the field.
  Field size - Recommended field sizes for different ages - U6, U8, U10, U12, U14 and Adult.

"Your stuff is the best I have ever read. I have been coaching for 35 years and wish I had your insights long ago." Scott, VT, Premium member

"At every practice we do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

"The difference in everyone's play since we started with the motivational patches is amazing." Coach Michael, FL

"Using the SoccerHelp concepts and the incentive patches, my soccer team just finished the season 8-0-0. This is the same team that last Fall was winless and only scored one goal." Dan, GA

Save $5 on SoccerHelp Premium - SoccerHelp Premium has 1,500 pages & 5,000 links for easy navigation. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. 15,000 Coaches have subscribed. 5-day money back guarantee. 1,000 Testimonials Sign up at http://soccerhelp.com/members/signup

  Advantage clause - Explains why the Referee may decide to not stop play even though a foul has occurred.
  Age rules - How to determine a player's "soccer age". A player's "Soccer Age" refers to the age group a player is placed in, such as "Under 8", which is called U8.
 Assistant referee - aka "Linesman"
  Ball - Explanation of soccer ball sizes and how to select a ball.
  Booking - What it means when the Referee "books" a player. 
  Box - aka the Penalty Box and Penalty Area. The large box in front of the goal in which the goalkeeper can touch the ball with hands. 
  Cards - Cards are explained. Also see Fouls. 
  Caution - When the Referee shows a player a Yellow Card.
  Center circle - The circle in the center of the field on the Halfway Line.
  Center mark - The mark in the center of the Center Circle on which the ball is placed for a kick-off.
  Coaching Do's and Don'ts - A list of things youth coaches are should do and not do. Above that, see no. 18, "Things You Are Not Allowed To Do".
  Coaching during games - If you are a Rec coach and only practice once a week, your players will learn faster if you coach during games. This article explains how to do that effectively.
  Corner flags - Flags that mark the corners of the field.
  Corner kick - Corner Kicks, how offside applies, when a Corner Kick is awarded and the procedure, and the rules. A goal may be scored directly from a corner kick.
  Dangerous play - Explains Dangerous Play and the penalties for Dangerous Play.
  Direct free kick - On a direct kick, a goal can be scored by kicking the ball into the goal without it first touching another player. 
  Encroachment - When a defender is closer than the rules allow on a goal kick, corner kick, free kick, kick off, or penalty kick.
  End line - aka the Goal Line
  Equipment - Rules regarding shin guards, cleats, clothing, jewelry, etc.
  Fair charging - See Shoulder Charge.
  Field center - The terms "center" and "middle" are often confused. The Center is an imaginary line between the 2 goals. The Middle is where the Middle Third of the field is and includes the Halfway Line.
  Field corner arc - The small arc at each corner of the field.
  Field diagram - A diagram of a soccer field.
  Field lines - Rules about the lines that define the field and that are on the field. When the ball is out of bounds, when the ball can be placed on the line, etc.
  Field "middle - The terms "middle" and "center" are often misused. The Middle is where the Middle Third of the field is and includes the Halfway Line, from sideline to sideline. The Center is an imaginary line between the 2 goals.
  Field size - Recommended field sizes for various ages.
  Forwards - Forwards are the primary scorers who usually play closer to the other team's goal than Midfielders and Fullbacks.
  Fouls - The 18 kinds of Fouls are explained.
  Free kick - The rules for Free Kicks are explained. There are 2 types of free kicks (direct and indirect) and a special type of Direct Free Kick called a Penalty Kick.
  Fullbacks - Fullbacks are primarily Defenders who usually play closer to their own goal than Midfielders and Forwards.
  Goal, when scored? - A goal is scored when the ball totally crosses the end line inside the goal.
  Goal area - aka the Goal Box. The small box in front of the goal within which the ball must be placed to take a goal kick - the ball can also be placed on the line that defines the Goal Box.
  Goal kick - Rules and tips.
  Goal line - aka the end line. The lines that define the ends of the field. 
  Goalkeeper - Also called GK or Goalie or Keeper. Rules affecting the Goalkeeper.
  Halfway line - Line across the middle of the length of the field (sideline to sideline) that splits it into two equal halves.
  Hand ball - When touching the ball with hands is allowed and not allowed. Definition of the "hand". Penalties for using hands.
  Impeding - Explanation and examples of "impeding". "Impeding the Progress of an Opponent" is an Indirect Kick Foul. This used to be called "obstruction". 
  Indirect free kick - Rules and tips. On an indirect kick, another player (on either team) must touch the ball before a goal can be scored. How to know if an indirect or a direct kick foul has been called. 
  Injuries - Rules and expected behavior when a player is injured on the field.
  Injury time - "Stoppage Time" is the correct term. This applies to high-level matches but not to most youth matches.
  Kick off - Rules and tips for kick offs.
  Late tackle - A Late Tackle is usually a slide tackle that makes contact with the ballhandler just after he has passed the ball.
  Laws of the Game - The rules of soccer.
  Lines - Rules relating to stepping on lines and the ball crossing the line.
  Linesman - Assistant Referees used to be called Linesmen.
  Midfielders - Midfielders usually play between Fullbacks and Forwards.
  Number of players - The official rules call for 11 players per side, but youth leagues usually reduce the number so players get more touches on the ball. Some leagues play with as few as 3 or 4 field players per side and no goalie.
  Obstruction - See "Impeding" above.
  Offside rule - Detailed  - Start with the Simplified Offside Rule that is below - it is much easier to understand. At this link is a Detailed explanation of the Offside Rule. Offside is a complicated rule. The article includes a coaching tip.

(Dustin - see number 6 above - add a link to  Offside Rule - Simplified  here - see number 6 above ) 

  Penalty area - aka the "Penalty Box" or "Box". This is the large box in front of the goal in which the goalkeeper can touch the ball with hands. 
  Penalty box arc - aka the "D". The half circle at the top of the Penalty Box.
  Penalty kick - aka "PK". Rules are explained. This is a special type of Direct Free Kick. Tips.
  Playing time - Most recreational leagues have a rule that each child must play at least 50% of every game he or she attends.
  Red card - A Red Card means a player is ejected from the game and may not be replaced. A Red Card does not have to be preceded by a Yellow Card.
  Referee - Most youth games have one referee on the field, called a "Center Referee", who is the referee-in-charge and some also have 2 Assistant Referees (Linesmen).
  Re-start - A Re-start happens any time play is stopped and restarted, such as on a Corner Kick, Goal Kick, Throw-In, Kick-Off, Free Kick or Penalty Kick.
  Sandwiching - Sandwiching is a foul that occurs when 2 or more teammates "hold" an opponent by boxing him in - it is penalized by a direct kick.
  Serious foul play - For Serious Foul Play, a player must be given a "red card" & "sent off" the field.
  Shoulder charge - aka Shoulder Tackle and Fair Charge. Rules for a legal Shoulder Charge,. A type of "tackle" which can be legally used to try to "win" (i.e., gain possession of) the ball.
  Side line - aka the "touch line". The long sides of the field.
  Slide tackle - Rules for when a Slide Tackle is a foul. A Slide Tackle is when a defender slides on the ground and attempts to kick the ball away from the ballhandler.
  Small sided - Definition of small-sided play and the advantages.
  Stoppage time - aka "Injury Time". This applies to high-level matches but not to most youth matches.
  Substitutions - Rules, procedures and tips for substituting players.
  Throw in - Rules for Throw-Ins.
  Touch line - aka the Side Lines. The long sides of the field.
  Unsporting Behavior - The Referee can give a Yellow Card for behavior that the Referee thinks is unsporting or causes an unfair advantage. Click the link for examples.
  Warning - Often the Referee will give a player an informal warning before giving a Yellow Card.
  Worrying the goalkeeper - This is explained. It is a foul to harass, interfere with, or obstruct the Goalkeeper from putting the ball into play.
  Yellow card - A Yellow Card is a serious "caution". Two Yellow Cards in one game and the player is shown a Red Card and ejected. See "Cards" above for more.
  Things you are not allowed to do - No. 18 at this link lists things coaches are not allowed to do. For example, Coaches may not go onto the field during a game except with the referee's permission.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.  Please take a peek at it to ensure this is what you wanted.

**Comment by david-huddleston** [comment]
Dustin, I posted the changed to this on GitHub
