### ISSUE TITLE
Premium Alphabetical Drills List - add (definitely try this) & "(definitely play this)" beside 2 links, 9-15-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#409]
I emailed this on 9-15-17 at 11:23 AM - use the email to see colors

Dustin, on http://www.soccerhelp.com/Soccer-Games-Drills-List.shtml >

1st - the first link is

1 vs.1 Attacking & Defending Game (4 Stars) New

Replace  New  with (definitely try this)

So it reads > 

1 vs.1 Attacking & Defending Game (4 Stars) (definitely try this)

2nd - the 4th link is > "Aggressive Play Game" * * * * Video of This

To the right of it add >

(definitely play this) 

So it reads >

"Aggressive Play Game" * * * * Video of This (definitely play this)

**Comment by dustinschaerer** [comment]
@david-huddleston I don't see the first link on the page being

1 vs.1 Attacking & Defending Game (4 Stars) New

Is this the right page?

**Comment by dustinschaerer** [comment]
@david-huddleston Are you sure this is the right page? I don't see that first link you mentioned above.

**Comment by dustinschaerer** [comment]
I got it! This is the page you want hte changes on: http://www.soccerhelp.com/premium/Alphabetical_Practice_Games.shtml

I'm on it now!

**Comment by dustinschaerer** [comment]
This is completed!
