### ISSUE TITLE
Add a New 5th Premium Test, Josh, 9-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#412]
I emailed this on 9-19-17 at 11:07 AM

Dustin, add below as a new  5th  Premium Test (below " -- --Dan, U8 Rec, assigned players, OH, Premium member & patch customer ")> 

"I've gotten quick and dramatic results after using the tips and strategies on your Premium site for just 2 weeks. We play 9 v 9, and I've got a mix of about 5 travel and travel-quality players, 4-5 average players, and 2-3 weak players. We don't have much team speed. The results have been unbelievable. Since adopting these strategies, we have won 3-1 (against a team from a neighboring suburb that usually dominates us with very skilled players), 4-1, and 1-0. We are no longer giving up breakaways, the kids are getting much more aggressive and strong on the ball, and they are getting the idea of passing to space to our faster forwards. I feel we can stay competitive in almost any match."
-- Josh, U12B, 9v9, IL, Premium Member

**Comment by dustinschaerer** [comment]
Completed.
