### ISSUE TITLE
Soccer Rules Changes, 9-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#413]
Dustin, on  http://www.soccerhelp.com/simplified-soccer-rules.shtml >

1st -  Replace the 2nd test with >

"At every practice we do Dribble Across a Square, Dribble Around A Cone and Pass, etc. - the poise my boys have on the ball is leaps and bounds above other teams now. Before, we were 4 wins 5 losses. Last season our record was 9 Wins 1 Tie." Coach T, U12 travel, MA, Premium member

2nd - at "Advantage clause", replace the text with >

 Explains why the Referee may decide to not stop play even though a foul has occurred.
 
3rd - at  "Age rules", replace the text with >

How to determine a player's "soccer age". A player's "Soccer Age" refers to the age group a player is placed in, such as "Under 8", which is called U8.

4th - Ccaution is misspelled (should be Caution )

5th - change the link destination of  "Age rules (U-6, U-8, etc.)"  to > http://www.soccerhelp.com/Basic_Info.shtml#recreational_select_soccer 

6th - In the link "Age rules (U-6, U-8, etc.)" , remove the 2 hyphens, so it reads > "Age rules (U6, U8, etc.)"

7th - change the link destination of  "Coaching Do's and Don'ts"   to > 
 http://www.soccerhelp.com/Basic_Info.shtml#be_a_good_role_model

8th - change the link destination of  "Coaching during games"   to > 
http://www.soccerhelp.com/Basic_Info.shtml#things_you_should_do

9th - change the link destination of  "Equipment"   to >  
http://www.soccerhelp.com/Basic_Info.shtml#rules

10th -  change the link destination of  "Playing time"   to >  
http://www.soccerhelp.com/Basic_Info.shtml#team_names_and_cheers

11th - change the link destination of  "Things you are not allowed to do"   to >
http://www.soccerhelp.com/Basic_Info.shtml#be_a_good_role_model

**Comment by dustinschaerer** [comment]
This is completed.
