### ISSUE TITLE
Kick-off changes to 2 pages on Basic, 9-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#414]
I emailed this on 9-19-17 at 4:08 PM

Dustin, make the same change to 2 pages >

- http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_K.shtml

- http://www.soccerhelp.com/terms/soccer-kick-off.shtml 

1st - The 9th, 10th and 11th sentences are >

However, the ball must move forward on the "kick off". The "kicker" may not touch the ball again until someone else (on either team) has touched it. However, the "kicker" may put his foot on top of the ball & barely move it forward so a teammate standing nearby can dribble it or pass it backward or forward. 

Replace those 3 sentences with the 2 sentences below >

The ball can go in any direction on the "kick-off" (forward, backward or sideways). The "kicker" may not touch the ball again until someone else (on either team) has touched it. 

2nd - AND about halfway thru is the sentence >

Some coaches teach passing the ball backward on kick off (after it has been touched by the kicker).

Delete >  (after it has been touched by the kicker) 

So it reads >

Some coaches teach passing the ball backward on kick off.

**Comment by dustinschaerer** [comment]
This is completed also.
