### ISSUE TITLE
Premium changes to Kick-off in 3 places, 9-19-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#415]
I emailed this on 9-19-17 at 4:07 PM

Dustin, 

On 3 pages, make the same change >

- http://www.soccerhelp.com/premium/Kick-Offs_Navigation_Page.shtml

- http://www.soccerhelp.com/premium/Dictionary_K.shtml#kick-off

- http://www.soccerhelp.com/premium/Kick-Offs.shtml  

at Kick-off Rules  , the 3rd, 4th and 5th sentences are > 

However, the ball must move forward on the "kick-off". The "kicker" may not touch the ball again until someone else (on either team) has touched it (if he does, the opponent gets the ball and an "indirect kick"). However, the "kicker" may put his foot on top of the ball & barely move it forward so a teammate standing nearby can dribble it or pass it backward or forward.

Replace them with >

The ball can go in any direction on the "kick-off" (forward, backward or sideways). The "kicker" may not touch the ball again until someone else (on either team) has touched it.

**Comment by dustinschaerer** [comment]
This is completed.
