### ISSUE TITLE
9 More Soccer Rules changes, 9-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#420]
I emailed this on 9-20-17 at 6:57 PM -  use the email to see the colors and the Red Balls.

Dustin , on http://www.soccerhelp.com/simplified-soccer-rules.shtml >

Below are changes to links that are to one sentence definitions. I want to turn the link into Black Text and put the definition to the right of it  - SO, the "links" listed below will NO longer be links - they will be text (leave the red    , like I did below>

1st - Replace

   Caution - When the Referee shows a player a Yellow Card.

with 

   Caution - An official disciplinary action where the Referee shows a player a "Yellow Card".

2nd - Make  Center mark   black text BUT the text to the right is Okay.

  Center mark - The mark in the center of the Center Circle on which the ball is placed for a kick-off.

3rd - Make  Corner flags  black text BUT the text to the right is Okay.

  Corner flags - Flags that mark the corners of the field.

4th - Make Encroachment  black text BUT the text to the right is Okay.

  Encroachment - When a defender is closer than the rules allow on a goal kick, corner kick, free kick, kick off, or penalty kick.    

5th - Replace  "Fair charging" (see shoulder charge)  with Fair charging  , like below. The text to the right is Okay.

  Fair charging - See Shoulder Charge.

6th - Make Field corner arc  black text BUT the text to the right is Okay.

  Field corner arc - The small arc at each corner of the field.

7th - Make  Linesman black text BUT the text to the right is Okay.

  Linesman - Assistant Referees used to be called Linesmen.

8th - Make Obstruction  black text BUT the text to the right is Okay.

  Obstruction - See "Impeding" above.

9th -  Make Penalty box arc  black text BUT the text to the right is Okay.

  Penalty box arc - aka the "D". The half circle at the top of the Penalty Box.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed!
