### ISSUE TITLE
Basic Info - change 4.d. of Equipment (about Soccer Balls), 9-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#421]
I emailed this on 9-20-17 - use the email to see the Bold.

Dustin, on http://www.soccerhelp.com/Basic_Info.shtml#equipment

4.d. is >

Each player should have a stitched ball (as opposed to a hard seamless ball) of proper size. (Soccer balls come in 3 different sizes: 3, 4, & 5. The ball size is shown on the ball. Also, look for a stamp that says either "official size & weight" or "FIFA Approved". Even if a ball is the official weight, some balls are heavier & harder than others. Don't get a ball that is too heavy or hard (some seamless balls are especially hard). Some balls are so hard that it is painful to kick them. If you have a choice, a shiny, waterproof surface is best because it won't absorb water & will last longer. Test the ball to see if it's round & will fly straight by tossing it into the air with a lot of spin on it to see if it wobbles. U-6 & U-8 (i.e., Under-6 & Under-8) use a size 3; U-10 & U-12 use a size 4; and U-13 & older use a size 5 ball).

Replace it with  >

Soccer Ball Sizes and How to Select a Ball - Each player should have a stitched ball (as opposed to a hard seamless ball) of proper size. Soccer balls come in 3 different sizes: 3, 4, & 5. The ball size is shown on the ball. Also, look for a stamp that says either "official size and weight" or "FIFA Approved". Even if a ball is the official weight, some balls are heavier and harder than others. Don't get a ball that is too heavy or hard (some seamless balls are especially hard). Some balls are so hard that it is painful to kick them. If you have a choice, a shiny, waterproof surface is best because it won't absorb water and will last longer. Test the ball to see if it's round and will fly straight by tossing it into the air with a lot of spin on it to see if it wobbles. Usually, U6 and U8 (i.e., Under-6 and Under-8) use a size 3; U10 & U12 use a size 4; and U13 & older use a size 5 ball, BUT check with your League to see what size you should buy. If you coach U6, do NOT overinflate the balls - in fact, carry an air pump "needle" so you can let air out of balls that are too hard - a hard ball can hurt little feet and make kids not want to kick the ball - it is better for them to be soft than too hard.

**Comment by dustinschaerer** [comment]
This is completed.
