### ISSUE TITLE
October - 6 Testimonials to add, 10-3-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#422]
Dustin, add the Tests below >

---- To PATCH Tests >   

Add as the Number 8 Patch Test >

"Today, we had our most impressive win in about 10 years, defeating a Team by slaughter rule 9 to 2, that we had previously lost to last year 4-0. I have used many of the SoccerHelp Premium techniques and I feel that we are finally starting to build a solid program. We still have a tremendous amount of work ahead of us to prepare for a very good opponent that we will play on Thursday, however is definitely a good start for us. We did not score nine goals the entire year last year! Having said all that, I just placed another patch order. Thanks again for all your help."
   -- Brian, VA, Middle School coach, Premium member

AND Add as the Number 10  and 11 Patch Tests (above the Test from Jeff, the Baseball coach)>>>

"Brilliant!!! I have used these patches in the past for my sons Travel Team I coached for years with positive results using these patches... I have dropped back to coach my daughters U10 Travel Team, once again these patches have proven to be a fun motivational tool for these young players. I use them for self accomplishments at practice and games as well as team accomplishments win or lose. The young players really enjoy collecting the different colors. Thank you for making such a simple motivational tool available to coaches and young soccer players everywhere...Well Done!"
  -- Dominic, U10 Girls, PA

"The patches are a huge hit!  I hand them out after every practice and game.  The kids are really motivated to get the patches."
  -- Kristen, U4 and U8, MA

-----------------------------

---- Add as the number 10 and 11  Premium Test, just below the "Nick" test > 

"With the practice games and information provided on SoccerHelp, I have managed to create an incredible atmosphere for my young players to really enjoy the game of soccer at the same time having almost every coach in the league stopping by once or twice a season to watch how I run my practices. By the time our first game is here we are a team that is unbeatable. Anyways I could go on for hours with this type of praise ." 
  -- Coach Gregg GA, U10, Premium Member for 2 years

"Today, we had our most impressive win in about 10 years, defeating a Team by slaughter rule 9 to 2, that we had previously lost to last year 4-0. I have used many of the SoccerHelp Premium techniques and I feel that we are finally starting to build a solid program. We still have a tremendous amount of work ahead of us to prepare for a very good opponent that we will play on Thursday, however is definitely a good start for us. We did not score nine goals the entire year last year! Having said all that, I just placed another patch order. Thanks again for all your help."
   -- Brian, VA, Middle School coach, Premium member

---- AND  Add to the end of PREMIUM Tests >

"Well coach, not surprisingly you were right. We've had two games since. A 4-0 win last week, and today a 3-0 win against a team that was 3-1, in 90 degree humid sunshine. Even in the 4th quarter when everyone was extremely fatigued, we got our third goal and missed a 4th by inches. Thank you for the tips on your site about playing in the heat. The ice water in a garden sprayer is a great idea, and I have no doubt it helped today!"
  -- Dan, OH

**Comment by dustinschaerer** [comment]
This is completed.

D
