### ISSUE TITLE
Dustin, question about BlogVault - Coach Doug backups, 9-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#423]
Dustin, is there any reason to keep backing up https://soccerhelp.com/coachdoug in BlogVault? It hasn't backed up in 20 days. 

It is also backing up http://www.soccerhelp.com/coachdoug

**Comment by dustinschaerer** [comment]
I'll remove it.

**Comment by dustinschaerer** [comment]
@david-huddleston It's removed.
