### ISSUE TITLE
October - http://6yearoldsoccerdrills.com/ changes, 9-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#424]
I emailed this on 9-26-17 at 10:35 AM - use the email so you can see the links.

Dustin, in October - 

On http://6yearoldsoccerdrills.com/ there are 2 links.

1st - Change the Destination of both links to >  http://www.soccerhelp.com/u6-Soccer-Drills.shtml 

2nd - the 2nd para is >

The best soccer drills for 6 year olds, U4 and U6 are not actually drills, they are Practice Games.

Make that link longer, so it includes the words " for 6 year olds ", and the link reads >

The best soccer drills for 6 year olds, U4 and U6 are not actually drills, they are Practice Games.

**Comment by dustinschaerer** [comment]
This is completed.
