### ISSUE TITLE
October - http://www.soccerhelp.com/u6-Soccer-Drills.shtml, delete link at top, 9-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#425]
Dustin, on http://www.soccerhelp.com/u6-Soccer-Drills.shtml , delete the link near the top of page (just below the title) >

Watch the Free Coach Doug DVD Video Clips of How to Coach Ages 3, 4, 5 and 6

**Comment by dustinschaerer** [comment]
This is completed.
