### ISSUE TITLE
October - Second Version - Add a new domain to BIR-2 - u8soccerdrills.com , 9-27-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#427]
I emailed this on 9-27-17 at 11:13 AM - use the email to see bold, the format, fonts and links.

Dustin, delete the prior version that I sent on 9-26-17 at 3:23 PM

Dustin, the Domain www.u8soccerdrills.com  is in GoDaddy but doesn't have a website.

Create a website on BIR-2 as shown below >

(a). Have the Title Tag, Description and Key Words be >

U8 soccer drills for kids age 7 and 8

(b). Dustin, rather than Text Links, use  www.soccerhelp.com/u8-Soccer-Drills.shtml and  www.soccerhelp.com/soccer-drills.shtml , as shown below. 

(c ). Can you make the page responsive? (if that is a problem, don't worry about it).

(d). Add the following sentence and link on the bottom of  www.soccerdrills.net  , just below "Site Map"  >

For U8 soccer drills, visit www.u8soccerdrills.com 

-----------------------

U8 Soccer Drills for Kids Age 7 and 8

If you coach U8 soccer, you will want the Best Drills that do 4 things -

1. Skills - Use drills that teach the most important soccer skills. 

2. No Lines - That means there aren't any lines, so ALL your players are practicing instead of standing in line. That is VERY important because standing in line is boring and wastes a lot of time. Your players will improve twice as fast if you use SoccerHelp No Lines Drills that teach soccer skills. Because they improve fast, they will enjoy practice and gain confidence. They will also play better and your team will win more games. 

4. Use Drills that are Practice Games - You will get MUCH better results if you use drills that are Practice Games. The reason is because Practice Games are more like real games and prepare players for real games. Kids will play as they practice - practice should teach skills that can be used in real games. Do NOT play silly games like "Body Parts Soccer" that can be confusing. SoccerHelp Practice Games keep score, are competitive, and players must play fast to win - so they train players to play fast while under pressure, like they must be able to do in real soccer matches.

4. Why Fun Matters - Fun drills are a lot better than drills that are boring because kids will enjoy coming to practice if the drills are fun. If they aren't fun, they might quit. SoccerHelp has developed No Lines drills that are fun.

Below are the best U8 Soccer Drills and No Lines Practice Games.

Over a 20 year period SoccerHelp has developed No Lines Drills that really work and teach real soccer skills. The proof is that there are hundreds of Testimonials from coaches about how SoccerHelp drills helped their players. The Soccer Journal published an article about SoccerHelp No Lines Practice Games over 10 years ago. The SoccerHelp drills continue to be improved based on feedback from coaches. SoccerHelp also provides other important tips for U8 coaches - such as how to teach positions and keep players from Bunching Up. 

Definitely try the Dribble Across a Square Practice Game - It is the best way to teach dribbling because every player has a ball and the players dribble across a square thru each other (all at the same time), instead of dribbling around cones. Dribbling thru other players gets players used to the chaos of real games and they develop instinctive reactions when they are in "traffic", just like they must be able to do in real games. There are testimonials from coaches who say that Dribble Across a Square taught their players fantastic dribbling skills. Dribble Across a Square was invented by SoccerHelp as a way to teach dribbling in traffic - it is only on SoccerHelp.

After 3 practices using the SoccerHelp No Lines Drills, you will notice that your players have improved. By the end of the season, you will notice a big difference and that your players have improved more than players on teams that don't use SoccerHelp drills.

For U8 soccer drills, instructional videos, and to read what U8 coaches say about how SoccerHelp No Lines Practice Games helped their players, visit www.soccerhelp.com/u8-Soccer-Drills.shtml 

There are instructions and videos for Dribble Across a Square and other SoccerHelp No Lines Soccer Drills at www.soccerhelp.com/soccer-drills.shtml

**Comment by dustinschaerer** [comment]
This is all completed, and I was able to make the page responsive.
