### ISSUE TITLE
October Priority- 3rd Version - Change to Dribble Across on Premium AND on Basic, 9-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#428]
I emailed this on 9-26-17 at 5::50 PM - use the email so you can see underlinines.

Dustin, delete the version I sent on 9-26-17 at 5:44 and 5:47 and use this one. 

Dustin, on http://www.soccerhelp.com/premium/practice_games/Dribble.shtml AND on http://www.soccerhelp.com/soccer_drills/Dribble.shtml , replace the Bullet Points under "Summary" with >  
•	Players dribble across a square and back from 4 directions. First to make 6 turns wins. Play 3 or 4 times with a small square to teach Control Dribbling in traffic and 3 more times with a larger square to train players to look for Open Space and to accelerate into Open Space (the larger square teaches players to speed up when they see Open Space). Only play to 6 and then start over - that works better than playing to 8 or 10 because it gives the kids lots of chances to win and forces them to give 100% effort. 
•	See the Diagram. Use 4 disk cones to make a square about 10 steps wide (smaller or larger depending on the age & number of players) -- make your "steps" the size of your players - so a "step" for U8 is shorter than a "step" for U12 - by doing this, the square will always be the correct size for your players.
•	Every player has a ball.
•	Spread players around the square, all facing inward (like the Diagram).
•	On "Go", all players dribble across to the opposite side of the square and turn, go back and turn, etc. Every turn is one point. Players keep their own score. Have the first player to reach 6 yell "Done" and raise his hand. As soon as a player yells "Done", blow your whistle and have all the other players stop as soon as they get back to the closest side of the square. Then, ask each player his score so you can monitor each player's progress and give tips for improvement.
•	Small Square and Larger Square - Play this game 3 times to 6 with the Square about 10 steps wide (use a "step" the length of your players steps) AND 3 MORE TIMES to 6 with the Square 50% larger (e.g., about 15 of your player's steps wide). The larger square will create over twice as much Open Space and will train players to look for Open Space and to accelerate into Open Space (in the large square, players have to do that to win - if they don't do that they will lose).
•	To keep it competitive and fun, make a Rectangle instead of a Square, and have your best players dribble across the long side and the "weak players" dribble across the short side. Adjust the lengths of the sides so it balances things out and creates a challenge for everyone (for example, make it 8x10 instead of 10 x 10). After each game, move the player who won the "weak group" to the "better group" and move the player with the lowest score in the "better group" to the "weak group" - that will keep it competitive.
Give a Tip after each game about how players can improve. For example - "You must look up while you are dribbling in traffic so you don't run into other players." and "You must keep control of the ball when you turn or you will lose." and "If you see Open Space, speed up by kicking your ball into the Open Space and running to it, BUT don't lose control of your ball - you must make your turn or you will lose." and "When you are in traffic, you must keep the ball near your feet or it might get accidentally kicked." (Tell players the rule is that they CANNOT intentionally kick balls away, but that in traffic balls might get accidentally kicked.) Watch the mistakes players make for ideas for Tips.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
