### ISSUE TITLE
Oct., Add to http://dribbleacrossasquare.com/, 9-27-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#429]
Dustin, on http://dribbleacrossasquare.com/,  add at the top, CENTERED under the title >

An updated version of this No Lines Drill is at www.soccerhelp.com/soccer-drills.shtml 

(Dustin, use the actual URL for the link, as shown above)

**Comment by dustinschaerer** [comment]
COMPLETED.
