### ISSUE TITLE
Credit Card Processing Encryption question, 10-4-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#432]
Dustin, I got the email below from Bank of America - Payeezy.  Are we okay with >

• | What: Confirm you can support TLS 1.2 encryption   technology
• | When: By January 24, 2018
• | Why: To avoid processing disruptions and to   protect against possible security breaches
• | How: Ensure you are processing with current   technology, i.e., PC operating systems and/or internet browsers. If you have   questions, contact the Payeezy Gateway Technical Support Team at Payeezy.Gateway.Support@firstdata.com   or 855.448.3493.

**Comment by dustinschaerer** [comment]
@david-huddleston Yep we are good to go!
![tls1-2-soccerhelp](https://user-images.githubusercontent.com/1232192/31188367-81885804-a8e9-11e7-84bc-19397ed129a6.png)
