### ISSUE TITLE
November - maybe switch to Stripe and Amazon Pay, 10-6-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#434]
Let's talk about this.

**Comment by dustinschaerer** [comment]
@david-huddleston Just wanted to let you that Stripe does  have integration with Amember already built, and open cart supports stripe through a plugin, that is $119.99.

So we should haven't any foreseeable hurdles moving to Stripe.

**Comment by dustinschaerer** [comment]
@david-huddleston I'm working on the stripe stuff now. I'll keep you posted.
