### ISSUE TITLE
November - Change Aggressive Play link on Premium Home page, 10-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#438]
I emailed this on 10-17-17 at 1:38 PM

Dustin, on Premium Home >

change the link  Aggressive Play - How To Teach 
to say >   Aggressive Play Drills & Games

Have it still go to http://www.soccerhelp.com/premium/Aggressive_Play_Practice_Games.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
