### ISSUE TITLE
November - change Premium "Bravery - How to Teach" link, 10-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#439]
I emailed this on 10-17-17 at 1:47 PM

Dustin, on Premium Home page, change the link >  
Bravery - How to Teach

to Say > 

Bravery - How to Teach No. 2

The link goes to http://www.soccerhelp.com/premium/Brave_And_Aggressive_Play.shtml

**Comment by dustinschaerer** [comment]
This is completed.
