### ISSUE TITLE
On Bottom of SH Home & other pages, add one row of Responsive Footer Links

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#44]
Dustin,

 I sent you this in an email on 6-14-17 at about 6:30 PM.

As discussed, on the bottom of SH Home AND on the bottom of all the other pages like http://www.soccerhelp.com/soccer-drills.shtml (but not the "Articles or "Drills" folder of pages) >

, add a row of small responsive Footer Links >

Contact Us   Site Map   About  Privacy Policy

Dustin,  Have the links go to >

Contact Us to  http://www.soccerhelp.com/soccershop/contact 
   
Site Map   to  http://www.soccerhelp.com/sitemap.html 

"About"   to  http://www.soccerhelp.com/about.shtml  (Dustin, this page doesn't exist - I will send it to you soon)

Privacy Policy   to  http://www.soccerhelp.com/Privacy-Policy.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
