### ISSUE TITLE
November - new article for Basic & Premium about Aggressive Play, 10-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#440]
I emailed this on 10-17-17 at 2:11 PM - use the email to see Bold, colors and links

Dustin, delete the version that I sent on 10-17-17 at 2:07 PM -- it had the wrong date  - it said 10-16-17 instead of 10-17-17

============

Dustin, 
Put the new article below on Both Basic and Premium.
On Basic > 
1. put it in the good Style Sheet and bootstrap it so it is mobile responsive
2. have the URL be > www.soccerhelp.com/aggressive-soccer-how-to-teach.shtml 
3. Have the Title Tag be > How to train aggressive soccer players.
4. Have the Meta Description be >  How to teach youth soccer players to be aggressive, tough and Brave. 
5. Have the Key Words be > Teach train aggressive soccer players
6. Put 3 links to it on SH Home >
Aggressive Soccer - How To Teach
and also >
Bravery - How to Teach
and also >
Timid Soccer Players

On Premium >
1. have the URL be > www.soccerhelp.com/premium/aggressive-soccer-how-to-teach.shtml 
2. Put 2 links to it on Premium Home that say >
Aggressive Play - How To Teach
and also 
Bravery - How to Teach

========== the article is below ==========================

How to Teach Players to Be Aggressive and Brave
Below is my reply to a Rec soccer coach who had several Timid players who were afraid of contact. He is a Premium member, so the links are to Premium. This article is from SoccerHelp Premium.

You can't make a slow player fast or turn an unathletic player into a great athlete, BUT you can teach and train most kids to be Brave (kids like the word "Brave" a lot better than "Aggressive" or "Tough" because heroes are Brave). EVERY player can be Brave. Kids who are afraid of contact can’t be good soccer players so it is important to teach motivate, praise and reward Bravery. Being scared of contact limits the positions that a player can successfully play. For example, if a player is afraid of contact, you don’t want to put him at Fullback (especially Center FB) because opponents can use him as a screen to block the Goalie's view and you will give up a lot of goals. And if a player can't Win the Ball, you can't put him at Stopper or Center Mid. The safest place for Timid players is Right Mid, Left Mid or Forward, but a player who is scared of contact is limited at Forward. 
Below are ideas for how to motivate, teach, train, and reward Bravery and Aggressive Play >

1. How to Motivate, Praise and Reward Bravery - Praise and reward Bravery by your players at a ceremony in front of ALL players - do this after every practice and after every game. Give a Bravery Patch to the players who have done something Brave - the players can iron the patch on their jersey or practice shirt and it becomes a visible sign of Bravery - like a Badge of Honor. It doesn’t have to be the B Patch - with boys a Red soccer ball works best if the coach calls it a “Blood Patch”. That approach creates a “Positive Peer Pressure” environment where it is cool to be Brave. When the Timid kids see the other kids earning Bravery Patches and being praised, they start to want to be Brave too.

2. To Train your Players, Play the SoccerHelp Aggressive Play Practice Games to get them used to contact - 7 of them are at www.soccerhelp.com/premium/Aggressive_Play_Practice_Games.shtml. Especially try "Win the 50/50 Ball or Be the First Defender" at www.soccerhelp.com/premium/practice_games/Win_The_Ball.shtml and "1v1 Attacking and Defending" at www.soccerhelp.com/premium/practice_games/1v1_Attacking_Defending.shtml . If players aren’t Brave they will never win a 50-50 Ball. Give Praise for winning those games. You can make the games a competition by keeping score and letting Winners play against Winners and Losers against Losers - or do a Round Robin. It is worth playing them for 15 minutes at 3 or 4 practices. Also, Dribble Across a Square at www.soccerhelp.com/premium/practice_games/Dribble.shtml will help because it will get players used to Traffic and chaos. (Note from SoccerHelp - if you coach U6, play U6 Practice Games that involve traffic and chaos like "Hit the Coach").
3. . Be Realistic About What is Possible - Skills and using a formation and Style of Play that fit your team can compensate for athletic ability to a degree BUT speed, athletic ability and aggressiveness (or lack of those things) MAKE a difference - be realistic about that. It is very hard to beat a team that is faster, more athletic and more aggressive - if you win it is an upset and you will only win if your players have superior skills, play their positions, are better coached, and are equally aggressive. You can’t teach athletic ability BUT you can teach and motivate Aggressive, Brave Play. 

David at SoccerHelp

**Comment by dustinschaerer** [comment]
This is all completed.
- [x] Add to Basic
- [x] Update basic home with links
- [x] Add to Premium
- [x] Update Premium home with links
- [x] Update all sitemaps
