### ISSUE TITLE
November - change a "Drills" link on Premium, 10-25-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#443]
Dustin, on Premium,

at the top of all the pages except Home Page is a menu and one of the links is "Drills".

That link goes to http://www.soccerhelp.com/premium/Alphabetical_Practice_Games.shtml 

Change it so it goes to http://www.soccerhelp.com/premium/Practice_Games.shtml#listing

**Comment by dustinschaerer** [comment]
This is complete.
