### ISSUE TITLE
November - add a link to "U4, U6, U8 Navigation page, 10-26-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#444]
Dustin, I emailed this on 10-26-17 at 10:36 AM - use the email to see links

Dustin, on 

http://www.soccerhelp.com/premium/U-4_U-6_U-8_Soccer_Coaching.shtml 

add a 5th link near the top, just below > Recommendations for U4 & U6 Coaches and Soccer Leagues
Have the link say >  18 Tips for U4 & U6 Soccer Coaches

Have the link go to > www.soccerhelp.com/U4-U6-soccer-coaching.shtml

**Comment by dustinschaerer** [comment]
Complete
