### ISSUE TITLE
New "About" page to add to SH

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#45]
Dustin, add the page below as a new page on SoccerHelp.  

>I emailed this to you at 7 pm CST - use the email so you can see the link and bolding.

A link to it is in the block of links I emailed you at 6:30 PM CST on 6-14-17 to add on the bottom of pages. 

I posted this on GitHub.

URL = http://www.soccerhelp.com/about.shtml

Title tag = About Us

Description = About Soccerhelp.com. No Lines soccer drills, hundreds of coaching tips, simplified rules, formations, how to teach skills, how to teach positions, and everything you need to be a great coach.

Dustin, the link below goes to http://soccerhelp.com/soccershop/testimonials 

=========Dustin, Below is the text to put on the page ===========

About SoccerHelp.com

SoccerHelp.com is the most visited youth soccer coaching website in the U.S. for a reason. There are over 500 pages of free coaching information, including age-appropriate No lines soccer drills that are games, soccer Practice Plans, hundreds of coaching tips, simplified rules, soccer formations, how to teach skills, how to teach positions, and everything you need to be a great coach.

All youth coaches of ages 3 to 18 can benefit from our training program. The SoccerHelp training program was developed over a 20 year period with the input of thousands of youth soccer coaches. 

Don't use Line Drills - they waste time and aren't fun. Try our No Lines Drills and you will immediately see a difference. 

Your players will improve twice as fast because they will be practicing instead of standing in line. And they will have more fun, so practice attendance will improve.

There are over 1,000 Testimonials from Coaches on SoccerHelp that were sent to us by coaches. 

If you want your players to develop great fundamental skills that they can use in soccer matches, try the Free Drills on SoccerHelp and see for yourself.

You will see a difference in your players within 2 practices. It isn't unusual for teams whose coaches use the SoccerHelp program to be the best in their age group within 2 or 3 years.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
