### ISSUE TITLE
2 changes to SH Home page - Footer & Blog

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#47]
Dustin, I sent this to you by email I sent on 6-15-17 at 5:35 PM CST >

Dustin, I posted this on GitHub.

1.  On the bottom of SH Home , add the same row of small responsive Footer Links that you added to the interior pages>

Contact Us | Site Map | About | Privacy Policy

(I'm going to delete those links from the Alphabetical List)

2.  Also on SH Home, change the link name SoccerHelp.com Google Plus Articles 

to   SoccerHelp.com Google Plus Blog 

3. Delete the HTML Site Map   link on the bottom

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
