### ISSUE TITLE
Change the address at Contact Us in the Cart, 1-2-18

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#472]
Dustin, no rush on this.

on https://www.soccerhelp.com/soccershop/contact change the address to >

Soccer Help
305 Maxwell Branch Road
Cottontown, TN 37048

**Comment by dustinschaerer** [comment]
Address is updated!

![newaddress](https://user-images.githubusercontent.com/1232192/34538224-72fdae72-f080-11e7-8b50-09ead172a6b0.png)
