### ISSUE TITLE
one change to Dictionary Home Page

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#48]
Dustin, I also emailed this on 6-15-17 at 5:40 pm CST >

in http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms.shtml

The second line of the Title is >

The Dictionary Can Navigate SoccerHelp

Change it to read >

Use This to Navigate SoccerHelp

**Comment by dustinschaerer** [comment]
@david-huddleston COMPLETED
