### ISSUE TITLE
Priority - Dustin - fix an error on the Value Packs page, 4-26-18

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#481]
Dustin, on https://www.soccerhelp.com/soccershop/patch-value-packs it says >

FREE Priority Shipping on Orders over $100 anywhere in the world.

Change it to say >

FREE Priority Mail Shipping on U.S. and Canada Orders over $100.

**Comment by dustinschaerer** [comment]
This is completed.
