### ISSUE TITLE
Priority - Move SH to a New Server

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#5]
Priority - move SH to a new server before changing to Stripe

**Comment by dustinschaerer** [comment]
@david-huddleston  That might not be a bad idea. I think we should move to the new server sooner than later, so that might be a good idea.

**Comment by david-huddleston** [comment]
Also, let's wait on finishing up Amazon Pay

**Comment by david-huddleston** [comment]
@dustinschaerer  - Let's talk about how large a cPanel server I need  - how much storage, etc.

I suppose the first thing to do is to move all the domains except for SH to the BIR-1 server

**Comment by dustin** [comment]
@david-huddleston I'm not related to this project.  Please stop including me in your communications.

**Comment by david-huddleston** [comment]
Sorry - Didn't know that was happening. We will fix it.

**Comment by dustinschaerer** [comment]
@david-huddleston  I'm closing this ticket in favor of [Issue #8](https://github.com/soccerhelp/soccerhelp/issues/8)
