### ISSUE TITLE
New bir-2.com server questions - number of IP's?

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#53]
I bought the domain bir-2.com to use for the new SSD server.

Remember to tell KnownHost Sales that I get a 20% discount on the server AND on IP's and all add-ons.

1. What server? Would the SSD-1 be enough?

2. Count up the number of Domains on the old SH server and on BIR-1 and let me know. 

3.  Let's figure out how many IP's we need. I'm coming up with about 20 > 

(a). I want the 7 Soccer domains that have the best traffic to be on separate IP's > 
- on BIR-1 = soccerdrills.net 
- on SoccerHelpServer2 =  soccerdrills.org , soccerformations.com , soccerpatch.net , socceerpositions.net , soccerrules.org , youthsoccerdrills.com

(b). Put Karl's websites all on one IP

(c). Spread Downard's websites over 5 IP's IP

(d). put your Dad's websites on not over 10 domains per IP (is that 3 or 4 domains?)

(e). you can put all the other soccer domains and Jack's domains and all the other domains on one IP?

**Comment by dustinschaerer** [comment]
@david-huddleston  We have 91 extra IPs on the BIR-1.com server.  That is way too many.  I'll turn in the additional IPs today.  I'd say let's get 20 IPs to spread everyone's sites across. You don't all those IPs for my Dads sites, we can use 10 -15 domains per IP.  

![ssd-1](https://user-images.githubusercontent.com/1232192/27399896-2b9cb1ec-5673-11e7-92a6-df06990f375f.png)

Yes, I think the SSD-1is plenty big enough.

**Comment by dustinschaerer** [comment]
@david-huddleston I turned in 27 unneeded IPs on the current BIR-1.com server.  They removed them from the server, then I removed them from our allocated pool of IPs.

**Comment by dustinschaerer** [comment]
They credited us back for the unused portion of the month of those.

**Comment by dustinschaerer** [comment]
@david-huddleston Status Update:

**Karl Trucks - Repointed all the following sites' DNS to ns1.bir-2.com and ns2.bir-2.com**
78 of 79 of HIS Godaddy sites point to bir-2.com  (all but truckslaw.com)

**Downard's Sites**
We own all of his sites at Godaddy and I've updated ALL the DNS NameServer records to point to BIR-2.com

**SH Feeder Sites ( All repointed to ns1.bir-2.com)**
*************************************************
GODADDY ACCOUNTS*********************************
*************************************************
===Patch, School === (10)
academicpatches.com             // changed
behaviorrewards.org             // changed
classroombehavior.net           // changed
gradesincentives.com            // changed
gradesrewards.com               // changed
schoolincentive.com             // changed
schoolincentives.net            // changed
schoolmotivation.com            // changed
schoolrewardpatches.com         // changed
studentmotivationalrewards.com  // changed

===SoccerLinks===(3/6)
soccer-help.com         // changed
soccerhelp.biz          // changed
soccerpassingdrills.net // changed

===Soccer June 5 2009=== (11/11)
aggressivereceivingsoccer.com                    // changed
beginnersoccerdrills.com                         // changed
dribbleacrossasquare.com                         // changed
dribbleacrossasquaresoccergame.com               // changed
dribblearoundcone.com                            // changed
dribblearoundconeandpassrelayrace.com            // changed
dribblearoundconesoccergame.com                  // changed
hitthecoachsoccergame.com                        // changed
monsterinvasionsoccergame.com                    // changed
soccerhelppracticegames.com                      // changed
u6soccer.com                                     // changed

==SH BIR== (18/18)
allsoccerdrills.com         // changed
coachdoug.org         // changed
coachdougsoccer.net         // changed
coachdougsoccer.org         // changed
highschoolsoccerdrills.com         // changed
soccer-patches.com         // changed
soccerballpatch.net         // changed
soccerballpatches.net         // changed
soccerballpatches.org         // changed
soccerformations.net         // changed
soccerformations.org         // changed
soccerpassingdrills.net             // changed
soccerpositiondiagram.com         // changed
soccertryoutdrills.com         // changed
soccertryoutdrills.org         // changed
u4soccer.com         // changed
youthsoccerformations.com         // changed
youthsoccerpositions.com         // changed


==Patch, Star === (45/45)
bandrewards.net
baseballincentive.com
baseballincentivepatches.com
baseballincentives.com
baseballmotivation.com
baseballrewards.net
basketballincentivepatches.com
basketballincentives.com
basketballmotivation.com
basketballpatch.com
basketballpatches.com
basketballpatches.net
basketballreward.net
cheerleadermotivation.com
dancepatches.net
dancerewards.com
defensepatch.com
footballincentive.com
footballincentives.net
footballrewards.net
funbasketballdrills.net
happyfacepatch.net
hockeyincentives.com
hockeyreward.com
hockeyrewards.com
lightningpatch.com
martialartsmotivation.com
motivatebaseballplayers.com
motivatebasketballplayers.com
motivatefootball.com
motivatefootballplayers.com
motivatefootballplayers.net
motivationalpatches.com
rewardpatches.com
soccerballpatches.com
soccerincentives.com
soccerpatchesforkids.com
softballmotivation.com
softballpatch.com
softballpatches.com
starpatches.com
swimmingmotivation.com
victorypatch.org
volleyballmotivation.com
volleyballpatches.com


======DEAD ACCOUNTS FROM BIR-1.com REMOVED from BIR-2.com, expired at Godaddy anymore===
academicmotivation.net
behaviorreward.com
behaviorrewards.net
behaviorstudent.net
cheerleaderpatch.com
dancepatch.com
dpatch.org
gradesmotivation.com
happyfacepatch.com
hockeyincentivepatches.com
hockeypatch.net
kid-soccer-drill.com
kidsbasketballdrills.net
kidssoccercoaching.com
motivationalpatches.net
rulesofsoccer.net
schoolreward.net
smileyfacepatches.com
socceraggressiveplay.com
soccerballpatch.com
soccerballpatch.org
soccerdrillsandgames.com
soccerdrillsvideos.com
soccerformation.org
soccerhustle.com
soccerincentivepatches.com
soccerposition.net
soccerpositiondrawing.net
soccerrewardpatches.com
soccerrulesforkids.org
soccertryoutdrills.net
softballpatch.net
softballpatches.org
studentincentive.net
studentincentives.net
studentincentivesawards.org
studentmotivation.net
studentmotivationalrewards.org
studentpatches.com
studentrewardsaward.org
studymotivation.com
swimmingpatch.com
u-4soccer.com
u-4soccerdrills.com
u-6soccer.com
u8soccerdrills.com

**SH Feeder Sites - Content is copied and DNS is updated to ns1.bir-2.com**
(FROM SOCCERHELPSERVER2.COM server)
nashvillecommercialrealestatenews.com
soccerdrills.org
soccerdrills1.com
soccerformation.com
soccerformations.com
soccerhelppremium.com
soccerpatch.net
soccerpositions.net
soccerpractice.org
soccerrules.org
soccertactic.com
soccertechnique.com
starpatch.us
teachingsoccer.com
youthsoccercoaching.com
youthsoccerdrills.com
youthsoccerrules.net

**DNS pointing to BIR-2.com now on the following sites:**
6yearoldsoccerdrills.com
academicmotivation.net
mudax.com
nashvillecommercialrealestatenews.com
soccerdrills.net  
soccerdrills.org
soccerdrills1.com
soccerformation.com
soccerformations.com
soccerhelppremium.com
soccerpatch.net
soccerpositions.net
soccerpractice.org
soccerrules.org
soccertactic.com
soccertechnique.com
starpatch.us
teachingsoccer.com
youthsoccercoaching.com
youthsoccerdrills.com
youthsoccerrules.net

**Dedicated IPs have been added to each of these sites:**
soccerdrills.net 
soccerdrills.org
soccerformations.com
soccerpatch.net
soccerpositions.net
soccerrules.org
youthsoccerdrills.com

**Comment by dustinschaerer** [comment]
@david-huddleston I've gotten all the (truly just) feeder sites moved over to BIR-2.com, and all the sites' DNS pointing to the new server, except my father's domains.  I'll get those switched tomorrow morning.

All the dedicated I sites will be switched tomorrow.

**Comment by dustinschaerer** [comment]
DNS pointing to BIR-2.com now on the following sites:
http://6yearoldsoccerdrills.com
http://academicmotivation.net
mudax.com

**Comment by dustinschaerer** [comment]
On Monday,

get these sites of Karl's working:
panamacitybeachdisabilityattorney.com   
panamacitybeachdisabilitylawfirm.com  
panamacitybeachdisabiltylawyer.com  
panamacitybeachdruglawyer.com   
panamacitybeachdruglawyerattorney.com   
panamacitybeachdui.com  
panamacitybeachduilawyer.com  
panamacitybeachpersonalinjuryattorney.com   
panamacitybeachpersonalinjurylawyer.com   
panamacitybeachsocialsecurity.com   
panamacitybeachsocialsecuritydisabilityassistance.com   
panamacitybeachsocialsecuritylawyerattorney.com   
panamacitybeachwrongfuldeathlawyerattorney.com 
panamacitybeachdisabilityattorney.com/
panamacitybeachwrongfuldeathlawyerattorney.com/

everything looks good!

**Comment by dustinschaerer** [comment]
@david-huddleston - All the above sites of Karl's are working now!

**Comment by david-huddleston** [comment]
Great

**Comment by dustinschaerer** [comment]
@david-huddleston I also just updated my Dad's sites' DNS records too.
