### ISSUE TITLE
 Priority -  major changes to www.soccerhelp.com/soccer-drills.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#55]
Dustin, see the email I sent you on 6-16-17 at 1:03 PM CST so you can see the colors, links, and formatting.

Dustin, on    www.soccerhelp.com/soccer-drills.shtml 

1. The Title Tag is  "Free Soccer Drills & Practices - SoccerHelp

Change it to  

Soccer Drills - No Lines Drills & Games by SoccerHelp

2. The H1 is "Free Soccer Drills"

 Change it to "Soccer Drills"

3. The H2 is   (Dustin, Hold off on this until David figures it out)

<h2>Free Soccer Drills and Practice Games: <span class="black">(Premium has 80 drills and 1,500 pages - improve your team fast)</span></h2>

Change it to "Free Soccer Drills"

4. There isn't a H3.  (Dustin, Hold off on this until David figures it out)

Add  a H3 named >

"Soccer Drills and Games"

5. Dustin, is there a way to Add "Soccer Drills"  to an alt tag? (Dustin, Hold off on this until David figures it out)

6. No. 1 starts "Dribble Across A Square ™" (U-8 & up) * * * *

Change that link name to >

Dribble Across A Square ™ Soccer Drill for U-8 to Adult. (Definitely try this).

7. Go thru the page and Unbold the following >

(a). all the testimonials

(b). the block of text and links below >
What Coaches Say about Our Training Program:  1,000 Testimonials     Success Stories
Soccer Practice Plans
View a Copy of the SoccerHelp Premium Home Page
Read a Soccer Journal article about why SoccerHelp Practice Games are better than drills.
Tips For a Good Soccer Practice
Things You Need For A Good Soccer Practice
70 Soccer Coaching Tips
18 Tips for U4 and U6 Soccer Coaches

(c). in the last para, unbold all but >

SoccerHelp Premium contains over 70 "Third Generation" Soccer Drills that are Practice Games

8. Add schema markup 
Dustin, for how to do this, go to   https://www.google.com/webmasters/markup-helper/u/0/ . I looked at it and for an article, it seems to be about highlighting the Key Words.
QUESTION - After you read about this, do you think the bold, colored Testimonials and bold links on the page are being confused as a "schemaorg markup"? Could that be sending the wrong message to the search engines? I notice that on  https://www.soccerxpert.com/drills.aspx , the main thing that is bolded are the words "Soccer Drills". 

Dustin, unless you have a better idea, ONLY do this for the first 4 times the keyword "Soccer Drills" appears.

The Google link tells you >
- How to add the Structured Data to your source code
- Please edit your web page’s HTML source, using the highlighted text as a guideline for what to add.
- Find more properties (optional)
- The schema.org documentation lists all properties available for this type. If you see any properties you are interested in that are not available in Markup Helper, you may add them manually.
- Test your Structured Data
- After implementing the recommended markup on your website, use the Structured Data Testing Tool to make sure Google understands it correctly.

9. Canonicalize the  IP address

10. Make the changes below to the page >

(a). The first 3 lines of the title are >

Free Soccer Drills
and Free Videos of our Exclusive No Lines Soccer Drills
Your Players Will Improve Twice as Fast if You Use Our Exclusive NO LINES Practice Games

Change it to (notice that only the top title is Bold)>
Soccer Drills
Free No Lines Drills and Videos for U4-Adult

Your Players Will Improve Twice as Fast if You Use Our Exclusive NO LINES Practice Games

(b). At the first of the last para, make the words "Soccer Drills" a bold link to http://www.soccerhelp.com/  , as shown below >

SoccerHelp Premium contains over 70 "Third Generation" Soccer Drills that are Practice Games

**Comment by dustinschaerer** [comment]
@david-huddleston This is mostly completed, we discussed you were going to make a few more changes and revisions to this issue, so I left it open.  I read up on the schema.org stuff and it could prove to be useful for us.  It's pretty specific what its used for, and I think it might be able to help us with our CTR on the organic google searches.
