### ISSUE TITLE
Priority - More changes to Soccer Drills

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#58]
Dustin, I sent you this revised version in an email on 6-18-17 at 4:29 PM CST. 

Use the email so you can see colors and formatting.

I'm going to try to keep titles short so they fit a cell phone

---------------

Dustin, on    www.soccerhelp.com/soccer-drills.shtml

1. The KeyWords are currently >

soccer drills, soccer training drills, youth drills

Change it to >

soccer drills

2. The second line of the Main Title is >

Free No Lines Drills and Videos for U4-Adult

Change it to >  

Free No Lines Drills, U6 to U18

3. The third line is >

Your Players Will Improve Twice as Fast if You Use Our Exclusive NO LINES Practice Games

Replace it with >

Players Improve Twice as Fast - Guaranteed

4. The first 3 paras are >

Try our free No Lines soccer drills and videos and you will immediately see the difference. 500 Testimonials from coaches. Your players will quickly improve and you will see amazing results after 5 or 6 practices. Our drills are copyrighted and only available on SoccerHelp.
Our No Lines soccer drills are Practice Games that are fun and teach skills - your players will learn 300% more at each practice compared to Line Drills, have better skills, and play better.
Why Players Improve Faster Using SoccerHelp No Lines Drills - Over a 20 year period we invented most of the No Lines Practice Games on SoccerHelp, so they are original, copyrighted, and only found on SoccerHelp. Our No Lines Practice Games are the best and most are self-teaching, so players learn skills by playing the games. The ball-ratio is usually 50% to 100%, so players spend most of practice actively learning skills instead of waiting in line. Our Practice Games prepare players to play fast while under pressure, so players play better in real games. These are NOT silly games like Crab Soccer - this is a carefully designed system to train fundamental soccer skills. That's why there are so many Testimonials from coaches.

Replace them with >

Try our free No Lines soccer drills and your players will IMPROVE MUCH FASTER (2 or 3 times faster). The reason is because players are practicing skills instead of standing in line. And because there aren't lines, players have more fun and love to practice. This is a training program that is designed to teach fundamental soccer skills. Most of our drills are actually Practice Games that teach players to play fast while under pressure. Our drills are copyrighted and only available on SoccerHelp. There are 500 Testimonials from coaches.

5. Above the List of Links is > 
What Coaches Say about Our Training Program:  1,000 Testimonials     Success Stories
Delete ALL but the link 1,000 Testimonials 

And make 1,000 Testimonials  be the first link in the Links List

6. Move the Links List to be just above the last para (that begins " SoccerHelp Premium contains " )  

7. Create a new H2 (a Bold Subtitle) that is above the 5 Testimonials near the top (make the font size the same as the Testimonials AND Bold Black)>

Comments About Our No Lines Soccer Drills
 

8. For the H3, use the Sub-Title that is above the list of Drills , BUT change it to BOLD Black AND make the font size the same size as the text that is below it >

Free Soccer Drills

9. Make a small Image of the words  (inconspicuous, black, and not bold)>

Soccer Drills    

and have the alt tag say "Soccer Drills"

Put it on the Bottom, Flush left,  above the SoccerHelp Logo

10. In the last para, unbold all but the part below>

SoccerHelp Premium contains over 70 "Third Generation" Soccer Drills that are Practice Games

11. In the last para, make the words "Soccer Drills" a bold link to http://www.soccerhelp.com/  , as shown below >

SoccerHelp Premium contains over 70 "Third Generation" Soccer Drills that are Practice Games

12. Add schema markup 
Dustin, for how to do this, go to   https://www.google.com/webmasters/markup-helper/u/0/ . I looked at it and for an article, it seems to be about highlighting the Key Words.
QUESTION - After you read about this, do you think the bold, colored Testimonials and bold links on the page are being confused as a "schemaorg markup"? Could that be sending the wrong message to the search engines? I notice that on  https://www.soccerxpert.com/drills.aspx , the main thing that is bolded are the words "Soccer Drills". 

Dustin, unless you have a better idea, ONLY do this for the first 4 times the keyword "Soccer Drills" appears.

The Google link tells you >
- How to add the Structured Data to your source code
- Please edit your web page’s HTML source, using the highlighted text as a guideline for what to add.
- Find more properties (optional)
- The schema.org documentation lists all properties available for this type. If you see any properties you are interested in that are not available in Markup Helper, you may add them manually.
- Test your Structured Data
- After implementing the recommended markup on your website, use the Structured Data Testing Tool to make sure Google understands it correctly.

13. Canonicalize the  IP address

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed!
