### ISSUE TITLE
Dustin - changes to www.soccerhelp.com/Soccer_Tactics_Weak_Teams.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#59]
Dustin, use  the email I sent you on 6-19-17 at 7:48 PM CST  so you can see colors and formatting >

Dustin, on    www.soccerhelp.com/Soccer_Tactics_Weak_Teams.shtml 

1. The current title is >

Soccer Tactics for Weak Teams
that are Losing Their Matches

    15 Ideas to Help a Losing Soccer Team
    Soccer Aggressiveness, Defense and Scoring
    Dealing With a Humiliating Soccer Defeat
    Teaching Players to Want to Win Soccer Games
    Is Equal Playing Time Necessary for Soccer Players?
    Don't Set Unrealistic Expectations
Scrimmaging Can Reduce Soccer Game Day Enthusiasm

Replace it with >

70 Soccer Tactics and Tips

2. Add as a H1 > 70 Soccer Tactics and Coaching Tips (that will be the Top Title)

3. Delete all the text down to No. 1 (which starts "Do you scrimmage at practice?" ) 

4. In place of the text you deleted put (the 2 links go to www.soccerhelp.com/soccer-drills.shtml and  http://soccerhelp.com/soccershop/soccer-patches-reviews-testimonials ) >

Soccer Coaching Tips & Tactics for U8 to U16

The soccer coaching tips and tactics below were written in reply to emails from coaches. About half the tips will apply to most youth teams that are U8 and older, but about half the tips are for weak soccer teams and don't apply to Travel teams. Look for ideas that might help your specific team. How a great Travel team with 100 percent great, motivated players can play is very different from a Recreational team that has 4 or 5 unskilled, slow, non-athletic, unmotivated players who don't practice.

The 2 best things a coach can do are to use SoccerHelp No Lines Soccer Drills so players develop strong fundamental soccer skills, and to motivate players to come to every practice, to hustle, to give 100% effort, to be Brave and not afraid of contact (there is a SoccerHelp drill to teach that), and to have good team spirit (see How to Motivate Soccer Players for ideas) . Our drills are fun and players will see fast improvement - for those 2 reasons they will want to come to practice.

5. Have the H2 be > 

Soccer Coaching Tips & Tactics for U8 to U16

6. Below the Titles >

12 More Ideas to Help a Losing Team 
2 Stopper Formation 
"Rules" for Rec Fullbacks 
22 Coaching Rules 
Teaching Terminology

Delete the section starting with >

(This is a continuation of the correspondence with Coach Tom.

Down to  the "Hi Tom" that is below the Green titles above - it is the second "Hi Tom" on the page  > 

Hi Tom, 
Thanks for the detailed reply. That helps me understand. 

7. After my reply to Tom, >

> leave the line below "David at SoccerHelp"   AND also  leave >

(Following is a letter we received from a Coach who had a humiliating loss, and our recommendations for improving his chances of success)

BUT DELETE what is below >
Dear SoccerHelp, 
I found your website out of desperation this week after a humiliating 7-0 loss in our first game with my boys U9 8 vs 8 team. I've been coaching for several years, very successfully I might add, but only with younger boys and no more than four on a side. Unfortunately, my team is not the most skilled team in the league. Instead, most of our players are "leftovers" from teams that decided to go more competitive or load their rec. team with better players. 
I have 13 boys on my team, of which only 3 would I consider good players for their age. One these three has fantastic ball control skills, but just doesn't want pass. The other two are strong natural forwards. I have one player on my team who has absolutely no athletic ability, skill, or stamina. On top of that I have two other very weak players. The remaining seven are not quite average. 
I find it interesting that all but my best three players want to play goalkeeper. Actually, three of the average players above, are in fact, above average goal keepers. Unfortunately, none of my worst three players has any ability in goal, even though they want to play. 
I've been scouring your premium website for the last day trying to figure out what kind of formation to use with this group of kids. We played a 2-3-2 formation in our first game and I encouraged our defensive backs to push up (as was instructed by our leagues' coaches "coach"). The other team played a 3-2-2, and never let the defensive backs push up beyond mid-field. Even though our "good" forward was able to retrieve a few balls in the attacking third, they were never able to completely penetrate, as their CDB always seemed to break up the play. Needless to say we suffered from a severe case of bunch ball, and had 3-4 goals scored on breakaways. 
The only bright spot in the game was goal keeping. Our keepers faced at least 15-20 odd man rushes and broke up two-thirds of them. Had we had one of our weaker players in goal, we probably would have lost 12-0 instead of 7-0, so I'm very nervous about allowing these boys (who really want to play goalkeeper) play goalie. 
So I have a couple of questions if you have the time: 
1.	What might be my best formation, and what should I do with my best 3 players who all want to play forward?
2.	What should I do with my 3 weak players, especially the really, really weak one?
3.	Should I limit the number of goalkeepers to 3 or 4 and not let some of the others have a try at it during a real game? I've given all that want to play a chance in practice, but half of them would be an absolute disaster if they ever get shot on (one even ducked when a boy went to shoot the ball).
At this point I don't have lofty goals. I'd be happy if the boys were able to play competitive in some of their games and get a few goals. I'd hate for them to get beat 5 or 10 to 'nil every week. 
Any thoughts are greatly appreciated. 
Sal 
----------------------

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.  Do you want me to get this code validated too since this is an important page?

**Comment by david-huddleston** [comment]
Yes - good idea.

**Comment by david-huddleston** [comment]
6-21-17, about 11:30 am - Yes, go ahead and Validate the W3C

**Comment by dustinschaerer** [comment]
@david-huddleston This is 100% completed.
