### ISSUE TITLE
On bottom of SH Pages, change the Link Block to Home, etc. , 6-17-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#60]
Dustin, I also sent you an email about this on 6-17-17 at 10:35 Am CST.

You added the link block below to most SH pages >

SoccerHelp Home Page | Soccer Drills | Soccer Patches | Soccer Dictionary | SoccerHelp Premium 

Shorten the link names as shown and delete the link  "Soccer Dictionary" , BUT leave "Soccer Drills"
so it looks like >

Home | Soccer Drills | Patches | Premium

( That way it will easily fit on cell phones.)

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
