### ISSUE TITLE
Changes to 21 Tips - http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#62]
Dustin, I sent you an email of this on 6-19-17 at about 5:45 PM CST. Use that see you can see colors and formatting.

delete the prior 3 versions, including the one sent on 6-17-17 at 12:40 PM, 6-17-17 at 1:39 PM, and 6-17-17 at 1:40 PM CST - I added a new # 7 

------------------------------

Dustin, on http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml >

1. The current Title is >

20 Tips to Quickly Improve Your Soccer Team 
How to Train a Soccer Goalie in 30 Minutes 
Soccer Formations and Positions 
Soccer Attacking Strategy 
Where to Hide Timid Players 
Motivate Soccer Players 
Control the Flow of the Game, Win 50/50 Balls, Steal Goal Kicks, No Breakaways

Replace it with >

21 Soccer Coaching Tips 
How To Teach Soccer Formations and Positions 
Soccer Attacking Strategy 
Where to Hide Timid Players 
Motivate Soccer Players 
Control the Flow of the Game 
Win 50/50 Balls 
Steal Goal Kicks 
No Breakaways
How to Train a Soccer Goalie in 30 Minutes

2. Delete the first para and the separator line below it >

There are 3 articles that discuss this soccer coaching success story. In order, they are 20 Tips to Quickly Improve Your Soccer Team , Mid-Season Success Story - 2 Week Turnaround and How to Turn Around a Losing Soccer Team in 3 Weeks. SUMMARY of the STORY: Coach M is a U10 Girls Rec coach. He contacted me after his team lost their first game 0-3. He was worried because in 2 weeks they would play a team that had won 14-0. He started using the SoccerHelp Program (our soccer drills, tactics and motivational patches) and tied the second game 2-2 . They then lost 0-4 to the team that was killing everyone else and in their 4th game everything came together and they won 3-1. The 3-1 victory was 3 weeks (20 days) after he started using the SoccerHelp Program. There are many good tips in these articles from both me and Coach M. If you have a U9, U10, U11 or U12 Rec soccer team they are worth reading.
________________________________________

3. Replace the first para with a Subtitle that is bold and flush Left >

21 Tips for a Weak Soccer Team

4. The first sentence will then be >

This article has 20 tips for how to improve your soccer team in 2 practices.

Replace it with >

This article has 21 tips for how to improve a weak youth soccer team in 2 practices. The tips below were for a U10 team in CA.

5. In the Meta description, change "20" to "21" so it reads -

<meta name="description" content="21 tips to improve your soccer team in 2 practices">

6. Add as the HI >

21 Soccer Coaching Tips

7. Delete the block of links at the bottom >

________________________________________
Links to 29 Pages of Free Soccer Coaching Tips, Tactics & a Drill to Teach Players to be Aggressive - http://www.soccerhelp.com/soccer_coaching_tips_drill_links.shtml
How Coaches and Teachers Use Our Patches to Motivate and Reward Achievements and Behavior
4-Step Plan for Successfully Motivating Players, Teams, Athletes and Students
Soccer Coaching Video Clips from DVDs We Sell
Soccer Incentive Patches 
Alphabetical List Of DVDs
500 Testimonials for Premium and our Motivational Soccer Patches Premium now has over 1,500 pages, 5,000 internal links, 70 copyrighted soccer drills that are soccer Practice Games, over 300 pages about soccer Formations (4v4, 5v5, 6v6, 7v7, 8v8, 9v9 and 11v11) and soccer Positions, and a soccer Forum where Members can ask questions to Members and David at SoccerHelp. Over 15,000 coaches have joined SoccerHelp Premium. 
________________________________________

8. Add as the H2 >

21 Tips for a Weak Soccer Team

9. Starting with the Blue Dear SoccerHelp, , delete Coach Mark's letter all the way down to Hi Coach M, > 

Below what to delete >
Dear SoccerHelp,
I have been a Premium member for a year and your website has been so helpful in my last two years of coaching. Of all the resources I use, I always go back to your website for by far the most help. It helped me tremendously last season and I know will do the same this season. I write to you because in my five years of coaching, I have a goal for our team that all the players are on board and wanted to get some of your valuable advice.
I currently coach a U10 (8 and 9 year old) Girls team in a Rec league. I have 12 girls on my team and we play 8 v 8 goalie included, I promise all girls they will play at least 25 minutes of each 50 minute games. There are ten teams in the league and we just lost our first game this past weekend 3-0 to probably the second best team in the league. Because half our team seemed to be on summer vacation, we usually had 6-8 girls at the five practices before the first game. We now have everyone showing up at practice. I see this team as having some really good athletes not the most talented team, but with our ability and heart, I think this team has some potential and I want to give these girls the best experience they have had and play up to our potential.
One of our goals: the best team in the league just beat another team 14-0 and rightfully so think they are going to go undefeated. This team has a tendency to play very physical and has a talented squad. Just hearing that they think they will go undefeated made me circle the game we have against them in three weeks. My goal is to at least play that game against them as competitive as possible.
Our main emphasis is for the girls and our team to play to our potential in that game and perhaps scare them a bit. Our team and our coaches like winning but this is a game that we really want to win.
Our team played a 2-3-2 in the game we lost 3-0 which I know is probably against your recommendations, so I know I need to start there. My strategy is to defend deep which backfired because two of the goals were scored when my two defenders were almost backed up to the goal line and froze when an attacker came toward the goal.
I did teach Coaching Rule number 3 but only half of them get it and only two of them can really jump on the opportunity. Maybe I need to work on that more during practice. Any suggestions on drills that work to help sink in. It will be good that I have our full squad on the practice field this week.
I have three skilled players who could play on a travelling team as backups, seven other players who have potential to be skilled, and two that just are not skilled and not athletic.
Most of my team is fast with the exception of the two unskilled. Three of the fast players are skilled, and three of the fast players have potential but are weak in soccer skills or desire.
Four girls can play goalie, Player 1 and Player 3 rather be in the field. Player 11 and 12 play goalie because they don't like to run. Player 11 shows some promise in goalie.
Some of my players are strong in the center between the 2 goals like Player 1, 3 and sometimes player 7. Player 5 and 6 could be good but sometimes react to the ball or do the opposite and don't move.
I need to work on positioning because my forwards absolutely don't get their position, they play like midfielders and are where the ball is with the exception of player 4 and 8. My fullbacks clear the ball to the sides or straight ahead if far enough from the goal. Midfielders like player 2 and 3 will be in position to get the ball, the others not so much.
I tend to focus on the strength of the players when assigning positions but do like to rotate the girls to different position focusing on their best positions.
We practice twice a week for an hour to an hour and a half and every girls has a soccer ball with an extra six in my bag. We do a lot of dribble across the box, dribble and pass around cone, small sided games, and will begin to work on shoulder to shoulder game today. My midfielders sometimes have a tendency just to go wherever the ball goes. My fullbacks stay out of the goal box except for the two that drifted in there during the game. My forwards are hit and miss sometimes they think they are midfielders other times they actually are ahead of the ball. Here is a list of my players from best to worst:
Player 1 is my best player who can play every position on the field. On defense, she can dominate her side of the ball. One of the strongest legs on the team, one of the fastest, and plays really tough. Although she can handle the ball really well, her only downfall is her tendency to dance around the ball too much. She could also play goalie. I told her if she can punt the ball past midfield consistently I would let her play goalie. I play her at defense and midfielder.
Player 2 is a very close second who is the fastest player on the team. She is one of the smaller players but never gets tired and is one of the tougher players, loves contact, and plays with absolutely no fear. Handles the ball well but does kick the ball too far ahead of her. Plays great with player 1 because they can read each other. Midfielder.
Player 3 is a smart player who has a very strong leg and at times can become pretty fast, once she gets going. She does get tired a little easier than player 1 and 2 but plays with a lot of heart. Great defender and can also play a solid goalie. Defense and Midfielder
Player 4 is always running and is a fast player. She has a weak foot but is pretty accurate in her passing. Really comfortable with the ball at her feet. Never gets tired, plays midfield and forward.
Player 5 can kick the ball the hardest and farthest. She could be an amazing player but has a tendency to tune out and not play smart. She can play tough but during the games she plays with quite a bit of fear, waiting for the ball to come to her. Plays every position.
Player 6 loves to stop the ball in anyway shape or form, sometime illegally and is a very tough and aggressive player. She is the smallest girl on the team but plays with a ton of heart. Average speed, weak foot, sometimes will not react quick to the ball. Average dribbling and ball control. Will play at half speed in practice and full speed in games. Plays mainly defense.
Player 7 is a fast player who loves competition. Weak foot but played an amazing defense in scrimmage and games. With player 1, they could probably stop most teams on defense. She has no left foot which could be a problem because she always delays her kick a little to get her right foot on the ball. Defense and Midfielder
Player 8 Fast player that absolutely does not get how to play positions no matter how much I tell her, except forward because I tell her to hang out with the opposing players defenders. Good dribbling, fairly strong kick. Good attitude but will crumble on contact.
Player 9 keeps getting better and could be one of the better players on the team given some time. Her brother plays on the travelling team so she has some really good ball skills but just doesn't know how to execute. She can get timid because she is smaller and has an inconsistent kick sometimes strong sometimes weak. Fairly fast girl but gets tired easy. Midfielder.
Player 10 could be the fastest player on the team but seems to not want to exert herself at times in practice or games. Plays very timid, has potential but sometimes she is not completely into the game. 
Player 11 is an inconsistent player. Sometimes works hard during practice and sometimes tunes out. She loves attention and loves playing goalie. Actually decent at goalie except does have the quickness to get to the ball. Her ball control is weak and is second slowest on the team. Goalie, left midfielder and forward.
Player 12 is the slowest player on the team. She wants to play goalie because she does not like to run. Has a fairly strong foot but has a tendency to give up on the ball when she's on the field. Seems to be playing the game because her parents want to and can be disruptive during practice. Goalie, and wherever I can hide her.
I will accept any help you can give me. Thank you!
Best,
Coach M, U10G, Premium Member

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
