### ISSUE TITLE
Add the 2 blocks of links to bottom of "articles" and "newsletters"

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#63]
Dustin, I sent this in an email on 6-17-17 at about 1:52 pm CST/ 

Dustin, add the 2 block of links that you put on the SH articles to the "articles" and "newsletter" articles, like >

http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml 

and

http://www.soccerhelp.com/newsletter_archive/Soccer_Drills_5_03_2010.shtml 

There is currently a block of red Links to the Home Page, etc. like there was on all the SH Pages, so delete that. 

> BE SURE to use the revised  block of links in the Issue I posted today  titled "On the bottom of SH Pages, change the Link Block to Home, etc." that are > 

Home | Soccer Drills | Patches | Premium

The other block of links to add is >

Contact Us | Site Map | About | Privacy Policy

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
