### ISSUE TITLE
Changes to www.soccerhelp.com/Soccer_Certificate_Award_Roster.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#66]
I emailed you this on 6-21-17 at about 9:18 AM CST

Dustin, on www.soccerhelp.com/Soccer_Certificate_Award_Roster.shtml >

1.  At the top of the page, change the link destination of  Soccer Patch Rewards  >

to go to  http://www.soccerhelp.com/soccershop/ 

2. Add a new second para >

If you want some awards or rewards to give out, consider our motivational soccer patches. They are inexpensive (10 for $5 with free shipping or 3 for $2 with free shipping) and we sell 32 kinds, including 12 colors of soccer balls, A, T, B, C, V, lightning bolts, Happy Face, Gold Star, Red Star, Blue Star, Silver Star, and more. You can see them at Soccer Patches Awards 

(Dustin, the link goes to  http://www.soccerhelp.com/soccershop/ )

3. Change the Code to as shown below >

<title>Soccer Certificates and Awards from SoccerHelp.com</title>
<meta name="keywords" content="soccer awards, soccer certificate">
<meta name="description" content="Soccer awards and certificates that are printable and can be filled in and edited.">

4.  Make the second line of the title the H2 >

Free Editable Soccer Certificates and Awards

**Comment by dustinschaerer** [comment]
@david-huddleston This is all completed.
