### ISSUE TITLE
Fix the "Site Map" link on SH Home page

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#7]
@dustinschaerer  on SH Home, the last link in the alphabetical list is "Site Map"

https://www.soccerhelp.com/sitemap.xml  which is a blank page or a hidden page. 

Can you have it go to the latest Site Map?

**Comment by dustinschaerer** [comment]
@david-huddleston I used some fancy editing tricks to deconstruct the XML sitemap into an HTML  scannable version so users can click on the sitemap link and actually get the linked URLs.

Hopefully it'll help someone, and it won't hurt us. Google knows where the sitemap.xml lives and I didn't change it.
