### ISSUE TITLE
Changes to www.soccerhelp.com/Soccer_Practice_Plans.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#70]
Dustin, I sent you this as an email on 6-19-17 at 12:54 PM . Use the email so you can see the colors.

Dustin, on   www.soccerhelp.com/Soccer_Practice_Plans.shtml 

1. Lower case and Dasherize this URL 

2. Validate for W3C

3. change the Meta Description to >

meta name="description" content="Free soccer practice plans for ages U4 to U16. No Lines drills and games. Fast Results.">

4. The 3-line Title is >

FREE SOCCER PRACTICE PLANS
Age Appropriate Training Sessions, U6-U14
Using No Lines Drills that are Games

Leave it the same color and font size, but change the words to >

SOCCER PRACTICE PLANS
Age Appropriate Soccer Practice Plans
No Lines Drills and Games, U6-U16

5. Delete the top link >

Soccer Practice Drills and Videos, U4 to U16

6. Change the H1 to match the new Top Title>

SOCCER PRACTICE PLANS

7. Make the H2 be the second line of the Title >

Age Appropriate Soccer Practice Plans

8. Make the H3 be the second Sub-Title >

Tips for Your Soccer Practice Plans

9. The first para is >

Below are Soccer Practice Plans for age U4 to U16. (The practice plans for U6 can also be used for U4 and the plans for U12 can also be used for U14 and U16). We use our exclusive "No Lines" Drills because they are better than Line Drills - your players will improve twice as fast, have more fun, and play better. There are many links below that will help you adjust the soccer practice plans to best help your team.

Replace it with >

Below are Soccer Practice Plans for age U4 to U16. (The practice plans for U6 can also be used for U4 and the plans for U12 can also be used for U14 and U16). Our exclusive No Lines Drills are MUCH BETTER than Line Drills - your players will improve twice as fast and have more fun because they don't waste time standing in line. This is a soccer skills training program. Some of the 1,000 Testimonials are below.

10. The second para is >

Save $5 on SoccerHelp Premium - This free site has 300 pages. SoccerHelp Premium has 1,500 pages. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. Sign up at http://soccerhelp.com/members/signup.

Change the 300 to 400 and change the Blue to Black, so it reads >

Save $5 on SoccerHelp Premium - This free site has 400 pages. SoccerHelp Premium has 1,500 pages. You can use the Coupon 5offpremium to subscribe to Premium for $10 for 30 days, $20 for 120 days, or $35 for a year. We do NOT automatically renew subscriptions. Sign up at http://soccerhelp.com/members/signup.

11. Unbold all 6 Testimonials (but leave the colors), so they look like >

"The Practice Games are AMAZINGLY EFFECTIVE!! Parents tell me that their girls cannot wait to go to practice." Coach M.J., Premium member
"My daughter is averaging 2-3 goals per game. It's been awesome watching her turn into a great player just by religiously doing SoccerHelp drills." Derik, U10 coach, Premium member for 3 years
"Our regional director says I'm the most requested coach she's ever seen. SoccerHelp is the reason!!! Every practice game, etc. came from SoccerHelp....WELL DONE!" Coach Mark, Michigan, Premium member
"At every practice we religiously do Dribble Across a Square, Dribble Around A Cone and Pass, etc, etc, - the poise my boys have on the ball is leaps and bounds above other teams now." Coach T, U12 Boys travel team, MA, Premium subscriber
"My U12 girls won the end of year tournament. The main thing I saw in my girls was a huge increase in their confidence while playing. Some of that was better skills, but more important was being used to playing under pressure and in chaotic conditions due to the SoccerHelp practice games." Philip, WA, Premium Member
"Our now U15-G Ann Arbor United Pumas went from being cellar dwellers to competitive against older and higher-level teams. One highlight was beating a high school team coached by a former English Premier League player!" Nick, MI, Premium Member

**Comment by dustinschaerer** [comment]
@david-huddleston This is ALL completed.
