### ISSUE TITLE
SH Soccer Drills Schema Text

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#71]
Dustin, maybe you can use this >

With SoccerHelp No Lines Soccer Drills, players practice without standing in line, so they improve faster and have more fun. Players learn skills twice as fast. This is a training program that is designed to teach fundamental soccer skills. Most of the SoccerHelp drills are Practice Games that teach players to play fast while under pressure. There are 1,000 Testimonials for the SoccerHelp Training Program.

**Comment by dustinschaerer** [comment]
@david-huddleston I used this!
