### ISSUE TITLE
More changes to www.soccerhelp.com/soccer-drills.shtml 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#78]
Dustin, I emailed you this. Use the version I sent you at 10:00 AM CST today (6-20-17)

Dustin, on www.soccerhelp.com/soccer-drills.shtml , 

1. Replace the first para (below "Players Improve Twice as Fast - Guaranteed") with >

Use our free No Lines Soccer Drills and your players will improve twice as fast. The reason is because players are practicing skills instead of standing in line. And because there aren't lines, players have more fun and love to practice. This is a training program that is designed to teach and improve soccer skills. Most of our drills are Practice Games that train players to play fast while under pressure, like good players must be able to do. Our drills are copyrighted and only on SoccerHelp. There are 500 Testimonials from coaches - some are below. 

2. Below the Testimonials, DELETE >

Save $5 on SoccerHelp Premium - Use the Coupon 5offpremium to get a one-year subscription for $35, 120 days for $20, or 30 days for $10. Premium has 1,500 pages for youth soccer coaches - 15,000 coaches have subscribed. We do NOT automatically renew subscriptions. Sign up at https://soccerhelp.com/members/signup
1,000 Testimonials Soccer Practice Plans
View a Copy of the SoccerHelp Premium Home Page

BUT LEAVE the 5 links below > 

Read a Soccer Journal article about why SoccerHelp Practice Games are better than drills.
Tips For a Good Soccer Practice
Things You Need For A Good Soccer Practice
70 Soccer Coaching Tips
18 Tips for U4 and U6 Soccer Coaches

3. Change the link > Read a Soccer Journal article about why SoccerHelp Practice Games are better than drills.
To > Soccer Journal article about SoccerHelp Practice Games

4. The last para is >

SoccerHelp Premium contains over 70 "Third Generation" Soccer Drills that are Practice Games, including 29 soccer drills for U4 and U6 (age 3, 4 and 5), 45 soccer drills for U8 (age 6 and 7), 52 soccer drills for U10 (age 8 and 9) and 50 soccer drills for U12 (age 10 and 11). Basic versions of nine of those practice games are found below. SoccerHelp Practice Games are superior to soccer drills in 15 ways, as listed below. Our Practice Games are fun and really work. Your team will learn by simply playing the games and you will achieve more in less time. Practice attendance will improve, players will have more enthusiasm and your team will play better and win more games. Our games have been tested by thousands of coaches, including Rec coaches, select and tournament team coaches, adult team coaches, beginning coaches, very experienced coaches, coaches who never played soccer and coaches who played college and professional soccer. In simple terms, we have invented a better "mousetrap". It is a unique, innovative program that quickly achieves results. Our Premium members get more enjoyment from coaching and their players learn more and have more fun. If you have any doubts, read the Testimonials or Coaches Comments. With a money back guarantee, there is no risk to trying it. If you aren't completely satisfied, just send us an e-mail during the first 10 days and we will give you a full refund with no questions asked. Premium now contains over 1,500 pages and 5,000 internal links. Over 15,000 coaches have subscribed to Premium.

> Replace it with the para below  (have SoccerHelp Premium go to http://www.soccerhelp.com/members/signup  , Soccer Drills  go to  http://www.soccerhelp.com/  ,   and  Testimonials go to http://soccerhelp.com/soccershop/soccerhelp-premium-reviews-testimonials  ) > 

SoccerHelp Premium contains over 70 No Lines Soccer Drills that are designed to train fundamental soccer skills. Most are Practice Games that train players to play fast while under pressure. Players learn skills by playing the Practice Games. There are 29 soccer drills for U4 and U6 (age 3, 4 and 5), 45 soccer drills for U8 (age 6 and 7), 52 soccer drills for U10 (age 8 and 9) and 50 soccer drills for U12 (age 10 and 11). There are 400 Testimonials from Coaches. If you aren't completely satisfied, just send us an e-mail during the first 10 days and we will give you a full refund with no questions asked. Premium now contains over 1,500 pages and 5,000 internal links. Over 15,000 coaches have subscribed to Premium.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
