### ISSUE TITLE
Can you write a code to unbold all links in SH? 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#79]
Dustin,

can you write a code to unbold all links in SH without messing up the links?

**Comment by dustinschaerer** [comment]
@david-huddleston - I can remove the bold style from the stylesheet but it won't remove the bolding from those links that aren't marked up with CSS.  Do you want me to do what I can?

**Comment by david-huddleston** [comment]
Yes

**Comment by dustinschaerer** [comment]
@david-huddleston THis is completed.  I unbolded the links on our main stylesheets.
