### ISSUE TITLE
SoccerHelp Server Switch

### ISSUE THREAD

**Issue by dustinschaerer** [soccerhelp/soccerhelp#8]
I opened this ticket to kickoff moving Soccerhelp.com to an new, isolated server. 

My personal recommendations for this would be to use Knownhost, Linux cPanel for our server, and to lean on  Knowhost as much as possible to help out with the cost of the process.  I'd also like to move the other feeder sites on the SoccerhelpServer2.com host to a different, new cPanel server.  That server could solely host static websites and we could disable all potentially dangerous security infiltration entry points.  Once completed, I'd like to migrate all the sites on the BIR-1.com server onto this new secure host. 

This should help isolate future vulnerabilities to SoccerHelp, which is the bread n butter.

@david-huddleston Feel free to chime in on this thread with any ideas or requests.

**Comment by dustinschaerer** [comment]
![knownhost ssd plans](https://cloud.githubusercontent.com/assets/1232192/26793209/0cfa8d16-49d2-11e7-8daa-f47add398125.png)

@david-huddleston I think the $50/month would be plenty sufficient to host SoccerHelp.com.  The SSD Solid State Drives are great and worth the extra $.  I think they come with two dedicated IPs so I don't we'd have to any anything on. What do you think?

**Comment by dustinschaerer** [comment]
Step 1 - Purchase and setup new SSD-3 server for $70. Lean on Knownhost to migrate the current soccerhelp domain and DB's to the new server.  Check and test all services, and then switch DNS to point traffic to new site when ready.

Step 2- Once soccerhelp.com is moved, scale down SHServer2's resources to a cheap plan.

Step 3 - Migrate remaining SH feeder sites to another new cPanel server, and find the right paln.. Shut down SHServer2.

Step 4 - Migrate all BIR-1 sites to the same new server as the SH Feeder sites are on. Shut down BIR-1

**Comment by david-huddleston** [comment]
Dustin - We just talked about this - remember , when we get the new server 

start with the big pages like /Soccer_Drills

and make the change in Apache that you discussed that will change the URL's to have a dash and NOT upper case letters (like /soccer-drills  )

**Comment by dustinschaerer** [comment]
**Checklist for Switch**

- [x] Cron Jobs Setup
- [x] S3Sync Backups Setup - **New server has its own really robust backup system.**

**Last Minute Only Items**
- [x] SSL Certificate
- [x] Update to Date File System transferred
Databases Transferred
- [x] soccershop
- [x] amember
- [x] amember-doug
- [x] amember-videos
- [ ] doug wordpress DB

Maintenance message on 
- [x] Shopping cart
- [x] amember
- [x] amember-doug
- [x] amember-videos
- [x] Switch DNS for soccerhelp.com

**Once switched, test live**
- [x] soccershop DB
- [x] soccershop purhcase
- [x] amember DB
- [x] amember login
- [x] amember purchase
- [x] amember-doug DB
- [x] amember-doug login
- [x] amember-doug purchase
- [x] doug wordpress admin login
- [x] amember-videos DB
- [x] amember-videos login
- [x] amember-videos purchase

- [x] BlogVault Coach Doug
