### ISSUE TITLE
Can you write a code to change all the blue underlined text (except for links) to Black underlined?

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#80]
Dustin,

Can you write a code to change all the blue underlined text (except for links) to Black underlined?

That would be a way to get rid of the old blue underlined text that is confusing because it looks like a link.

**Comment by dustinschaerer** [comment]
@david-huddleston  - That sounds pretty tricky, but I can try.  Please give me an example of page with that underlined blue text on it.

**Comment by david-huddleston** [comment]
There is quite a bit of it. See http://www.soccerhelp.com/Soccer_Practice.shtml Sent from XFINITY Connect Mobile App------ Original Message ------From: Dustin SchaererTo: soccerhelp/soccerhelpCc: David Huddleston, AuthorSent: June 20, 2017 at 3:05 PMSubject: Re: [soccerhelp/soccerhelp] Can you write a code to change all the blue underlined text (except for links) to Black underlined? (#80)That sounds pretty tricky, but I can try.  Please give me an example of page with that underlined blue text on it.
