### ISSUE TITLE
More Changes to Soccer Drills page, 6-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#81]
Dustin, I sent you this as an email on 6-20-17 at 12:20 PM

Dustin,

2 more changes based on the Audit report I ran after you made the last changes >

1. Re-run the W3C Validator  (it says the page isn't validated)

2. Underline "Soccer Drills" in the first line, which is >

Use our free No Lines Soccer Drills and your players will improve twice as fast.

3. Underline the Sub-title >

Free Soccer Drills

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed and validated: https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.soccerhelp.com%2Fsoccer-drills.shtml
