### ISSUE TITLE
3 Changes to Links List on Soccer Drills page

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#82]
Dustin, I also emailed you this on 6-20-17 at 1:31 PM.

Dustin, on the Soccer Drills page http://www.soccerhelp.com/soccer-drills.shtml 

(1). At the bottom of the List of 5 Links, (just below   ) 

add a link named  Free Soccer Practice Plans  >

That goes to > http://www.soccerhelp.com/Soccer_Practice_Plans.shtml 

(2) Delete the second and third links, which are named >

Tips For a Good Soccer Practice
Things You Need For A Good Soccer Practice

(3). as a new second link, add >

15 Soccer Practice Tips 

(have the link go to http://www.soccerhelp.com/Soccer_Practice.shtml )

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
