### ISSUE TITLE
Changes to Soccer Practice -www.soccerhelp.com/Soccer_Practice.shtml, 6-20-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#84]
Dustin, I sent you an email version on 6-21-17 at 9:35 AM CST - use the email so you can see colors.

Dustin, this is an important page SO, go ahead and do the W3C and Lower Case and Dasherize the page. 

Changes to www.soccerhelp.com/Soccer_Practice.shtml .

1. in Apache, go ahead and Lower Case and Dasherize the URL 

to www.soccerhelp.com/soccer-practice.shtml 

2. Validate the page for W3C

3. The second line of the Title is >

Soccer Practice Can Be Fun and Your Players Can Improve Twice as Fast

Change it to below (Make "Soccer Practice" Bold BUT unbold the other words AND make the Font Size the same size as the Text and Black - leave a separator line where shown below after the second line) > 

Soccer Practice Can Be Fun
Players Can Improve Twice as Fast

29 Practice Tips and
Tips from 3 Famous Coaches

4.  Delete the 2 links that are just below the Title >

Soccer Practice Plans
Soccer Practice Drills and Videos

5. Have the H2 be > Soccer Practice Can Be Fun

6. Have the H3 be >  Things to Do at Soccer Practice

7. There are 15 places that have Blue text underlined.

Leave the text underlined BUT change the blue color to Black.

Example >

Change > 

Be sure each child has a ball

to >

Be sure each child has a ball

8. Replace the first and second paras with >
Soccer practice tips, plans, No Lines Soccer Drills, and a training program that is fun and really works. Use our No Lines Drills and your players will improve Twice as Fast because they will be practicing instead of standing in line. Most SoccerHelp drills are Practice Games that train players to play fast - try the free drills and you will see the difference. There are over 400 Testimonials and Success Stories from coaches at the link below.

9. At the end of  Things to Do at Soccer Practice:: is an extra : for you to delete

10. Under Things to Do at Soccer Practice:, Number 1 is >

Be organized, have a practice plan and get to practice 10 minutes early to check the field and set up for your first Soccer Practice Drill.

Replace it with (Dustin,  Free Practice Plans  goes to  http://www.soccerhelp.com/Soccer_Practice_Plans.shtml   ) >

Be organized, have a practice plan and get to practice 10 minutes early to check the field and set up for your first SoccerHelp No Lines Drill. If you need ideas, check out Free Practice Plans

11. In number 3. delete the word "soccer", so it reads > Ideally, every player should be active and never stand in line for the entire practice.

12. In number 4, in the 4th sentence, delete the word "Soccer", so it reads > 

The very best No Lines Practice Drills,

13. In number 4, delete the last sentence > We have spent hundreds of hours selecting, testing and refining the SoccerHelp No Lines Soccer Practice Drills.

14. In number 4, unbold the link > Testimonials and Success Stories 

15. At the end of Things to Avoid at Soccer Practice:: is an extra : to delete

AND delete the word "Soccer" so it reads >

Things to Avoid at Practice:

16. Under  Things to Avoid at Practice: , Replace number 2 with > Don't use Line Drills if you can use No Lines Drills.

   
17. Under "Things to Do at Soccer Practice" add the new No. 13 below >

7 Practice Tips from the Great Jay Martin, the winningest coach in college men's soccer history:

1. Practice should be pleasant, exciting, and filled with learning opportunities.

2. Make it fun – Don’t make soccer “work”. Players will come to practice and keep playing soccer if it is fun.

3. Praise performance.

4. Set Realistic Goals – Goals that are unattainable cause frustration.

5. Give positive and informative feedback.

6. Give players recognition whenever possible for effort or achievements

7. Success in training increases confidence, which increases motivation.

The above tips are from an article by Dr. Jay Martin in the NSCAA Soccer Journal. Jay is a great guy, a great coach, and Editor of Soccer Journal - he is the winningest coach in college men's soccer history with a total of over 680 wins. I encourage all youth coaches to join the NSCAA.

18. Under  "Things to Do at Soccer Practice"  , move number 5 to be number 7 and move up numbers 6 and 7. Number 5 is >

Practice attendance is CRITICAL. Players won't improve unless they practice. Players are MUCH more likely to attend practice and be on time if your practices are FUN and if you minimize lines and maximize activity. But, if players don't attend practice or are late, motivate and reward them. Praise and reward the things you want your players to do, such as hustling, improving, and giving 100% effort (every player can do those things). We have had great success using small iron-on patches to motivate players - you have probably seen them - we sell soccer balls, Lightning Bolts to reward hustle, a B for Bravery, a D for defense, a Happy Face, T for Team Work, etc. You can see them at Motivational Patch Incentives

**Comment by dustinschaerer** [comment]
@david-huddleston This is all completed, validated, and dasherized, and all the links replaced on SH including sitemaps and htaccess rules.
