### ISSUE TITLE
2 changes to a Certificates page - http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#85]
Dustin, I sent you this email on 6-21-17 at 9:07 Am CST

Dustin, on http://www.soccerhelp.com/newsletter_archive/11.03.2008.shtml >

Delete 2 lines >

1. Delete the first line of text >

(The following was posted in the Premium Forum).

2. Under " Hi Coach C.H., " delete the third line >

There is a "Great Job Certificate" that is really good and allows you to fill in the Child's name and the Award they are getting -- there are 2 -- one for boys and one for girls.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed
