### ISSUE TITLE
More changes to Soccer Tactics - www.soccerhelp.com/Soccer_Tactics_Weak_Teams.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#86]
Dustin, I emailed you this on 6-21-17 at 2:02 PM CST. Use the email so you can see the colors.

Dustin,

1. Make the changes below and THEN validate for W3C

2. As discussed, Lower Case and Dasherize this URL to >

http://www.soccerhelp.com/soccer-tactics.shtml 

3. Change the Code to be as shown below >

<title>Soccer Tactics</title>

<meta name="description" content="Soccer Tactics for Youth Teams and for Weak Soccer Teams. Tips for Coaching a Weak Soccer Team">

<meta name="keywords" content="Soccer Tactics ">

4. Unbold all the links 

5. The Top Title is 70 Soccer Tactics and Tips

> Change it to as below with a second line below it that has font size the same as the Text and unbold - leave a separation line as shown >

Soccer Tactics

70 Coaching Tips and Soccer Tactics
6. So, the H1 will be >   Soccer Tactics

7. Have the H2 be > 70 Coaching Tips and Soccer Tactics

8. The first subtitle is > Soccer Coaching Tips & Tactics for U8 to U16
> Replace that with >  Soccer Tactics and 70 Tips for U8 to U18

(Reduce the Font Size to the same size as the text and make "Soccer Tactics" Black Bold - only those 2 words bold)

9. Have the H3 be > Soccer Tactics and 70 Tips for U8 to U18

10. Replace the first para with >

The 70 soccer tactics and coaching tips below were written in reply to emails from coaches who were losing or had weak teams. About half the tips will apply to most youth teams that are U8 and older, but about half the tips are for weak soccer teams and don't apply to Travel teams. Look for ideas that might help your specific team. How a great Travel team with 100 percent great, motivated players can play is very different from a Recreational team that has unskilled, slow, non-athletic, unmotivated players.

11. Move # 8 to be # 1 and revise it to >
Train Your Players to Be Brave, Tough and Aggressive. Use the free Aggressive Soccer Drill to toughen up your players and get them used to contact so they don't get pushed around. If you are a Premium Member, also use the Win the 50/50 Ball No Lines Drill to train players to win 50/50 balls.
(Dustin, change the link name   Shoulder Tackle and Strength on the Ball Game  to Aggressive Soccer Drill  . The link Win the 50/50 Ball No Lines Drill should go to http://www.soccerhelp.com/premium/practice_games/Win_The_Ball.shtml  )
12. Move # 4 to be # 2
13. Move # 5 to be # 3
14. Move # 3 to be # 15 >

To keep yourself motivated, try the Motivational coaching quotes... I read them myself.
15. Number 4 will then be > Do you scrimmage at practice? If you do, stop scrimmaging... kids play with more enthusiasm in their real matches if they don't scrimmage at practice.
Replace that text with > 
Do you scrimmage at practice? If you do, reduce scrimmaging to 10 minutes or less per practice. Scrimmaging is an inefficient way to teach skills because most players don't get enough time on the ball. If you need to teach positions or formations, do a slow walk-thru. SoccerHelp No Lines Drills are a MUCH better way to teach skills because in many of them every player has a ball. Also, some kids play with more enthusiasm in their real matches if they don't scrimmage at practice. If you scrimmage, scrimmage without a Goalie as explained at Small Sided Scrimmage Without A Goalie  .
(Dustin, the link goes to  http://www.soccerhelp.com/soccer_drills/Small_Sided_Scrimmage.shtml  )

16. Number 6 is >
Don't try to emphasize passing yet, except by playing the Dribble Around Cone & Pass Relay Race -- tell your scorers to try to score and teach them to look for rebounds and to be aggressive. Tell defenders to kick it hard straight ahead and teach Forwards to Win the Ball and give them a patch if they do.
Replace it with >

How to Teach Passing and Receiving - For U8 and older, a great way to teach passing and receiving is by using the Dribble Around Cone & Pass Relay Race No Lines Drill. It is a Practice Game where pairs of players compete. It teaches passing, how to play fast, Aggressive Receiving (being alert and moving to the ball), passing while running, and a more. 

17. In the Second part, above 12 More Ideas to Help a Losing Team  , add (in Black Bold and the same font size as the text >

More Soccer Tactics and Tips

So it reads (leave a line between it and the text below) >

More Soccer Tactics and Tips

12 More Ideas to Help a Losing Team 
2 Stopper Formation 
"Rules" for Rec Fullbacks 
22 Coaching Rules 
Teaching Terminology

18. Make the H3 be >  More Soccer Tactics and Tips

**Comment by dustinschaerer** [comment]
@david-huddleston This is 100% complete!
