### ISSUE TITLE
IP's - I want 7 domains on separate IP's - see below

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#87]
Dustin, I want the 7 Soccer domains that have the best traffic to be on separate IP's >

From BIR-1 = soccerdrills.net
From SoccerHelpServer2 = soccerdrills.org , soccerformations.com , soccerpatch.net , socceerpositions.net , soccerrules.org , youthsoccerdrills.com

**Comment by dustinschaerer** [comment]
@david-huddleston I ordered the IPs from Knowhost yesterday and received them this morning.  I added them to our server's IP pool and will be assigning them as requested above.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
