### ISSUE TITLE
Changes to Soccer Practice - http://www.soccerhelp.com/soccer-practice.shtml 

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#89]
Dustin, I emailed you this on 6-22-17 at 8:58 AM CST

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml '

1. The first and second paras are >

Soccer practice plans, fun "No Lines" drills, and a training program that really works for ages 3-18. Use our soccer practice drills and your players will improve Twice as Fast because they will get 3 times the touches on the ball. There are over 300 Testimonials and Success Stories from coaches at the link below.
Your soccer practice attendance will improve, practice will be lots more fun and your soccer team will improve much more quickly if you follow the tips listed below:

> Replace them with (have the link go to  http://www.soccerhelp.com/soccer-drills.shtml )  >

Soccer practice tips, plans, Free No Lines Soccer Drills, and a training program that is fun and really works. Use our No Lines Drills and your players will improve Twice as Fast because they will be practicing instead of standing in line. Most SoccerHelp drills are Practice Games that train players to play fast - try the free drills below and you will see the difference. There are over 400 Testimonials and Success Stories from coaches at the link below.

2. Change the code to be like below >

<title>Soccer Practice</title>
<meta name="keywords" content='Soccer Practice'>

3. The first sentence in # 4 is >

The best way to teach your players is by using our No Lines Soccer Practice Drills. 

Replace it with >

The best way to teach your players is by using SoccerHelp No Lines Practice Drills.

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
