### ISSUE TITLE
Changes to Dribble Across, http://www.soccerhelp.com/soccer_drills/Dribble.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#90]
Dustin, I emailed this on 6-21-17 at 7:03 PM CST. use the email version so you can see colors.

Dustin, on http://www.soccerhelp.com/soccer_drills/Dribble.shtml 

1. The Title is >
Dribble Across A Square ™ Soccer Drill (4 Stars)
- Make it the same size as the Text and Delete Soccer Drill (4 Stars)

- Add below it with a line in between in black unbold >

No Lines Soccer Drill
that is a Practice Game

- So it reads (all in black with the Top Line Bold) >

Dribble Across A Square ™

No Lines Soccer Drill
that is a Practice Game

2. There are 4 links in a Links List near the top of the page >

Watch a Video of this Soccer Training Drill and Many Others
Best Free Soccer Drills and Practice Games
See the List of 70 Premium Soccer Practice Games
View a Copy of the Premium Home Page
2.(a). Delete the fourth Link (View a Copy of the Premium Home Page
2.(b). Unbold the 3 remaining links
2.(c). Make the font size the same as the text size for all 3, so they look like >
Watch a Video of this Soccer Training Drill and Many Others
Best Free Soccer Drills and Practice Games
See the List of 70 Premium Soccer Practice Games
3. Unbold the Testimonials
4. Above the Instructions are 2 links >

We highly recommend the "Dribble Around Cone & Pass Relay Race" Practice Game 
Watch a Video of this Soccer Training Drill and Many Others
>Make them unbold and the same size as the text (they are 2 different sizes)

**Comment by dustinschaerer** [comment]
@david-huddleston This one is completed, but not validated yet.  I'm starting an issue thread for important pages to get validated soon, but where validation isn't as important as just sifting through the page content.

**Comment by david-huddleston** [comment]
No
