### ISSUE TITLE
Changes to Dribble Around Cone,  www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#91]
Dustin, I emailed you this on 6-21-17 at 7:19 PM CST. Use the email.

Dustin, on    www.soccerhelp.com/soccer_drills/Dribble_Around_Cone_Pass.shtml 

1. Delete the first line, which is >

Soccer Drills That Are Practice Games

2. The next line is >

Dribble Around Cone & Pass Relay Race ™ (4 Stars)

- Make it the same size as the Text and Delete (4 Stars)

- Add below it with a line in between in black unbold >

No Lines Soccer Drill
that is a Practice Game

- So it reads (all in black with the Top Line Bold) >

Dribble Around Cone & Pass Relay Race ™

No Lines Soccer Drill
that is a Practice Game

3. There are 3 links in a Links List near the top of the page >

Best Free Soccer Drills and Practice Games
See the List of 70 Premium Soccer Practice Games 
View a Copy of the Premium Home Page 

3.(a). Delete the third Link (View a Copy of the Premium Home Page
3.(b). Unbold the links
3.(c). Make the font size the same as the text size

4. Unbold the Testimonials

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed, and I'm adding this page on the list of pages to eventually get W3C validated.
