### ISSUE TITLE
2 Changes to Soccer Practice - http://www.soccerhelp.com/soccer-practice.shtml , 6-23-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#92]
Dustin, I emailed this to you on 6-23-17 at 1:50 PM CST. Use the email version so you can see colors.

Dustin, on http://www.soccerhelp.com/soccer-practice.shtml 

1. In the first sentence,

> bold the first 2 words

> and make   Free No Lines Soccer Drills  a link to http://www.soccerhelp.com/soccer-drills.shtml 

have the link go to  http://www.soccerhelp.com/soccer-drills.shtml ) , so it reads >

Soccer practice tips, plans, Free No Lines Soccer Drills, and a training program that is fun and really works. 

2. At the bottom, add 2  new first links to the Links List >

70 Tips & Tactics   that goes to http://www.soccerhelp.com/soccer-tactics.shtml 

21 Tips for Weak Team   that goes to http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml

**Comment by dustinschaerer** [comment]
@david-huddleston This is a completed.
