### ISSUE TITLE
Changes to Soccer Rules www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#94]
Dustin, I emailed you this on 6-24-17 at  10:39 AM CSt. Use the emailed version.

Dustin, on  www.soccerhelp.com/Soccer_Rules_Rules_Of_Soccer.shtml 

1. Change the URL to >

www.soccerhelp.com/simplified-soccer-rules.shtml

2. Validate for W3C

3. Change the title to (bold "Soccer Rules" in the second line) >

Soccer Rules
70 Simplified Soccer Rules
for Youth Coaches

4. Delete the first 2 paras >

Soccer rules (rules of soccer), rules for soccer, soccer rules and regulations, the rules of soccer and soccer rules for kids. 
Rules of soccer, rules for soccer, youth soccer rules, the soccer offside rule and soccer age rules are explained. 

5. The current third para (which will be the first para is >

The official soccer rules are often difficult to understand. Following are simplified soccer rules and links to the complete soccer rules. The official soccer rules are often modified for recreational, youth and indoor soccer leagues. SoccerHelp has helped make these rules easier to understand.

Replace it with (bold "soccer rules") >

The official soccer rules are often difficult to understand. Below are 70 simplified rules and definitions of commonly used terms such as "Hand Ball", "Linesmen" and "Obstruction". There are even simplified and detailed versions of complex rules such as the "Offside Rule". The official rules are often modified for recreational, youth and indoor leagues. IMPORTANT - Check with your League or Club to see if they have modified the official rules. Typical modifications include field sizes, the number of players on the field, the offside rule, and at young ages whether a Goalkeeper is allowed. 

6. The first centered Sub-Title is >

There are links below to over 70 soccer rules, official soccer rules and soccer rules-related definitions.

Replace it with >

Below are links to 70 soccer rules and definitions

7. Unbold the 4 testimonials

8. In the Alphabetical Links List, Delete >

Soccer formations   (that goes to http://www.soccerformations.com/ 

Soccer positions   (that goes to http://www.soccerpositions.net/ 

9. In the code, change >

<title>Soccer Rules-Rules Of Soccer</title>

To>

<title>Soccer Rules</title>

10. Make the H1 the Top Title>  Soccer Rules

11. Make the H2 the second line of the title > 70 Simplified Soccer Rules

12. Make the H3 >  Below are links to 70 soccer rules and definitions

**Comment by dustinschaerer** [comment]
@david-huddleston This is ALL completed.
