### ISSUE TITLE
Changes to Soccer Tactics-Soccer Tips Index

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#97]
Dustin, I emailed you this on 6-25-17 at 2:38 PM - use the email

Dustin, on http://www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml 

1. Change the Title to (have the font be the same size as the text ) 

Soccer Tactics and Coaching Tips

Navigation for Tactics and Tips

2. Delete the first sentence, which is >

Soccer tactics, soccer tips, formations, assigning positions and styles of play rom SoccerHelp.com.

3. Add at the top of the Links List >

70 Soccer Coaching Tips    (goes to http://www.soccerhelp.com/soccer-tactics.shtml )

21 Soccer Coaching Tips    (goes to http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml 

4. Toward the bottom is an article. The title is >

Importance of a Stopper in 8V8 Soccer 
2-1-2-2 vs. 2-3-2 Soccer Formation 
Analysis, Evaluation and Tips 
How to launch a counterattack and score more goals against a Pushed Up Team

Leave the font the same size and color but replace the title with >

Soccer Coaching Tips and Tactics
Importance of a Stopper 
2-1-2-2 vs. 2-3-2 Soccer Formation 
Analysis, Evaluation and Tips 
How to Beat a Pushed Up Defense

5. Have the H1 be the Main Title > Soccer Tactics and Coaching Tips

6. Have the H2 be the second line of the title > Navigation for Tactics and Tips 

7. Have the H3 be the First Line of the Lower Title > Soccer Coaching Tips and Tactics

8. Change the code to >

<title>Soccer Tactics and Coaching Tips</title>
<meta name="keywords" content="Soccer Tactics, Soccer Coaching Tips">
<meta name="description" content="Proven soccer tactics and youth coaching tips that will produce fast results, improve your team's play, and win more games.">

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed, and W3C validated.
