### ISSUE TITLE
Change name of the "70 Tips" link on Soccer Drills

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#98]
Dustin, I emailed you this on 6-25-17 at 3:35 PM

Dustin,

on   http://www.soccerhelp.com/soccer-drills.shtml , 

In the Links List, Change the name of the link >

70 Soccer Coaching Tips 

to >

70 Soccer Tactics and Tips

**Comment by dustinschaerer** [comment]
@david-huddleston This is completed.
