### ISSUE TITLE
Changes to 21 Tips, Third Version

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#99]
Dustin, I sent you this on 6-25-17 at 4:32 PM - the Subject Line  starts "Third Version" . Use the email

Remember to use the "Third Version"

Dustin, on http://www.soccerhelp.com/soccer-articles/120903-Improve-Soccer-Team-2-Practices.shtml >

1. In the Code, change >

<title>Quickly Improve Soccer Team</title>

to >

<title>21 Soccer Coaching Tips</title>

2. The current Title is >

21 Soccer Coaching Tips

How To Teach Soccer Formations and Positions 
Soccer Attacking Strategy 
Where to Hide Timid Players 
Motivate Soccer Players 
Control the Flow of the Game 
Win 50/50 Balls 
Steal Goal Kicks 
No Breakaways
How to Train a Soccer Goalie in 30 Minutes

2.(a). Dustin, Reduce the font size of the Top Title to the same size as the text

2.(b). Replace all but the top title with (fonts the same size as text) >

How to Teach Positions and Formations 
Attacking Strategy 
Where to Hide Timid Players 
Motivate Players 
Train a Goalie in 30 Minutes
No Lines Practice Games
Stopping Breakaways
Control the Flow of the Game

2.(c). So it looks like (all fonts the same size and Bold) >

21 Soccer Coaching Tips

How to Teach Positions and Formations 
Attacking Strategy 
Where to Hide Timid Players 
Motivate Players 
Train a Goalie in 30 Minutes
No Lines Practice Games
Stopping Breakaways
Control the Flow of the Game

3. The first Subtitle is >

21 Tips for a Weak Soccer Team

> Reduce the font size to the same size as the Text and make it black bold, like >

21 Tips for a Weak Soccer Team

4. Delete the first 2 sentences of the second para, which are >

Below is a letter from a soccer coach and my reply. He was worried that his U10 team might get killed by the "best" team who they play in 3 weeks, and which just beat another team 14-0.

5. Starting with the Blue Dear SoccerHelp, (the third para), delete Coach Mark's letter all the way down to Hi Coach M, (which is below the line break) > 

Dustin, Below what to delete >
Dear SoccerHelp,
I have been a Premium member for a year and your website has been so helpful in my last two years of coaching. Of all the resources I use, I always go back to your website for by far the most help. It helped me tremendously last season and I know will do the same this season. I write to you because in my five years of coaching, I have a goal for our team that all the players are on board and wanted to get some of your valuable advice.
I currently coach a U10 (8 and 9 year old) Girls team in a Rec league. I have 12 girls on my team and we play 8 v 8 goalie included, I promise all girls they will play at least 25 minutes of each 50 minute games. There are ten teams in the league and we just lost our first game this past weekend 3-0 to probably the second best team in the league. Because half our team seemed to be on summer vacation, we usually had 6-8 girls at the five practices before the first game. We now have everyone showing up at practice. I see this team as having some really good athletes not the most talented team, but with our ability and heart, I think this team has some potential and I want to give these girls the best experience they have had and play up to our potential.
One of our goals: the best team in the league just beat another team 14-0 and rightfully so think they are going to go undefeated. This team has a tendency to play very physical and has a talented squad. Just hearing that they think they will go undefeated made me circle the game we have against them in three weeks. My goal is to at least play that game against them as competitive as possible.
Our main emphasis is for the girls and our team to play to our potential in that game and perhaps scare them a bit. Our team and our coaches like winning but this is a game that we really want to win.
Our team played a 2-3-2 in the game we lost 3-0 which I know is probably against your recommendations, so I know I need to start there. My strategy is to defend deep which backfired because two of the goals were scored when my two defenders were almost backed up to the goal line and froze when an attacker came toward the goal.
I did teach Coaching Rule number 3 but only half of them get it and only two of them can really jump on the opportunity. Maybe I need to work on that more during practice. Any suggestions on drills that work to help sink in. It will be good that I have our full squad on the practice field this week.
I have three skilled players who could play on a travelling team as backups, seven other players who have potential to be skilled, and two that just are not skilled and not athletic.
Most of my team is fast with the exception of the two unskilled. Three of the fast players are skilled, and three of the fast players have potential but are weak in soccer skills or desire.
Four girls can play goalie, Player 1 and Player 3 rather be in the field. Player 11 and 12 play goalie because they don't like to run. Player 11 shows some promise in goalie.
Some of my players are strong in the center between the 2 goals like Player 1, 3 and sometimes player 7. Player 5 and 6 could be good but sometimes react to the ball or do the opposite and don't move.
I need to work on positioning because my forwards absolutely don't get their position, they play like midfielders and are where the ball is with the exception of player 4 and 8. My fullbacks clear the ball to the sides or straight ahead if far enough from the goal. Midfielders like player 2 and 3 will be in position to get the ball, the others not so much.
I tend to focus on the strength of the players when assigning positions but do like to rotate the girls to different position focusing on their best positions.
We practice twice a week for an hour to an hour and a half and every girls has a soccer ball with an extra six in my bag. We do a lot of dribble across the box, dribble and pass around cone, small sided games, and will begin to work on shoulder to shoulder game today. My midfielders sometimes have a tendency just to go wherever the ball goes. My fullbacks stay out of the goal box except for the two that drifted in there during the game. My forwards are hit and miss sometimes they think they are midfielders other times they actually are ahead of the ball. Here is a list of my players from best to worst:
Player 1 is my best player who can play every position on the field. On defense, she can dominate her side of the ball. One of the strongest legs on the team, one of the fastest, and plays really tough. Although she can handle the ball really well, her only downfall is her tendency to dance around the ball too much. She could also play goalie. I told her if she can punt the ball past midfield consistently I would let her play goalie. I play her at defense and midfielder.
Player 2 is a very close second who is the fastest player on the team. She is one of the smaller players but never gets tired and is one of the tougher players, loves contact, and plays with absolutely no fear. Handles the ball well but does kick the ball too far ahead of her. Plays great with player 1 because they can read each other. Midfielder.
Player 3 is a smart player who has a very strong leg and at times can become pretty fast, once she gets going. She does get tired a little easier than player 1 and 2 but plays with a lot of heart. Great defender and can also play a solid goalie. Defense and Midfielder
Player 4 is always running and is a fast player. She has a weak foot but is pretty accurate in her passing. Really comfortable with the ball at her feet. Never gets tired, plays midfield and forward.
Player 5 can kick the ball the hardest and farthest. She could be an amazing player but has a tendency to tune out and not play smart. She can play tough but during the games she plays with quite a bit of fear, waiting for the ball to come to her. Plays every position.
Player 6 loves to stop the ball in anyway shape or form, sometime illegally and is a very tough and aggressive player. She is the smallest girl on the team but plays with a ton of heart. Average speed, weak foot, sometimes will not react quick to the ball. Average dribbling and ball control. Will play at half speed in practice and full speed in games. Plays mainly defense.
Player 7 is a fast player who loves competition. Weak foot but played an amazing defense in scrimmage and games. With player 1, they could probably stop most teams on defense. She has no left foot which could be a problem because she always delays her kick a little to get her right foot on the ball. Defense and Midfielder
Player 8 Fast player that absolutely does not get how to play positions no matter how much I tell her, except forward because I tell her to hang out with the opposing players defenders. Good dribbling, fairly strong kick. Good attitude but will crumble on contact.
Player 9 keeps getting better and could be one of the better players on the team given some time. Her brother plays on the travelling team so she has some really good ball skills but just doesn't know how to execute. She can get timid because she is smaller and has an inconsistent kick sometimes strong sometimes weak. Fairly fast girl but gets tired easy. Midfielder.
Player 10 could be the fastest player on the team but seems to not want to exert herself at times in practice or games. Plays very timid, has potential but sometimes she is not completely into the game. 
Player 11 is an inconsistent player. Sometimes works hard during practice and sometimes tunes out. She loves attention and loves playing goalie. Actually decent at goalie except does have the quickness to get to the ball. Her ball control is weak and is second slowest on the team. Goalie, left midfielder and forward.
Player 12 is the slowest player on the team. She wants to play goalie because she does not like to run. Has a fairly strong foot but has a tendency to give up on the ball when she's on the field. Seems to be playing the game because her parents want to and can be disruptive during practice. Goalie, and wherever I can hide her.
I will accept any help you can give me. Thank you!
Best,
Coach M, U10G, Premium Member

6. Below what you just deleted is >

Hi Coach M,
Thanks for being a Premium member and for the kind words.
I think you can make a few changes and see a big improvement in your team.
Below are my thoughts:

> Above " Below are my thoughts:" add > 

For more tips and tactics see More Soccer Tips and Tactics and the Coaching Navigation Page at Soccer Coaching Navigation 

(Dustin, have the 2 links go to http://www.soccerhelp.com/Soccer_Tactics_Soccer_Tips_Index.shtml and http://www.soccerhelp.com/Soccer-Coaching-Navigation.shtml ) 

> So it reads >

Hi Coach M,
Thanks for being a Premium member and for the kind words.
I think you can make a few changes and see a big improvement in your team.
For more tips and tactics see More Soccer Tips and Tactics and the Coaching Navigation Page at More Soccer Coaching Tips
Below are my thoughts:

7. The section below the section that has 21 tips is >
More Tips for Coach M:
Hi Coach M,
Below are 3 drills to try that were recommended by coaches --
"We added the Push & Blast Off practice game to warm-ups late in the season. This helped them to understand how to get around a defender and to be quick by pushing off hard." Coach Corey, U12G whose team won their tournament 
"My players love the soccer patches and are always eager to earn a patch. I am seeing amazing results from the patches and Premium soccer drills. Dribble Across a Square, the Defensive Footwork drills and Chips/Lofted Passes drills have helped my players and I see it in games. My U8 team just beat the best team in the league which last season beat us easily." Kevin, MD, U8 and U10, Premium member 

7.(a). Dustin , make  "More Tips for Coach M:" the same font size as the Text

7.(b). unbold the 2 paras below that have Green text (the links too)  so it looks like >

More Tips for Coach M:
Hi Coach M,
Below are 3 drills to try that were recommended by coaches --
"We added the Push & Blast Off practice game to warm-ups late in the season. This helped them to understand how to get around a defender and to be quick by pushing off hard." Coach Corey, U12G whose team won their tournament 
"My players love the soccer patches and are always eager to earn a patch. I am seeing amazing results from the patches and Premium soccer drills. Dribble Across a Square, the Defensive Footwork drills and Chips/Lofted Passes drills have helped my players and I see it in games. My U8 team just beat the best team in the league which last season beat us easily." Kevin, MD, U8 and U10, Premium member

8. Replace More Tips for Coach M:

with > 3 Soccer Drills to Try

9. Make the H3 >

3 Soccer Drills to Try

10. Number 7 is >
Style of Play - Keep Defending Deep. Let your Fullbacks Push Up to the top of the Penalty Box when you are on attack and STRESS do NOT go inside the Goal Box except in an emergency. You can put slow players at Fullback IF they are brave. You should not put timid players at Fullback who are scared of being hit by the ball or of being bumped - you will get killed if you do. The best strategy for your team is for your FBs and Stopper to kick the ball straight ahead HARD. When the ball is in your Penalty Box, have your CMF stay a pass out from the ball and keep "shifting" from side-to-side with the ball so she is in position to win those cleared balls AND have your Forward stay a LONG kick away from the ball and keep shifting with the ball. That way when your FBs or Stopper clear the ball straight ahead, you have 2 good players in position to win the cleared ball.
10.a > Make Defending Deep a link in 2 places to > http://www.soccerhelp.com/Soccer_Tips_Dictionary_Terms_D.shtml#defending_deep 
10.b. And add to the end of the above para >
Defending Deep and Coaching Rule Number 3 will keep you from giving up goals on Breakaways. 
(Make Coaching Rule No. 3 a link to http://www.soccerhelp.com/premium/Coaching_Rules.shtml ) 
> So it reads >
Style of Play - Keep Defending Deep . Let your Fullbacks Push Up to the top of the Penalty Box when you are on attack and STRESS do NOT go inside the Goal Box except in an emergency. You can put slow players at Fullback IF they are brave. You should not put timid players at Fullback who are scared of being hit by the ball or of being bumped - you will get killed if you do. The best strategy for your team is for your FBs and Stopper to kick the ball straight ahead HARD. When the ball is in your Penalty Box, have your CMF stay a pass out from the ball and keep "shifting" from side-to-side with the ball so she is in position to win those cleared balls AND have your Forward stay a LONG kick away from the ball and keep shifting with the ball. That way when your FBs or Stopper clear the ball straight ahead, you have 2 good players in position to win the cleared ball. Defending Deep and Coaching Rule Number 3 will keep you from giving up goals on Breakaways.

(Dustin - make the 2 links bold red to match the others)

**Comment by dustinschaerer** [comment]
@david-huddleston Do you want this W3C validated?

**Comment by dustinschaerer** [comment]
Its not too much work on this page so I'll do it.

**Comment by dustinschaerer** [comment]
@david-huddleston This is ALL completed and validated.
